/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2007, 2010, Oracle and/or its affiliates. All rights reserved.
 */

#ifndef CLIENTSOAPFAULTCODES_H
#define CLIENTSOAPFAULTCODES_H

/**
 * Enumeration of error codes that have corresponding soap error strings.
 * Note: These start at 1000 to avoid overlapping with other soap error codes
 *
 * The format of these enumerations is roughly as follows:
 *
 * Start with CLIENT_ERROR_
 *
 * Next, put AGENT if the error is intended for the KMA Agent interface
 *       put MANAGER if the error is intended for the KMS Manager interface
 *       put SERVER if the error is the fault of the KMS server for any interface
 *
 * After that, briefly describe the error.
 */
enum SoapClientErrorCode
{
    INVALID_CLIENT_ERROR = 0,
    CLIENT_ERROR_ACCESS_DENIED = 1000,
    CLIENT_ERROR_SERVER_BUSY,
    CLIENT_ERROR_AUTHENTICATION_FAILED,
    CLIENT_ERROR_NETWORK_ADDRESS_UNREACHABLE,
    CLIENT_ERROR_INVALID_EXPECTED_PEER_LAST_KNOWN_TIMESTAMP_VECTOR,
    CLIENT_ERROR_INCOMPATIBLE_VERSION,
    CLIENT_ERROR_INCOMPATIBLE,
    CLIENT_ERROR_BUNDLE_ALREADY_IN_PROGRESS,
    CLIENT_ERROR_AGENT_INVALID_PARAMETERS,
    CLIENT_ERROR_AGENT_KEY_DOES_NOT_EXIST,
    CLIENT_ERROR_AGENT_KEY_DESTROYED,
    CLIENT_ERROR_AGENT_DATA_UNIT_ID_NOT_FOUND_EXTERNAL_ID_EXISTS,
    CLIENT_ERROR_AGENT_DATA_UNIT_EXPIRED,
    CLIENT_ERROR_INVALID_DATA_UNIT_ID,
    CLIENT_ERROR_INVALID_KEY_ID,
    CLIENT_ERROR_AGENT_DUPLICATE_EXTERNAL_ID,
    CLIENT_ERROR_AGENT_INVALID_EXTERNAL_ID,
    CLIENT_ERROR_AGENT_DATA_UNIT_NOT_REKEYABLE,
    CLIENT_ERROR_AGENT_APPLIANCE_LOCKED,
    CLIENT_ERROR_AGENT_INVALID_PASSPHRASE,
    CLIENT_ERROR_DATA_UNIT_NOT_FOUND,
    CLIENT_ERROR_AGENT_NO_READY_KEYS,
    CLIENT_ERROR_MANAGER_INVALID_PARAMETERS,
    CLIENT_ERROR_MANAGER_DATA_UNIT_NOT_DESTROYED,
    CLIENT_ERROR_MANAGER_APPLIANCE_EXISTS,
    CLIENT_ERROR_MANAGER_APPLIANCE_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_CANNOT_DELETE_LOCAL_APPLIANCE,
    CLIENT_ERROR_MANAGER_APPLIANCE_IN_USE,
    CLIENT_ERROR_MANAGER_AGENT_EXISTS,
    CLIENT_ERROR_MANAGER_AGENT_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_AGENT_IN_USE,
    CLIENT_ERROR_MANAGER_USER_EXISTS,
    CLIENT_ERROR_MANAGER_USER_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_USER_IN_USE,
    CLIENT_ERROR_MANAGER_ROLE_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_USER_ROLE_EXISTS,
    CLIENT_ERROR_MANAGER_USER_ROLE_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_CANNOT_DELETE_ONLY_SECURITY_OFFICER,
    CLIENT_ERROR_MANAGER_CANNOT_REMOVE_ONLY_SECURITY_OFFICER_ROLE,
    CLIENT_ERROR_MANAGER_SITE_EXISTS,
    CLIENT_ERROR_MANAGER_SITE_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_SITE_IN_USE,
    CLIENT_ERROR_MANAGER_CANNOT_SET_PASSPHRASE_FOR_LOCAL_APPLIANCE,
    CLIENT_ERROR_MANAGER_INVALID_PASSPHRASE,
    CLIENT_ERROR_MANAGER_LIFETIME_OVERRIDE_NOT_PERMITTED,
    CLIENT_ERROR_MANAGER_AGENT_ALREADY_IN_KEY_GROUP,
    CLIENT_ERROR_MANAGER_AGENT_ALREADY_HAS_DEFAULT_KEY_GROUP,
    CLIENT_ERROR_MANAGER_AGENT_NOT_IN_KEY_GROUP,
    CLIENT_ERROR_MANAGER_CORE_SECURITY_ALREADY_LOCKED,
    CLIENT_ERROR_MANAGER_CORE_SECURITY_ALREADY_UNLOCKED,
    CLIENT_ERROR_MANAGER_BACKUP_ID_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_BACKUP_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_BACKUP_RESTORE_DENIED,
    CLIENT_ERROR_MANAGER_BACKUP_OR_RESTORE_IN_PROGRESS,
    CLIENT_ERROR_MANAGER_BACKUP_RESTORE_FILE_DUPLICATE_ENTITY_FAILURE,
    CLIENT_ERROR_MANAGER_BACKUP_RESTORE_FILE_INVALID,
    CLIENT_ERROR_MANAGER_FILE_CHUNK_OFFSET_INVALID,
    CLIENT_ERROR_MANAGER_FILE_CHUNK_IO_ERROR,
    CLIENT_ERROR_MANAGER_BACKUP_ALREADY_DESTROYED,
    CLIENT_ERROR_MANAGER_BACKUP_DESTROYED,
    CLIENT_ERROR_MANAGER_BACKUP_NOT_AVAILABLE,
    CLIENT_ERROR_MANAGER_CLOCK_ADJUSTMENT_LIMIT_EXCEEDED,
    CLIENT_ERROR_MANAGER_CLOCK_ADJUSTMENT_ALREADY_PERFORMED_TODAY,
    CLIENT_ERROR_MANAGER_CLOCK_ADJUSTMENT_FAILED,
    CLIENT_ERROR_MANAGER_SOFTWARE_UPGRADE_FILE_NOT_FOUND,
    CLIENT_ERROR_MANAGER_SOFTWARE_UPGRADE_FAILED,
    CLIENT_ERROR_MANAGER_LIST_SOFTWARE_VERSIONS_FAILED,
    CLIENT_ERROR_MANAGER_CHANGE_SOFTWARE_VERSION_FAILED,
    CLIENT_ERROR_MANAGER_VERIFY_SOFTWARE_UPLOAD_FAILED,
    CLIENT_ERROR_MANAGER_SNMP_MANAGER_EXISTS,
    CLIENT_ERROR_MANAGER_SNMP_MANAGER_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_EXISTS,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_IN_USE,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_ALREADY_IN_KEY_GROUP,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_NOT_IN_KEY_GROUP,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_NOT_ENABLED,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_NOT_ALLOWED_EXPORT_TO,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_HAS_NO_PUBLIC_KEYS,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_PUBLIC_KEY_ID_ALREADY_EXISTS,
    CLIENT_ERROR_MANAGER_APPLIANCE_LOCKED,
    CLIENT_ERROR_MANAGER_DATA_UNIT_EXPIRED,
    CLIENT_ERROR_MANAGER_UNEXPECTED_TRANSFER_PARTNER,
    CLIENT_ERROR_MANAGER_KEY_GROUP_DOES_NOT_ALLOW_EXPORT_FROM,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_KEY_GROUP_ACCESS_DENIED,
    CLIENT_ERROR_MANAGER_TRANSFER_PARTNER_NOT_ALLOWED_IMPORT_FROM,
    CLIENT_ERROR_MANAGER_KEY_GROUP_NOT_ALLOWED_IMPORT_TO,
    CLIENT_ERROR_MANAGER_DUPLICATE_DATA_UNIT_ID,
    CLIENT_ERROR_MANAGER_DUPLICATE_DATA_UNIT_KEY_ID,
    CLIENT_ERROR_MANAGER_DUPLICATE_EXTERNAL_ID,
    CLIENT_ERROR_MANAGER_CORE_SECURITY_PUBLIC_KEY_NOT_FOUND,
    CLIENT_ERROR_MANAGER_CHANGE_PRIMARY_LOCAL_NETWORK_ADDRESS_DENIED,
    CLIENT_ERROR_MANAGER_CHANGE_SECONDARY_LOCAL_NETWORK_ADDRESS_DENIED,
    CLIENT_ERROR_MANAGER_KEY_POLICY_EXISTS,
    CLIENT_ERROR_MANAGER_KEY_POLICY_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_KEY_POLICY_IN_USE,
    CLIENT_ERROR_MANAGER_CHANGE_SOFTWARE_VERSION_IN_PROGRESS,
    CLIENT_ERROR_MANAGER_VERIFY_SOFTWARE_UPLOAD_IN_PROGRESS,
    CLIENT_ERROR_MANAGER_APPLY_SOFTWARE_VERSION_IN_PROGRESS,
    CLIENT_ERROR_MANAGER_KEY_GROUP_EXISTS,
    CLIENT_ERROR_MANAGER_KEY_GROUP_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_KEY_GROUP_IN_USE,
    CLIENT_ERROR_MANAGER_KEY_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_KEY_ALREADY_COMPROMISED,
    CLIENT_ERROR_MANAGER_KEY_ALREADY_IN_KEY_GROUP,
    CLIENT_ERROR_MANAGER_INVALID_BACKUP_ID,
    CLIENT_ERROR_MANAGER_LIMIT_EXCEEDED,
    CLIENT_ERROR_MANAGER_SYSTEM_DUMP_FAILED,
    CLIENT_ERROR_MANAGER_SYSTEM_DUMP_DOES_NOT_EXIST,
    CLIENT_ERROR_MANAGER_ADD_NTP_SERVER_FAILED,
    CLIENT_ERROR_MANAGER_DELETE_NTP_SERVER_FAILED,
    CLIENT_ERROR_MANAGER_NTP_SERVER_SPECIFIED,
    CLIENT_ERROR_MANAGER_GET_LOCAL_CLOCK_FAILED,
    CLIENT_ERROR_MANAGER_ADJUST_LOCAL_CLOCK_FAILED,
    CLIENT_ERROR_MANAGER_NEED_CORE_SECURITY_BACKUP,
    CLIENT_ERROR_MANAGER_KEY_DESTRUCTION_IN_PROGRESS,
    CLIENT_ERROR_IMPORT_10KEYS_ALREADY_UPLOADED,
    CLIENT_ERROR_IMPORT_10KEYS_FILE_DOES_NOT_EXIST,
    CLIENT_ERROR_IMPORT_10KEYS_INVALID_FILE_FORMAT,
    CLIENT_ERROR_IMPORT_10KEYS_FILE_READ_ERROR,
    CLIENT_ERROR_IMPORT_10KEYS_FAILED,
    CLIENT_ERROR_IMPORT_10KEYS_DUPLICATE_KEY_ID_AND_VALUE,
    CLIENT_ERROR_IMPORT_10KEYS_DUPLICATE_KEY_ID,
    CLIENT_ERROR_IMPORT_10KEYS_KEY_VALUE_NOT_HEX,
    CLIENT_ERROR_INVALID_BACKUP_TIME,
    CLIENT_ERROR_KEY_TRANSFER_IN_PROGRESS,
    CLIENT_ERROR_KEY_TRANSFER_FILE_NOT_VALIDATED,
    CLIENT_ERROR_LOCAL_APPLIANCE_NOT_PEER_SERVER,
    CLIENT_ERROR_CANNOT_CONTACT_PEER_SERVER,
    CLIENT_ERROR_MISMATCHED_SIGNING_PUBLIC_KEY_ID,
    CLIENT_ERROR_MISMATCHED_ENCRYPTION_PUBLIC_KEY_ID,
    CLIENT_ERROR_DATA_UNIT_HAS_NO_EXPORTABLE_KEYS,
    CLIENT_ERROR_SOME_KEYS_NOT_EXPORTABLE, // This is actually a warning -- should we treat it differently? Start at 2000?
    CLIENT_ERROR_UPDATE_REPLICATION_SCHEMA,
    CLIENT_ERROR_NOT_SUPPORTED,
    CLIENT_ERROR_AGENT_KWK_NOT_REGISTERED,
    CLIENT_ERROR_AGENT_KWK_ID_MISMATCH,
    CLIENT_ERROR_LIST_KMA_NETWORK_ADDRESSES_FAILED,
    CLIENT_ERROR_GET_KMA_DNS_INFORMATION_FAILED,
    CLIENT_ERROR_LIST_KMA_ROUTING_TABLE_ENTRIES_FAILED,
    CLIENT_ERROR_EXPORT_FORMAT_DISALLOWED,
    CLIENT_ERROR_TRANSFER_FORMAT_DISALLOWED,
    CLIENT_ERROR_FIPS_MODE_REQUIRED,
    CLIENT_ERROR_CLIENT_UPGRADE_REQUIRED,
    CLIENT_ERROR_RESTORE_INVALID_BACKUP_XML_FORMAT,
    CLIENT_ERROR_MANAGER_INVALID_MASTER_KEY_PROVIDER_PARAMETERS,
    CLIENT_ERROR_MANAGER_PENDED_OPERATION_ID_DOES_NOT_EXIST,
    CLIENT_ERROR_INVALID_PENDED_OPERATION_TYPE,
    CLIENT_ERROR_SERVER_HSM_REQUIRED_BUT_MISSING,
    CLIENT_ERROR_MANAGER_INTERNAL,
    CLIENT_ERROR_AGENT_INVALID_HMAC,
    CLIENT_ERROR_AGENT_INVALID_KEY,
    CLIENT_ERROR_QUORUM_NOT_MET,
    CLIENT_ERROR_MANAGER_CANNOT_QUERY_NTP_SERVER,
    CLIENT_ERROR_MANAGER_NTP_SERVER_DELTA_TOO_BIG,
    CLIENT_ERROR_MANAGER_CANNOT_UPDATE_NTP_CONFIG,
    CLIENT_ERROR_MANAGER_CANNOT_CONTACT_SNMP_MANAGER,
    CLIENT_ERROR_MANAGER_CORE_SECURITY_ERROR_INTERNAL,
    CLIENT_ERROR_MANAGER_CORE_SECURITY_NOT_FOUND,

    //  NOTE:  When you add a new CLIENT_ERROR_* definition above this comment,
    //         you should also add:
    //
    //         1)  A case statement for it near the end of the switch
    //             statement in the GetSoapClientErrorCodeMessage() routine
    //             in the Common/SoapFaults/ClientSoapFaults.cpp file
    //         2)  A case statement for it near the end of the switch
    //             statement in the GetTranslatedSoapFault() routine in the
    //             Common/SoapFaults/ClientSoapErrorTranslator.cpp file
    //         3)  A case statement for it near the end of the switch statement
    //             in the GetErrorString routine in the
    //             Client/Manager/Global.cpp file

    CLIENT_ERROR_LAST
};


#define GET_FAULT_CODE(errstr) (atoi(errstr))

#endif //CLIENTSOAPFAULTCODES_H
