#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 1998 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.

#ident	"%Z%%M%	%I%	%E% SMI"

BIN		= bin$(TARGET_ARCH)
LDFLAGS		+= -g $(LDLIBS)

#
#	Compiler selection
#
TARG_SYS:sh =                                   \
 (                                              \
   UNAME=` uname -r 2>/dev/null` ||.;           \
   case $UNAME in                               \
   '') echo SUNOS;;                             \
   4.*) echo SUNOS;;                            \
   5.*) PNAME=`uname -p 2>/dev/null` ||.;       \
        case $PNAME in                          \
        '') echo SVR4;;                         \
        i386) echo INTEL;;                      \
        *) echo SVR4;;                          \
        esac;;                                  \
   *)  echo SVR4;;                              \
   esac                                         \
 )

CCC += -norunpath -nolib

SVR4_STRIP= /usr/ccs/bin/strip
INTEL_STRIP= /usr/ccs/bin/strip
SUNOS_STRIP=/bin/strip
_STRIP=$(SVR4_STRIP)
STRIP=$($(TARG_SYS)_STRIP)

SVR4_SNMHOME=/opt/SUNWconn/snm
INTEL_SNMHOME=
SUNOS_SNMHOME=/usr/snm
_SNMHOME=$(SVR4_SNMHOME)
SNMHOME=$($(TARG_SYS)_SNMHOME)

#
#	Misc Tools
#

TEST	 = test

