#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.

interval=$2

. /lib/svc/share/xvm_include.sh

case $1 in 
'start')
	#
	# This service should only be enabled in a PV domU.
	#
	if is_dom0 || [ `uname -i` != "i86xpv" ]; then
		echo "This service will only run in a PV xVM domU."
		svcadm disable -t svc:/system/xvm/ipagent:default
		exit $SMF_EXIT_OK
	fi

	/usr/lib/xen/bin/ipagent $interval &

	;;

*)
	echo "Usage: $0 start [report_interval]"
	exit 1
	;;
esac	

exit $?
