.Dd Jan 25, 2017
.Dt INTRO 9
.Os
.Sh NAME
.Nm Intro ,
.Nm intro
.Nd introduction to kernel concepts
.Sh DESCRIPTION
This section outlines high-level concepts of the illumos kernel and its
subsystems.  Specific documentation can be found in this section's
sub\-sections.
.Bl -tag -width Ds
.It Section 9E
Driver Entry Points
.It Section 9F
Kernel Functions for Drivers
.It Section 9P
Kernel Properties for Drivers
.It Section 9S
Data Structures for Drivers
.El
