#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#ident	"%Z%%M%	%I%	%E% SMI"


@ _END_

# Message file for cmd/sgs/libelf (32bit specific - basically).

# More C++ gibberish

@ MSG_STR_LT		"lt"
@ MSG_STR_LS		"ls"
@ MSG_STR_DV		"dv"
@ MSG_STR_GT		"gt"
@ MSG_STR_RS		"rs"
@ MSG_STR_MD		"md"
@ MSG_STR_LE		"le"
@ MSG_STR_ML		"ml"
@ MSG_STR_PL		"pl"
@ MSG_STR_GE		"ge"
@ MSG_STR_AD		"ad"
@ MSG_STR_MI		"mi"
@ MSG_STR_NE		"ne"
@ MSG_STR_OR		"or"
@ MSG_STR_ER		"er"
@ MSG_STR_AA		"aa"
@ MSG_STR_OO		"oo"
@ MSG_STR_AS		"as"
@ MSG_STR_APL		"apl"
@ MSG_STR_AMI		"ami"
@ MSG_STR_AMU		"amu"
@ MSG_STR_ADV		"adv"
@ MSG_STR_AMD		"amd"
@ MSG_STR_AAD		"aad"
@ MSG_STR_AOR		"aor"
@ MSG_STR_AER		"aer"
@ MSG_STR_ALS		"als"
@ MSG_STR_ARS		"ars"
@ MSG_STR_PP		"pp"
@ MSG_STR_MM		"mm"
@ MSG_STR_VC		"vc"
@ MSG_STR_CL		"cl"
@ MSG_STR_RF		"rf"
@ MSG_STR_EQ		"eq"
@ MSG_STR_CO		"co"
@ MSG_STR_NT		"nt"
@ MSG_STR_NW		"nw"
@ MSG_STR_DL		"dl"

@ MSG_STR_OPNANGBRAK	"<"
@ MSG_STR_DBLOPNANGBRAK	"<<"
@ MSG_STR_SLASH		"/"
@ MSG_STR_CLOANGBRAK	">"
@ MSG_STR_DBLCLOANGBRAK	">>"
@ MSG_STR_PERCENT	"%"
@ MSG_STR_OPNANGBRAKEQU	"<="
@ MSG_STR_PLUS		"+"
@ MSG_STR_CLOANGBRAKEQU	">="
@ MSG_STR_MINUS		"-"
@ MSG_STR_BANGEQU	"!="
@ MSG_STR_PIPE		"|"
@ MSG_STR_CARAT		"^"
@ MSG_STR_DBLAMP	"&&"
@ MSG_STR_DBLPIPE	"||"
@ MSG_STR_EQU		"="
@ MSG_STR_PLUSEQU	"+="
@ MSG_STR_MINUSEQU	"-="
@ MSG_STR_STARTEQU	"*="
@ MSG_STR_SLASHEQU	"/="
@ MSG_STR_PERCENTEQU	"%="
@ MSG_STR_AMPEQU	"&="
@ MSG_STR_PIPEEQU	"|="
@ MSG_STR_CARATEQU	"^="
@ MSG_STR_DBLOPENABKEQU	"<<="
@ MSG_STR_DBLCLOSABKEQU	">>="
@ MSG_STR_DBLPLUS	"++"
@ MSG_STR_DBLMINUS	"--"
@ MSG_STR_OPENCLOBRAK	"[]"
@ MSG_STR_MINUSCLOANGBK	"->"
@ MSG_STR_DBLEQU	"=="
@ MSG_STR_BANG		"!"
@ MSG_STR_NEW		" new"
@ MSG_STR_DELETE	" delete"
@ MSG_STR_AMP		"&"
@ MSG_STR_OPENCLOSEPAR	"()"
@ MSG_STR_STAR		"*"
@ MSG_STR_TILDE		"~"
@ MSG_STR_EMPTY		""
@ MSG_STR_COMMA		","
@ MSG_STR_DBLCOL	"::"
@ MSG_STR_DBLCOLSTAR	"::*"
@ MSG_STR_SPACE		" "
@ MSG_STR_ELIPSE	"..."
@ MSG_STR_OPENPAR	"("
@ MSG_STR_CLOSEPAR	")"
@ MSG_STR_OPENBRAK	"["
@ MSG_STR_CLOSEBRAK	"]"
@ MSG_STR_DBLUNDBAR	"__"
@ MSG_STR_TDBLUNDBAR	"t__"

@ MSG_STR_CONST_1	"const "
@ MSG_STR_CONST_2	" const"
@ MSG_STR_VOLATILE_1	"volatile "
@ MSG_STR_VOLATILE_2	" volatile"
@ MSG_STR_UNSIGNED	"unsigned "
@ MSG_STR_SIGNED	"signed "
@ MSG_STR_INT		"int"
@ MSG_STR_CHAR		"char"
@ MSG_STR_SHORT		"short"
@ MSG_STR_LONG		"long"
@ MSG_STR_FLOAT		"float"
@ MSG_STR_DOUBLE	"double"
@ MSG_STR_LONGDOUBLE	"long double"
@ MSG_STR_VOID		"void"
@ MSG_STR_OP		"op"
@ MSG_STR_OPERATOR_1	"operator"
@ MSG_STR_OPERATOR_2	"operator "
