#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/libsasl/plugins/login/sparc/Makefile

include ../Makefile.com

install: all $(ROOTLIBS)
