#!/bin/sh
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

if [ "${BASEDIR:=/}" != "/" ]
then
	BASEDIR_OPT="-b $BASEDIR"
fi

not_installed() {
	driver=$1
	grep "^${driver} " $BASEDIR/etc/name_to_major > /dev/null 2>&1
	return $?
}

EXIT=0

not_installed sdpib || add_drv -b ${BASEDIR} -m '* 0644 root sys' sdpib || EXIT=1

exit $EXIT
