#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
 
PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

LOGIN_ENTRY_RE="/dev/console    0600    /dev/usb/[0-9a-f]+[.][0-9a-f]+/[0-9]+/* driver=scsa2usb,usb_mid,usbprn # libusb/ugen devices"
LOGIN_ENTRY_NON_RE="/dev/usb/\[0-9a-f\]\+\[.\]\[0-9a-f\]\+/\[0-9\]\+/\*"

not_installed() {
	driver=$1
	grep "^${driver} " $BASEDIR/etc/name_to_major > /dev/null 2>&1

	return $?
}

# ugen devices should be default be accessible by console owner only
# so libusb applications will just work

no_logindevperm() {
	egrep "$LOGIN_ENTRY_NON_RE" $BASEDIR/etc/logindevperm > /dev/null 2>&1

	return $?
}

EXIT=0

not_installed ugen || add_drv -b ${BASEDIR} -m '* 0644 root sys' \
	ugen || EXIT=1

no_logindevperm || echo "$LOGIN_ENTRY_RE" >> $BASEDIR/etc/logindevperm

exit $EXIT
