#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#

include ../Makefile.com

LICENSEFILES += ../../uts/common/io/aac/THIRDPARTYLICENSE
CDDL=

.KEEP_STATE:

all: $(FILES) depend postinstall postremove
install: all pkg

include ../Makefile.targ
