#! /bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#

PATH="/bin:/usr/bin:/usr/sbin:${PATH}"
export PATH

TMP=/tmp/$$.pcmemvold

remove_token()
{

    cp $1 $TMP

    (   echo "g/$2/s///g"
        echo 'g/ $/s///g'
        echo 'w'
        echo 'q'
    ) | ed -s $TMP >/dev/null

    cp $TMP $1
    rm -f $TMP
}

#
# vold.conf processing
#

FILE="$BASEDIR/etc/vold.conf"

if test -f $FILE ; then

  #
  # clear out any old pcmem lines in vold.conf
  #
  egrep -v 'use pcmem drive' $FILE >$TMP
  cp $TMP $FILE
  rm -f $TMP

  #
  # clear out any old pcmem entries in vold.conf
  #
  remove_token "$FILE" 'pcmem'
fi

#
# rmmount.conf processing
#
FILE="$BASEDIR/etc/rmmount.conf"

if test -f $FILE ; then

    #
    # clear out any old pcmem entries in rmmount.conf
    #
    remove_token "$FILE" 'pcmem'
fi

exit 0

