#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
#	This Makefile defines all build rules for the promif version for
#	IEEE 1275 compliant firmware (generic portions).

#
#	C object build rules
#

$(OBJS_DIR)/%.o:		$(PSMBASE)/promif/ieee1275/sun4v/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(PSMBASE)/promif/ieee1275/sun4u/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(PSMBASE)/promif/ieee1275/sun4/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

#
#	Lint `object' build rules
#
$(LINTS_DIR)/%.ln:		$(PSMBASE)/promif/ieee1275/sun4v/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(PSMBASE)/promif/ieee1275/sun4u/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(PSMBASE)/promif/ieee1275/sun4/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))
