#! /bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# Preremove script for SUNWn2cp.v.
#
# This script removes driver with rem_drv(1M) if necessary.
#
DRV=n2cp
NAMEMAJOR="${BASEDIR}/etc/name_to_major"

#
# Determine if we are on an alternate BASEDIR
#
if [ "${BASEDIR:=/}" = "/" ]
then
        REM_DRV="/usr/sbin/rem_drv"
else
        REM_DRV="/usr/sbin/rem_drv -b ${BASEDIR}"
fi

#
# Remove the driver, but only if this has not already been done.
#
grep -w "${DRV}" ${NAMEMAJOR} > /dev/null 2>&1
if [ $? -eq 0 ]; then
    ${REM_DRV} ${DRV} || exit 1
fi

exit 0
