#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/gss_mechs/mech_dummy/sparcv9/Makefile

MAPDIR= ../spec/sparcv9
include ../Makefile.com
include ../../../Makefile.lib.64

sparcv9_C_PICFLAGS = $(C_BIGPICFLAGS64)

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBDIR64) $(ROOTLIBS64) $(ROOTLINKS64)
