'\" te
.\" Copyright (c) 2001, Sun Microsystems, Inc.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH ADDBIB 1 "Sep 14, 1992"
.SH NAME
addbib \- create or extend a bibliographic database
.SH SYNOPSIS
.LP
.nf
\fBaddbib\fR [\fB-a\fR] [\fB-p\fR \fIpromptfile\fR] \fIdatabase\fR
.fi

.SH DESCRIPTION
.sp
.LP
When \fBaddbib\fR starts up, answering \fBy\fR to the initial
\fBInstructions?\fR prompt yields directions. Typing \fBn\fR (or RETURN) skips
the directions. \fBaddbib\fR then prompts for various bibliographic fields,
reads responses from the terminal, and sends output records to \fIdatabase.\fR
A null response (just RETURN) means to leave out that field. A `\fB\(mi\fR\&'
(minus sign) means to go back to the previous field. A trailing backslash
allows a field to be continued on the next line. The repeating \fBContinue?\fR
prompt allows the user either to resume by typing \fBy\fR (or RETURN), to quit
the current session by typing \fBn\fR or \fBq\fR, or to edit \fIdatabase\fR
with any system editor  (see \fBvi\fR(1), \fBex\fR(1), \fBed\fR(1)).
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.na
\fB\fB-a\fR\fR
.ad
.RS 17n
Suppresses prompting for an abstract. Asking for an abstract is the default.
Abstracts are ended with a Control\(miD.
.RE

.sp
.ne 2
.na
\fB\fB-p\fR \fIpromptfile\fR\fR
.ad
.RS 17n
Uses a new prompting skeleton, defined in \fIpromptfile\fR. This file should
contain prompt strings, a TAB, and the key-letters to be written to the
\fIdatabase\fR.
.RE

.SH USAGE
.SS "Bibliography Key Letters"
.sp
.LP
The most common key-letters and their meanings are given below. \fBaddbib\fR
insulates you from these key-letters, since it gives you prompts in English,
but if you edit the bibliography file later on, you will need to know this
information.
.sp
.ne 2
.na
\fB\fB%A\fR\fR
.ad
.RS 8n
Author's name
.RE

.sp
.ne 2
.na
\fB\fB%B\fR\fR
.ad
.RS 8n
Book containing article referenced
.RE

.sp
.ne 2
.na
\fB\fB%C\fR\fR
.ad
.RS 8n
City (place of publication)
.RE

.sp
.ne 2
.na
\fB\fB%D\fR\fR
.ad
.RS 8n
Date of publication
.RE

.sp
.ne 2
.na
\fB\fB%E\fR\fR
.ad
.RS 8n
Editor of book containing article referenced
.RE

.sp
.ne 2
.na
\fB\fB%F\fR\fR
.ad
.RS 8n
Footnote number or label (supplied by   \fBrefer\fR)
.RE

.sp
.ne 2
.na
\fB\fB%G\fR\fR
.ad
.RS 8n
Government order number
.RE

.sp
.ne 2
.na
\fB\fB%H\fR\fR
.ad
.RS 8n
Header commentary, printed before reference
.RE

.sp
.ne 2
.na
\fB\fB%I\fR\fR
.ad
.RS 8n
Issuer (publisher)
.RE

.sp
.ne 2
.na
\fB\fB%J\fR\fR
.ad
.RS 8n
Journal containing article
.RE

.sp
.ne 2
.na
\fB\fB%K\fR\fR
.ad
.RS 8n
Keywords to use in locating reference
.RE

.sp
.ne 2
.na
\fB\fB%L\fR\fR
.ad
.RS 8n
Label field used by \fB-k\fR option of  \fBrefer\fR
.RE

.sp
.ne 2
.na
\fB\fB%M\fR\fR
.ad
.RS 8n
Bell Labs Memorandum (undefined)
.RE

.sp
.ne 2
.na
\fB\fB%N\fR\fR
.ad
.RS 8n
Number within volume
.RE

.sp
.ne 2
.na
\fB\fB%O\fR\fR
.ad
.RS 8n
Other commentary, printed at end of reference
.RE

.sp
.ne 2
.na
\fB\fB%P\fR\fR
.ad
.RS 8n
Page number(s)
.RE

.sp
.ne 2
.na
\fB\fB%Q\fR\fR
.ad
.RS 8n
Corporate or Foreign Author (unreversed)
.RE

.sp
.ne 2
.na
\fB\fB%R\fR\fR
.ad
.RS 8n
Report, paper, or thesis (unpublished)
.RE

.sp
.ne 2
.na
\fB\fB%S\fR\fR
.ad
.RS 8n
Series title
.RE

.sp
.ne 2
.na
\fB\fB%T\fR\fR
.ad
.RS 8n
Title of article or book
.RE

.sp
.ne 2
.na
\fB\fB%V\fR\fR
.ad
.RS 8n
Volume number
.RE

.sp
.ne 2
.na
\fB\fB%X\fR\fR
.ad
.RS 8n
Abstract \(em used by \fBroffbib\fR, not by \fBrefer\fR
.RE

.sp
.ne 2
.na
\fB\fB%Y,Z\fR\fR
.ad
.RS 8n
Ignored by \fBrefer\fR
.RE

.SH EXAMPLES
.LP
\fBExample 1 \fREditing the bibliography file
.sp
.LP
Except for \fBA\fR, each field should be given just once. Only relevant fields
should be supplied.

.sp
.in +2
.nf
\fB%A	Mark Twain
%T	Life on the Mississippi
%I	Penguin Books
%C	New York
%D	1978\fR
.fi
.in -2
.sp

.SH SEE ALSO
.sp
.LP
\fBed\fR(1), \fBex\fR(1), \fBindxbib\fR(1), \fBlookbib\fR(1), \fBrefer\fR(1),
\fBroffbib\fR(1), \fBsortbib\fR(1), \fBvi\fR(1), \fBattributes\fR(5)
