'\" te
.\"  Copyright 1989 AT&T  Copyright (c) 1992, Sun Microsystems, Inc.  All Rights Reserved
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH CKGID 1 "Sep 14, 1992"
.SH NAME
ckgid, errgid, helpgid, valgid \- prompts for and validates a group id
.SH SYNOPSIS
.LP
.nf
\fBckgid\fR [\fB-Q\fR] [\fB-W\fR \fIwidth\fR] [\fB-m\fR] [\fB-d\fR \fIdefault\fR] [\fB-h\fR \fIhelp\fR]
     [\fB-e\fR \fIerror\fR] [\fB-p\fR \fIprompt\fR] [\fB-k\fR \fIpid\fR [\fB-s\fR \fIsignal\fR]]
.fi

.LP
.nf
\fB/usr/sadm/bin/errgid\fR [\fB-W\fR \fIwidth\fR] [\fB-e\fR \fIerror\fR]
.fi

.LP
.nf
\fB/usr/sadm/bin/helpgid\fR [\fB-W\fR \fIwidth\fR] [\fB-m\fR] [\fB-h\fR \fIhelp\fR]
.fi

.LP
.nf
\fB/usr/sadm/bin/valgid\fR \fIinput\fR
.fi

.SH DESCRIPTION
.sp
.LP
\fBckgid\fR prompts a user and validates the response. It defines, among other
things, a prompt message whose response should be an existing  group ID, text
for help and error messages, and a default value (which will be returned if the
user responds with a carriage return).
.sp
.LP
All messages are limited in length to 70 characters and are formatted
automatically. Any white space used in the definition (including newline) is
stripped. The \fB-W\fR option cancels the automatic formatting. When a tilde is
placed at the beginning or end of a message definition, the default text will
be inserted at that point, allowing both custom text and the default text to be
displayed.
.sp
.LP
If the prompt, help or error message is not defined, the default message (as
defined under \fBNOTES\fR) will be displayed.
.sp
.LP
Three visual tool modules are linked to the \fBckgid\fR command.  They are
\fBerrgid\fR (which formats and displays an error message), \fBhelpgid\fR
(which formats and displays a help message), and \fBvalgid\fR (which validates
a response). These modules should be used in conjunction with \fBFML\fR
objects. In this instance, the \fBFML\fR object defines the prompt.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.na
\fB\fB-d\fR\fI default\fR\fR
.ad
.RS 14n
Defines the default value as \fIdefault\fR. The default is not validated and so
does not have to meet any criteria.
.RE

.sp
.ne 2
.na
\fB\fB-e\fR\fI error\fR\fR
.ad
.RS 14n
Defines the error message as \fI error\fR.
.RE

.sp
.ne 2
.na
\fB\fB-h\fR\fI help\fR\fR
.ad
.RS 14n
Defines the help messages as \fI help\fR.
.RE

.sp
.ne 2
.na
\fB\fB-k\fR\fI pid\fR\fR
.ad
.RS 14n
Specifies that process \fBID\fR \fIpid\fR is to be sent a signal if the user
chooses to abort.
.RE

.sp
.ne 2
.na
\fB\fB-m\fR\fR
.ad
.RS 14n
Displays a list of all groups when help is requested or when the user makes an
error.
.RE

.sp
.ne 2
.na
\fB\fB-p\fR\fI prompt\fR\fR
.ad
.RS 14n
Defines the prompt message as \fIprompt\fR.
.RE

.sp
.ne 2
.na
\fB\fB-Q\fR\fR
.ad
.RS 14n
Specifies that quit will not be allowed as a valid response.
.RE

.sp
.ne 2
.na
\fB\fB-s\fR\fI signal\fR\fR
.ad
.RS 14n
Specifies that the process \fBID\fR \fIpid\fR defined with the \fB-k\fR option
is to be sent signal \fI signal\fR when quit is chosen. If no signal is
specified, \fBSIGTERM\fR is used.
.RE

.sp
.ne 2
.na
\fB\fB-W\fR\fI width\fR\fR
.ad
.RS 14n
Specifies that prompt, help and error messages will be formatted to a line
length of \fIwidth\fR.
.RE

.SH OPERANDS
.sp
.LP
The following operand is supported:
.sp
.ne 2
.na
\fB\fIinput\fR\fR
.ad
.RS 9n
Input to be verified against \fB/etc/group\fR.
.RE

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.na
\fB\fB0\fR\fR
.ad
.RS 5n
Successful execution.
.RE

.sp
.ne 2
.na
\fB\fB1\fR\fR
.ad
.RS 5n
\fBEOF\fR on input, or negative width on \fB-W\fR option, or usage error.
.RE

.sp
.ne 2
.na
\fB\fB3\fR\fR
.ad
.RS 5n
User termination (quit).
.RE

.SH SEE ALSO
.sp
.LP
\fBattributes\fR(5)
.SH NOTES
.sp
.LP
The default prompt for \fBckgid\fR is:
.sp
.in +2
.nf
Enter the name of an existing group [?,q]:
.fi
.in -2
.sp

.sp
.LP
The default error message is:
.sp
.in +2
.nf
ERROR: Please enter one of the following group names: [\fIList\fR]
.fi
.in -2
.sp

.sp
.LP
If the \fB-m\fR option of \fBckgid\fR is used, a list of valid groups is
displayed here.
.sp
.LP
The default help message is:
.sp
.in +2
.nf
ERROR: Please enter one of the following group names: [\fIList\fR]
.fi
.in -2
.sp

.sp
.LP
If the \fB-m\fR option of \fBckgid\fR is used, a  list of valid groups is
displayed here.
.sp
.LP
When the quit option is chosen (and allowed), \fBq\fR is returned along with
the return code \fB3\fR. The \fBvalgid\fR module will not produce any output.
It returns \fB0\fR for success and non-zero for failure.
