'\" te
.\"  Copyright 1989 AT&T  Copyright (c) 1994 Sun Microsystems, Inc. - All Rights Reserved.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH LOGOUT 1 "Apr 15, 1994"
.SH NAME
logout \- shell built-in function to exit from a login session
.SH SYNOPSIS
.SS "csh"
.LP
.nf
\fBlogout\fR
.fi

.SH DESCRIPTION
.SS "csh"
.sp
.LP
Terminate a login shell.
.SH SEE ALSO
.sp
.LP
\fBcsh\fR(1), \fBlogin\fR(1), \fBattributes\fR(5)
