'\" te
.\"  Copyright (c) 2004, Sun Microsystems, Inc. All Rights Reserved
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH PROJECTS 1 "May 13, 2004"
.SH NAME
projects \- print project membership of user
.SH SYNOPSIS
.LP
.nf
\fBprojects\fR [\fB-dv\fR] [ \fIuser\fR]
.fi

.LP
.nf
\fBprojects\fR \fB-l\fR [\fIprojectname\fR [\fIprojectname\fR]...]
.fi

.SH DESCRIPTION
.sp
.LP
The \fBprojects\fR command prints on standard output the projects to which the
invoking user or an optionally specified user belongs. Each user belongs to
some set of projects specified in the \fBproject\fR(4) file and possibly in the
associated \fBNIS\fR maps and \fBLDAP\fR databases for project information.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.na
\fB\fB-d\fR\fR
.ad
.RS 6n
Prints only default project.
.RE

.sp
.ne 2
.na
\fB\fB-l\fR\fR
.ad
.RS 6n
Prints verbose info on each project projectname. If no projectnames are given,
info on all projects is printed.
.RE

.sp
.ne 2
.na
\fB\fB-v\fR\fR
.ad
.RS 6n
Prints project descriptions along with project names.
.RE

.SH OPERANDS
.sp
.LP
The following operand is supported:
.sp
.ne 2
.na
\fB\fIprojectname\fR\fR
.ad
.RS 15n
Display information for the specified project.
.RE

.sp
.ne 2
.na
\fB\fIuser\fR\fR
.ad
.RS 15n
Displays project memberships for the specified user.
.RE

.SH EXAMPLES
.LP
\fBExample 1 \fRDisplaying Membership for a Specified User
.sp
.in +2
.nf
example$ \fBprojects paul\fR
default beatles wings
example$ \fBprojects ringo\fR
default beatles
example$ \fBprojects -d paul\fR
beatles
.fi
.in -2
.sp

.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.na
\fB\fB0\fR \fR
.ad
.RS 6n
Successful completion.
.RE

.sp
.ne 2
.na
\fB\fB1\fR\fR
.ad
.RS 6n
A fatal error occurred during execution.
.RE

.sp
.ne 2
.na
\fB\fB2\fR\fR
.ad
.RS 6n
Invalid command line options were specified.
.RE

.SH FILES
.sp
.ne 2
.na
\fB\fB/etc/project\fR\fR
.ad
.RS 16n
Local database containing valid project definitions for this machine.
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for a description of the following attributes:
.sp

.sp
.TS
box;
c | c
l | l .
ATTRIBUTE TYPE	ATTRIBUTE VALUE
Stability	See below.
.TE

.sp
.LP
The invocation is Evolving. The human-readable output is Unstable.
.SH SEE ALSO
.sp
.LP
\fBgetdefaultproj\fR(3PROJECT), \fBgetprojent\fR(3PROJECT), \fBproject\fR(4),
\fBattributes\fR(5)
