#
# Copyright (c) 2010, Oracle and/or its affiliates. All rights reserved.
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Message file for cmd/sgs/libconv/common/audit.c

@ MSG_LA_FLG_BINDTO	"LA_FLG_BINDTO"
@ MSG_LA_FLG_BINDFROM	"LA_FLG_BINDFROM"

@ MSG_LA_ACT_CONSISTENT	"[ LA_ACT_CONSISTENT ]"
@ MSG_LA_ACT_ADD	"[ LA_ACT_ADD ]"
@ MSG_LA_ACT_DELETE	"[ LA_ACT_DELETE ]"

@ MSG_LA_SER_ORIG	"LA_SER_ORIG"
@ MSG_LA_SER_LIBPATH	"LA_SER_LIBPATH"
@ MSG_LA_SER_RUNPATH	"LA_SER_RUNPATH"
@ MSG_LA_SER_DEFAULT	"LA_SER_DEFAULT"
@ MSG_LA_SER_CONFIG	"LA_SER_CONFIG"
@ MSG_LA_SER_SECURE	"LA_SER_SECURE"

@ MSG_LA_SYMB_NOPLTENTER	"LA_SYMB_NOPLTENTER"
@ MSG_LA_SYMB_NOPLTEXIT		"LA_SYMB_NOPLTEXIT"
@ MSG_LA_SYMB_STRUCTCALL	"LA_SYMB_STRUCTCALL"
@ MSG_LA_SYMB_DLSYM		"LA_SYMB_DLSYM"
@ MSG_LA_SYMB_ALTVALUE		"LA_SYMB_ALTVALUE"

@ MSG_GBL_ZERO		"0"
@ MSG_GBL_NULL		""
