#
# Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright 2022 Oxide Computer Company
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Message file for cmd/sgs/libconv/common/cap.c

@ MSG_CA_SUNW_NULL_CF		"CA_SUNW_NULL"			# 0
@ MSG_CA_SUNW_NULL_NF			"null"
@ MSG_CA_SUNW_HW_1_CF		"CA_SUNW_HW_1"			# 1
@ MSG_CA_SUNW_HW_1_NF			"hw_1"
@ MSG_CA_SUNW_SF_1_CF		"CA_SUNW_SF_1"			# 2
@ MSG_CA_SUNW_SF_1_NF			"sf_1"
@ MSG_CA_SUNW_HW_2_CF		"CA_SUNW_HW_2"			# 3
@ MSG_CA_SUNW_HW_2_NF			"hw_2"
@ MSG_CA_SUNW_PLAT_CF		"CA_SUNW_PLAT"			# 4
@ MSG_CA_SUNW_PLAT_NF			"plat"
@ MSG_CA_SUNW_MACH_CF		"CA_SUNW_MACH"			# 5
@ MSG_CA_SUNW_MACH_NF			"mach"
@ MSG_CA_SUNW_ID_CF		  "CA_SUNW_ID"			# 6
@ MSG_CA_SUNW_ID_NF			  "id"
@ MSG_CA_SUNW_HW_3_CF		"CA_SUNW_HW_3"			# 7
@ MSG_CA_SUNW_HW_3_NF			"hw_3"

@ MSG_GBL_ZERO		"0"
@ MSG_GBL_OSQBRKT	"0x%llx  [ "
@ MSG_GBL_CSQBRKT	" ]"
