#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# Message file for cmd/sgs/libconv/common/config.c

@ MSG_CONF_EDLIBPATH	"ELF-DEFAULT-LIBPATH"
@ MSG_CONF_ESLIBPATH	"ELF-SECURE-LIBPATH"
@ MSG_CONF_ADLIBPATH	"AOUT-DEFAULT-LIBPATH"
@ MSG_CONF_ASLIBPATH	"AOUT-SECURE-LIBPATH"
@ MSG_CONF_DIRCFG	"DIRECTORY-CONFIG"
@ MSG_CONF_OBJALT	"OBJECT-ALTERNATIVES"
@ MSG_CONF_MEMRESV	"MEMORY-RESERVATION"
@ MSG_CONF_ENVS		"ENVIRONMENT-VARIABLES"
@ MSG_CONF_FLTR		"FILTER-ASSOCIATIONS"

@ MSG_CONF_DIRENT	"DIR"
@ MSG_CONF_ALLENTS	"ALL-ENTRIES"
@ MSG_CONF_NOEXIST	"NON-EXISTENT"
@ MSG_CONF_EXEC		"EXEC"
@ MSG_CONF_OPTIONAL	"OPTIONAL-ALTERNATE"
@ MSG_CONF_ALTER	"ALTERNATE"
@ MSG_CONF_DUMP		"DUMPED"
@ MSG_CONF_REALPATH	"REALPATH"
@ MSG_CONF_NOALTER	"NO-ALTERNATE"
@ MSG_CONF_GROUP	"GROUP"
@ MSG_CONF_APP		"SPECIFIC-APP"
@ MSG_CONF_CMDLINE	"COMMAND-LINE"
@ MSG_CONF_FILTER	"FILTER"
@ MSG_CONF_FILTEE	"FILTEE"

@ MSG_GBL_NULL		""
