#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"

@ MSG_DATA_BYTE		"BYTE"
@ MSG_DATA_ADDR		"ADDR"
@ MSG_DATA_DYN		"DYN"
@ MSG_DATA_EHDR		"EHDR"
@ MSG_DATA_HALF		"HALF"
@ MSG_DATA_OFF		"OFF"
@ MSG_DATA_PHDR		"PHDR"
@ MSG_DATA_RELA		"RELA"
@ MSG_DATA_REL		"REL"
@ MSG_DATA_SHDR		"SHDR"
@ MSG_DATA_SWORD	"SWORD"
@ MSG_DATA_SYM		"SYM"
@ MSG_DATA_WORD		"WORD"
@ MSG_DATA_VDEF		"VDEF"
@ MSG_DATA_VNEED	"VNEED"
@ MSG_DATA_SXWORD	"SXWORD"
@ MSG_DATA_XWORD	"XWORD"
@ MSG_DATA_SYMINFO	"SYMINFO"
@ MSG_DATA_NOTE		"NOTE"
@ MSG_DATA_MOVE		"MOVE"
@ MSG_DATA_MOVEP	"MOVEP"
@ MSG_DATA_CAP		"CAP"
