#
# Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Message file for cmd/sgs/libconv/common/dl.c

@ MSG_RTLD_LAZY		"RTLD_LAZY"
@ MSG_RTLD_NOW		"RTLD_NOW"
@ MSG_RTLD_GLOBAL	"RTLD_GLOBAL"
@ MSG_RTLD_LOCAL	"RTLD_LOCAL"
@ MSG_RTLD_PARENT	"RTLD_PARENT"
@ MSG_RTLD_GROUP	"RTLD_GROUP"
@ MSG_RTLD_WORLD	"RTLD_WORLD"
@ MSG_RTLD_NODELETE	"RTLD_NODELETE"
@ MSG_RTLD_NOLOAD	"RTLD_NOLOAD"
@ MSG_RTLD_FIRST	"RTLD_FIRST"
@ MSG_RTLD_CONFGEN	"RTLD_CONFGEN"

@ MSG_RTLD_REL_RELATIVE	"RTLD_REL_RELATIVE"
@ MSG_RTLD_REL_EXEC	"RTLD_REL_EXEC"
@ MSG_RTLD_REL_DEPENDS	"RTLD_REL_DEPENDS"
@ MSG_RTLD_REL_PRELOAD	"RTLD_REL_PRELOAD"
@ MSG_RTLD_REL_SELF	"RTLD_REL_SELF"
@ MSG_RTLD_REL_WEAK	"RTLD_REL_WEAK"
@ MSG_RTLD_REL_ALL	"RTLD_REL_ALL"

@ MSG_RTLD_MEMORY	"RTLD_MEMORY"
@ MSG_RTLD_STRIP	"RTLD_STRIP"
@ MSG_RTLD_NOHEAP	"RTLD_NOHEAP"
@ MSG_RTLD_CONFSET	"RTLD_CONFSET"

@ MSG_RTLD_DI_LMID            "RTLD_DI_LMID"
@ MSG_RTLD_DI_LINKMAP         "RTLD_DI_LINKMAP"
@ MSG_RTLD_DI_CONFIGADDR      "RTLD_DI_CONFIGADDR"
@ MSG_RTLD_DI_SERINFO         "RTLD_DI_SERINFO"
@ MSG_RTLD_DI_SERINFOSIZE     "RTLD_DI_SERINFOSIZE"
@ MSG_RTLD_DI_ORIGIN          "RTLD_DI_ORIGIN"
@ MSG_RTLD_DI_PROFILENAME     "RTLD_DI_PROFILENAME"
@ MSG_RTLD_DI_PROFILEOUT      "RTLD_DI_PROFILEOUT"
@ MSG_RTLD_DI_GETSIGNAL       "RTLD_DI_GETSIGNAL"
@ MSG_RTLD_DI_SETSIGNAL       "RTLD_DI_SETSIGNAL"
@ MSG_RTLD_DI_ARGSINFO        "RTLD_DI_ARGSINFO"
@ MSG_RTLD_DI_MMAPS           "RTLD_DI_MMAPS"
@ MSG_RTLD_DI_MMAPCNT         "RTLD_DI_MMAPCNT"

@ MSG_GBL_SEP		" | "
@ MSG_GBL_QUOTE		"\""
@ MSG_GBL_ZERO		"0"
