#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"

@ MSG_DWEHE_OMIT	" omit "
@ MSG_DWEHE_ABSPTR	" absptr "

@ MSG_DWEHE_ULEB128	" uleb128 "
@ MSG_DWEHE_UDATA2	" udata2 "
@ MSG_DWEHE_UDATA4	" udata4 "
@ MSG_DWEHE_UDATA8	" udata8 "
@ MSG_DWEHE_SLEB128	" sleb128 "
@ MSG_DWEHE_SDATA2	" sdata2 "
@ MSG_DWEHE_SDATA4	" sdata4 "
@ MSG_DWEHE_SDATA8	" sdata8 "

@ MSG_DWEHE_PCREL	" pcrel "
@ MSG_DWEHE_TEXTREL	" textrel "
@ MSG_DWEHE_DATAREL	" datarel "
@ MSG_DWEHE_FUNCREL	" funcrel "
@ MSG_DWEHE_ALIGNED	" aligned "
@ MSG_DWEHE_INDIRECT	" indirect "

@ MSG_GBL_OSQBRKT	"["
@ MSG_GBL_CSQBRKT	"]"
