#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"

@ MSG_GPH_ZERO		" GPH_ZERO "
@ MSG_GPH_LDSO		" GPH_LDSO "
@ MSG_GPH_FIRST		" GPH_FIRST "
@ MSG_GPH_PARENT	" GPH_PARENT "
@ MSG_GPH_FILTEE	" GPH_FILTEE "
@ MSG_GPH_INITIAL	" GPH_INITIAL "
@ MSG_GPH_STICKY	" GPH_STICKY "

@ MSG_GBL_NULL		""
@ MSG_GBL_OSQBRKT	"["
@ MSG_GBL_CSQBRKT	"]"
