#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

@ MSG_PT_NULL			"[ PT_NULL ]"			# 0
@ MSG_PT_NULL_CF			"PT_NULL"
@ MSG_PT_NULL_CFNP			"NULL"
@ MSG_PT_NULL_NF			"null"
@ MSG_PT_LOAD			"[ PT_LOAD ]"			# 1
@ MSG_PT_LOAD_CF			"PT_LOAD"
@ MSG_PT_LOAD_CFNP			"LOAD"
@ MSG_PT_LOAD_NF			"load"
@ MSG_PT_DYNAMIC		"[ PT_DYNAMIC ]"		# 2
@ MSG_PT_DYNAMIC_DMP			"DYN"
@ MSG_PT_DYNAMIC_CF			"PT_DYNAMIC"
@ MSG_PT_DYNAMIC_CFNP			"DYNAMIC"
@ MSG_PT_DYNAMIC_NF			"dynamic"
@ MSG_PT_INTERP			"[ PT_INTERP ]"			# 3
@ MSG_PT_INTERP_CF			"PT_INTERP"
@ MSG_PT_INTERP_CFNP			"INTERP"
@ MSG_PT_INTERP_NF			"interp"
@ MSG_PT_NOTE			"[ PT_NOTE ]"			# 4
@ MSG_PT_NOTE_CF			"PT_NOTE"
@ MSG_PT_NOTE_CFNP			"NOTE"
@ MSG_PT_NOTE_NF			"note"
@ MSG_PT_SHLIB			"[ PT_SHLIB ]"			# 5
@ MSG_PT_SHLIB_CF			"PT_SHLIB"
@ MSG_PT_SHLIB_CFNP			"SHLIB"
@ MSG_PT_SHLIB_NF			"shlib"
@ MSG_PT_PHDR			"[ PT_PHDR ]"			# 6
@ MSG_PT_PHDR_CF			"PT_PHDR"
@ MSG_PT_PHDR_CFNP			"PHDR"
@ MSG_PT_PHDR_NF			"phdr"
@ MSG_PT_TLS			"[ PT_TLS ]"			# 7
@ MSG_PT_TLS_CF				"PT_TLS"
@ MSG_PT_TLS_CFNP			"TLS"
@ MSG_PT_TLS_NF				"tls"

@ MSG_PT_SUNW_UNWIND		"[ PT_SUNW_UNWIND ]"		# 0x6464e550
@ MSG_PT_SUNW_UNWIND_CF			"PT_SUNW_UNWIND"
@ MSG_PT_SUNW_UNWIND_CFNP		"SUNW_UNWIND"
@ MSG_PT_SUNW_UNWIND_NF			"sunw_unwind"
@ MSG_PT_SUNW_EH_FRAME		"[ PT_SUNW_EH_FRAME ]"		# 0x6474e550
@ MSG_PT_SUNW_EH_FRAME_CF		"PT_SUNW_EH_FRAME"
@ MSG_PT_SUNW_EH_FRAME_CFNP		"SUNW_EH_FRAME"
@ MSG_PT_SUNW_EH_FRAME_NF		"sunw_eh_frame"

@ MSG_PT_GNU_EH_FRAME		"[ PT_GNU_EH_FRAME ]"		# 0x6474e550
@ MSG_PT_GNU_EH_FRAME_CF		"PT_GNU_EH_FRAME"
@ MSG_PT_GNU_EH_FRAME_CFNP		"GNU_EH_FRAME"
@ MSG_PT_GNU_EH_FRAME_NF		"gnu_eh_frame"
@ MSG_PT_GNU_STACK		"[ PT_GNU_STACK ]"		# 0x6474e551
@ MSG_PT_GNU_STACK_CF			"PT_GNU_STACK"
@ MSG_PT_GNU_STACK_CFNP			"GNU_STACK"
@ MSG_PT_GNU_STACK_NF			"gnu_stack"
@ MSG_PT_GNU_RELRO		"[ PT_GNU_RELRO ]"		# 0x6474e552
@ MSG_PT_GNU_RELRO_CF			"PT_GNU_RELRO"
@ MSG_PT_GNU_RELRO_CFNP			"GNU_RELRO"
@ MSG_PT_GNU_RELRO_NF			"gnu_relro"

@ MSG_PT_SUNWBSS		"[ PT_SUNWBSS ]"		# 0x6ffffffa
@ MSG_PT_SUNWBSS_CF			"PT_SUNWBSS"
@ MSG_PT_SUNWBSS_CFNP			"SUNWBSS"
@ MSG_PT_SUNWBSS_NF			"sunwbss"
@ MSG_PT_SUNWSTACK		"[ PT_SUNWSTACK ]"		# 0x6ffffffb
@ MSG_PT_SUNWSTACK_CF			"PT_SUNWSTACK"
@ MSG_PT_SUNWSTACK_CFNP			"SUNWSTACK"
@ MSG_PT_SUNWSTACK_NF			"sunwstack"
@ MSG_PT_SUNWDTRACE		"[ PT_SUNWDTRACE ]"		# 0x6ffffffc
@ MSG_PT_SUNWDTRACE_CF			"PT_SUNWDTRACE"
@ MSG_PT_SUNWDTRACE_CFNP		"SUNWDTRACE"
@ MSG_PT_SUNWDTRACE_NF			"sunwdtrace"
@ MSG_PT_SUNWCAP		"[ PT_SUNWCAP ]"		# 0x6ffffffd
@ MSG_PT_SUNWCAP_CF			"PT_SUNWCAP"
@ MSG_PT_SUNWCAP_CFNP			"SUNWCAP"
@ MSG_PT_SUNWCAP_NF			"sunwcap"

@ MSG_PF_X_CF			 "PF_X"				# 0x1
@ MSG_PF_X_NF				 "x"
@ MSG_PF_W_CF			 "PF_W"				# 0x2
@ MSG_PF_W_NF				 "w"
@ MSG_PF_R_CF			 "PF_R"				# 0x4
@ MSG_PF_R_NF				 "r"
@ MSG_PF_SUNW_FAILURE_CF	 "PF_SUNW_FAILURE"		# 0x00100000
@ MSG_PF_SUNW_FAILURE_NF		 "sunw_failure"

@ MSG_GBL_ZERO		"0"
