#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

@ MSG_PT_NULL		"[ PT_NULL ]"
@ MSG_PT_NULL_ALT	"PT_NULL"
@ MSG_PT_LOAD		"[ PT_LOAD ]"
@ MSG_PT_LOAD_ALT	"PT_LOAD"
@ MSG_PT_DYNAMIC	"[ PT_DYNAMIC ]"
@ MSG_PT_DYNAMIC_ALT	"PT_DYNAMIC"
@ MSG_PT_INTERP		"[ PT_INTERP ]"
@ MSG_PT_INTERP_ALT	"PT_INTERP"
@ MSG_PT_NOTE		"[ PT_NOTE ]"
@ MSG_PT_NOTE_ALT	"PT_NOTE"
@ MSG_PT_SHLIB		"[ PT_SHLIB ]"
@ MSG_PT_SHLIB_ALT	"PT_SHLIB"
@ MSG_PT_PHDR		"[ PT_PHDR ]"
@ MSG_PT_PHDR_ALT	"PT_PHDR"
@ MSG_PT_TLS		"[ PT_TLS ]"
@ MSG_PT_TLS_ALT	"PT_TLS"

@ MSG_PT_SUNWBSS	"[ PT_SUNWBSS ]"
@ MSG_PT_SUNWBSS_ALT	"PT_SUNWBSS"
@ MSG_PT_SUNWSTACK	"[ PT_SUNWSTACK ]"
@ MSG_PT_SUNWSTACK_ALT	"PT_SUNWSTACK"
@ MSG_PT_SUNWDTRACE	"[ PT_SUNWDTRACE ]"
@ MSG_PT_SUNWDTRACE_ALT	"PT_SUNWDTRACE"
@ MSG_PT_SUNWCAP	"[ PT_SUNWCAP ]"
@ MSG_PT_SUNWCAP_ALT	"PT_SUNWCAP"

@ MSG_PT_SUNW_UNWIND	"[ PT_SUNW_UNWIND ]"
@ MSG_PT_SUNW_UNWIND_ALT	"PT_SUNW_UNWIND"

@ MSG_PF_X		 "PF_X"
@ MSG_PF_W		 "PF_W"
@ MSG_PF_R		 "PF_R"
@ MSG_PF_SUNW_FAILURE	 "PF_SUNW_FAILURE"

@ MSG_GBL_ZERO		"0"
