#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#pragma ident	"%Z%%M%	%I%	%E% SMI"
#

@ MSG_R_AMD64_NONE		"R_AMD64_NONE"		# 0
@ MSG_R_AMD64_64		"R_AMD64_64"		# 1
@ MSG_R_AMD64_PC32		"R_AMD64_PC32"		# 2
@ MSG_R_AMD64_GOT32		"R_AMD64_GOT32"		# 3
@ MSG_R_AMD64_PLT32		"R_AMD64_PLT32"		# 4
@ MSG_R_AMD64_COPY		"R_AMD64_COPY"		# 5
@ MSG_R_AMD64_GLOB_DATA		"R_AMD64_GLOB_DATA"	# 6
@ MSG_R_AMD64_JUMP_SLOT		"R_AMD64_JUMP_SLOT"	# 7
@ MSG_R_AMD64_RELATIVE		"R_AMD64_RELATIVE"	# 8
@ MSG_R_AMD64_GOTPCREL		"R_AMD64_GOTPCREL"	# 9
@ MSG_R_AMD64_32		"R_AMD64_32"		# 10
@ MSG_R_AMD64_32S		"R_AMD64_32S"		# 11
@ MSG_R_AMD64_16		"R_AMD64_16"		# 12
@ MSG_R_AMD64_PC16		"R_AMD64_PC16"		# 13
@ MSG_R_AMD64_8			"R_AMD64_8"		# 14
@ MSG_R_AMD64_PC8		"R_AMD64_PC8"		# 15
@ MSG_R_AMD64_DTPMOD64		"R_AMD64_DTPMOD64"	# 16
@ MSG_R_AMD64_DTPOFF64		"R_AMD64_DTPOFF64"	# 17
@ MSG_R_AMD64_TPOFF64		"R_AMD64_TPOFF64"	# 18
@ MSG_R_AMD64_TLSGD		"R_AMD64_TLSGD"		# 19
@ MSG_R_AMD64_TLSLD		"R_AMD64_TLSLD"		# 20
@ MSG_R_AMD64_DTPOFF32		"R_AMD64_DTPOFF32"	# 21
@ MSG_R_AMD64_GOTTPOFF		"R_AMD64_GOTTPOFF"	# 22
@ MSG_R_AMD64_TPOFF32		"R_AMD64_TPOFF32"	# 23
@ MSG_R_AMD64_PC64		"R_AMD64_PC64"		# 24
@ MSG_R_AMD64_GOTPC32		"R_AMD64_GOTPC32"	# 25
@ MSG_R_AMD64_GOTOFF64		"R_AMD64_GOTOFF64"	# 26
