#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#pragma ident	"%Z%%M%	%I%	%E% SMI"
#
# Message file for cmd/sgs/libconv/common/sections.c

@ MSG_SHT_NULL			"[ SHT_NULL ]"
@ MSG_SHT_NULL_ALT		"NULL"
@ MSG_SHT_PROGBITS		"[ SHT_PROGBITS ]"
@ MSG_SHT_PROGBITS_ALT		"PBIT"
@ MSG_SHT_SYMTAB		"[ SHT_SYMTAB ]"
@ MSG_SHT_SYMTAB_ALT		"SYMT"
@ MSG_SHT_STRTAB		"[ SHT_STRTAB ]"
@ MSG_SHT_STRTAB_ALT		"STRT"
@ MSG_SHT_RELA			"[ SHT_RELA ]"
@ MSG_SHT_RELA_ALT		"RELA"
@ MSG_SHT_HASH			"[ SHT_HASH ]"
@ MSG_SHT_HASH_ALT		"HASH"
@ MSG_SHT_DYNAMIC		"[ SHT_DYNAMIC ]"
@ MSG_SHT_DYNAMIC_ALT		"DYNM"
@ MSG_SHT_NOTE			"[ SHT_NOTE ]"
@ MSG_SHT_NOTE_ALT		"NOTE"
@ MSG_SHT_NOBITS		"[ SHT_NOBITS ]"
@ MSG_SHT_NOBITS_ALT		"NOBI"
@ MSG_SHT_REL			"[ SHT_REL ]"
@ MSG_SHT_REL_ALT		"REL "
@ MSG_SHT_SHLIB			"[ SHT_SHLIB ]"
@ MSG_SHT_SHLIB_ALT		"SHLB"
@ MSG_SHT_DYNSYM		"[ SHT_DYNSYM ]"
@ MSG_SHT_DYNSYM_ALT		"DYNS"
@ MSG_SHT_UNKNOWN12		"[ UNKNOWN12 ]"
@ MSG_SHT_UNKNOWN13		"[ UNKNOWN13 ]"
@ MSG_SHT_INIT_ARRAY		"[ SHT_INIT_ARRAY ]"
@ MSG_SHT_INIT_ARRAY_ALT	"INAR"
@ MSG_SHT_FINI_ARRAY		"[ SHT_FINI_ARRAY ]"
@ MSG_SHT_FINI_ARRAY_ALT	"FNAR"
@ MSG_SHT_PREINIT_ARRAY		"[ SHT_PREINIT_ARRAY ]"
@ MSG_SHT_PREINIT_ARRAY_ALT	"PNAR"
@ MSG_SHT_GROUP			"[ SHT_GROUP ]"
@ MSG_SHT_GROUP_ALT		"GRP "
@ MSG_SHT_SYMTAB_SHNDX		"[ SHT_SYMTAB_SHNDX ]"
@ MSG_SHT_SYMTAB_SHNDX_ALT	"SHDX"

@ MSG_SHT_SUNW_symsort		"[ SHT_SUNW_symsort ]"
@ MSG_SHT_SUNW_symsort_ALT	"SSRT"
@ MSG_SHT_SUNW_tlssort		"[ SHT_SUNW_tlssort ]"
@ MSG_SHT_SUNW_tlssort_ALT	"TSRT"
@ MSG_SHT_SUNW_LDYNSYM		"[ SHT_SUNW_LDYNSYM ]"
@ MSG_SHT_SUNW_LDYNSYM_ALT	"LDSM"
@ MSG_SHT_SUNW_dof		"[ SHT_SUNW_dof ]"
@ MSG_SHT_SUNW_dof_ALT		"DOF "
@ MSG_SHT_SUNW_cap		"[ SHT_SUNW_cap ]"
@ MSG_SHT_SUNW_cap_ALT		"CAP "
@ MSG_SHT_SUNW_SIGNATURE	"[ SHT_SUNW_SIGNATURE ]"
@ MSG_SHT_SUNW_SIGNATURE_ALT	"SIGN"
@ MSG_SHT_SUNW_ANNOTATE		"[ SHT_SUNW_ANNOTATE ]"
@ MSG_SHT_SUNW_ANNOTATE_ALT	"ANOT"
@ MSG_SHT_SUNW_DEBUGSTR		"[ SHT_SUNW_DEBUGSTR ]"
@ MSG_SHT_SUNW_DEBUGSTR_ALT	"DBGS"
@ MSG_SHT_SUNW_DEBUG		"[ SHT_SUNW_DEBUG ]"
@ MSG_SHT_SUNW_DEBUG_ALT	"DBG "
@ MSG_SHT_SUNW_move		"[ SHT_SUNW_move ]"
@ MSG_SHT_SUNW_move_ALT		"MOVE"
@ MSG_SHT_SUNW_COMDAT		"[ SHT_SUNW_COMDAT ]"
@ MSG_SHT_SUNW_COMDAT_ALT	"COMD"
@ MSG_SHT_SUNW_syminfo		"[ SHT_SUNW_syminfo ]"
@ MSG_SHT_SUNW_syminfo_ALT	"SYMI"
@ MSG_SHT_SUNW_verdef		"[ SHT_SUNW_verdef ]"
@ MSG_SHT_SUNW_verdef_ALT	"VERD"
@ MSG_SHT_SUNW_verneed		"[ SHT_SUNW_verneed ]"
@ MSG_SHT_SUNW_verneed_ALT	"VERN"
@ MSG_SHT_SUNW_versym		"[ SHT_SUNW_versym ]"
@ MSG_SHT_SUNW_versym_ALT	"VERS"

@ MSG_SHT_AMD64_UNWIND		"[ SHT_AMD64_UNWIND ]"
@ MSG_SHT_AMD64_UNWIND_ALT	"UNWD"

@ MSG_SHT_SPARC_GOTDATA		"[ SHT_SPARC_GOTDATA ]"
@ MSG_SHT_SPARC_GOTDATA_ALT	"GOTD"

@ MSG_SHN_AFTER		"[ SHN_AFTER ]"
@ MSG_SHN_BEFORE	"[ SHN_BEFORE ]"

@ MSG_SHF_WRITE		"SHF_WRITE"
@ MSG_SHF_ALLOC		"SHF_ALLOC"
@ MSG_SHF_EXECINSTR	"SHF_EXECINSTR"
@ MSG_SHF_MERGE		"SHF_MERGE"
@ MSG_SHF_STRINGS	"SHF_STRINGS"
@ MSG_SHF_INFO_LINK	"SHF_INFO_LINK"
@ MSG_SHF_LINK_ORDER	"SHF_LINK_ORDER"
@ MSG_SHF_OS_NONCONFORMING	"SHF_OS_NONCONFORMING"
@ MSG_SHF_GROUP		"SHF_GROUP"
@ MSG_SHF_TLS		"SHF_TLS"
@ MSG_SHF_EXCLUDE	"SHF_EXCLUDE"
@ MSG_SHF_ORDERED	"SHF_ORDERED"
@ MSG_SHF_AMD64_LARGE	"SHF_AMD64_LARGE"

@ MSG_GBL_ZERO		"0"
