#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"

@ MSG_FLG_SG_VADDR	"FLG_SG_VADDR"
@ MSG_FLG_SG_PADDR	"FLG_SG_PADDR"
@ MSG_FLG_SG_LENGTH	"FLG_SG_LENGTH"
@ MSG_FLG_SG_ALIGN	"FLG_SG_ALIGN"
@ MSG_FLG_SG_ROUND	"FLG_SG_ROUND"
@ MSG_FLG_SG_FLAGS	"FLG_SG_FLAGS"
@ MSG_FLG_SG_TYPE	"FLG_SG_TYPE"
@ MSG_FLG_SG_ORDER	"FLG_SG_ORDER"
@ MSG_FLG_SG_NOHDR	"FLG_SG_NOHDR"
@ MSG_FLG_SG_EMPTY	"FLG_SG_EMPTY"
@ MSG_FLG_SG_KEY	"FLG_SG_KEY"
@ MSG_FLG_SG_DISABLED	"FLG_SG_DISABLED"
@ MSG_FLG_SG_PHREQ	"FLG_SG_PHREQ"

@ MSG_GBL_ZERO		"0"
