#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#

@ MSG_STO_REGISTERG1	"REG_G1"
@ MSG_STO_REGISTERG2	"REG_G2"
@ MSG_STO_REGISTERG3	"REG_G3"
@ MSG_STO_REGISTERG4	"REG_G4"
@ MSG_STO_REGISTERG5	"REG_G5"
@ MSG_STO_REGISTERG6	"REG_G6"
@ MSG_STO_REGISTERG7	"REG_G7"
