#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#

@ MSG_STT_NOTYPE	"NOTY"
@ MSG_STT_OBJECT	"OBJT"
@ MSG_STT_FUNC		"FUNC"
@ MSG_STT_SECTION	"SECT"
@ MSG_STT_FILE		"FILE"
@ MSG_STT_COMMON	"COMM"
@ MSG_STT_TLS		"TLS "
@ MSG_STT_REGISTER	"REGI"

@ MSG_STB_LOCAL		"LOCL"
@ MSG_STB_GLOBAL	"GLOB"
@ MSG_STB_WEAK		"WEAK"

@ MSG_SHN_UNDEF		"UNDEF"
@ MSG_SHN_SUNW_IGNORE	"IGNORE"
@ MSG_SHN_ABS		"ABS"
@ MSG_SHN_COMMON	"COMMON"
@ MSG_SHN_AMD64_LCOMMON	"LCOMMON"
@ MSG_SHN_AFTER		"AFTER"
@ MSG_SHN_BEFORE	"BEFORE"
@ MSG_SHN_XINDEX	"XINDEX"

@ MSG_SYM_FMT_VAL_32	"0x%8.8llx"
@ MSG_SYM_FMT_VAL_64	"0x%16.16llx"
