#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

@ MSG_SYMINFO_FLG_DIRECT_CF		"SYMINFO_FLG_DIRECT"		# 0x01
@ MSG_SYMINFO_FLG_DIRECT_CFNP			"DIRECT"
@ MSG_SYMINFO_FLG_DIRECT_NF			"direct"
@ MSG_SYMINFO_FLG_FILTER_CF		"SYMINFO_FLG_FILTER"		# 0x02
@ MSG_SYMINFO_FLG_FILTER_CFNP			"FILTER"
@ MSG_SYMINFO_FLG_FILTER_NF			"filter"
@ MSG_SYMINFO_FLG_COPY_CF		"SYMINFO_FLG_COPY"		# 0x04
@ MSG_SYMINFO_FLG_COPY_CFNP			"COPY"
@ MSG_SYMINFO_FLG_COPY_NF			"copy"
@ MSG_SYMINFO_FLG_LAZYLOAD_CF		"SYMINFO_FLG_LAZYLOAD"		# 0x08
@ MSG_SYMINFO_FLG_LAZYLOAD_CFNP			"LAZYLOAD"
@ MSG_SYMINFO_FLG_LAZYLOAD_NF			"lazyload"
@ MSG_SYMINFO_FLG_DIRECTBIND_CF		"SYMINFO_FLG_DIRECTBIND"	# 0x10
@ MSG_SYMINFO_FLG_DIRECTBIND_CFNP		"DIRECTBIND"
@ MSG_SYMINFO_FLG_DIRECTBIND_NF			"directbind"
@ MSG_SYMINFO_FLG_NOEXTDIRECT_CF	"SYMINFO_FLG_NOEXTDIRECT"	# 0x20
@ MSG_SYMINFO_FLG_NOEXTDIRECT_CFNP		"NOEXTDIRECT"
@ MSG_SYMINFO_FLG_NOEXTDIRECT_NF		"noextdirect"
@ MSG_SYMINFO_FLG_AUXILIARY_CF		"SYMINFO_FLG_AUXILIARY"		# 0x40
@ MSG_SYMINFO_FLG_AUXILIARY_CFNP		"AUXILIARY"
@ MSG_SYMINFO_FLG_AUXILIARY_NF			"auxiliary"
@ MSG_SYMINFO_FLG_INTERPOSE_CF		"SYMINFO_FLG_INTERPOSE"		# 0x80
@ MSG_SYMINFO_FLG_INTERPOSE_CFNP		"INTERPOSE"
@ MSG_SYMINFO_FLG_INTERPOSE_NF			"interpose"

@ MSG_SYMINFO_BT_EXTERN_CF	"SYMINFO_BT_EXTERN"		# 0xfffc
@ MSG_SYMINFO_BT_EXTERN_CFNP		"EXTERN"
@ MSG_SYMINFO_BT_EXTERN_NF		"extern"
@ MSG_SYMINFO_BT_NONE_CF	"SYMINFO_BT_NONE"		# 0xfffd
@ MSG_SYMINFO_BT_NONE_CFNP		"NONE"
@ MSG_SYMINFO_BT_NONE_NF		"none"
@ MSG_SYMINFO_BT_PARENT_CF	"SYMINFO_BT_PARENT"		# 0xfffe
@ MSG_SYMINFO_BT_PARENT_CFNP		"PARENT"
@ MSG_SYMINFO_BT_PARENT_NF		"parent"
@ MSG_SYMINFO_BT_SELF_CF	"SYMINFO_BT_SELF"		# 0xffff
@ MSG_SYMINFO_BT_SELF_CFNP		"SELF"
@ MSG_SYMINFO_BT_SELF_NF		"self"


@ MSG_GBL_ZERO			"0"
