#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
#

#
# NAME
#       passwd.exp
#
# DESCRIPTION
#       The Expect script will change the passwd of a user
#


set timeout 5
set name [lindex $argv 0]
set passwd [lindex $argv 1]

spawn passwd  $name
expect {
	timeout {
		send "\r"
		send_error "\n passwd is time out\n"
		exit 1
	}

	"User unknown:" {
		send_error "\n User $name doesn't exist\n"
		exit 1
	}

	"New Password" {
		send "$passwd\r"
		sleep 2
		expect {
			timeout {
				send "\r"
				send_error "\n passwd is time out\n"
				exit 1
			}
			"Re-enter new Password:" {
				send "$passwd\r"
				sleep 2
			}
		}
	}
}

send_user "\n"
exit 0
