#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#

include		$(SRC)/Makefile.master
include		../../../Makefile.com

ROOTTESTDIR=	$(ROOTOPTPKG)/tests/smbfs/mmap

TESTS=	\
		tp_mmap_001	\
		tp_mmap_002	\
		tp_mmap_003	\
		tp_mmap_004	\
		tp_mmap_005	\
		tp_mmap_006	\
		tp_mmap_007	\
		tp_mmap_008	\
		tp_mmap_009	\
		tp_mmap_010

include		../../Makefile.tests
