
/* : : generated by proto : : */
/***********************************************************************
*                                                                      *
*               This software is part of the ast package               *
*           Copyright (c) 1985-2007 AT&T Knowledge Ventures            *
*                      and is licensed under the                       *
*                  Common Public License, Version 1.0                  *
*                      by AT&T Knowledge Ventures                      *
*                                                                      *
*                A copy of the License is available at                 *
*            http://www.opensource.org/licenses/cpl1.0.txt             *
*         (with md5 checksum 059e8cd6165cb4c31e351f2b69388fd9)         *
*                                                                      *
*              Information and Software Systems Research               *
*                            AT&T Research                             *
*                           Florham Park NJ                            *
*                                                                      *
*                 Glenn Fowler <gsf@research.att.com>                  *
*                  David Korn <dgk@research.att.com>                   *
*                   Phong Vo <kpv@research.att.com>                    *
*                                                                      *
***********************************************************************/
                  
/*
 * legacy standard getopt interface
 */

#ifndef _AST_GETOPT_H
#if !defined(__PROTO__)
#include <prototyped.h>
#endif
#if !defined(__LINKAGE__)
#define __LINKAGE__		/* 2004-08-11 transition */
#endif

#define _AST_GETOPT_H		1

extern __MANGLE__ int	opterr;
extern __MANGLE__ int	optind;
extern __MANGLE__ int	optopt;
extern __MANGLE__ char*	optarg;

#ifndef NULL	/* in case <stdlib.h> or <stdio.h> got here first */

extern __MANGLE__ int	getopt __PROTO__((int, char* const*, const char*));
extern __MANGLE__ int	getsubopt __PROTO__((char**, char* const*, char**));

#endif

#endif
