#!/sbin/sh
#
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
# Copyright 2012 Joyent, Inc.  All rights reserved.
#

. /lib/svc/share/smf_include.sh

# Trusted Extensions non-global zones need special handling

if (smf_is_system_labeled); then
	if (smf_is_nonglobalzone); then
		if [ ! -f /var/tsol/doors/nscd_per_label ]; then

			# If needed create a door to the global zone daemon.
			if [ -r /var/run/name_service_door ]; then
				rm /var/run/name_service_door
			fi
			ln -s /var/tsol/doors/name_service_door  \
				/var/run || exit $SMF_EXIT_ERR_FATAL

			# If current service duration is not "transient",
			# create a dummy background process to preserve
			# contract lifetime.
			duration=""
			if /bin/svcprop -q -c -p startd/duration $SMF_FMRI
			    then
				duration=`/bin/svcprop -c -p startd/duration  \
					$SMF_FMRI`
			fi
			if [ "$duration" != "transient" ]; then
				[ -n "$SMF_EXIT_NODAEMON" ] && \
				    exit $SMF_EXIT_NODAEMON
				(while true ; do sleep 3600 ; done) &
			fi

			# The real daemon is not started in non-global zones,
			# so exit now.
			exit $SMF_EXIT_OK
		else
			# remove the door to the global zone daemon
			if [ -L /var/run/name_service_door ]; then
				rm /var/run/name_service_door
			fi
		fi
	fi
fi

if [ -f /etc/nscd.conf -a -f /usr/sbin/nscd ]; then
	/usr/sbin/nscd < /dev/null > /dev/msglog 2>&1 &
else
	echo "No /etc/nscd.conf or no /usr/sbin/nscd"
	exit $SMF_EXIT_ERR_CONFIG
fi
