'\" te
.\" Copyright (c) 1992, Sun Microsystems, Inc.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH MS 5 "Feb 25, 1992"
.SH NAME
ms \- text formatting macros
.SH SYNOPSIS
.LP
.nf
\fBnroff\fR  \fB-ms\fR [\fIoptions\fR] \fIfilename\fR...
.fi

.LP
.nf
\fBtroff\fR  \fB-ms\fR [\fIoptions\fR] \fIfilename\fR...
.fi

.SH DESCRIPTION
.sp
.LP
This package of \fBnroff\fR(1) and \fBtroff\fR(1) macro definitions provides a
formatting facility for various styles of articles, theses, and books. When
producing 2-column output on a terminal or lineprinter, or when reverse line
motions are needed, filter the output through \fBcol\fR(1). All external
\fB-ms\fR macros are defined below.
.sp
.LP
Note: this  \fB-ms\fR macro package is an extended version written at Berkeley
and is a superset of the standard  \fB-ms\fR macro packages as supplied by Bell
Labs.  Some of the Bell Labs macros have been removed; for instance, it is
assumed that the user has little interest in producing headers stating that the
memo was generated at Whippany Labs.
.sp
.LP
Many \fBnroff\fR and \fBtroff\fR requests are unsafe in conjunction with this
package. However, the first four requests below may be used with impunity after
initialization, and the last two may be used even before initialization:
.sp
.ne 2
.na
\fB\fB\&.bp\fR\fR
.ad
.RS 11n
begin new page
.RE

.sp
.ne 2
.na
\fB\fB\&.br\fR\fR
.ad
.RS 11n
break output line
.RE

.sp
.ne 2
.na
\fB\fB\&.sp\fR\fI n\fR\fR
.ad
.RS 11n
insert n spacing lines
.RE

.sp
.ne 2
.na
\fB\fB\&.ce\fR\fI n\fR\fR
.ad
.RS 11n
center next n lines
.RE

.sp
.ne 2
.na
\fB\fB\&.ls\fR\fI n\fR\fR
.ad
.RS 11n
line spacing: \fIn\fR\fB=1\fR single, \fIn\fR\fB=2\fR double space
.RE

.sp
.ne 2
.na
\fB\fB\&.na\fR\fR
.ad
.RS 11n
no alignment of right margin
.RE

.sp
.LP
Font and point size changes with \fB\ef\fR and \fB\es\fR are also allowed; for
example, \fB\efIword\efR\fR will italicize \fIword\fR. Output of the
\fBtbl\fR(1), \fBeqn\fR(1) and \fBrefer\fR(1) preprocessors for equations,
tables, and references is acceptable as input.
.SH REQUESTS
.sp

.sp
.TS
c | c | c | c
l | l | l | l .
Macro Name	Initial Value	Break? Reset?	Explanation
_
\fB\&.AB\fR \fIx\fR	-	y	T{
begin abstract; if \fIx\fR=no do not label abstract
T}
_
\fB\&.AE\fR	-	y	end abstract
_
\fB\&.AI\fR	-	y	author's institution
_
\fB\&.AM\fR	-	n	better accent mark definitions
_
\fB\&.AU\fR	-	y	author's name
_
\fB\&.B\fR \fIx\fR	-	n	embolden \fIx\fR; if no \fIx\fR, switch to boldface
_
\fB\&.B1\fR	-	y	begin text to be enclosed in a box
_
\fB\&.B2\fR	-	y	end boxed text and print it
_
\fB\&.BT\fR	date	n	bottom title, printed at foot of page
_
\fB\&.BX\fR \fIx\fR	-	n	print word \fIx\fR in a box
_
\fB\&.CM\fR	if t	n	cut mark between pages
_
\fB\&.CT\fR	-	y,y	T{
chapter title: page number moved to CF (TM only)
T}
_
\fB\&.DA\fR \fIx\fR	if n	n	T{
force date \fIx\fR at bottom of page; today if no \fIx\fR
T}
_
\fB\&.DE\fR	-	y	end display (unfilled text) of any kind
_
\fB\&.DS\fR \fIx y\fR	I	y	T{
begin display with keep; \fIx\fR=I,\|L,\|C,\|B; \fIy\fR=indent
T}
_
\fB\&.ID\fR\fI y\fR	8n,.5i	y	indented display with no keep; \fIy\fR=indent
_
\fB\&.LD\fR	-	y	left display with no keep
_
\fB\&.CD\fR	-	y	centered display with no keep
_
\fB\&.BD\fR	-	y	block display; center entire block
_
\fB\&.EF\fR \fIx\fR	-	n	even page footer \fIx\fR (3 part as for \fB\&.tl\fR)
_
\fB\&.EH\fR \fIx\fR	-	n	even page header \fIx\fR (3 part as for \fB\&.tl\fR)
_
\fB\&.EN\fR	-	y	end displayed equation produced by \fBeqn\fR
_
\fB\&.EQ\fR \fIx y\fR	-	y	T{
break out equation; \fIx\fR=L,I,C; \fIy\fR=equation number
T}
_
\fB\&.FE\fR	-	n	T{
end footnote to be placed at bottom of page
T}
_
\fB\&.FP\fR	-	n	T{
numbered footnote paragraph; may be redefined
T}
_
\fB\&.FS\fR \fIx\fR	-	n	T{
start footnote; \fIx\fR is optional footnote label
T}
_
\fB\&.HD\fR	undef	n	optional page header below header margin
_
\fB\&.I\fR \fIx\fR	-	n	italicize \fIx\fR; if no \fIx\fR, switch to italics
_
\fB\&.IP\fR \fIx y\fR	-	y,y	T{
indented paragraph, with hanging tag \fIx\fR; \fIy\fR=indent
T}
_
\fB\&.IX\fR \fIx y\fR	-	y	T{
index words \fIx\fR \fIy\fR and so on (up to 5 levels)
T}
_
\fB\&.KE\fR	-	n	end keep of any kind
_
\fB\&.KF\fR	-	n	T{
begin floating keep; text fills remainder of page
T}
_
\fB\&.KS\fR	-	y	T{
begin keep; unit kept together on a single page
T}
_
\fB\&.LG\fR	-	n	larger; increase point size by 2
_
\fB\&.LP\fR	-	y,y	left (block) paragraph.
_
\fB\&.MC\fR \fIx\fR	-	y,y	multiple columns; \fIx\fR=column width
_
\fB\&.ND\fR \fIx\fR	if t	n	T{
no date in page footer; \fIx\fR is date on cover
T}
_
\fB\&.NH\fR \fIx y\fR	-	y,y	T{
numbered header; \fIx\fR=level, \fIx\fR=0 resets, \fIx\fR=S sets to \fIy\fR
T}
_
\fB\&.NL\fR	10p	n	set point size back to normal
_
\fB\&.OF\fR \fIx\fR	-	n	odd page footer \fIx\fR (3 part as for \fB\&.tl\fR)
_
\fB\&.OH\fR \fIx\fR	-	n	odd page header \fIx\fR (3 part as for \fB\&.tl\fR)
_
\fB\&.P1\fR	if TM	n	print header on first page
_
\fB\&.PP\fR	-	y,y	paragraph with first line indented
_
\fB\&.PT\fR	- % -	n	page title, printed at head of page
_
\fB\&.PX\fR \fIx\fR	-	y	T{
print index (table of contents); \fIx\fR=no suppresses title
T}
_
\fB\&.QP\fR	-	y,y	quote paragraph (indented and shorter)
_
\fB\&.R\fR	on	n	return to Roman font
_
\fB\&.RE\fR	5n	y,y	T{
retreat: end level of relative indentation
T}
_
\fB\&.RP\fR \fIx\fR	-	n	T{
released paper format; \fIx\fR=no stops title on first page
T}
_
\fB\&.RS\fR	5n	y,y	T{
right shift: start level of relative indentation
T}
_
\fB\&.SH\fR	-	y,y	section header, in boldface
_
\fB\&.SM\fR	-	n	smaller; decrease point size by 2
_
\fB\&.TA\fR	8n,5n	n	T{
set TAB characters to 8n 16n .\|.\|. (\fBnroff\fR)  or 5n 10n .\|.\|. (\fBtroff\fR)
T}
_
\fB\&.TC\fR \fIx\fR	-	y	T{
print table of contents at end; \fIx\fR=no suppresses title
T}
_
_
\fB\&.TH\fR - Y "multi-page end, header"
_
\fB\&.TL\fR	-	y	title in boldface and two points larger
_
\fB\&.TM\fR	off	n	UC Berkeley thesis mode
_
\fB\&.TE\fR	-	y	end of table processed by \fBtbl\fR
\fB\&.TS\fR \fIx\fR	-	y,y	T{
begin table; if \fIx\fR=H table has multi-page header
T}
_
\fB\&.UL\fR \fIx\fR	-	n	underline \fIx\fR, even in \fBtroff\fR
_
\fB\&.UX\fR \fIx\fR	-	n	T{
UNIX; trademark message first time; \fIx\fR appended
T}
_
\fB\&.XA\fR \fIx y\fR	-	y	T{
another index entry; \fIx\fR=page or no for none;  y=indent
T}
_
\fB\&.XE\fR	-	y	T{
end index entry (or series of \fB\&.IX\fR entries)
T}
_
\fB\&.XP\fR	-	y,y	T{
paragraph with first line indented, others indented
T}
_
\fB\&.XS\fR \fIx y\fR	-	y	T{
begin index entry; \fIx\fR=page or no for none; \fIy\fR=indent
T}
_
\fB\&.1C\fR	on	y,y	one column format, on a new page
_
\fB\&.2C\fR	-	y,y	begin two column format
_
\fB\&.]\|-\fR	-	n	beginning of \fBrefer\fR reference
_
\fB\&.[\|0\fR	-	n	end of unclassifiable type of reference
_
\fB\&.[\|N\fR	-	n	T{
N= 1:journal-article, 2:book, 3:book-article, 4:report
T}
.TE

.SH REGISTERS
.sp
.LP
Formatting distances can be controlled in \fB-ms\fR by means of built-in number
registers. For example, this sets the line length to 6.5 inches:
.sp
.in +2
.nf
\&.nr  LL  6.5i
.fi
.in -2

.sp
.LP
Here is a table of number registers and their default values:
.sp

.sp
.TS
c | c | c | c
l | l | l | l .
Name	Register Controls	Takes Effect	Default
_
\fBPS\fR	point size      	paragraph	10
_
\fBVS\fR	vertical spacing	paragraph	12
_
\fBLL\fR	line length     	paragraph	6i
_
\fBLT\fR	title length    	next page	same as \fBLL\fR
_
\fBFL\fR	footnote length 	next \fB\&.FS\fR	5.5i
_
\fBPD\fR	paragraph distance	paragraph	1v (if n), .3v (if t)
_
\fBDD\fR	display distance	displays	1v (if n), .5v (if t)
_
\fBPI\fR	paragraph indent	paragraph	5n
_
\fBQI\fR	quote indent    	next \fB\&.QP\fR	5n
_
\fBFI\fR	footnote indent 	next \fB\&.FS\fR	2n
_
\fBPO\fR	page offset     	next page	0 (if n), \(ap1i (if t)
_
\fBHM\fR	header margin   	next page	1i
_
\fBFM\fR	footer margin   	next page	1i
_
\fBFF\fR	footnote format 	next \fB\&.FS\fR	0 (1, 2, 3 available)
.TE

.sp
.LP
When resetting these values, make sure to specify the appropriate units.
Setting the line length to 7, for example, will result in output with one
character per line. Setting \fBFF\fR to 1 suppresses footnote superscripting;
setting it to 2 also suppresses indentation of the first line; and setting it
to 3 produces an \fB\&.IP\fR-like footnote paragraph.
.sp
.LP
Here is a list of string registers available in \fB-ms\fR; they may be used
anywhere in the text:
.sp

.sp
.TS
c | c
l | l .
Name	String's Function
_
\fB\e*Q\fR	quote (\fB"\fR in \fBnroff,\fR\| \fB"\fR in \fBtroff\fR )
_
\fB\e*U\fR 	unquote (\fB"\fR in \fBnroff,\fR\| \fB"\fR in \fBtroff\fR )
_
\fB\e*-\fR	dash (\fB--\fR in \fBnroff,\fR \fB\(em\fR in \fBtroff\fR )
_
\fB\e*(MO\fR	month (month of the year)
_
\fB\e*(DY\fR	day (current date)
_
\fB\e**\fR	automatically numbered footnote
_
\fB\e*'\fR	acute accent (before letter)
_
\fB\e*`\fR	grave accent (before letter)
_
\fB\e*^\fR	circumflex (before letter)
_
\fB\e*,\fR	cedilla (before letter)
_
\fB\e*:\fR	umlaut (before letter)
_
\fB\e*~\fR	tilde (before letter)
.TE

.sp
.LP
When using the extended accent mark definitions available with \fB\&.AM\fR,
these strings should come after, rather than before, the letter to be accented.
.SH FILES
.sp
.ne 2
.na
\fB\fB/usr/share/lib/tmac/s\fR\fR
.ad
.RS 30n

.RE

.sp
.ne 2
.na
\fB\fB/usr/share/lib/tmac/ms.???\fR\fR
.ad
.RS 30n

.RE

.SH SEE ALSO
.sp
.LP
\fBcol\fR(1), \fBeqn\fR(1), \fBnroff\fR(1), \fBrefer\fR(1), \fBtbl\fR(1),
\fBtroff\fR(1)
.SH BUGS
.sp
.LP
Floating keeps and regular keeps are diverted to the same space, so they cannot
be mixed together with predictable results.
