#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2025 Oxide Computer Company
#

SCRIPTS = \
	cleanup \
	i2cadm-io \
	i2cadm-map \
	i2cadm-scan \
	i2cadm \
	mux-active-cleanup \
	setup-full

FILES = common.ksh

TESTDIR = i2cadm

include $(SRC)/test/i2c-tests/tests/Makefile.com
