'\" te
.\"  Copyright 1989 AT&T  Copyright (c) 2000, Sun Microsystems, Inc.  All Rights Reserved
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH SETPGRP 2 "Jan 5, 2000"
.SH NAME
setpgrp \- set process group ID
.SH SYNOPSIS
.LP
.nf
#include <sys/types.h>
#include <unistd.h>

\fBpid_t\fR \fBsetpgrp\fR(\fBvoid\fR);
.fi

.SH DESCRIPTION
.sp
.LP
If the calling process is not already a session leader, the \fBsetpgrp()\fR
function makes it one by setting its process group \fBID\fR and session
\fBID\fR to the value of its process \fBID\fR, and releases its controlling
terminal. See \fBIntro\fR(2) for more information on process group \fBID\fRs
and session leaders.
.SH RETURN VALUES
.sp
.LP
The \fBsetpgrp()\fR function returns the value of the new process group
\fBID\fR.
.SH ERRORS
.sp
.LP
No errors are defined.
.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
box;
c | c
l | l .
ATTRIBUTE TYPE	ATTRIBUTE VALUE
_
Interface Stability	Standard
.TE

.SH SEE ALSO
.sp
.LP
\fBsetpgrp\fR(1), \fBIntro\fR(2), \fBexec\fR(2), \fBfork\fR(2),
\fBgetpid\fR(2), \fBgetsid\fR(2), \fBkill\fR(2), \fBsignal\fR(3C),
\fBattributes\fR(5), \fBstandards\fR(5)
