#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# SUNWcti2 postinstall script
#

PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

DEVLINKTB="${BASEDIR}/etc/devlink.tab"

if test ! -f ${DEVLINKTB} -o ! -w ${DEVLINKTB}; then
	echo "SUNWcti2: file ${DEVLINKTB} is missing/inaccessible." >&2
	exit 1
fi

trap "rm -f /tmp/$$.*;exit 1" 1 2 3 13 15
TMP=/tmp/$$

#
# rem_devlink - removes an entry from ${DEVLINKTB}
#
rem_devlink()
{
	PATTERN="$1"
	LINK="$2"
	PLINK="`echo $LINK | sed 's/[$*^|\]/\\\&/g'`"
	grep -v "^$PATTERN      $PLINK$" ${DEVLINKTB} >$TMP.devlink
	#
	#  Must use 'cp' here in order to preserve the original
	#  mode, owner and group of devlink.tab
	#
	cp $TMP.devlink ${DEVLINKTB}
	rm -f $TMP.devlink
}

not_installed() {
	driver=$1
	grep "^${driver} " ${BASEDIR}/etc/name_to_major > /dev/null 2>&1
	return $?
}

EXIT=0

rem_devlink 'type=ddi_pseudo;name=scsb' 'pcihpc/scsb\N0'
not_installed acebus || add_drv -b ${BASEDIR} -n acebus || EXIT=1
not_installed scsb || add_drv -b ${BASEDIR} -i '"nct-ATML,at27c64"' -n scsb || EXIT=1

exit $EXIT
