#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 1995-2002 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#pragma ident	"%Z%%M%	%I%	%E% SMI"
#
PATH=/usr/sadm/bin:$PATH

#
# figure out CLASSES to install
#
CLASSES="none"

#
#determine the version of SDS. 
# Classify into 3 group, SLVM, 421 and pre421
#
#Need to check if its an update, ie someone is simply pkgadding because
# a file was deleted.
#

#if we were upgrading from pre SDS 4.2.1, legacy class action script needs to
# be run to create symlinks from old to the new location.

if [ "$UPDATE" != "yes" ]; then
	pkginfo -R ${PKG_INSTALL_ROOT:-/} -q SUNWmd\*;
	if [ $? -eq 0 ]; then
		CLASSES="${CLASSES} legacy"
	fi
fi

#
# export environment variables to install
#
echo CLASSES="${CLASSES}" >> $1

exit 0
