
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

# Copyright 2018, Richard Lowe.

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results

[/opt/elf-tests/tests/linker-sets]
tests = ['simple', 'in-use-check']

[/opt/elf-tests/tests/assert-deflib]
tests = ['test-deflib']

[/opt/elf-tests/tests/tls/amd64/ie]
arch = i86pc
tests = ['amd64-ie-test']

[/opt/elf-tests/tests/tls/i386/ld]
arch = i86pc
tests = ['i386-ld-test']

[/opt/elf-tests/tests/tls/amd64/ld]
arch = i86pc
tests = ['amd64-ld-test']
