#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# ident	"%Z%%M%	%I%	%E% SMI"
# Copyright (c) 1999, by Sun Microsystems, Inc.
# All rights reserved.
#
# This filter accepts a pmHelpResources.java file as input
# and produces formatted HTML as output.
# 

while read line; do
	echo "$line" | grep '^.*{".*\.tag"' > /dev/null
	if [[ $? == 0 ]]; then
		print -n "<br> <h2> "
		print -n `echo "$line" | sed s/'\.'/\ / | \
				sed s/\"/\ /g | awk '{print \$2}'`
		print " </h2>"
	fi

	echo "$line" | grep '^\".*+$' | sed s/^\"//g | sed s/\"\ +\$//

done
