#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 Joyent, Inc.
#

[DEFAULT]
outputdir = /var/tmp/test_results
quiet = False
timeout = 60

[/opt/net-tests/tests/forwarding]
tests = [
	'ip_fwd_no_cksum',
	'ip_fwd_partial_cksum',
	'ip_fwd_full_cksum',
	'ip_fwd_partial_cksum_lso',
	'ip_fwd_full_cksum_lso'
	]
user = root
