#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
# Copyright 2019 Joyent, Inc.
#

[DEFAULT]
pre =
verbose = False
quiet = False
#
# Unfortunately, if the tpm based PKCS11 library is present, libtspi will make
# socket calls left and right that take a bit to timeout which induce latency
# into every test case. Bump the timeout until this is no longer a problem.
#
timeout = 250
post =
outputdir = /var/tmp/test_results

[/opt/crypto-tests/tests/aes/pkcs]
tests = ['aes_cbc_32', 'aes_ccm_32', 'aes_cmac_32',
         'aes_ctr_32', 'aes_ecb_32', 'aes_gcm_32',
         'aes_cbc_64', 'aes_ccm_64', 'aes_cmac_64',
         'aes_ctr_64', 'aes_ecb_64', 'aes_gcm_64']

[/opt/crypto-tests/tests/aes/kcf]
pre = setup
user = root
tests = ['aes_cbc_32', 'aes_ccm_32', 'aes_cmac_32',
         'aes_ctr_32', 'aes_ecb_32', 'aes_gcm_32',
         'aes_cbc_64', 'aes_ccm_64', 'aes_cmac_64',
         'aes_ctr_64', 'aes_ecb_64', 'aes_gcm_64']
post = cleanup

[/opt/crypto-tests/tests/digest/pkcs]
tests = ['sha1_32', 'sha256_32', 'sha384_32', 'sha512_32', 'sha512_224_32',
         'sha512_256_32', 'md5_32',
         'sha1_64', 'sha256_64', 'sha384_64', 'sha512_64', 'sha512_224_64',
         'sha512_256_64', 'md5_64' ]

[/opt/crypto-tests/tests/digest/kcf]
pre = setup
user = root
tests = ['sha1_32', 'sha256_32', 'sha384_32', 'sha512_32', 'sha512_224_32',
         'sha512_256_32', 'md5_32',
         'sha1_64', 'sha256_64', 'sha384_64', 'sha512_64', 'sha512_224_64',
         'sha512_256_64', 'md5_64' ]
post = cleanup

[/opt/crypto-tests/tests/hmac/pkcs]
tests = ['hmac_sha1_32', 'hmac_sha1_64']

[/opt/crypto-tests/tests/hmac/kcf]
pre = setup
user = root
tests = ['hmac_sha1_32', 'hmac_sha1_64']
post = cleanup

[/opt/crypto-tests/tests/longhash]
tests = ['longhash_32', 'longhash_64']
