#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
# Copyright 2018, Joyent, Inc.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results

[/opt/crypto-tests/tests/pkcs/aes]
tests = ['aes_cbc', 'aes_ccm', 'aes_cmac', 'aes_ctr', 'aes_ecb', 'aes_gcm']

[/opt/crypto-tests/tests/kcf/aes]
pre = setup
user = root
tests = ['aes_cbc', 'aes_ccm', 'aes_cmac', 'aes_ctr', 'aes_ecb', 'aes_gcm']
post = cleanup

[/opt/crypto-tests/tests/digest/pkcs]
tests = ['sha1', 'sha256', 'sha384', 'sha512']

[/opt/crypto-tests/tests/digest/kcf]
pre = setup
user = root
tests = ['sha1', 'sha256', 'sha384', 'sha512']
post = cleanup
