#! /bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

#
# remove_minor - removes minor node in /dev for passed driver
#
#    Usage:	remove_minor {driver_name}
#
remove_minor()
{
	DRIVER="$1"
	DEVNODE="${BASEDIR}/dev/${DRIVER}"
	rm -f $DEVNODE
}

#
# We remove any dangling /dev links in this order:
#
#    SPARC:
#	/dev/pem
#
#    x86:
#	/dev/ra
#	/dev/pcic
#	/dev/pem
#
case "${ARCH}" in
	sparc)
		;;
	i386)
		remove_minor ra
		remove_minor pcic
		;;
esac

remove_minor pem

#
# remove all traces of the former pcmcia nexus.  This allows upgrade
# to work and not leave the system unbootable
#
grep pcmcia ${BASEDIR}/etc/name_to_major >/dev/null &&
rem_drv -b ${BASEDIR} pcmcia

[ -c ${BASEDIR}/dev/pcmcia ] && rm -f ${BASEDIR}/dev/pcmcia

#
# make sure we don't have left over /dev/ra, /dev/pcic
#
[ ! -h ${BASEDIR}/dev/ra ]      && rm -f ${BASEDIR}/dev/ra
[ ! -h ${BASEDIR}/dev/pcic ]    && rm -f ${BASEDIR}/dev/pcic

exit 0
