#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results
user =

[/opt/smbclient-tests/tests/smbutil]
tests = ['tp_smbutil_001', 'tp_smbutil_002', 'tp_smbutil_003', 'tp_smbutil_004',
	'tp_smbutil_005', 'tp_smbutil_006', 'tp_smbutil_007', 'tp_smbutil_008',
	'tp_smbutil_009', 'tp_smbutil_010', 'tp_smbutil_011', 'tp_smbutil_012',
	'tp_smbutil_013', 'tp_smbutil_014', 'tp_smbutil_015', 'tp_smbutil_016']
