#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results
user =

[/opt/smbclient-tests/tests/smbmount]
tests = ['tp_smbmount_001', 'tp_smbmount_002', 'tp_smbmount_003',
	'tp_smbmount_004', 'tp_smbmount_005', 'tp_smbmount_006',
	'tp_smbmount_007', 'tp_smbmount_008', 'tp_smbmount_009',
	'tp_smbmount_010', 'tp_smbmount_011', 'tp_smbmount_012',
	'tp_smbmount_013', 'tp_smbmount_014', 'tp_smbmount_015',
	'tp_smbmount_016']
