#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results
user =

[/opt/smbclient-tests/tests/smbfs/acl]
tests = ['tp_acl_001', 'tp_acl_002', 'tp_acl_003', 'tp_acl_004', 'tp_acl_005']

[/opt/smbclient-tests/tests/smbfs/cptest]
tests = ['tp_cptest_001', 'tp_cptest_002', 'tp_cptest_003', 'tp_cptest_004',
	'tp_cptest_005', 'tp_cptest_006', 'tp_cptest_007', 'tp_cptest_008',
	'tp_cptest_009']
timeout = 600

[/opt/smbclient-tests/tests/smbfs/create]
tests = ['tp_create_001', 'tp_create_002', 'tp_create_003', 'tp_create_004',
	'tp_create_005', 'tp_create_006', 'tp_create_007', 'tp_create_008',
	'tp_create_009', 'tp_create_010', 'tp_create_011', 'tp_create_012']
timeout = 300

[/opt/smbclient-tests/tests/smbfs/error]
tests = ['tp_error_001', 'tp_error_002']

[/opt/smbclient-tests/tests/smbfs/misc]
tests = ['tp_misc_001', 'tp_misc_002', 'tp_misc_003']

[/opt/smbclient-tests/tests/smbfs/mkdir]
tests = ['tp_mkdir_001', 'tp_mkdir_002', 'tp_mkdir_003', 'tp_mkdir_004',
	'tp_mkdir_005', 'tp_mkdir_006']

[/opt/smbclient-tests/tests/smbfs/mmap]
tests = ['tp_mmap_001', 'tp_mmap_002', 'tp_mmap_003', 'tp_mmap_004',
	'tp_mmap_005', 'tp_mmap_006', 'tp_mmap_007', 'tp_mmap_008',
	'tp_mmap_009', 'tp_mmap_010']

[/opt/smbclient-tests/tests/smbfs/mvtest]
tests = ['tp_mvtest_001', 'tp_mvtest_002', 'tp_mvtest_003', 'tp_mvtest_004',
	'tp_mvtest_005', 'tp_mvtest_006', 'tp_mvtest_007']

[/opt/smbclient-tests/tests/smbfs/xattr]
tests = ['tp_xattr_001', 'tp_xattr_002', 'tp_xattr_003', 'tp_xattr_004',
	'tp_xattr_005', 'tp_xattr_006', 'tp_xattr_007', 'tp_xattr_008',
	'tp_xattr_009']
