#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2015, 2016 by Delphix. All rights reserved.
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
timeout = 0
post = cleanup
outputdir = /var/tmp/test_results

[/opt/smbclient-tests/tests/performance/filebench]
tests = ['tp_filebench_001', 'tp_filebench_002', 'tp_filebench_003',
	'tp_filebench_004', 'tp_filebench_005']
