#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
# Copyright 2019 Peter Tribble.
#

#
# This Makefile defines the build rules for the shared dr
# module used by uts/sun4u/starcat.
#

#
# Section 1a: C object build rules
#

$(OBJS_DIR)/%.o:		$(UTSBASE)/sun4u/ngdr/io/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

NGDR_IO=	$(UTSBASE)/sun4u/ngdr/io
SBD_IOCTL=	$(UTSBASE)/sun4u/sys/sbd_ioctl.h
SBDGENERR=	$(NGDR_IO)/sbdgenerr.pl
SBDGENERRCMD=   $(PERL) $(SBDGENERR)

CLEANFILES +=	$(NGDR_IO)/dr_err.c

$(NGDR_IO)/dr_err.c:	$(SBDGENERR) $(SBD_IOCTL)
	$(RM) $@
	$(SBDGENERRCMD) ESBD < $(SBD_IOCTL) > $(NGDR_IO)/dr_err.c

#
# Section 1b: Lint object build rules
#

$(LINTS_DIR)/%.ln:		$(UTSBASE)/sun4u/ngdr/io/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

