#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#

include		$(SRC)/Makefile.master
include		../../../Makefile.com

ROOTTESTDIR=	$(ROOTOPTPKG)/tests/smbfs/acl

TESTS=	\
		tp_acl_001	\
		tp_acl_002	\
		tp_acl_003	\
		tp_acl_004	\
		tp_acl_005

include		../../Makefile.tests
