#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/libsasl/spec/Makefile.targ
#

LIBRARY	=	libsasl.a
VERS	=	.1

OBJECTS	=	sasl.o

SPECCPP =	-I..
