'\" te
.\"  Copyright 1989 AT&T  Copyright (c) 2004 Sun Microsystems, Inc. - All Rights Reserved.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH RPC.SPRAYD 8 "Nov 4, 2004"
.SH NAME
rpc.sprayd, sprayd \- spray server
.SH SYNOPSIS
.LP
.nf
\fB/usr/lib/netsvc/spray/rpc.sprayd\fR
.fi

.SH DESCRIPTION
.sp
.LP
\fBrpc.sprayd\fR is a server that records the packets sent by \fBspray\fR(8).
The \fBrpc.sprayd\fR daemon may be started by \fBinetd\fR(8) or
\fBlisten\fR(8).
.sp
.LP
The service provided by \fBrpc.sprayd\fR is not useful as a networking
benchmark as it uses unreliable connectionless transports, (udp for example).
It can report a large number of packets dropped when the drops were caused by
the program sending packets faster than they can be buffered locally (before
the packets get to the network medium).
.SH SEE ALSO
.sp
.LP
\fBsvcs\fR(1), \fBinetadm\fR(8), \fBinetd\fR(8) \fBattributes\fR(7),
.BR smf (7),
.BR listen (8),
.BR pmadm (8),
.BR sacadm (8),
.BR spray (8),
.BR svcadm (8)
.SH NOTES
.sp
.LP
The \fBrpc.sprayd\fR service is managed by the service management facility,
\fBsmf\fR(7), under the service identifier:
.sp
.in +2
.nf
svc:/network/rpc/spray:default
.fi
.in -2
.sp

.sp
.LP
Administrative actions on this service, such as enabling, disabling, or
requesting restart, can be performed using \fBsvcadm\fR(8). Responsibility for
initiating and restarting this service is delegated to \fBinetd\fR(8). Use
\fBinetadm\fR(8) to make configuration changes and to view configuration
information for this service. The service's status can be queried using the
\fBsvcs\fR(1) command.
