# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#pragma ident	"%Z%%M%	%I%	%E% SMI"
#

include ../Makefile.com

all: $(FILES) depend
install: all pkg    

include ../Makefile.targ


