#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"

include $(SRC)/Makefile.master

PKGARCHIVE = $(CODEMGR_WS)/pkgarchive/$(MACH)
PACKAGE :sh= basename `pwd`
ROOTOPTPKG = $(ROOT)/opt/$(PACKAGE)
PSTAMP :sh= echo "`echo \$LOGNAME`:`date +%Y-%m-%d`:`basename \$CODEMGR_WS`"

DATAFILES = copyright depend
FILES = $(DATAFILES) pkginfo prototype_com prototype_$(MACH)

CLEANFILES = $(DATAFILES) pkginfo awk_pkginfo ../bld_awk_pkginfo
CLOBBERFILES = $(PKGARCHIVE)/$(PACKAGE)

.KEEP_STATE:

all: $(FILES)

lint:

clean:
	$(RM) $(CLEANFILES)

clobber: clean
	$(RM) -r $(CLOBBERFILES)

$(PKGARCHIVE):
	[ -d $(PKGARCHIVE) ] || mkdir -p $(PKGARCHIVE)

$(DATAFILES): ../common/$$@
	 $(RM) $@; cp ../common/$@ $@

awk_pkginfo: ../bld_awk_pkginfo
	../bld_awk_pkginfo -m $(MACH) -p "$(RELEASE)/$(VERSION)/$(USER)" -o $@

pkginfo: pkginfo.tmpl awk_pkginfo
	$(RM) $@; nawk -f awk_pkginfo $@.tmpl > $@

pkg: $(PKGARCHIVE) FRC
	pkgmk -f prototype_$(MACH) -d $(PKGARCHIVE) -r $(ROOT) -o \
		-p $(PSTAMP) $(PACKAGE)

../%: ../common/%.ksh
	$(RM) $@
	cp $< $@
	chmod +x $@

$(ROOTOPTPKG)/%: ../common/%
	$(RM) $@
	cp $< $@

FRC:
