#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

. /lib/svc/share/smf_include.sh

case "$1" in
'start')
	if smf_is_nonglobalzone; then
		/usr/sbin/svcadm disable -t svc:/system/iscsitgt
		echo "The iSCSI target is not supported in a local zone"
		sleep 5 &
		exit $SMF_EXIT_OK
	fi

	/usr/sbin/iscsitgtd

	if [ $? -ne 0 ]; then
		echo "Failed to start iSCSI daemon"
		exit 1
	fi

	if [ -x /usr/sbin/zfs ]; then
		/usr/sbin/zfs share -a iscsi
	fi

	;;

'stop')
	# Kill any processes in the service contract
	smf_kill_contract $2 TERM
	[ $? -ne 0 ] && exit 1
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac

exit $SMF_EXIT_OK
