#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2015 Garrett D'Amore <garrett@damore.org>
# Copyright 2019 Joyent, Inc.
# Copyright 2022 OmniOS Community Edition (OmniOSce) Association.
# Copyright 2023 Bill Sommerfeld <sommerfeld@alum.mit.edu>
# Copyright 2024 Oxide Computer Company
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 120
post =
outputdir = /var/tmp/test_results

[/opt/libc-tests/tests/fexecve_test]
[/opt/libc-tests/tests/fpround_test]
[/opt/libc-tests/tests/newlocale_test]
[/opt/libc-tests/tests/nl_langinfo_test]
[/opt/libc-tests/tests/wcsrtombs_test]
[/opt/libc-tests/tests/wctype_test]

[/opt/libc-tests/tests/strcoll-strxfrm-6907.32]
[/opt/libc-tests/tests/strcoll-strxfrm-6907.64]
[/opt/libc-tests/tests/wcsncasecmp.32]
[/opt/libc-tests/tests/wcsncasecmp.64]
[/opt/libc-tests/tests/wcsncasecmp-7344.32]
[/opt/libc-tests/tests/wcsncasecmp-7344.64]
[/opt/libc-tests/tests/wcsncasecmp-7350.32]
[/opt/libc-tests/tests/wcsncasecmp-7350.64]

[/opt/libc-tests/tests/i18n/bindtextdomain_test]
[/opt/libc-tests/tests/qsort/qsort_test]

[/opt/libc-tests/tests/random/getrandom]
[/opt/libc-tests/tests/random/getentropy]
[/opt/libc-tests/tests/random/chacha]
[/opt/libc-tests/tests/random/inz_child]
[/opt/libc-tests/tests/random/inz_inval]
#
# root privs required for mlock privileges
#
[/opt/libc-tests/tests/random/inz_mlock]
user = root
[/opt/libc-tests/tests/random/inz_region]
[/opt/libc-tests/tests/random/inz_split]
[/opt/libc-tests/tests/random/inz_split_vpp]
[/opt/libc-tests/tests/random/inz_vpp]
[/opt/libc-tests/tests/random/arc4random]
[/opt/libc-tests/tests/random/arc4random_fork]
[/opt/libc-tests/tests/random/arc4random_prefork]
[/opt/libc-tests/tests/random/arc4random_forkall]
[/opt/libc-tests/tests/random/arc4random_preforkall]
[/opt/libc-tests/tests/random/arc4random_forksig]
[/opt/libc-tests/tests/random/arc4random_preforksig]
#
# root privs required for DTrace
#
[/opt/libc-tests/tests/random/arc4key.ksh]
user = root

[/opt/libc-tests/tests/regex/regex_test]

[/opt/libc-tests/tests/select/select.sh]
timeout = 600

[/opt/libc-tests/tests/stdio/fileno.32]
[/opt/libc-tests/tests/stdio/fileno.64]
[/opt/libc-tests/tests/stdio/fmemopentest.32]
[/opt/libc-tests/tests/stdio/fmemopentest.64]
[/opt/libc-tests/tests/stdio/ftell_ungetc.32]
[/opt/libc-tests/tests/stdio/ftell_ungetc.64]
[/opt/libc-tests/tests/stdio/ftello_12768.lfs]
[/opt/libc-tests/tests/stdio/ftello_12768.64]
[/opt/libc-tests/tests/stdio/memstream.32]
[/opt/libc-tests/tests/stdio/memstream.64]
[/opt/libc-tests/tests/stdio/memstream_reopen.32]
[/opt/libc-tests/tests/stdio/memstream_reopen.64]
[/opt/libc-tests/tests/stdio/open_memstreamtest.32]
[/opt/libc-tests/tests/stdio/open_memstreamtest.64]
[/opt/libc-tests/tests/stdio/orientation_test.32]
[/opt/libc-tests/tests/stdio/orientation_test.64]
[/opt/libc-tests/tests/stdio/test_mbrtowc.32]
[/opt/libc-tests/tests/stdio/test_mbrtowc.64]

[/opt/libc-tests/tests/aligned_alloc]
[/opt/libc-tests/tests/ascftime.32]
[/opt/libc-tests/tests/ascftime.64]
[/opt/libc-tests/tests/asprintf-14933.32]
[/opt/libc-tests/tests/asprintf-14933.64]
[/opt/libc-tests/tests/c11_threads.32]
[/opt/libc-tests/tests/c11_threads.64]
[/opt/libc-tests/tests/c11_tss.32]
[/opt/libc-tests/tests/c11_tss.64]
[/opt/libc-tests/tests/call_once.32]
[/opt/libc-tests/tests/call_once.64]
[/opt/libc-tests/tests/clock_lock.32]
[/opt/libc-tests/tests/clock_lock.64]
[/opt/libc-tests/tests/closefrom.32]
[/opt/libc-tests/tests/closefrom.64]
[/opt/libc-tests/tests/catopen]
[/opt/libc-tests/tests/endian.32]
[/opt/libc-tests/tests/endian.64]
[/opt/libc-tests/tests/env-7076.32]
[/opt/libc-tests/tests/env-7076.64]
[/opt/libc-tests/tests/err/err.ksh]
[/opt/libc-tests/tests/fnmatch.32]
[/opt/libc-tests/tests/fnmatch.64]
[/opt/libc-tests/tests/isatty.32]
[/opt/libc-tests/tests/isatty.64]
[/opt/libc-tests/tests/memchr.32]
[/opt/libc-tests/tests/memchr.64]
[/opt/libc-tests/tests/memset_s.32]
[/opt/libc-tests/tests/memset_s.64]
[/opt/libc-tests/tests/mutex-16200.32]
[/opt/libc-tests/tests/mutex-16200.64]
[/opt/libc-tests/tests/posix_memalign.32]
[/opt/libc-tests/tests/posix_memalign.64]
[/opt/libc-tests/tests/printf-15294.32]
[/opt/libc-tests/tests/printf-15294.64]
[/opt/libc-tests/tests/printf-6961.64]
[/opt/libc-tests/tests/printf-9511.32]
[/opt/libc-tests/tests/printf-9511.64]
[/opt/libc-tests/tests/priv_gettext]
[/opt/libc-tests/tests/psignal]
[/opt/libc-tests/tests/ptsname.32]
[/opt/libc-tests/tests/ptsname.64]
[/opt/libc-tests/tests/quick_exit]
[/opt/libc-tests/tests/set_constraint_handler_s.32]
[/opt/libc-tests/tests/set_constraint_handler_s.64]
[/opt/libc-tests/tests/stdbit.32]
[/opt/libc-tests/tests/stdbit.64]
[/opt/libc-tests/tests/strerror.32]
[/opt/libc-tests/tests/strerror.64]
[/opt/libc-tests/tests/strtonum.32]
[/opt/libc-tests/tests/strtonum.64]
[/opt/libc-tests/tests/thread_name]
[/opt/libc-tests/tests/timespec_get.32]
[/opt/libc-tests/tests/timespec_get.64]
[/opt/libc-tests/tests/uchar.32]
[/opt/libc-tests/tests/uchar.64]
[/opt/libc-tests/tests/utimes.32]
[/opt/libc-tests/tests/utimes.64]

#
# root privs required for priority changes
#
[/opt/libc-tests/tests/pthread_attr_get_np]
user=root

[/opt/libc-tests/tests/symbols]
pre = setup
tests = [
	'assert_h',
	'ctype_h',
	'dirent_h',
	'fcntl_h',
	'locale_h',
	'math_h',
	'netdb_h',
	'pthread_h',
	'signal_h',
	'stdalign_h',
	'stddef_h',
	'stdio_h',
	'stdlib_h',
	'stdnoreturn_h',
	'string_h',
	'strings_h',
	'sys_atomic_h',
	'sys_mman_h',
	'sys_stat_h',
	'sys_time_h',
	'sys_timeb_h',
	'time_h',
	'threads_h',
	'ucontext_h',
	'unistd_h',
	'wchar_h',
	'wctype_h'
	 ]
timeout = 180
