#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2014 Garrett D'Amore <garrett@damore.org>
# Copyright 2016 Joyent, Inc.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results

[/opt/libc-tests/tests/fpround_test]
[/opt/libc-tests/tests/newlocale_test]
[/opt/libc-tests/tests/nl_langinfo_test]
[/opt/libc-tests/tests/wcsrtombs_test]
[/opt/libc-tests/tests/wctype_test]
[/opt/libc-tests/tests/wcsncasecmp.32]
[/opt/libc-tests/tests/wcsncasecmp.64]
[/opt/libc-tests/tests/wcsncasecm-7344.32]
[/opt/libc-tests/tests/wcsncasecmp-7344.64]
[/opt/libc-tests/tests/wcsncasecm-7350.32]
[/opt/libc-tests/tests/wcsncasecmp-7350.64]

[/opt/libc-tests/tests/random/getrandom]
[/opt/libc-tests/tests/random/getentropy]
[/opt/libc-tests/tests/random/chacha]
[/opt/libc-tests/tests/random/inz_child]
[/opt/libc-tests/tests/random/inz_inval]
[/opt/libc-tests/tests/random/inz_mlock]
[/opt/libc-tests/tests/random/inz_region]
[/opt/libc-tests/tests/random/inz_split]
[/opt/libc-tests/tests/random/inz_split_vpp]
[/opt/libc-tests/tests/random/inz_vpp]
[/opt/libc-tests/tests/random/arc4random]
[/opt/libc-tests/tests/random/arc4random_fork]
[/opt/libc-tests/tests/random/arc4random_prefork]
[/opt/libc-tests/tests/random/arc4random_forkall]
[/opt/libc-tests/tests/random/arc4random_preforkall]
[/opt/libc-tests/tests/random/arc4random_forksig]
[/opt/libc-tests/tests/random/arc4random_preforksig]
[/opt/libc-tests/tests/random/arc4key.ksh]

[/opt/libc-tests/tests/aligned_alloc.32]
[/opt/libc-tests/tests/aligned_alloc.64]
[/opt/libc-tests/tests/c11_threads.32]
[/opt/libc-tests/tests/c11_threads.64]
[/opt/libc-tests/tests/c11_tss.32]
[/opt/libc-tests/tests/c11_tss.64]
[/opt/libc-tests/tests/call_once.32]
[/opt/libc-tests/tests/call_once.64]
[/opt/libc-tests/tests/catopen]
[/opt/libc-tests/tests/env-7076.32]
[/opt/libc-tests/tests/env-7076.64]
[/opt/libc-tests/tests/endian.32]
[/opt/libc-tests/tests/endian.64]
[/opt/libc-tests/tests/quick_exit]
[/opt/libc-tests/tests/priv_gettext]
[/opt/libc-tests/tests/strerror]
[/opt/libc-tests/tests/timespec_get.32]
[/opt/libc-tests/tests/timespec_get.64]

[/opt/libc-tests/tests/pthread_attr_get_np]

[/opt/libc-tests/tests/symbols]
pre = setup
tests = [
	'assert_h',
	'ctype_h',
	'dirent_h',
	'fcntl_h',
	'locale_h',
	'math_h',
	'netdb_h',
	'pthread_h',
	'signal_h',
	'stdalign_h',
	'stddef_h',
	'stdio_h',
	'stdlib_h',
	'stdnoreturn_h',
	'string_h',
	'strings_h',
	'sys_stat_h',
	'sys_time_h',
	'sys_timeb_h',
	'time_h',
	'threads_h',
	'ucontext_h',
	'unistd_h',
	'wchar_h',
	'wctype_h'
	 ]
