#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"

#
# Start/Stop client LDAP service
#

. /lib/svc/share/smf_include.sh

case "$1" in
'start')
	if [ ! -r /var/ldap/ldap_client_file ]; then
		echo "WARNING: /var/ldap/ldap_client_file is missing or not readable" >& 2
		exit $SMF_EXIT_ERR_CONFIG
	fi

	exec /usr/lib/ldap/ldap_cachemgr
	;;

'stop')
	exec /usr/lib/ldap/ldap_cachemgr -K
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
