#! /bin/sh
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

PATH="/bin:/usr/bin:/usr/sbin:${PATH}"
export PATH

EXIT=0

grep '^pcelx\>' ${BASEDIR}/etc/name_to_major > /dev/null && \
rem_drv -b ${BASEDIR} pcelx
add_drv -b ${BASEDIR} -n -m '* 0666 root sys' \
-i '"pccard101,556" "pccard101,574" "pccard101,589" "pccard101,562,0"' pcelx \
|| EXIT=1
echo 'pcelx:* read_priv_set=net_rawaccess write_priv_set=net_rawaccess' >> \
	${BASEDIR}/etc/security/device_policy

exit ${EXIT}
