#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright 2016 Hans Rosenfeld <rosenfeld@grumpf.hope-2000.org>
#

# Scripts that generate IPfilter rules for SMB server

. /lib/svc/share/smf_include.sh
. /lib/svc/share/ipf_include.sh

create_ipf_rules()
{
	FMRI=$1
	file=`fmri_to_file $FMRI $IPF_SUFFIX`
	file6=`fmri_to_file $FMRI $IPF6_SUFFIX`
	policy=`get_policy ${FMRI}`
	iana_names="microsoft-ds netbios-ns netbios-dgm netbios-ssn"

	#
	# Enforce policy on each port
	#
	echo "# $FMRI" >$file
	echo "# $FMRI" >$file6
	for name in $iana_names; do
		port=`$SERVINFO -p -s $name 2>/dev/null`
		if [ -z "$port" ]; then
			continue;
		fi
		generate_rules $FMRI $policy "tcp" $port $file
		generate_rules $FMRI $policy "tcp" $port $file6 _6
		generate_rules $FMRI $policy "udp" $port $file
		generate_rules $FMRI $policy "udp" $port $file6 _6
	done
}

if [ "$1" = "ipfilter" ]; then
	create_ipf_rules $2
fi
exit 0
