#! /bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# SUNWust1.v preremove script
#

PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

EXIT=0

# If architecture is not sun4v, then do unmount the libc_psr_hwcap1 library.
ARCH=`uname -m`
if [ $ARCH != "sun4v" ]
then
	exit $EXIT
fi

# Unmount the specific mount point where libc_psr_hwcap1 library is
# mounted. Presently this package delivers only one hwcap library. If
# this package is updated to deliver more hwcap libraries, then script
# will need to be modified to unmount mount points for those hwcap
# libraries.

mount_points=`mount | grep libc_psr_hwcap1 | awk '{print $1}' | tr -s "\n" " "`
for mount_point in $mount_points
do
	echo "Unmounting $mount_point"
	umount $mount_point
done

exit $EXIT
