#! /bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
#pragma ident	"%Z%%M%	%I%	%E% SMI"
#
# Copyright (c) 1999-2000 by Sun Microsystems, Inc.
# All rights reserved.
#

PATH=/usr/bin:/usr/sbin:${PATH}
export PATH


TMP=/tmp/$$


#
# Make sure add_drv has *not* been previously executed
# before attempting to add the driver.
#
grep '^scmi2c\>' ${BASEDIR}/etc/name_to_major > /dev/null 2>&1
if [ $? -ne 0 ]; then
	add_drv -b ${BASEDIR} -i 'i2c-scm001 card-reader' scmi2c
	if [ $? -ne 0 ]; then
                echo "\nFailed add_drv!\n" >&2
                exit 1
        fi
fi
exit 0
