#!/usr/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at http://smartos.org/CDDL
#
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file.
#
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2012, Joyent, Inc. All rights reserved.
#

set -o xtrace

. /lib/svc/share/smf_include.sh
smf_is_globalzone && exit ${SMF_EXIT_OK}

# If we got as far as running the user-script the 'provision' was a success
# from here out a failure will leave the zone running.
if [ -f /var/svc/provisioning ]; then
    mv /var/svc/provision{ing,_success}
fi

if [[ -x /var/svc/mdata-operator-script ]]; then
    /var/svc/mdata-operator-script
    operator_script_exit=$?
    if [[ ${operator_script_exit} -gt 0 ]]; then
        echo "WARNING: operator-script failed: exited ${operator_script_exit}" \
            >&2
    fi
fi

user_script_exit=${SMF_EXIT_OK}
if [ -x /var/svc/mdata-user-script ]; then
    /var/svc/mdata-user-script
    [ $? -gt 0 ] && user_script_exit=${SMF_EXIT_ERR_FATAL}
fi

exit ${user_script_exit}
