#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"

. /lib/svc/share/smf_include.sh

#
# In a zone we need this service to be up, but all of the work
# it tries to do is irrelevant (and will actually lead to the service
# failing if we try to do it), so just bail out.
#
if [ `/sbin/zonename` != "global" ]; then
	exit 0
fi

#
# Cause ifconfig to not automatically start in.mpathd when IPMP groups are
# configured.  This is not strictly necessary but makes it so that in.mpathd
# will always be started explicitly from /lib/svc/method/net-init (the 
# svc:/network/initial service), when we're sure that /usr is mounted.
#
SUNW_NO_MPATHD=; export SUNW_NO_MPATHD

#
# Before any interfaces are configured, we need to set the system
# default IP forwarding behavior.  This will be the setting for
# interfaces that don't modify the per-interface setting with the
# router or -router ifconfig command in their /etc/hostname.<intf>
# files.  The -F option tells routeadm to only update the forwarding
# configuration for the system, and not dynamic routing.  We don't
# want routing daemons started until later in the boot process (see
# the net-init method for that).
#
/sbin/routeadm -u -F

# IPv4 loopback
/sbin/ifconfig lo0 plumb 127.0.0.1 up

# Configure the v6 loopback if any IPv6 interfaces are configured.
interface_names="`echo /etc/hostname6.*[0-9] 2>/dev/null`"
if [ "$interface_names" != "/etc/hostname6.*[0-9]" ]; then
        ORIGIFS="$IFS"
        IFS="$IFS."
        set -- $interface_names
        IFS="$ORIGIFS"
        while [ $# -ge 2 ]; do
                shift
                if [ $# -gt 1 -a "$2" != "/etc/hostname6" ]; then
                        while [ $# -gt 1 -a "$1" != "/etc/hostname6" ]; do
                                shift
                        done
                else
                        inet6_list="$inet6_list $1"
                        shift
                fi
        done
fi

if [ -n "$inet6_list" ]; then
	/sbin/ifconfig lo0 inet6 plumb ::1 up
else
	exit 0
fi
