#!/usr/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# Get the path/ppdfilename for this ppd NickName
# Input:
#	make: model: ppd:
#	PrintersRus: ABC Model 1234: Foomatic/Postscript (recommended):
#

if [[ $# -lt 3 ]]; then
        exit 1
fi

if [[ -f /usr/lib/lp/model/ppd/ppdcache ]]; then
	typeset make=$(echo $* | /usr/bin/nawk '{FS=":"; print $1}')
	# strip leading blanks
	typeset model=$(echo $* | /usr/bin/nawk '{FS=":"; print $2}' |
			sed -e 's/^[ ]*//')
	typeset ppd=$(echo $* | /usr/bin/nawk '{FS=":"; print $3}' |
			sed -e 's/^[ ]*//')

	# Do not use ":" with $make. printmgr collapses manufacturer name
	# to first word, ie PrintersRus and PrintersRus International become
	# PrintersRus
	/bin/grep "${make}" /usr/lib/lp/model/ppd/ppdcache | 
	/bin/grep "${model}:" |
	/bin/grep "${ppd}:"  |
	nawk '{FS=":"; print $4}' 

	exit 0
else
	exit 1
fi
