#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# SUNWustcar.v postinstall script
#

PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

EXIT=0

# If architecture is not sun4v, then do not mount the libc_psr_hwcap1
# library.

ARCH=`uname -m`
if [ $ARCH != "sun4v" ]
then
	exit $EXIT
fi

BASEDIR=${BASEDIR:-/}

# If this package is being installed on an alternate root, then do not
# remount libc_psr_hwcal1.so.1 library as it was not unmounted to start
# with.

if [ $BASEDIR != "/" ]; then
	exit $EXIT
fi

PLAT=`uname -i`
LIBC_MOE_32=`moe -32 /platform/$PLAT/lib/libc_psr/'$HWCAP'`
if [ -n "$LIBC_MOE_32" ]; then
	mount | egrep -s "^/platform/[^/]*/lib/libc_psr.so.1 on "
	if [ $? -ne 0 ]; then
		mount -O -F lofs $LIBC_MOE_32 /platform/$PLAT/lib/libc_psr.so.1
	fi
fi

LIBC_MOE_64=`moe -64 /platform/$PLAT/lib/sparcv9/libc_psr/'$HWCAP'`
if [ -n "$LIBC_MOE_64" ]; then
	mount | egrep -s "^/platform/[^/]*/lib/sparcv9/libc_psr.so.1 on "
	if [ $? -ne 0 ]; then
		mount -O -F lofs $LIBC_MOE_64 \
		    /platform/$PLAT/lib/sparcv9/libc_psr.so.1
	fi
fi

exit $EXIT
