#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#pragma ident	"%Z%%M%	%I%	%E% SMI"
#
 
include ../Makefile.com

.KEEP_STATE:

all: $(FILES) depend
install: all pkg

include ../Makefile.targ
