#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
#ident	"%Z%%M%	%I%	%E% SMI"
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

include ../Makefile.com

LICENSEFILES += \
	../../ucbcmd/basename/THIRDPARTYLICENSE \
	../../ucbcmd/echo/THIRDPARTYLICENSE \
	../../ucbcmd/from/THIRDPARTYLICENSE \
	../../ucbcmd/groups/THIRDPARTYLICENSE \
	../../ucbcmd/ln/THIRDPARTYLICENSE \
	../../ucbcmd/ls/THIRDPARTYLICENSE \
	../../ucbcmd/plot/THIRDPARTYLICENSE \
	../../ucbcmd/sum/THIRDPARTYLICENSE \
	../../ucbcmd/test/THIRDPARTYLICENSE \
	../../ucbcmd/tset/THIRDPARTYLICENSE \
	../../ucbcmd/users/THIRDPARTYLICENSE \
	../../ucbcmd/whereis/THIRDPARTYLICENSE \
	../../ucbcmd/whoami/THIRDPARTYLICENSE \
	../../ucblib/libcurses/THIRDPARTYLICENSE \
	../../ucblib/libtermcap/THIRDPARTYLICENSE \
	../../ucblib/libucb/THIRDPARTYLICENSE


.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
