#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"

if [ -z "$_INIT_PREV_LEVEL" ]; then
	set -- `/usr/bin/who -r`
	_INIT_PREV_LEVEL="$9"
fi

[ $_INIT_PREV_LEVEL != S -a $_INIT_PREV_LEVEL != 1 ] && exit 0

# Uncomment this line to print the complete system configuration on startup
#[ -x /usr/sbin/prtconf ] && /usr/sbin/prtconf

# If there are trademark files, print them.

[ -d /etc/tm ] && /usr/bin/cat /etc/tm/* 2>/dev/null

#
# Set default scheduling class
#
if [ -f /etc/dispadmin.conf ] && [ -x /usr/sbin/dispadmin ] && \
     [ -x /usr/bin/priocntl ] && \
     [ "${_INIT_ZONENAME:=`/sbin/zonename`}" = "global" ]; then
	ERROR="$0: cannot set default scheduling class to "
	DISPADMIN_D=`/usr/sbin/dispadmin -d`

	if [ $? -eq 0 ]; then
		#
		# Inform the kernel about the default scheduling class.
		#
		dispadmin -u

		DEFAULT_SCHEDULER=`echo $DISPADMIN_D | \
			/usr/bin/awk '{ print $1 }'`

		/usr/bin/priocntl -s -c $DEFAULT_SCHEDULER \
			-i all >/dev/null 2>&1

		if [ $? -ne 0 ]; then
			echo $ERROR $DEFAULT_SCHEDULER
		else
			#
			# Also need to move init process explicitly
			# because it was ignored by "-i all". 
			#
			/usr/bin/priocntl -s -c $DEFAULT_SCHEDULER \
				-i pid 1 >/dev/null 2>&1
			if [ $? -ne 0 ]; then
				echo $ERROR $DEFAULT_SCHEDULER
			fi
		fi
	fi
fi

#
# Run rctladm to configure system resource controls based on the settings
# previously saved by rctladm.  See rctladm(1m) for instructions on how to
# modify resource control settings.
#
if [ -f /etc/rctladm.conf ] && [ -x /usr/sbin/rctladm ]; then
	/usr/sbin/rctladm -u
fi

#
# Run pooladm to configure system pools.  See pooladm(1m) for more information.
#
if [ -f /etc/pooladm.conf ] && [ -x /usr/sbin/pooladm ] && \
    [ "$_INIT_ZONENAME" = "global" ]; then
	/usr/sbin/pooladm -e
	/usr/sbin/pooladm -c
fi
