/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2010, Oracle and/or its affiliates. All rights reserved.
 */

/* KMS_AgentStub.h
   Generated by gSOAP 2.7.17 from ../gsoapStubs/AgentService/KMS_Agent_SOAP.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef KMS_AgentStub_H
#define KMS_AgentStub_H
#ifndef WITH_NONAMESPACES
#define WITH_NONAMESPACES
#endif
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#include "stdsoap2.h"

namespace KMS_Agent {

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__SortOrder
#define SOAP_TYPE_KMS_Agent_KMS_Agent__SortOrder (24)
/* KMS-Agent:SortOrder */
enum KMS_Agent__SortOrder {SORT_ORDER_ASCENDING = 0, SORT_ORDER_DESCENDING = 1};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__FilterOperator
#define SOAP_TYPE_KMS_Agent_KMS_Agent__FilterOperator (25)
/* KMS-Agent:FilterOperator */
enum KMS_Agent__FilterOperator {FILTER_OPERATOR_EQUAL = 0, FILTER_OPERATOR_NOT_EQUAL = 1, FILTER_OPERATOR_GREATER_THAN = 2, FILTER_OPERATOR_LESS_THAN = 3, FILTER_OPERATOR_GREATER_THAN_OR_EQUAL = 4, FILTER_OPERATOR_LESS_THAN_OR_EQUAL = 5, FILTER_OPERATOR_STARTS_WITH = 6};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__KeyType
#define SOAP_TYPE_KMS_Agent_KMS_Agent__KeyType (30)
/* KMS-Agent:KeyType */
enum KMS_Agent__KeyType {KEY_TYPE_AES_256 = 0};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__KeyState
#define SOAP_TYPE_KMS_Agent_KMS_Agent__KeyState (31)
/* KMS-Agent:KeyState */
enum KMS_Agent__KeyState {KEY_STATE_GENERATED = 0, KEY_STATE_READY = 1, KEY_STATE_PROTECT_AND_PROCESS = 2, KEY_STATE_PROCESS_ONLY = 3, KEY_STATE_DEACTIVATED = 4, KEY_STATE_COMPROMISED = 5, KEY_STATE_DESTROYED_INCOMPLETE = 6, KEY_STATE_DESTROYED_COMPLETE = 7, KEY_STATE_DESTROYED_COMPROMISED_INCOMPLETE = 8, KEY_STATE_DESTROYED_COMPROMISED_COMPLETE = 9};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__DataUnitState
#define SOAP_TYPE_KMS_Agent_KMS_Agent__DataUnitState (32)
/* KMS-Agent:DataUnitState */
enum KMS_Agent__DataUnitState {DATA_UNIT_STATE_NO_KEY = 0, DATA_UNIT_STATE_READABLE_NORMAL = 1, DATA_UNIT_STATE_READABLE_NEEDS_REKEY = 2, DATA_UNIT_STATE_SHREDDED = 3};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__AuditLogRetention
#define SOAP_TYPE_KMS_Agent_KMS_Agent__AuditLogRetention (40)
/* KMS-Agent:AuditLogRetention */
enum KMS_Agent__AuditLogRetention {AUDIT_LOG_LONG_TERM_RETENTION = 0, AUDIT_LOG_MEDIUM_TERM_RETENTION = 1, AUDIT_LOG_SHORT_TERM_RETENTION = 2, AUDIT_LOG_ZERO_RETENTION = 3};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__AuditLogCondition
#define SOAP_TYPE_KMS_Agent_KMS_Agent__AuditLogCondition (41)
/* KMS-Agent:AuditLogCondition */
enum KMS_Agent__AuditLogCondition {AUDIT_LOG_SUCCESS_CONDITION = 0, AUDIT_LOG_ERROR_CONDITION = 1, AUDIT_LOG_WARNING_CONDITION = 2};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_KMS_Agent_xsd__hexBinary
#define SOAP_TYPE_KMS_Agent_xsd__hexBinary (18)
/* hexBinary schema type: */
struct xsd__hexBinary
{
public:
	unsigned char *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__ArrayOfHexBinary
#define SOAP_TYPE_KMS_Agent_KMS_Agent__ArrayOfHexBinary (22)
/* Sequence of KMS-Agent:ArrayOfHexBinary schema type: */
struct KMS_Agent__ArrayOfHexBinary
{
public:
	struct xsd__hexBinary *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__FilterParameters
#define SOAP_TYPE_KMS_Agent_KMS_Agent__FilterParameters (26)
/* KMS-Agent:FilterParameters */
struct KMS_Agent__FilterParameters
{
public:
	char *FieldName;	/* optional element of type xsd:string */
	enum KMS_Agent__FilterOperator FilterOperator;	/* required element of type KMS-Agent:FilterOperator */
	char *FieldValue;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__ArrayOfFilterParameters
#define SOAP_TYPE_KMS_Agent_KMS_Agent__ArrayOfFilterParameters (27)
/* Sequence of KMS-Agent:ArrayOfFilterParameters schema type: */
struct KMS_Agent__ArrayOfFilterParameters
{
public:
	struct KMS_Agent__FilterParameters *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__QueryParameters
#define SOAP_TYPE_KMS_Agent_KMS_Agent__QueryParameters (29)
/* KMS-Agent:QueryParameters */
struct KMS_Agent__QueryParameters
{
public:
	long NextPageSize;	/* required element of type xsd:int */
	char *SortFieldName;	/* optional element of type xsd:string */
	enum KMS_Agent__SortOrder SortOrder;	/* required element of type KMS-Agent:SortOrder */
	struct KMS_Agent__ArrayOfFilterParameters FilterParameters;	/* optional element of type KMS-Agent:ArrayOfFilterParameters */
	char *PreviousPageLastIDValue;	/* optional element of type xsd:string */
	char *PreviousPageLastSortFieldValue;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__KeyGroup
#define SOAP_TYPE_KMS_Agent_KMS_Agent__KeyGroup (33)
/* KMS-Agent:KeyGroup */
struct KMS_Agent__KeyGroup
{
public:
	char *KeyGroupID;	/* optional element of type xsd:string */
	char *Description;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__ArrayOfKeyGroups
#define SOAP_TYPE_KMS_Agent_KMS_Agent__ArrayOfKeyGroups (34)
/* Sequence of KMS-Agent:ArrayOfKeyGroups schema type: */
struct KMS_Agent__ArrayOfKeyGroups
{
public:
	struct KMS_Agent__KeyGroup *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__Key
#define SOAP_TYPE_KMS_Agent_KMS_Agent__Key (36)
/* KMS-Agent:Key */
struct KMS_Agent__Key
{
public:
	char *KeyID;	/* optional element of type xsd:string */
	enum KMS_Agent__KeyState KeyState;	/* required element of type KMS-Agent:KeyState */
	enum KMS_Agent__KeyType KeyType;	/* required element of type KMS-Agent:KeyType */
	char *KeyGroupID;	/* optional element of type xsd:string */
	struct xsd__hexBinary Key;	/* required element of type xsd:hexBinary */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__ArrayOfKeys
#define SOAP_TYPE_KMS_Agent_KMS_Agent__ArrayOfKeys (37)
/* Sequence of KMS-Agent:ArrayOfKeys schema type: */
struct KMS_Agent__ArrayOfKeys
{
public:
	struct KMS_Agent__Key *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__DataUnit
#define SOAP_TYPE_KMS_Agent_KMS_Agent__DataUnit (39)
/* KMS-Agent:DataUnit */
struct KMS_Agent__DataUnit
{
public:
	char *DataUnitID;	/* optional element of type xsd:string */
	char *ExternalUniqueID;	/* optional element of type xsd:string */
	char *ExternalTag;	/* optional element of type xsd:string */
	char *Description;	/* optional element of type xsd:string */
	enum KMS_Agent__DataUnitState DataUnitState;	/* required element of type KMS-Agent:DataUnitState */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__ListKeyGroupsResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__ListKeyGroupsResponse (42)
/* KMS-Agent:ListKeyGroupsResponse */
struct KMS_Agent__ListKeyGroupsResponse
{
public:
	struct KMS_Agent__ArrayOfKeyGroups KeyGroups;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type KMS-Agent:ArrayOfKeyGroups */
	bool LastPage;	/* required element of type xsd:boolean */
	struct KMS_Agent__QueryParameters NextPageQueryParameters;	/* required element of type KMS-Agent:QueryParameters */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__ListKeyGroups
#define SOAP_TYPE_KMS_Agent_KMS_Agent__ListKeyGroups (45)
/* KMS-Agent:ListKeyGroups */
struct KMS_Agent__ListKeyGroups
{
public:
	struct KMS_Agent__QueryParameters QueryParameters;	/* required element of type KMS-Agent:QueryParameters */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__CreateDataUnitResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__CreateDataUnitResponse (46)
/* KMS-Agent:CreateDataUnitResponse */
struct KMS_Agent__CreateDataUnitResponse
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:DataUnit */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__CreateDataUnit
#define SOAP_TYPE_KMS_Agent_KMS_Agent__CreateDataUnit (49)
/* KMS-Agent:CreateDataUnit */
struct KMS_Agent__CreateDataUnit
{
public:
	char *ExternalUniqueID;	/* optional element of type xsd:string */
	char *ExternalTag;	/* optional element of type xsd:string */
	char *Description;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitResponse (50)
/* KMS-Agent:RetrieveDataUnitResponse */
struct KMS_Agent__RetrieveDataUnitResponse
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:DataUnit */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnit
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnit (53)
/* KMS-Agent:RetrieveDataUnit */
struct KMS_Agent__RetrieveDataUnit
{
public:
	char *DataUnitID;	/* optional element of type xsd:string */
	char *ExternalUniqueID;	/* optional element of type xsd:string */
	char *ExternalTag;	/* optional element of type xsd:string */
	char *Description;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitByExternalUniqueIDResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitByExternalUniqueIDResponse (54)
/* KMS-Agent:RetrieveDataUnitByExternalUniqueIDResponse */
struct KMS_Agent__RetrieveDataUnitByExternalUniqueIDResponse
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:DataUnit */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitByExternalUniqueID
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitByExternalUniqueID (57)
/* KMS-Agent:RetrieveDataUnitByExternalUniqueID */
struct KMS_Agent__RetrieveDataUnitByExternalUniqueID
{
public:
	char *ExternalUniqueID;	/* optional element of type xsd:string */
	char *ExternalTag;	/* optional element of type xsd:string */
	char *Description;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__DisassociateDataUnitKeysResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__DisassociateDataUnitKeysResponse (58)
/* KMS-Agent:DisassociateDataUnitKeysResponse */
struct KMS_Agent__DisassociateDataUnitKeysResponse
{
public:
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__DisassociateDataUnitKeys
#define SOAP_TYPE_KMS_Agent_KMS_Agent__DisassociateDataUnitKeys (63)
/* KMS-Agent:DisassociateDataUnitKeys */
struct KMS_Agent__DisassociateDataUnitKeys
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__CreateKeyResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__CreateKeyResponse (64)
/* KMS-Agent:CreateKeyResponse */
struct KMS_Agent__CreateKeyResponse
{
public:
	struct KMS_Agent__Key Key;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:Key */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__CreateKey
#define SOAP_TYPE_KMS_Agent_KMS_Agent__CreateKey (67)
/* KMS-Agent:CreateKey */
struct KMS_Agent__CreateKey
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
	char *KeyGroupID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__CreateKey2Response
#define SOAP_TYPE_KMS_Agent_KMS_Agent__CreateKey2Response (68)
/* KMS-Agent:CreateKey2Response */
struct KMS_Agent__CreateKey2Response
{
public:
	struct KMS_Agent__Key Key;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:Key */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__CreateKey2
#define SOAP_TYPE_KMS_Agent_KMS_Agent__CreateKey2 (71)
/* KMS-Agent:CreateKey2 */
struct KMS_Agent__CreateKey2
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
	char *KeyGroupID;	/* optional element of type xsd:string */
	char *AgentKWKID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveKeyResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveKeyResponse (72)
/* KMS-Agent:RetrieveKeyResponse */
struct KMS_Agent__RetrieveKeyResponse
{
public:
	struct KMS_Agent__Key Key;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:Key */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveKey
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveKey (75)
/* KMS-Agent:RetrieveKey */
struct KMS_Agent__RetrieveKey
{
public:
	char *KeyID;	/* optional element of type xsd:string */
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
	char *KeyGroupID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveKey2Response
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveKey2Response (76)
/* KMS-Agent:RetrieveKey2Response */
struct KMS_Agent__RetrieveKey2Response
{
public:
	struct KMS_Agent__Key Key;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:Key */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveKey2
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveKey2 (79)
/* KMS-Agent:RetrieveKey2 */
struct KMS_Agent__RetrieveKey2
{
public:
	char *KeyID;	/* optional element of type xsd:string */
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
	char *KeyGroupID;	/* optional element of type xsd:string */
	char *AgentKWKID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitKeysResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitKeysResponse (80)
/* KMS-Agent:RetrieveDataUnitKeysResponse */
struct KMS_Agent__RetrieveDataUnitKeysResponse
{
public:
	LONG64 KeysRemaining;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:long */
	struct KMS_Agent__ArrayOfKeys Keys;	/* optional element of type KMS-Agent:ArrayOfKeys */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitKeys
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitKeys (83)
/* KMS-Agent:RetrieveDataUnitKeys */
struct KMS_Agent__RetrieveDataUnitKeys
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
	long PageSize;	/* required element of type xsd:int */
	long PageOffset;	/* required element of type xsd:int */
	char *KeyID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitKeys2Response
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitKeys2Response (84)
/* KMS-Agent:RetrieveDataUnitKeys2Response */
struct KMS_Agent__RetrieveDataUnitKeys2Response
{
public:
	LONG64 KeysRemaining;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:long */
	struct KMS_Agent__ArrayOfKeys Keys;	/* optional element of type KMS-Agent:ArrayOfKeys */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitKeys2
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveDataUnitKeys2 (87)
/* KMS-Agent:RetrieveDataUnitKeys2 */
struct KMS_Agent__RetrieveDataUnitKeys2
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
	long PageSize;	/* required element of type xsd:int */
	long PageOffset;	/* required element of type xsd:int */
	char *KeyID;	/* optional element of type xsd:string */
	char *AgentKWKID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveProtectAndProcessKeyResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveProtectAndProcessKeyResponse (88)
/* KMS-Agent:RetrieveProtectAndProcessKeyResponse */
struct KMS_Agent__RetrieveProtectAndProcessKeyResponse
{
public:
	struct KMS_Agent__Key Key;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:Key */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveProtectAndProcessKey
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveProtectAndProcessKey (91)
/* KMS-Agent:RetrieveProtectAndProcessKey */
struct KMS_Agent__RetrieveProtectAndProcessKey
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
	char *KeyGroupID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveProtectAndProcessKey2Response
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveProtectAndProcessKey2Response (92)
/* KMS-Agent:RetrieveProtectAndProcessKey2Response */
struct KMS_Agent__RetrieveProtectAndProcessKey2Response
{
public:
	struct KMS_Agent__Key Key;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type KMS-Agent:Key */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveProtectAndProcessKey2
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RetrieveProtectAndProcessKey2 (95)
/* KMS-Agent:RetrieveProtectAndProcessKey2 */
struct KMS_Agent__RetrieveProtectAndProcessKey2
{
public:
	struct KMS_Agent__DataUnit DataUnit;	/* required element of type KMS-Agent:DataUnit */
	char *KeyGroupID;	/* optional element of type xsd:string */
	char *AgentKWKID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__CreateAuditLogResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__CreateAuditLogResponse (96)
/* KMS-Agent:CreateAuditLogResponse */
struct KMS_Agent__CreateAuditLogResponse
{
public:
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__CreateAuditLog
#define SOAP_TYPE_KMS_Agent_KMS_Agent__CreateAuditLog (99)
/* KMS-Agent:CreateAuditLog */
struct KMS_Agent__CreateAuditLog
{
public:
	enum KMS_Agent__AuditLogRetention Retention;	/* required element of type KMS-Agent:AuditLogRetention */
	enum KMS_Agent__AuditLogCondition Condition;	/* required element of type KMS-Agent:AuditLogCondition */
	bool IssueAlert;	/* required element of type xsd:boolean */
	char *Message;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__GetAgentKWKPublicKeyResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__GetAgentKWKPublicKeyResponse (100)
/* KMS-Agent:GetAgentKWKPublicKeyResponse */
struct KMS_Agent__GetAgentKWKPublicKeyResponse
{
public:
	struct xsd__hexBinary KWKPublicKey;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:hexBinary */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__GetAgentKWKPublicKey
#define SOAP_TYPE_KMS_Agent_KMS_Agent__GetAgentKWKPublicKey (103)
/* KMS-Agent:GetAgentKWKPublicKey */
struct KMS_Agent__GetAgentKWKPublicKey
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RegisterAgentKWKResponse
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RegisterAgentKWKResponse (104)
/* KMS-Agent:RegisterAgentKWKResponse */
struct KMS_Agent__RegisterAgentKWKResponse
{
public:
	char *AgentKWKID;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_KMS_Agent__RegisterAgentKWK
#define SOAP_TYPE_KMS_Agent_KMS_Agent__RegisterAgentKWK (107)
/* KMS-Agent:RegisterAgentKWK */
struct KMS_Agent__RegisterAgentKWK
{
public:
	struct xsd__hexBinary AgentKWK;	/* required element of type xsd:hexBinary */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_SOAP_ENV__Header
#define SOAP_TYPE_KMS_Agent_SOAP_ENV__Header (108)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_SOAP_ENV__Code
#define SOAP_TYPE_KMS_Agent_SOAP_ENV__Code (109)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_SOAP_ENV__Detail
#define SOAP_TYPE_KMS_Agent_SOAP_ENV__Detail (111)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_SOAP_ENV__Reason
#define SOAP_TYPE_KMS_Agent_SOAP_ENV__Reason (112)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_KMS_Agent_SOAP_ENV__Fault
#define SOAP_TYPE_KMS_Agent_SOAP_ENV__Fault (113)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE_KMS_Agent__QName
#define SOAP_TYPE_KMS_Agent__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_KMS_Agent__XML
#define SOAP_TYPE_KMS_Agent__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_KMS_Agent_xsd__string
#define SOAP_TYPE_KMS_Agent_xsd__string (7)
typedef char *xsd__string;
#endif

#ifndef SOAP_TYPE_KMS_Agent_xsd__float
#define SOAP_TYPE_KMS_Agent_xsd__float (9)
typedef float xsd__float;
#endif

#ifndef SOAP_TYPE_KMS_Agent_xsd__int
#define SOAP_TYPE_KMS_Agent_xsd__int (11)
typedef long xsd__int;
#endif

#ifndef SOAP_TYPE_KMS_Agent_xsd__boolean
#define SOAP_TYPE_KMS_Agent_xsd__boolean (13)
typedef bool xsd__boolean;
#endif

#ifndef SOAP_TYPE_KMS_Agent_xsd__long
#define SOAP_TYPE_KMS_Agent_xsd__long (15)
typedef LONG64 xsd__long;
#endif

#ifndef SOAP_TYPE_KMS_Agent_xsd__dateTime
#define SOAP_TYPE_KMS_Agent_xsd__dateTime (16)
typedef char *xsd__dateTime;
#endif

#ifndef SOAP_TYPE_KMS_Agent_xsd__duration
#define SOAP_TYPE_KMS_Agent_xsd__duration (17)
typedef char *xsd__duration;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__ListKeyGroups(struct soap*, struct KMS_Agent__QueryParameters QueryParameters, struct KMS_Agent__ListKeyGroupsResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__CreateDataUnit(struct soap*, char *ExternalUniqueID, char *ExternalTag, char *Description, struct KMS_Agent__CreateDataUnitResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RetrieveDataUnit(struct soap*, char *DataUnitID, char *ExternalUniqueID, char *ExternalTag, char *Description, struct KMS_Agent__RetrieveDataUnitResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RetrieveDataUnitByExternalUniqueID(struct soap*, char *ExternalUniqueID, char *ExternalTag, char *Description, struct KMS_Agent__RetrieveDataUnitByExternalUniqueIDResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__DisassociateDataUnitKeys(struct soap*, struct KMS_Agent__DataUnit DataUnit, struct KMS_Agent__DisassociateDataUnitKeysResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__CreateKey(struct soap*, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, struct KMS_Agent__CreateKeyResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__CreateKey2(struct soap*, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, char *AgentKWKID, struct KMS_Agent__CreateKey2Response &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RetrieveKey(struct soap*, char *KeyID, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, struct KMS_Agent__RetrieveKeyResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RetrieveKey2(struct soap*, char *KeyID, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, char *AgentKWKID, struct KMS_Agent__RetrieveKey2Response &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RetrieveDataUnitKeys(struct soap*, struct KMS_Agent__DataUnit DataUnit, long PageSize, long PageOffset, char *KeyID, struct KMS_Agent__RetrieveDataUnitKeysResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RetrieveDataUnitKeys2(struct soap*, struct KMS_Agent__DataUnit DataUnit, long PageSize, long PageOffset, char *KeyID, char *AgentKWKID, struct KMS_Agent__RetrieveDataUnitKeys2Response &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RetrieveProtectAndProcessKey(struct soap*, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, struct KMS_Agent__RetrieveProtectAndProcessKeyResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RetrieveProtectAndProcessKey2(struct soap*, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, char *AgentKWKID, struct KMS_Agent__RetrieveProtectAndProcessKey2Response &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__CreateAuditLog(struct soap*, enum KMS_Agent__AuditLogRetention Retention, enum KMS_Agent__AuditLogCondition Condition, bool IssueAlert, char *Message, struct KMS_Agent__CreateAuditLogResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__GetAgentKWKPublicKey(struct soap*, struct KMS_Agent__GetAgentKWKPublicKeyResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent__RegisterAgentKWK(struct soap*, struct xsd__hexBinary AgentKWK, struct KMS_Agent__RegisterAgentKWKResponse &result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 KMS_Agent_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__ListKeyGroups(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__CreateDataUnit(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RetrieveDataUnit(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RetrieveDataUnitByExternalUniqueID(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__DisassociateDataUnitKeys(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__CreateKey(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__CreateKey2(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RetrieveKey(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RetrieveKey2(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RetrieveDataUnitKeys(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RetrieveDataUnitKeys2(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RetrieveProtectAndProcessKey(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RetrieveProtectAndProcessKey2(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__CreateAuditLog(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__GetAgentKWKPublicKey(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_KMS_Agent__RegisterAgentKWK(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__ListKeyGroups(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__QueryParameters QueryParameters, struct KMS_Agent__ListKeyGroupsResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__CreateDataUnit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ExternalUniqueID, char *ExternalTag, char *Description, struct KMS_Agent__CreateDataUnitResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RetrieveDataUnit(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *DataUnitID, char *ExternalUniqueID, char *ExternalTag, char *Description, struct KMS_Agent__RetrieveDataUnitResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RetrieveDataUnitByExternalUniqueID(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ExternalUniqueID, char *ExternalTag, char *Description, struct KMS_Agent__RetrieveDataUnitByExternalUniqueIDResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__DisassociateDataUnitKeys(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__DataUnit DataUnit, struct KMS_Agent__DisassociateDataUnitKeysResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__CreateKey(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, struct KMS_Agent__CreateKeyResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__CreateKey2(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, char *AgentKWKID, struct KMS_Agent__CreateKey2Response &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RetrieveKey(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *KeyID, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, struct KMS_Agent__RetrieveKeyResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RetrieveKey2(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *KeyID, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, char *AgentKWKID, struct KMS_Agent__RetrieveKey2Response &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RetrieveDataUnitKeys(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__DataUnit DataUnit, long PageSize, long PageOffset, char *KeyID, struct KMS_Agent__RetrieveDataUnitKeysResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RetrieveDataUnitKeys2(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__DataUnit DataUnit, long PageSize, long PageOffset, char *KeyID, char *AgentKWKID, struct KMS_Agent__RetrieveDataUnitKeys2Response &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RetrieveProtectAndProcessKey(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, struct KMS_Agent__RetrieveProtectAndProcessKeyResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RetrieveProtectAndProcessKey2(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__DataUnit DataUnit, char *KeyGroupID, char *AgentKWKID, struct KMS_Agent__RetrieveProtectAndProcessKey2Response &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__CreateAuditLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, enum KMS_Agent__AuditLogRetention Retention, enum KMS_Agent__AuditLogCondition Condition, bool IssueAlert, char *Message, struct KMS_Agent__CreateAuditLogResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__GetAgentKWKPublicKey(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct KMS_Agent__GetAgentKWKPublicKeyResponse &result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_KMS_Agent__RegisterAgentKWK(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct xsd__hexBinary AgentKWK, struct KMS_Agent__RegisterAgentKWKResponse &result);

} // namespace KMS_Agent


#endif

/* End of KMS_AgentStub.h */
