#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2015 Nexenta Systems, Inc. All rights reserved.
# Copyright 2016 Toomas Soome <tsoome@me.com>
# Copyright (c) 2017, Chris Fraire <cfraire@me.com>.
# Copyright (c) 2016 by Delphix. All rights reserved.
# Copyright 2020 Joyent, Inc.
# Copyright 2024 Oxide Computer Company
#

file path=usr/share/man/man8/6to4relay.8
file path=usr/share/man/man8/Intro.8
file path=usr/share/man/man8/acctadm.8
file path=usr/share/man/man8/add_drv.8
file path=usr/share/man/man8/addbadsec.8
file path=usr/share/man/man8/arp.8
file path=usr/share/man/man8/audit.8
file path=usr/share/man/man8/audit_warn.8
file path=usr/share/man/man8/auditconfig.8
file path=usr/share/man/man8/auditd.8
file path=usr/share/man/man8/auditrecord.8
file path=usr/share/man/man8/auditreduce.8
file path=usr/share/man/man8/auditstat.8
link path=usr/share/man/man8/audlinks.8 target=devfsadm.8
file path=usr/share/man/man8/autopush.8
file path=usr/share/man/man8/bootadm.8
file path=usr/share/man/man8/busstat.8
file path=usr/share/man/man8/captoinfo.8
file path=usr/share/man/man8/cfgadm.8
file path=usr/share/man/man8/cfgadm_cardbus.8
file path=usr/share/man/man8/cfgadm_fp.8
file path=usr/share/man/man8/cfgadm_ib.8
file path=usr/share/man/man8/cfgadm_pci.8
file path=usr/share/man/man8/cfgadm_sata.8
file path=usr/share/man/man8/cfgadm_sbd.8
file path=usr/share/man/man8/cfgadm_scsi.8
file path=usr/share/man/man8/cfgadm_usb.8
file path=usr/share/man/man8/chroot.8
file path=usr/share/man/man8/clear_locks.8
file path=usr/share/man/man8/clinfo.8
file path=usr/share/man/man8/clri.8
file path=usr/share/man/man8/connstat.8
file path=usr/share/man/man8/consadm.8
file path=usr/share/man/man8/coreadm.8
file path=usr/share/man/man8/cron.8
file path=usr/share/man/man8/cryptoadm.8
link path=usr/share/man/man8/dcopy.8 target=clri.8
file path=usr/share/man/man8/dd.8
file path=usr/share/man/man8/devattr.8
file path=usr/share/man/man8/devfree.8
file path=usr/share/man/man8/devfsadm.8
link path=usr/share/man/man8/devfsadmd.8 target=devfsadm.8
file path=usr/share/man/man8/devinfo.8
file path=usr/share/man/man8/devlinks.8
file path=usr/share/man/man8/devnm.8
file path=usr/share/man/man8/devprop.8
file path=usr/share/man/man8/devreserv.8
file path=usr/share/man/man8/df.8
file path=usr/share/man/man8/df_ufs.8
file path=usr/share/man/man8/dfmounts.8
file path=usr/share/man/man8/dfmounts_nfs.8
file path=usr/share/man/man8/dfshares.8
file path=usr/share/man/man8/dfshares_nfs.8
file path=usr/share/man/man8/dhcpagent.8
file path=usr/share/man/man8/disks.8
file path=usr/share/man/man8/diskscan.8
file path=usr/share/man/man8/dispadmin.8
file path=usr/share/man/man8/dlmgmtd.8
file path=usr/share/man/man8/dminfo.8
file path=usr/share/man/man8/domainname.8
file path=usr/share/man/man8/drvconfig.8
file path=usr/share/man/man8/dumpadm.8
file path=usr/share/man/man8/edquota.8
file path=usr/share/man/man8/eeprom.8
file path=usr/share/man/man8/embedded_su.8
file path=usr/share/man/man8/fdetach.8
file path=usr/share/man/man8/fdisk.8
file path=usr/share/man/man8/ff.8
file path=usr/share/man/man8/ff_ufs.8
file path=usr/share/man/man8/fiocompress.8
file path=usr/share/man/man8/fmthard.8
file path=usr/share/man/man8/format.8
file path=usr/share/man/man8/fsck.8
file path=usr/share/man/man8/fsck_ufs.8
file path=usr/share/man/man8/fsdb.8
file path=usr/share/man/man8/fsdb_ufs.8
file path=usr/share/man/man8/fsirand.8
file path=usr/share/man/man8/fssnap.8
file path=usr/share/man/man8/fssnap_ufs.8
file path=usr/share/man/man8/fsstat.8
file path=usr/share/man/man8/fstyp.8
file path=usr/share/man/man8/fuser.8
file path=usr/share/man/man8/getdev.8
file path=usr/share/man/man8/getdevpolicy.8
file path=usr/share/man/man8/getdgrp.8
file path=usr/share/man/man8/getent.8
file path=usr/share/man/man8/getty.8
file path=usr/share/man/man8/getvol.8
file path=usr/share/man/man8/groupadd.8
file path=usr/share/man/man8/groupdel.8
file path=usr/share/man/man8/groupmod.8
file path=usr/share/man/man8/growfs.8
link path=usr/share/man/man8/grpck.8 target=pwck.8
file path=usr/share/man/man8/halt.8
file path=usr/share/man/man8/hostconfig.8
file path=usr/share/man/man8/hotplug.8
file path=usr/share/man/man8/id.8
file path=usr/share/man/man8/idmap.8
file path=usr/share/man/man8/idmapd.8
file path=usr/share/man/man8/if_mpadm.8
file path=usr/share/man/man8/ifconfig.8
file path=usr/share/man/man8/ifparse.8
file path=usr/share/man/man8/ikeadm.8
file path=usr/share/man/man8/ikecert.8
file path=usr/share/man/man8/in.iked.8
file path=usr/share/man/man8/in.mpathd.8
file path=usr/share/man/man8/inetadm.8
file path=usr/share/man/man8/inetconv.8
file path=usr/share/man/man8/inetd.8
file path=usr/share/man/man8/infocmp.8
file path=usr/share/man/man8/init.8
file path=usr/share/man/man8/install.8
file path=usr/share/man/man8/installboot.8
file path=usr/share/man/man8/installgrub.8
file path=usr/share/man/man8/intrd.8
link path=usr/share/man/man8/intro.8 target=Intro.8
file path=usr/share/man/man8/iostat.8
file path=usr/share/man/man8/ipaddrsel.8
file path=usr/share/man/man8/ipmpstat.8
file path=usr/share/man/man8/ipsecalgs.8
file path=usr/share/man/man8/ipsecconf.8
file path=usr/share/man/man8/ipseckey.8
file path=usr/share/man/man8/keyserv.8
file path=usr/share/man/man8/killall.8
file path=usr/share/man/man8/labelit.8
file path=usr/share/man/man8/labelit_hsfs.8
file path=usr/share/man/man8/labelit_ufs.8
file path=usr/share/man/man8/link.8
file path=usr/share/man/man8/listdgrp.8
file path=usr/share/man/man8/listen.8
file path=usr/share/man/man8/locator.8
file path=usr/share/man/man8/lockfs.8
file path=usr/share/man/man8/lofiadm.8
file path=usr/share/man/man8/logadm.8
file path=usr/share/man/man8/logins.8
file path=usr/share/man/man8/mail.local.8
file path=usr/share/man/man8/makedbm.8
file path=usr/share/man/man8/mkdevalloc.8
file path=usr/share/man/man8/mkdevmaps.8
file path=usr/share/man/man8/mkfile.8
file path=usr/share/man/man8/mkfs.8
file path=usr/share/man/man8/mkfs_ufs.8
file path=usr/share/man/man8/mknod.8
file path=usr/share/man/man8/mkpwdict.8
file path=usr/share/man/man8/modinfo.8
file path=usr/share/man/man8/modload.8
file path=usr/share/man/man8/modunload.8
file path=usr/share/man/man8/mount.8
file path=usr/share/man/man8/mount_hsfs.8
file path=usr/share/man/man8/mount_tmpfs.8
file path=usr/share/man/man8/mount_ufs.8
file path=usr/share/man/man8/mountall.8
file path=usr/share/man/man8/mpstat.8
file path=usr/share/man/man8/msgid.8
file path=usr/share/man/man8/mvdir.8
file path=usr/share/man/man8/ncheck.8
file path=usr/share/man/man8/ncheck_ufs.8
file path=usr/share/man/man8/ndd.8
file path=usr/share/man/man8/ndp.8
file path=usr/share/man/man8/netstat.8
file path=usr/share/man/man8/netstrategy.8
file path=usr/share/man/man8/newfs.8
file path=usr/share/man/man8/nlsadmin.8
file path=usr/share/man/man8/nscd.8
file path=usr/share/man/man8/nwamd.8
file path=usr/share/man/man8/passmgmt.8
file path=usr/share/man/man8/pbind.8
file path=usr/share/man/man8/ping.8
file path=usr/share/man/man8/pmadm.8
file path=usr/share/man/man8/ports.8
link path=usr/share/man/man8/poweroff.8 target=halt.8
file path=usr/share/man/man8/praudit.8
file path=usr/share/man/man8/prstat.8
file path=usr/share/man/man8/prtconf.8
file path=usr/share/man/man8/prtdiag.8
file path=usr/share/man/man8/prtvtoc.8
file path=usr/share/man/man8/psradm.8
file path=usr/share/man/man8/psrinfo.8
file path=usr/share/man/man8/psrset.8
file path=usr/share/man/man8/putdev.8
file path=usr/share/man/man8/putdgrp.8
file path=usr/share/man/man8/pwck.8
file path=usr/share/man/man8/pwconv.8
file path=usr/share/man/man8/quot.8
file path=usr/share/man/man8/quota.8
file path=usr/share/man/man8/quotacheck.8
link path=usr/share/man/man8/quotaoff.8 target=quotaon.8
file path=usr/share/man/man8/quotaon.8
file path=usr/share/man/man8/raidctl.8
file path=usr/share/man/man8/ramdiskadm.8
file path=usr/share/man/man8/rctladm.8
$(i386_ONLY)file path=usr/share/man/man8/rdmsr.8 variant.opensolaris.zone=global
file path=usr/share/man/man8/reboot.8
file path=usr/share/man/man8/rem_drv.8
file path=usr/share/man/man8/repquota.8
link path=usr/share/man/man8/restricted_shell.8 target=rsh.8
file path=usr/share/man/man8/roleadd.8
file path=usr/share/man/man8/roledel.8
file path=usr/share/man/man8/rolemod.8
file path=usr/share/man/man8/root_archive.8
file path=usr/share/man/man8/route.8
file path=usr/share/man/man8/routeadm.8
file path=usr/share/man/man8/rpcbind.8
file path=usr/share/man/man8/rpcinfo.8
file path=usr/share/man/man8/rsh.8
file path=usr/share/man/man8/rtc.8
file path=usr/share/man/man8/sac.8
file path=usr/share/man/man8/sacadm.8
file path=usr/share/man/man8/saf.8
file path=usr/share/man/man8/savecore.8
file path=usr/share/man/man8/share.8
file path=usr/share/man/man8/share_nfs.8
file path=usr/share/man/man8/shareall.8
file path=usr/share/man/man8/sharectl.8
file path=usr/share/man/man8/sharemgr.8
file path=usr/share/man/man8/shutdown.8
file path=usr/share/man/man8/smbios.8
file path=usr/share/man/man8/soconfig.8
file path=usr/share/man/man8/stmsboot.8
file path=usr/share/man/man8/strace.8
file path=usr/share/man/man8/strclean.8
file path=usr/share/man/man8/strerr.8
file path=usr/share/man/man8/sttydefs.8
file path=usr/share/man/man8/su.8
file path=usr/share/man/man8/sulogin.8
file path=usr/share/man/man8/svc.configd.8
file path=usr/share/man/man8/svc.ipfd.8
file path=usr/share/man/man8/svc.startd.8
file path=usr/share/man/man8/svcadm.8
file path=usr/share/man/man8/svccfg.8
file path=usr/share/man/man8/swap.8
file path=usr/share/man/man8/sync.8
file path=usr/share/man/man8/syncinit.8
file path=usr/share/man/man8/syncloop.8
file path=usr/share/man/man8/syncstat.8
file path=usr/share/man/man8/sysdef.8
file path=usr/share/man/man8/syseventadm.8
file path=usr/share/man/man8/syseventconfd.8
file path=usr/share/man/man8/syseventd.8
file path=usr/share/man/man8/syslogd.8
file path=usr/share/man/man8/tapes.8
file path=usr/share/man/man8/tcpkey.8
link path=usr/share/man/man8/telinit.8 target=init.8
file path=usr/share/man/man8/tic.8
file path=usr/share/man/man8/tpmadm.8
file path=usr/share/man/man8/traceroute.8
file path=usr/share/man/man8/trapstat.8
file path=usr/share/man/man8/ttyadm.8
file path=usr/share/man/man8/ttymon.8
file path=usr/share/man/man8/tunefs.8
file path=usr/share/man/man8/tzreload.8
file path=usr/share/man/man8/tzselect.8
file path=usr/share/man/man8/uadmin.8
file path=usr/share/man/man8/ucodeadm.8
file path=usr/share/man/man8/ufsdump.8
file path=usr/share/man/man8/ufsrestore.8
link path=usr/share/man/man8/umount.8 target=mount.8
link path=usr/share/man/man8/umountall.8 target=mountall.8
link path=usr/share/man/man8/unlink.8 target=link.8
file path=usr/share/man/man8/unshare.8
file path=usr/share/man/man8/unshare_nfs.8
link path=usr/share/man/man8/unshareall.8 target=shareall.8
file path=usr/share/man/man8/update_drv.8
file path=usr/share/man/man8/useradd.8
file path=usr/share/man/man8/userdel.8
file path=usr/share/man/man8/usermod.8
file path=usr/share/man/man8/utmpd.8
file path=usr/share/man/man8/vmstat.8
file path=usr/share/man/man8/volcopy.8
file path=usr/share/man/man8/volcopy_ufs.8
file path=usr/share/man/man8/wall.8
file path=usr/share/man/man8/whodo.8
file path=usr/share/man/man8/wracct.8
file path=usr/share/man/man8/zdump.8
file path=usr/share/man/man8/zic.8
