#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
# Copyright 2021 OmniOS Community Edition (OmniOSce) Association.
#

file path=usr/share/man/man5/Intro.5
link path=usr/share/man/man5/TIMEZONE.5 target=init.5
file path=usr/share/man/man5/audit.log.5
file path=usr/share/man/man5/audit_class.5
file path=usr/share/man/man5/audit_event.5
file path=usr/share/man/man5/auth_attr.5
file path=usr/share/man/man5/contract.5
file path=usr/share/man/man5/core.5
file path=usr/share/man/man5/crypt.conf.5
file path=usr/share/man/man5/crypto_certs.5
file path=usr/share/man/man5/ctf.5
file path=usr/share/man/man5/d_passwd.5
file path=usr/share/man/man5/dacf.conf.5
file path=usr/share/man/man5/default_fs.5
file path=usr/share/man/man5/defaultrouter.5
file path=usr/share/man/man5/device_allocate.5
file path=usr/share/man/man5/device_contract.5
file path=usr/share/man/man5/device_maps.5
file path=usr/share/man/man5/devices.5
link path=usr/share/man/man5/devid_cache.5 target=devices.5
link path=usr/share/man/man5/devname_cache.5 target=devices.5
file path=usr/share/man/man5/dfstab.5
file path=usr/share/man/man5/dhcp_inittab.5
file path=usr/share/man/man5/dialups.5
link path=usr/share/man/man5/dumpdates.5 target=ufsdump.5
file path=usr/share/man/man5/ethers.5
file path=usr/share/man/man5/exec_attr.5
link path=usr/share/man/man5/fbtab.5 target=logindevperm.5
file path=usr/share/man/man5/format.dat.5
link path=usr/share/man/man5/fs.5 target=default_fs.5
file path=usr/share/man/man5/fspec.5
file path=usr/share/man/man5/fstypes.5
file path=usr/share/man/man5/ftpusers.5
file path=usr/share/man/man5/fx_dptbl.5
file path=usr/share/man/man5/group.5
file path=usr/share/man/man5/hosts.5
file path=usr/share/man/man5/ike.config.5
file path=usr/share/man/man5/ike.preshared.5
file path=usr/share/man/man5/inet_type.5
file path=usr/share/man/man5/inetd.conf.5
file path=usr/share/man/man5/init.5
file path=usr/share/man/man5/init.d.5
file path=usr/share/man/man5/inittab.5
link path=usr/share/man/man5/intro.5 target=Intro.5
file path=usr/share/man/man5/ipaddrsel.conf.5
file path=usr/share/man/man5/ipnodes.5
file path=usr/share/man/man5/issue.5
file path=usr/share/man/man5/logadm.conf.5
file path=usr/share/man/man5/logindevperm.5
file path=usr/share/man/man5/loginlog.5
file path=usr/share/man/man5/magic.5
file path=usr/share/man/man5/menu.lst.5
link path=usr/share/man/man5/mdi_ib_cache.5 target=devices.5
link path=usr/share/man/man5/mdi_scsi_vhci_cache.5 target=devices.5
file path=usr/share/man/man5/mnttab.5
file path=usr/share/man/man5/ndpd.conf.5
file path=usr/share/man/man5/netconfig.5
file path=usr/share/man/man5/netgroup.5
file path=usr/share/man/man5/netid.5
file path=usr/share/man/man5/netmasks.5
file path=usr/share/man/man5/networks.5
file path=usr/share/man/man5/nodename.5
file path=usr/share/man/man5/nologin.5
file path=usr/share/man/man5/notrouter.5
file path=usr/share/man/man5/nscd.conf.5
file path=usr/share/man/man5/nsswitch.conf.5
file path=usr/share/man/man5/packingrules.5
file path=usr/share/man/man5/pam.conf.5
file path=usr/share/man/man5/passwd.5
link path=usr/share/man/man5/pci_unitaddr_persistent.5 target=devices.5
file path=usr/share/man/man5/phones.5
file path=usr/share/man/man5/policy.conf.5
file path=usr/share/man/man5/prof_attr.5
file path=usr/share/man/man5/profile.5
file path=usr/share/man/man5/project.5
file path=usr/share/man/man5/protocols.5
file path=usr/share/man/man5/queuedefs.5
file path=usr/share/man/man5/rcmscript.5
file path=usr/share/man/man5/remote.5
file path=usr/share/man/man5/rpc.5
file path=usr/share/man/man5/rt_dptbl.5
file path=usr/share/man/man5/service_bundle.5
file path=usr/share/man/man5/service_provider.conf.5
file path=usr/share/man/man5/services.5
file path=usr/share/man/man5/shadow.5
file path=usr/share/man/man5/sharetab.5
file path=usr/share/man/man5/shells.5
link path=usr/share/man/man5/snapshot_cache.5 target=devices.5
file path=usr/share/man/man5/sulog.5
file path=usr/share/man/man5/syslog.conf.5
file path=usr/share/man/man5/term.5
file path=usr/share/man/man5/terminfo.5
file path=usr/share/man/man5/timezone.5
file path=usr/share/man/man5/ttydefs.5
file path=usr/share/man/man5/ttysrch.5
file path=usr/share/man/man5/ufsdump.5
file path=usr/share/man/man5/user_attr.5
file path=usr/share/man/man5/utmp.5
file path=usr/share/man/man5/utmpx.5
file path=usr/share/man/man5/vfstab.5
link path=usr/share/man/man5/wtmp.5 target=utmp.5
link path=usr/share/man/man5/wtmpx.5 target=utmpx.5
file path=usr/share/man/man5/zoneinfo.5
