#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2011, Richard Lowe

file path=usr/share/man/man4d/kstat.4d
file path=usr/share/man/man4d/ksyms.4d
file path=usr/share/man/man4d/ptm.4d
link path=usr/share/man/man4d/pts.4d target=ptm.4d
