#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

link path=usr/share/man/man7/ANSI.7 target=standards.7
link path=usr/share/man/man7/C++.7 target=standards.7
link path=usr/share/man/man7/C.7 target=standards.7
link path=usr/share/man/man7/CSI.7 target=attributes.7
link path=usr/share/man/man7/ISO.7 target=standards.7
file path=usr/share/man/man7/Intro.7
link path=usr/share/man/man7/MT-Level.7 target=attributes.7
link path=usr/share/man/man7/POSIX.1.7 target=standards.7
link path=usr/share/man/man7/POSIX.2.7 target=standards.7
link path=usr/share/man/man7/POSIX.7 target=standards.7
link path=usr/share/man/man7/RBAC.7 target=rbac.7
link path=usr/share/man/man7/SUS.7 target=standards.7
link path=usr/share/man/man7/SUSv2.7 target=standards.7
link path=usr/share/man/man7/SUSv3.7 target=standards.7
link path=usr/share/man/man7/SVID.7 target=standards.7
link path=usr/share/man/man7/SVID3.7 target=standards.7
link path=usr/share/man/man7/XNS.7 target=standards.7
link path=usr/share/man/man7/XNS4.7 target=standards.7
link path=usr/share/man/man7/XNS5.7 target=standards.7
link path=usr/share/man/man7/XPG.7 target=standards.7
link path=usr/share/man/man7/XPG3.7 target=standards.7
link path=usr/share/man/man7/XPG4.7 target=standards.7
link path=usr/share/man/man7/XPG4v2.7 target=standards.7
file path=usr/share/man/man7/acl.7
file path=usr/share/man/man7/ad.7
link path=usr/share/man/man7/architecture.7 target=attributes.7
file path=usr/share/man/man7/ascii.7
file path=usr/share/man/man7/attributes.7
link path=usr/share/man/man7/availability.7 target=attributes.7
file path=usr/share/man/man7/device_clean.7
file path=usr/share/man/man7/dhcp.7
file path=usr/share/man/man7/filesystem.7
file path=usr/share/man/man7/formats.7
file path=usr/share/man/man7/iconv.7
file path=usr/share/man/man7/iconv_unicode.7
link path=usr/share/man/man7/intro.7 target=Intro.7
file path=usr/share/man/man7/privileges.7
file path=usr/share/man/man7/rbac.7
file path=usr/share/man/man7/resource_controls.7
file path=usr/share/man/man7/security-flags.7
file path=usr/share/man/man7/smf.7
file path=usr/share/man/man7/smf_bootstrap.7
file path=usr/share/man/man7/smf_method.7
file path=usr/share/man/man7/smf_restarter.7
file path=usr/share/man/man7/smf_security.7
file path=usr/share/man/man7/smf_template.7
link path=usr/share/man/man7/stability.7 target=attributes.7
link path=usr/share/man/man7/standard.7 target=attributes.7
file path=usr/share/man/man7/standards.7
file path=usr/share/man/man7/sticky.7
file path=usr/share/man/man7/style.7
file path=usr/share/man/man7/term.7
