#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man5/Intro.5
file path=usr/share/man/man5/acl.5
file path=usr/share/man/man5/ad.5
file path=usr/share/man/man5/ascii.5
file path=usr/share/man/man5/attributes.5
file path=usr/share/man/man5/device_clean.5
file path=usr/share/man/man5/dhcp.5
file path=usr/share/man/man5/filesystem.5
file path=usr/share/man/man5/formats.5
file path=usr/share/man/man5/iconv.5
file path=usr/share/man/man5/iconv_unicode.5
file path=usr/share/man/man5/privileges.5
file path=usr/share/man/man5/rbac.5
file path=usr/share/man/man5/resource_controls.5
file path=usr/share/man/man5/security-flags.5
file path=usr/share/man/man5/smf.5
file path=usr/share/man/man5/smf_bootstrap.5
file path=usr/share/man/man5/smf_method.5
file path=usr/share/man/man5/smf_restarter.5
file path=usr/share/man/man5/smf_security.5
file path=usr/share/man/man5/smf_template.5
file path=usr/share/man/man5/standards.5
file path=usr/share/man/man5/sticky.5
file path=usr/share/man/man5/term.5
link path=usr/share/man/man5/ANSI.5 target=standards.5
link path=usr/share/man/man5/C++.5 target=standards.5
link path=usr/share/man/man5/C.5 target=standards.5
link path=usr/share/man/man5/CSI.5 target=attributes.5
link path=usr/share/man/man5/ISO.5 target=standards.5
link path=usr/share/man/man5/MT-Level.5 target=attributes.5
link path=usr/share/man/man5/POSIX.1.5 target=standards.5
link path=usr/share/man/man5/POSIX.2.5 target=standards.5
link path=usr/share/man/man5/POSIX.5 target=standards.5
link path=usr/share/man/man5/RBAC.5 target=rbac.5
link path=usr/share/man/man5/SUS.5 target=standards.5
link path=usr/share/man/man5/SUSv2.5 target=standards.5
link path=usr/share/man/man5/SUSv3.5 target=standards.5
link path=usr/share/man/man5/SVID.5 target=standards.5
link path=usr/share/man/man5/SVID3.5 target=standards.5
link path=usr/share/man/man5/XNS.5 target=standards.5
link path=usr/share/man/man5/XNS4.5 target=standards.5
link path=usr/share/man/man5/XNS5.5 target=standards.5
link path=usr/share/man/man5/XPG.5 target=standards.5
link path=usr/share/man/man5/XPG3.5 target=standards.5
link path=usr/share/man/man5/XPG4.5 target=standards.5
link path=usr/share/man/man5/XPG4v2.5 target=standards.5
link path=usr/share/man/man5/architecture.5 target=attributes.5
link path=usr/share/man/man5/availability.5 target=attributes.5
link path=usr/share/man/man5/intro.5 target=Intro.5
link path=usr/share/man/man5/stability.5 target=attributes.5
link path=usr/share/man/man5/standard.5 target=attributes.5
