#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2015 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man1/Intro.1
file path=usr/share/man/man1/alias.1
file path=usr/share/man/man1/allocate.1
file path=usr/share/man/man1/amt.1
file path=usr/share/man/man1/arch.1
file path=usr/share/man/man1/at.1
file path=usr/share/man/man1/atq.1
file path=usr/share/man/man1/atrm.1
file path=usr/share/man/man1/auths.1
file path=usr/share/man/man1/basename.1
file path=usr/share/man/man1/break.1
file path=usr/share/man/man1/builtin.1
file path=usr/share/man/man1/cat.1
file path=usr/share/man/man1/cd.1
file path=usr/share/man/man1/chgrp.1
file path=usr/share/man/man1/chmod.1
file path=usr/share/man/man1/chown.1
file path=usr/share/man/man1/ckdate.1
file path=usr/share/man/man1/ckgid.1
file path=usr/share/man/man1/ckint.1
file path=usr/share/man/man1/ckitem.1
file path=usr/share/man/man1/ckkeywd.1
file path=usr/share/man/man1/ckpath.1
file path=usr/share/man/man1/ckrange.1
file path=usr/share/man/man1/ckstr.1
file path=usr/share/man/man1/cksum.1
file path=usr/share/man/man1/cktime.1
file path=usr/share/man/man1/ckuid.1
file path=usr/share/man/man1/ckyorn.1
file path=usr/share/man/man1/clear.1
file path=usr/share/man/man1/cmp.1
file path=usr/share/man/man1/comm.1
file path=usr/share/man/man1/command.1
file path=usr/share/man/man1/cp.1
file path=usr/share/man/man1/cpio.1
file path=usr/share/man/man1/crle.1
file path=usr/share/man/man1/crontab.1
file path=usr/share/man/man1/crypt.1
file path=usr/share/man/man1/csh.1
file path=usr/share/man/man1/ctrun.1
file path=usr/share/man/man1/ctstat.1
file path=usr/share/man/man1/ctwatch.1
file path=usr/share/man/man1/cut.1
file path=usr/share/man/man1/date.1
file path=usr/share/man/man1/deallocate.1
file path=usr/share/man/man1/dhcpinfo.1
file path=usr/share/man/man1/digest.1
file path=usr/share/man/man1/disown.1
file path=usr/share/man/man1/dispgid.1
file path=usr/share/man/man1/dispuid.1
file path=usr/share/man/man1/du.1
file path=usr/share/man/man1/dumpcs.1
file path=usr/share/man/man1/echo.1
file path=usr/share/man/man1/ed.1
file path=usr/share/man/man1/egrep.1
file path=usr/share/man/man1/eject.1
file path=usr/share/man/man1/encrypt.1
file path=usr/share/man/man1/env.1
file path=usr/share/man/man1/exec.1
file path=usr/share/man/man1/exit.1
file path=usr/share/man/man1/expr.1
file path=usr/share/man/man1/fdformat.1
file path=usr/share/man/man1/fgrep.1
file path=usr/share/man/man1/file.1
file path=usr/share/man/man1/find.1
file path=usr/share/man/man1/fmt.1
file path=usr/share/man/man1/fmtmsg.1
file path=usr/share/man/man1/fold.1
file path=usr/share/man/man1/getconf.1
file path=usr/share/man/man1/getfacl.1
file path=usr/share/man/man1/getopt.1
file path=usr/share/man/man1/getoptcvt.1
file path=usr/share/man/man1/getopts.1
file path=usr/share/man/man1/gettext.1
file path=usr/share/man/man1/glob.1
file path=usr/share/man/man1/grep.1
file path=usr/share/man/man1/groups.1
file path=usr/share/man/man1/hash.1
file path=usr/share/man/man1/head.1
file path=usr/share/man/man1/history.1
file path=usr/share/man/man1/hostid.1
file path=usr/share/man/man1/hostname.1
file path=usr/share/man/man1/iconv.1
file path=usr/share/man/man1/isainfo.1
file path=usr/share/man/man1/isalist.1
file path=usr/share/man/man1/jobs.1
file path=usr/share/man/man1/join.1
file path=usr/share/man/man1/kbd.1
file path=usr/share/man/man1/keylogin.1
file path=usr/share/man/man1/keylogout.1
file path=usr/share/man/man1/kill.1
file path=usr/share/man/man1/kmfcfg.1
file path=usr/share/man/man1/ksh93.1
file path=usr/share/man/man1/kvmstat.1
file path=usr/share/man/man1/ld.so.1.1
file path=usr/share/man/man1/let.1
file path=usr/share/man/man1/limit.1
file path=usr/share/man/man1/line.1
file path=usr/share/man/man1/list_devices.1
file path=usr/share/man/man1/listusers.1
file path=usr/share/man/man1/ln.1
file path=usr/share/man/man1/loadkeys.1
file path=usr/share/man/man1/localedef.1
file path=usr/share/man/man1/logger.1
file path=usr/share/man/man1/login.1
file path=usr/share/man/man1/logname.1
file path=usr/share/man/man1/logout.1
file path=usr/share/man/man1/ls.1
file path=usr/share/man/man1/m4.1
file path=usr/share/man/man1/mac.1
file path=usr/share/man/man1/mach.1
file path=usr/share/man/man1/mail.1
file path=usr/share/man/man1/mailx.1
file path=usr/share/man/man1/makekey.1
file path=usr/share/man/man1/mesg.1
file path=usr/share/man/man1/mkdir.1
file path=usr/share/man/man1/mktemp.1
file path=usr/share/man/man1/moe.1
file path=usr/share/man/man1/more.1
file path=usr/share/man/man1/mt.1
file path=usr/share/man/man1/mv.1
file path=usr/share/man/man1/newgrp.1
file path=usr/share/man/man1/newtask.1
file path=usr/share/man/man1/nice.1
file path=usr/share/man/man1/nohup.1
file path=usr/share/man/man1/optisa.1
file path=usr/share/man/man1/pagesize.1
file path=usr/share/man/man1/passwd.1
file path=usr/share/man/man1/paste.1
file path=usr/share/man/man1/pathchk.1
file path=usr/share/man/man1/pax.1
file path=usr/share/man/man1/pfexec.1
file path=usr/share/man/man1/pg.1
file path=usr/share/man/man1/pgrep.1
file path=usr/share/man/man1/pktool.1
file path=usr/share/man/man1/pr.1
file path=usr/share/man/man1/prctl.1
file path=usr/share/man/man1/print.1
file path=usr/share/man/man1/priocntl.1
file path=usr/share/man/man1/proc.1
file path=usr/share/man/man1/profiles.1
file path=usr/share/man/man1/projects.1
file path=usr/share/man/man1/ps.1
file path=usr/share/man/man1/pwd.1
file path=usr/share/man/man1/read.1
file path=usr/share/man/man1/readonly.1
file path=usr/share/man/man1/renice.1
file path=usr/share/man/man1/rev.1
file path=usr/share/man/man1/rm.1
file path=usr/share/man/man1/roles.1
file path=usr/share/man/man1/runat.1
file path=usr/share/man/man1/script.1
file path=usr/share/man/man1/sed.1
file path=usr/share/man/man1/set.1
file path=usr/share/man/man1/setfacl.1
file path=usr/share/man/man1/setpgrp.1
file path=usr/share/man/man1/shcomp.1
file path=usr/share/man/man1/shell_builtins.1
file path=usr/share/man/man1/shift.1
file path=usr/share/man/man1/sleep.1
file path=usr/share/man/man1/strchg.1
file path=usr/share/man/man1/stty.1
file path=usr/share/man/man1/sum.1
file path=usr/share/man/man1/suspend.1
file path=usr/share/man/man1/svcprop.1
file path=usr/share/man/man1/svcs.1
file path=usr/share/man/man1/tabs.1
file path=usr/share/man/man1/tail.1
file path=usr/share/man/man1/tar.1
file path=usr/share/man/man1/tee.1
file path=usr/share/man/man1/test.1
file path=usr/share/man/man1/time.1
file path=usr/share/man/man1/times.1
file path=usr/share/man/man1/tip.1
file path=usr/share/man/man1/touch.1
file path=usr/share/man/man1/tput.1
file path=usr/share/man/man1/tr.1
file path=usr/share/man/man1/trap.1
file path=usr/share/man/man1/true.1
file path=usr/share/man/man1/tty.1
file path=usr/share/man/man1/type.1
file path=usr/share/man/man1/typeset.1
file path=usr/share/man/man1/umask.1
file path=usr/share/man/man1/uname.1
file path=usr/share/man/man1/uniq.1
file path=usr/share/man/man1/uptime.1
file path=usr/share/man/man1/w.1
file path=usr/share/man/man1/wait.1
file path=usr/share/man/man1/wc.1
file path=usr/share/man/man1/which.1
file path=usr/share/man/man1/who.1
file path=usr/share/man/man1/write.1
file path=usr/share/man/man1/xargs.1
file path=usr/share/man/man1/xstr.1
file path=usr/share/man/man1/zonename.1
link path=usr/share/man/man1/batch.1 target=at.1
link path=usr/share/man/man1/bg.1 target=jobs.1
link path=usr/share/man/man1/case.1 target=shell_builtins.1
link path=usr/share/man/man1/chdir.1 target=cd.1
link path=usr/share/man/man1/continue.1 target=break.1
link path=usr/share/man/man1/decrypt.1 target=encrypt.1
link path=usr/share/man/man1/dirname.1 target=basename.1
link path=usr/share/man/man1/dirs.1 target=cd.1
link path=usr/share/man/man1/dumpkeys.1 target=loadkeys.1
link path=usr/share/man/man1/edit.1 target=../../../has/man/man1has/edit.1has
link path=usr/share/man/man1/errange.1 target=ckrange.1
link path=usr/share/man/man1/errdate.1 target=ckdate.1
link path=usr/share/man/man1/errgid.1 target=ckgid.1
link path=usr/share/man/man1/errint.1 target=ckint.1
link path=usr/share/man/man1/erritem.1 target=ckitem.1
link path=usr/share/man/man1/errpath.1 target=ckpath.1
link path=usr/share/man/man1/errstr.1 target=ckstr.1
link path=usr/share/man/man1/errtime.1 target=cktime.1
link path=usr/share/man/man1/erruid.1 target=ckuid.1
link path=usr/share/man/man1/erryorn.1 target=ckyorn.1
link path=usr/share/man/man1/eval.1 target=exec.1
link path=usr/share/man/man1/export.1 target=set.1
link path=usr/share/man/man1/false.1 target=true.1
link path=usr/share/man/man1/fc.1 target=history.1
link path=usr/share/man/man1/fg.1 target=jobs.1
link path=usr/share/man/man1/for.1 target=shell_builtins.1
link path=usr/share/man/man1/foreach.1 target=shell_builtins.1
link path=usr/share/man/man1/function.1 target=shell_builtins.1
link path=usr/share/man/man1/goto.1 target=exit.1
link path=usr/share/man/man1/hashstat.1 target=hash.1
link path=usr/share/man/man1/helpdate.1 target=ckdate.1
link path=usr/share/man/man1/helpgid.1 target=ckgid.1
link path=usr/share/man/man1/helpint.1 target=ckint.1
link path=usr/share/man/man1/helpitem.1 target=ckitem.1
link path=usr/share/man/man1/helppath.1 target=ckpath.1
link path=usr/share/man/man1/helprange.1 target=ckrange.1
link path=usr/share/man/man1/helpstr.1 target=ckstr.1
link path=usr/share/man/man1/helptime.1 target=cktime.1
link path=usr/share/man/man1/helpuid.1 target=ckuid.1
link path=usr/share/man/man1/helpyorn.1 target=ckyorn.1
link path=usr/share/man/man1/hist.1 target=history.1
link path=usr/share/man/man1/if.1 target=shell_builtins.1
link path=usr/share/man/man1/intro.1 target=Intro.1
link path=usr/share/man/man1/jsh.1 target=ksh93.1
link path=usr/share/man/man1/ksh.1 target=ksh93.1
link path=usr/share/man/man1/notify.1 target=jobs.1
link path=usr/share/man/man1/onintr.1 target=trap.1
link path=usr/share/man/man1/page.1 target=more.1
link path=usr/share/man/man1/pcred.1 target=proc.1
link path=usr/share/man/man1/pfcsh.1 target=pfexec.1
link path=usr/share/man/man1/pfiles.1 target=proc.1
link path=usr/share/man/man1/pfksh.1 target=pfexec.1
link path=usr/share/man/man1/pflags.1 target=proc.1
link path=usr/share/man/man1/pfsh.1 target=pfexec.1
link path=usr/share/man/man1/pkill.1 target=pgrep.1
link path=usr/share/man/man1/pldd.1 target=proc.1
link path=usr/share/man/man1/popd.1 target=cd.1
link path=usr/share/man/man1/prun.1 target=proc.1
link path=usr/share/man/man1/psig.1 target=proc.1
link path=usr/share/man/man1/pstack.1 target=proc.1
link path=usr/share/man/man1/pstop.1 target=proc.1
link path=usr/share/man/man1/ptime.1 target=proc.1
link path=usr/share/man/man1/pushd.1 target=cd.1
link path=usr/share/man/man1/pwait.1 target=proc.1
link path=usr/share/man/man1/pwdx.1 target=proc.1
link path=usr/share/man/man1/red.1 target=ed.1
link path=usr/share/man/man1/rehash.1 target=hash.1
link path=usr/share/man/man1/repeat.1 target=shell_builtins.1
link path=usr/share/man/man1/return.1 target=exit.1
link path=usr/share/man/man1/rksh.1 target=ksh93.1
link path=usr/share/man/man1/rksh93.1 target=ksh93.1
link path=usr/share/man/man1/rmail.1 target=mail.1
link path=usr/share/man/man1/rmdir.1 target=rm.1
link path=usr/share/man/man1/select.1 target=shell_builtins.1
link path=usr/share/man/man1/setenv.1 target=set.1
link path=usr/share/man/man1/settime.1 target=touch.1
link path=usr/share/man/man1/sh.1 target=ksh93.1
link path=usr/share/man/man1/source.1 target=exec.1
link path=usr/share/man/man1/stop.1 target=jobs.1
link path=usr/share/man/man1/strconf.1 target=strchg.1
link path=usr/share/man/man1/switch.1 target=shell_builtins.1
link path=usr/share/man/man1/ulimit.1 target=limit.1
link path=usr/share/man/man1/unalias.1 target=alias.1
link path=usr/share/man/man1/unhash.1 target=hash.1
link path=usr/share/man/man1/unlimit.1 target=limit.1
link path=usr/share/man/man1/unset.1 target=set.1
link path=usr/share/man/man1/unsetenv.1 target=set.1
link path=usr/share/man/man1/until.1 target=shell_builtins.1
link path=usr/share/man/man1/valdate.1 target=ckdate.1
link path=usr/share/man/man1/valgid.1 target=ckgid.1
link path=usr/share/man/man1/valint.1 target=ckint.1
link path=usr/share/man/man1/valpath.1 target=ckpath.1
link path=usr/share/man/man1/valrange.1 target=ckrange.1
link path=usr/share/man/man1/valstr.1 target=ckstr.1
link path=usr/share/man/man1/valtime.1 target=cktime.1
link path=usr/share/man/man1/valuid.1 target=ckuid.1
link path=usr/share/man/man1/valyorn.1 target=ckyorn.1
link path=usr/share/man/man1/vedit.1 target=../../../has/man/man1has/vi.1has
link path=usr/share/man/man1/whence.1 target=typeset.1
link path=usr/share/man/man1/while.1 target=shell_builtins.1
