#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man4fs/bootfs.4fs
file path=usr/share/man/man4fs/ctfs.4fs
file path=usr/share/man/man4fs/dcfs.4fs
file path=usr/share/man/man4fs/dev.4fs
file path=usr/share/man/man4fs/devfs.4fs
file path=usr/share/man/man4fs/fd.4fs
file path=usr/share/man/man4fs/hsfs.4fs
file path=usr/share/man/man4fs/lofs.4fs
file path=usr/share/man/man4fs/objfs.4fs
file path=usr/share/man/man4fs/sharefs.4fs
link path=usr/share/man/man4fs/stderr.4fs target=fd.4fs
link path=usr/share/man/man4fs/stdin.4fs target=fd.4fs
link path=usr/share/man/man4fs/stdout.4fs target=fd.4fs
file path=usr/share/man/man4fs/tmpfs.4fs
file path=usr/share/man/man4fs/ufs.4fs
