#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man5/cardbus.5
link path=usr/share/man/man5/dir.5 target=dir_ufs.5
file path=usr/share/man/man5/dir_ufs.5
file path=usr/share/man/man5/driver.conf.5
file path=usr/share/man/man5/pci.5
link path=usr/share/man/man5/pcie.5 target=pci.5
file path=usr/share/man/man5/priv_names.5
file path=usr/share/man/man5/proc.5
file path=usr/share/man/man5/process.5
file path=usr/share/man/man5/pseudo.5
file path=usr/share/man/man5/scsi.5
file path=usr/share/man/man5/sock2path.d.5
file path=usr/share/man/man5/system.5
file path=usr/share/man/man5/ts_dptbl.5
