#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2014 Nexenta Systems, Inc.
#

link path=usr/share/man/man7/advance.7 target=regexp.7
file path=usr/share/man/man7/audit_binfile.7
file path=usr/share/man/man7/audit_remote.7
file path=usr/share/man/man7/audit_syslog.7
file path=usr/share/man/man7/byteorder.7
file path=usr/share/man/man7/cancellation.7
file path=usr/share/man/man7/charmap.7
link path=usr/share/man/man7/compile.7 target=regexp.7
file path=usr/share/man/man7/condition.7
file path=usr/share/man/man7/crypt_bsdbf.7
file path=usr/share/man/man7/crypt_bsdmd5.7
file path=usr/share/man/man7/crypt_sha256.7
file path=usr/share/man/man7/crypt_sha512.7
file path=usr/share/man/man7/crypt_sunmd5.7
file path=usr/share/man/man7/crypt_unix.7
link path=usr/share/man/man7/endian.7 target=byteorder.7
file path=usr/share/man/man7/environ.7
file path=usr/share/man/man7/eventfd.7
file path=usr/share/man/man7/extendedFILE.7
file path=usr/share/man/man7/fnmatch.7
file path=usr/share/man/man7/isalist.7
file path=usr/share/man/man7/largefile.7
file path=usr/share/man/man7/lf64.7
file path=usr/share/man/man7/lfcompile.7
file path=usr/share/man/man7/lfcompile64.7
file path=usr/share/man/man7/locale.7
file path=usr/share/man/man7/mutex.7
file path=usr/share/man/man7/pam_allow.7
file path=usr/share/man/man7/pam_authtok_check.7
file path=usr/share/man/man7/pam_authtok_get.7
file path=usr/share/man/man7/pam_authtok_store.7
file path=usr/share/man/man7/pam_deny.7
file path=usr/share/man/man7/pam_dhkeys.7
file path=usr/share/man/man7/pam_dial_auth.7
file path=usr/share/man/man7/pam_ldap.7
file path=usr/share/man/man7/pam_list.7
file path=usr/share/man/man7/pam_passwd_auth.7
file path=usr/share/man/man7/pam_rhosts_auth.7
file path=usr/share/man/man7/pam_roles.7
file path=usr/share/man/man7/pam_sample.7
file path=usr/share/man/man7/pam_timestamp.7
file path=usr/share/man/man7/pam_tsol_account.7
file path=usr/share/man/man7/pam_unix_account.7
file path=usr/share/man/man7/pam_unix_auth.7
file path=usr/share/man/man7/pam_unix_cred.7
file path=usr/share/man/man7/pam_unix_session.7
file path=usr/share/man/man7/pkcs11_kernel.7
file path=usr/share/man/man7/pkcs11_softtoken.7
file path=usr/share/man/man7/pkcs11_tpm.7
link path=usr/share/man/man7/pthreads.7 target=threads.7
file path=usr/share/man/man7/regex.7
file path=usr/share/man/man7/regexp.7
link path=usr/share/man/man7/step.7 target=regexp.7
file path=usr/share/man/man7/threads.7
file path=usr/share/man/man7/timerfd.7
