#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2017, Richard Lowe

file path=usr/share/man/man3resolv/resolver.3resolv
link path=usr/share/man/man3resolv/dn_comp.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/dn_expand.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/fp_resstat.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/herror.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/hstrerror.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_getservers.3resolv \
    target=resolver.3resolv
link path=usr/share/man/man3resolv/res_hostalias.3resolv \
    target=resolver.3resolv
link path=usr/share/man/man3resolv/res_init.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_mkquery.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_nclose.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_ndestroy.3resolv \
    target=resolver.3resolv
link path=usr/share/man/man3resolv/res_ninit.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_nmkquery.3resolv \
    target=resolver.3resolv
link path=usr/share/man/man3resolv/res_nquery.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_nquerydomain.3resolv \
    target=resolver.3resolv
link path=usr/share/man/man3resolv/res_nsearch.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_nsend.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_nsendsigned.3resolv \
    target=resolver.3resolv
link path=usr/share/man/man3resolv/res_query.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_search.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_send.3resolv target=resolver.3resolv
link path=usr/share/man/man3resolv/res_setservers.3resolv \
    target=resolver.3resolv
