#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3curses/curs_addch.3curses
file path=usr/share/man/man3curses/curs_addchstr.3curses
file path=usr/share/man/man3curses/curs_addstr.3curses
file path=usr/share/man/man3curses/curs_addwch.3curses
file path=usr/share/man/man3curses/curs_addwchstr.3curses
file path=usr/share/man/man3curses/curs_addwstr.3curses
file path=usr/share/man/man3curses/curs_alecompat.3curses
file path=usr/share/man/man3curses/curs_attr.3curses
file path=usr/share/man/man3curses/curs_beep.3curses
file path=usr/share/man/man3curses/curs_bkgd.3curses
file path=usr/share/man/man3curses/curs_border.3curses
file path=usr/share/man/man3curses/curs_clear.3curses
file path=usr/share/man/man3curses/curs_color.3curses
file path=usr/share/man/man3curses/curs_delch.3curses
file path=usr/share/man/man3curses/curs_deleteln.3curses
file path=usr/share/man/man3curses/curs_getch.3curses
file path=usr/share/man/man3curses/curs_getstr.3curses
file path=usr/share/man/man3curses/curs_getwch.3curses
file path=usr/share/man/man3curses/curs_getwstr.3curses
file path=usr/share/man/man3curses/curs_getyx.3curses
file path=usr/share/man/man3curses/curs_inch.3curses
file path=usr/share/man/man3curses/curs_inchstr.3curses
file path=usr/share/man/man3curses/curs_initscr.3curses
file path=usr/share/man/man3curses/curs_inopts.3curses
file path=usr/share/man/man3curses/curs_insch.3curses
file path=usr/share/man/man3curses/curs_insstr.3curses
file path=usr/share/man/man3curses/curs_instr.3curses
file path=usr/share/man/man3curses/curs_inswch.3curses
file path=usr/share/man/man3curses/curs_inswstr.3curses
file path=usr/share/man/man3curses/curs_inwch.3curses
file path=usr/share/man/man3curses/curs_inwchstr.3curses
file path=usr/share/man/man3curses/curs_inwstr.3curses
file path=usr/share/man/man3curses/curs_kernel.3curses
file path=usr/share/man/man3curses/curs_move.3curses
file path=usr/share/man/man3curses/curs_outopts.3curses
file path=usr/share/man/man3curses/curs_overlay.3curses
file path=usr/share/man/man3curses/curs_pad.3curses
file path=usr/share/man/man3curses/curs_printw.3curses
file path=usr/share/man/man3curses/curs_refresh.3curses
file path=usr/share/man/man3curses/curs_scanw.3curses
file path=usr/share/man/man3curses/curs_scr_dump.3curses
file path=usr/share/man/man3curses/curs_scroll.3curses
file path=usr/share/man/man3curses/curs_slk.3curses
file path=usr/share/man/man3curses/curs_termattrs.3curses
file path=usr/share/man/man3curses/curs_termcap.3curses
file path=usr/share/man/man3curses/curs_terminfo.3curses
file path=usr/share/man/man3curses/curs_touch.3curses
file path=usr/share/man/man3curses/curs_util.3curses
file path=usr/share/man/man3curses/curs_window.3curses
file path=usr/share/man/man3curses/curses.3curses
file path=usr/share/man/man3curses/form_cursor.3curses
file path=usr/share/man/man3curses/form_data.3curses
file path=usr/share/man/man3curses/form_driver.3curses
file path=usr/share/man/man3curses/form_field.3curses
file path=usr/share/man/man3curses/form_field_attributes.3curses
file path=usr/share/man/man3curses/form_field_buffer.3curses
file path=usr/share/man/man3curses/form_field_info.3curses
file path=usr/share/man/man3curses/form_field_just.3curses
file path=usr/share/man/man3curses/form_field_new.3curses
file path=usr/share/man/man3curses/form_field_opts.3curses
file path=usr/share/man/man3curses/form_field_userptr.3curses
file path=usr/share/man/man3curses/form_field_validation.3curses
file path=usr/share/man/man3curses/form_fieldtype.3curses
file path=usr/share/man/man3curses/form_hook.3curses
file path=usr/share/man/man3curses/form_new.3curses
file path=usr/share/man/man3curses/form_new_page.3curses
file path=usr/share/man/man3curses/form_opts.3curses
file path=usr/share/man/man3curses/form_page.3curses
file path=usr/share/man/man3curses/form_post.3curses
file path=usr/share/man/man3curses/form_userptr.3curses
file path=usr/share/man/man3curses/form_win.3curses
file path=usr/share/man/man3curses/forms.3curses
file path=usr/share/man/man3curses/menu_attributes.3curses
file path=usr/share/man/man3curses/menu_cursor.3curses
file path=usr/share/man/man3curses/menu_driver.3curses
file path=usr/share/man/man3curses/menu_format.3curses
file path=usr/share/man/man3curses/menu_hook.3curses
file path=usr/share/man/man3curses/menu_item_current.3curses
file path=usr/share/man/man3curses/menu_item_name.3curses
file path=usr/share/man/man3curses/menu_item_new.3curses
file path=usr/share/man/man3curses/menu_item_opts.3curses
file path=usr/share/man/man3curses/menu_item_userptr.3curses
file path=usr/share/man/man3curses/menu_item_value.3curses
file path=usr/share/man/man3curses/menu_item_visible.3curses
file path=usr/share/man/man3curses/menu_items.3curses
file path=usr/share/man/man3curses/menu_mark.3curses
file path=usr/share/man/man3curses/menu_new.3curses
file path=usr/share/man/man3curses/menu_opts.3curses
file path=usr/share/man/man3curses/menu_pattern.3curses
file path=usr/share/man/man3curses/menu_post.3curses
file path=usr/share/man/man3curses/menu_userptr.3curses
file path=usr/share/man/man3curses/menu_win.3curses
file path=usr/share/man/man3curses/menus.3curses
file path=usr/share/man/man3curses/panel_above.3curses
file path=usr/share/man/man3curses/panel_move.3curses
file path=usr/share/man/man3curses/panel_new.3curses
file path=usr/share/man/man3curses/panel_show.3curses
file path=usr/share/man/man3curses/panel_top.3curses
file path=usr/share/man/man3curses/panel_update.3curses
file path=usr/share/man/man3curses/panel_userptr.3curses
file path=usr/share/man/man3curses/panel_window.3curses
file path=usr/share/man/man3curses/panels.3curses
link path=usr/share/man/man3curses/addch.3curses target=curs_addch.3curses
link path=usr/share/man/man3curses/addchnstr.3curses \
    target=curs_addchstr.3curses
link path=usr/share/man/man3curses/addchstr.3curses \
    target=curs_addchstr.3curses
link path=usr/share/man/man3curses/addnstr.3curses target=curs_addstr.3curses
link path=usr/share/man/man3curses/addnwstr.3curses \
    target=curs_addwstr.3curses
link path=usr/share/man/man3curses/addstr.3curses target=curs_addstr.3curses
link path=usr/share/man/man3curses/addwch.3curses target=curs_addwch.3curses
link path=usr/share/man/man3curses/addwchnstr.3curses \
    target=curs_addwchstr.3curses
link path=usr/share/man/man3curses/addwchstr.3curses \
    target=curs_addwchstr.3curses
link path=usr/share/man/man3curses/addwstr.3curses target=curs_addwstr.3curses
link path=usr/share/man/man3curses/adjcurspos.3curses \
    target=curs_alecompat.3curses
link path=usr/share/man/man3curses/attroff.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/attron.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/attrset.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/baudrate.3curses \
    target=curs_termattrs.3curses
link path=usr/share/man/man3curses/beep.3curses target=curs_beep.3curses
link path=usr/share/man/man3curses/bkgd.3curses target=curs_bkgd.3curses
link path=usr/share/man/man3curses/bkgdset.3curses target=curs_bkgd.3curses
link path=usr/share/man/man3curses/border.3curses target=curs_border.3curses
link path=usr/share/man/man3curses/bottom_panel.3curses \
    target=panel_top.3curses
link path=usr/share/man/man3curses/box.3curses target=curs_border.3curses
link path=usr/share/man/man3curses/can_change_color.3curses \
    target=curs_color.3curses
link path=usr/share/man/man3curses/cbreak.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/clear.3curses target=curs_clear.3curses
link path=usr/share/man/man3curses/clearok.3curses target=curs_outopts.3curses
link path=usr/share/man/man3curses/clrtobot.3curses target=curs_clear.3curses
link path=usr/share/man/man3curses/clrtoeol.3curses target=curs_clear.3curses
link path=usr/share/man/man3curses/color_content.3curses \
    target=curs_color.3curses
link path=usr/share/man/man3curses/copywin.3curses target=curs_overlay.3curses
link path=usr/share/man/man3curses/current_field.3curses \
    target=form_page.3curses
link path=usr/share/man/man3curses/current_item.3curses \
    target=menu_item_current.3curses
link path=usr/share/man/man3curses/curs_set.3curses target=curs_kernel.3curses
link path=usr/share/man/man3curses/data_ahead.3curses target=form_data.3curses
link path=usr/share/man/man3curses/data_behind.3curses \
    target=form_data.3curses
link path=usr/share/man/man3curses/def_prog_mode.3curses \
    target=curs_kernel.3curses
link path=usr/share/man/man3curses/def_shell_mode.3curses \
    target=curs_kernel.3curses
link path=usr/share/man/man3curses/del_curterm.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/del_panel.3curses target=panel_new.3curses
link path=usr/share/man/man3curses/delay_output.3curses \
    target=curs_util.3curses
link path=usr/share/man/man3curses/delch.3curses target=curs_delch.3curses
link path=usr/share/man/man3curses/deleteln.3curses \
    target=curs_deleteln.3curses
link path=usr/share/man/man3curses/delscreen.3curses \
    target=curs_initscr.3curses
link path=usr/share/man/man3curses/delwin.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/derwin.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/doupdate.3curses \
    target=curs_refresh.3curses
link path=usr/share/man/man3curses/dup_field.3curses \
    target=form_field_new.3curses
link path=usr/share/man/man3curses/dupwin.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/dynamic_field_info.3curses \
    target=form_field_info.3curses
link path=usr/share/man/man3curses/echo.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/echochar.3curses target=curs_addch.3curses
link path=usr/share/man/man3curses/echowchar.3curses \
    target=curs_addwch.3curses
link path=usr/share/man/man3curses/endwin.3curses target=curs_initscr.3curses
link path=usr/share/man/man3curses/erase.3curses target=curs_clear.3curses
link path=usr/share/man/man3curses/erasechar.3curses \
    target=curs_termattrs.3curses
link path=usr/share/man/man3curses/field_arg.3curses \
    target=form_field_validation.3curses
link path=usr/share/man/man3curses/field_back.3curses \
    target=form_field_attributes.3curses
link path=usr/share/man/man3curses/field_buffer.3curses \
    target=form_field_buffer.3curses
link path=usr/share/man/man3curses/field_count.3curses \
    target=form_field.3curses
link path=usr/share/man/man3curses/field_fore.3curses \
    target=form_field_attributes.3curses
link path=usr/share/man/man3curses/field_index.3curses \
    target=form_page.3curses
link path=usr/share/man/man3curses/field_info.3curses \
    target=form_field_info.3curses
link path=usr/share/man/man3curses/field_init.3curses target=form_hook.3curses
link path=usr/share/man/man3curses/field_just.3curses \
    target=form_field_just.3curses
link path=usr/share/man/man3curses/field_opts.3curses \
    target=form_field_opts.3curses
link path=usr/share/man/man3curses/field_opts_off.3curses \
    target=form_field_opts.3curses
link path=usr/share/man/man3curses/field_opts_on.3curses \
    target=form_field_opts.3curses
link path=usr/share/man/man3curses/field_pad.3curses \
    target=form_field_attributes.3curses
link path=usr/share/man/man3curses/field_status.3curses \
    target=form_field_buffer.3curses
link path=usr/share/man/man3curses/field_term.3curses target=form_hook.3curses
link path=usr/share/man/man3curses/field_type.3curses \
    target=form_field_validation.3curses
link path=usr/share/man/man3curses/field_userptr.3curses \
    target=form_field_userptr.3curses
link path=usr/share/man/man3curses/filter.3curses target=curs_util.3curses
link path=usr/share/man/man3curses/flash.3curses target=curs_beep.3curses
link path=usr/share/man/man3curses/flushinp.3curses target=curs_util.3curses
link path=usr/share/man/man3curses/form_fields.3curses \
    target=form_field.3curses
link path=usr/share/man/man3curses/form_init.3curses target=form_hook.3curses
link path=usr/share/man/man3curses/form_opts_off.3curses \
    target=form_opts.3curses
link path=usr/share/man/man3curses/form_opts_on.3curses \
    target=form_opts.3curses
link path=usr/share/man/man3curses/form_sub.3curses target=form_win.3curses
link path=usr/share/man/man3curses/form_term.3curses target=form_hook.3curses
link path=usr/share/man/man3curses/free_field.3curses \
    target=form_field_new.3curses
link path=usr/share/man/man3curses/free_fieldtype.3curses \
    target=form_fieldtype.3curses
link path=usr/share/man/man3curses/free_form.3curses target=form_new.3curses
link path=usr/share/man/man3curses/free_item.3curses \
    target=menu_item_new.3curses
link path=usr/share/man/man3curses/free_menu.3curses target=menu_new.3curses
link path=usr/share/man/man3curses/getbegyx.3curses target=curs_getyx.3curses
link path=usr/share/man/man3curses/getch.3curses target=curs_getch.3curses
link path=usr/share/man/man3curses/getmaxyx.3curses target=curs_getyx.3curses
link path=usr/share/man/man3curses/getnwstr.3curses \
    target=curs_getwstr.3curses
link path=usr/share/man/man3curses/getparyx.3curses target=curs_getyx.3curses
link path=usr/share/man/man3curses/getstr.3curses target=curs_getstr.3curses
link path=usr/share/man/man3curses/getsyx.3curses target=curs_kernel.3curses
link path=usr/share/man/man3curses/getwch.3curses target=curs_getwch.3curses
link path=usr/share/man/man3curses/getwin.3curses target=curs_util.3curses
link path=usr/share/man/man3curses/getwstr.3curses target=curs_getwstr.3curses
link path=usr/share/man/man3curses/getyx.3curses target=curs_getyx.3curses
link path=usr/share/man/man3curses/halfdelay.3curses \
    target=curs_inopts.3curses
link path=usr/share/man/man3curses/has_colors.3curses \
    target=curs_color.3curses
link path=usr/share/man/man3curses/has_ic.3curses \
    target=curs_termattrs.3curses
link path=usr/share/man/man3curses/has_il.3curses \
    target=curs_termattrs.3curses
link path=usr/share/man/man3curses/hide_panel.3curses \
    target=panel_show.3curses
link path=usr/share/man/man3curses/idcok.3curses target=curs_outopts.3curses
link path=usr/share/man/man3curses/idlok.3curses target=curs_outopts.3curses
link path=usr/share/man/man3curses/immedok.3curses target=curs_outopts.3curses
link path=usr/share/man/man3curses/inch.3curses target=curs_inch.3curses
link path=usr/share/man/man3curses/inchnstr.3curses \
    target=curs_inchstr.3curses
link path=usr/share/man/man3curses/inchstr.3curses target=curs_inchstr.3curses
link path=usr/share/man/man3curses/init_color.3curses \
    target=curs_color.3curses
link path=usr/share/man/man3curses/init_pair.3curses target=curs_color.3curses
link path=usr/share/man/man3curses/initscr.3curses target=curs_initscr.3curses
link path=usr/share/man/man3curses/innstr.3curses target=curs_instr.3curses
link path=usr/share/man/man3curses/innwstr.3curses target=curs_inwstr.3curses
link path=usr/share/man/man3curses/insch.3curses target=curs_insch.3curses
link path=usr/share/man/man3curses/insdelln.3curses \
    target=curs_deleteln.3curses
link path=usr/share/man/man3curses/insertln.3curses \
    target=curs_deleteln.3curses
link path=usr/share/man/man3curses/insnstr.3curses target=curs_insstr.3curses
link path=usr/share/man/man3curses/insnwstr.3curses \
    target=curs_inswstr.3curses
link path=usr/share/man/man3curses/insstr.3curses target=curs_insstr.3curses
link path=usr/share/man/man3curses/instr.3curses target=curs_instr.3curses
link path=usr/share/man/man3curses/inswch.3curses target=curs_inswch.3curses
link path=usr/share/man/man3curses/inswstr.3curses target=curs_inswstr.3curses
link path=usr/share/man/man3curses/intrflush.3curses \
    target=curs_inopts.3curses
link path=usr/share/man/man3curses/inwch.3curses target=curs_inwch.3curses
link path=usr/share/man/man3curses/inwchnstr.3curses \
    target=curs_inwchstr.3curses
link path=usr/share/man/man3curses/inwchstr.3curses \
    target=curs_inwchstr.3curses
link path=usr/share/man/man3curses/inwstr.3curses target=curs_inwstr.3curses
link path=usr/share/man/man3curses/is_linetouched.3curses \
    target=curs_touch.3curses
link path=usr/share/man/man3curses/is_wintouched.3curses \
    target=curs_touch.3curses
link path=usr/share/man/man3curses/isendwin.3curses \
    target=curs_initscr.3curses
link path=usr/share/man/man3curses/item_count.3curses \
    target=menu_items.3curses
link path=usr/share/man/man3curses/item_description.3curses \
    target=menu_item_name.3curses
link path=usr/share/man/man3curses/item_index.3curses \
    target=menu_item_current.3curses
link path=usr/share/man/man3curses/item_init.3curses target=menu_hook.3curses
link path=usr/share/man/man3curses/item_name.3curses \
    target=menu_item_name.3curses
link path=usr/share/man/man3curses/item_opts.3curses \
    target=menu_item_opts.3curses
link path=usr/share/man/man3curses/item_opts_off.3curses \
    target=menu_item_opts.3curses
link path=usr/share/man/man3curses/item_opts_on.3curses \
    target=menu_item_opts.3curses
link path=usr/share/man/man3curses/item_term.3curses target=menu_hook.3curses
link path=usr/share/man/man3curses/item_userptr.3curses \
    target=menu_item_userptr.3curses
link path=usr/share/man/man3curses/item_value.3curses \
    target=menu_item_value.3curses
link path=usr/share/man/man3curses/item_visible.3curses \
    target=menu_item_visible.3curses
link path=usr/share/man/man3curses/keyname.3curses target=curs_util.3curses
link path=usr/share/man/man3curses/keypad.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/killchar.3curses \
    target=curs_termattrs.3curses
link path=usr/share/man/man3curses/leaveok.3curses target=curs_outopts.3curses
link path=usr/share/man/man3curses/link_field.3curses \
    target=form_field_new.3curses
link path=usr/share/man/man3curses/link_fieldtype.3curses \
    target=form_fieldtype.3curses
link path=usr/share/man/man3curses/longname.3curses \
    target=curs_termattrs.3curses
link path=usr/share/man/man3curses/menu_back.3curses \
    target=menu_attributes.3curses
link path=usr/share/man/man3curses/menu_fore.3curses \
    target=menu_attributes.3curses
link path=usr/share/man/man3curses/menu_grey.3curses \
    target=menu_attributes.3curses
link path=usr/share/man/man3curses/menu_init.3curses target=menu_hook.3curses
link path=usr/share/man/man3curses/menu_opts_off.3curses \
    target=menu_opts.3curses
link path=usr/share/man/man3curses/menu_opts_on.3curses \
    target=menu_opts.3curses
link path=usr/share/man/man3curses/menu_pad.3curses \
    target=menu_attributes.3curses
link path=usr/share/man/man3curses/menu_sub.3curses target=menu_win.3curses
link path=usr/share/man/man3curses/menu_term.3curses target=menu_hook.3curses
link path=usr/share/man/man3curses/meta.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/move.3curses target=curs_move.3curses
link path=usr/share/man/man3curses/move_field.3curses \
    target=form_field.3curses
link path=usr/share/man/man3curses/move_panel.3curses \
    target=panel_move.3curses
link path=usr/share/man/man3curses/movenextch.3curses \
    target=curs_alecompat.3curses
link path=usr/share/man/man3curses/moveprevch.3curses \
    target=curs_alecompat.3curses
link path=usr/share/man/man3curses/mvaddch.3curses target=curs_addch.3curses
link path=usr/share/man/man3curses/mvaddchnstr.3curses \
    target=curs_addchstr.3curses
link path=usr/share/man/man3curses/mvaddchstr.3curses \
    target=curs_addchstr.3curses
link path=usr/share/man/man3curses/mvaddnstr.3curses \
    target=curs_addstr.3curses
link path=usr/share/man/man3curses/mvaddnwstr.3curses \
    target=curs_addwstr.3curses
link path=usr/share/man/man3curses/mvaddstr.3curses target=curs_addstr.3curses
link path=usr/share/man/man3curses/mvaddwch.3curses target=curs_addwch.3curses
link path=usr/share/man/man3curses/mvaddwchnstr.3curses \
    target=curs_addwchstr.3curses
link path=usr/share/man/man3curses/mvaddwchstr.3curses \
    target=curs_addwchstr.3curses
link path=usr/share/man/man3curses/mvaddwstr.3curses \
    target=curs_addwstr.3curses
link path=usr/share/man/man3curses/mvcur.3curses target=curs_terminfo.3curses
link path=usr/share/man/man3curses/mvdelch.3curses target=curs_delch.3curses
link path=usr/share/man/man3curses/mvderwin.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/mvgetch.3curses target=curs_getch.3curses
link path=usr/share/man/man3curses/mvgetnwstr.3curses \
    target=curs_getwstr.3curses
link path=usr/share/man/man3curses/mvgetstr.3curses target=curs_getstr.3curses
link path=usr/share/man/man3curses/mvgetwch.3curses target=curs_getwch.3curses
link path=usr/share/man/man3curses/mvgetwstr.3curses \
    target=curs_getwstr.3curses
link path=usr/share/man/man3curses/mvinch.3curses target=curs_inch.3curses
link path=usr/share/man/man3curses/mvinchnstr.3curses \
    target=curs_inchstr.3curses
link path=usr/share/man/man3curses/mvinchstr.3curses \
    target=curs_inchstr.3curses
link path=usr/share/man/man3curses/mvinnstr.3curses target=curs_instr.3curses
link path=usr/share/man/man3curses/mvinnwstr.3curses \
    target=curs_inwstr.3curses
link path=usr/share/man/man3curses/mvinsch.3curses target=curs_insch.3curses
link path=usr/share/man/man3curses/mvinsnstr.3curses \
    target=curs_insstr.3curses
link path=usr/share/man/man3curses/mvinsnwstr.3curses \
    target=curs_inswstr.3curses
link path=usr/share/man/man3curses/mvinsstr.3curses target=curs_insstr.3curses
link path=usr/share/man/man3curses/mvinstr.3curses target=curs_instr.3curses
link path=usr/share/man/man3curses/mvinswch.3curses target=curs_inswch.3curses
link path=usr/share/man/man3curses/mvinswstr.3curses \
    target=curs_inswstr.3curses
link path=usr/share/man/man3curses/mvinwch.3curses target=curs_inwch.3curses
link path=usr/share/man/man3curses/mvinwchnstr.3curses \
    target=curs_inwchstr.3curses
link path=usr/share/man/man3curses/mvinwchstr.3curses \
    target=curs_inwchstr.3curses
link path=usr/share/man/man3curses/mvinwstr.3curses target=curs_inwstr.3curses
link path=usr/share/man/man3curses/mvprintw.3curses target=curs_printw.3curses
link path=usr/share/man/man3curses/mvscanw.3curses target=curs_scanw.3curses
link path=usr/share/man/man3curses/mvwaddch.3curses target=curs_addch.3curses
link path=usr/share/man/man3curses/mvwaddchnstr.3curses \
    target=curs_addchstr.3curses
link path=usr/share/man/man3curses/mvwaddchstr.3curses \
    target=curs_addchstr.3curses
link path=usr/share/man/man3curses/mvwaddnstr.3curses \
    target=curs_addstr.3curses
link path=usr/share/man/man3curses/mvwaddnwstr.3curses \
    target=curs_addwstr.3curses
link path=usr/share/man/man3curses/mvwaddstr.3curses \
    target=curs_addstr.3curses
link path=usr/share/man/man3curses/mvwaddwch.3curses \
    target=curs_addwch.3curses
link path=usr/share/man/man3curses/mvwaddwchnstr.3curses \
    target=curs_addwchstr.3curses
link path=usr/share/man/man3curses/mvwaddwchstr.3curses \
    target=curs_addwchstr.3curses
link path=usr/share/man/man3curses/mvwaddwstr.3curses \
    target=curs_addwstr.3curses
link path=usr/share/man/man3curses/mvwdelch.3curses target=curs_delch.3curses
link path=usr/share/man/man3curses/mvwgetch.3curses target=curs_getch.3curses
link path=usr/share/man/man3curses/mvwgetnwstr.3curses \
    target=curs_getwstr.3curses
link path=usr/share/man/man3curses/mvwgetstr.3curses \
    target=curs_getstr.3curses
link path=usr/share/man/man3curses/mvwgetwch.3curses \
    target=curs_getwch.3curses
link path=usr/share/man/man3curses/mvwgetwstr.3curses \
    target=curs_getwstr.3curses
link path=usr/share/man/man3curses/mvwin.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/mvwinch.3curses target=curs_inch.3curses
link path=usr/share/man/man3curses/mvwinchnstr.3curses \
    target=curs_inchstr.3curses
link path=usr/share/man/man3curses/mvwinchstr.3curses \
    target=curs_inchstr.3curses
link path=usr/share/man/man3curses/mvwinnstr.3curses target=curs_instr.3curses
link path=usr/share/man/man3curses/mvwinnwstr.3curses \
    target=curs_inwstr.3curses
link path=usr/share/man/man3curses/mvwinsch.3curses target=curs_insch.3curses
link path=usr/share/man/man3curses/mvwinsnstr.3curses \
    target=curs_insstr.3curses
link path=usr/share/man/man3curses/mvwinsnwstr.3curses \
    target=curs_inswstr.3curses
link path=usr/share/man/man3curses/mvwinsstr.3curses \
    target=curs_insstr.3curses
link path=usr/share/man/man3curses/mvwinstr.3curses target=curs_instr.3curses
link path=usr/share/man/man3curses/mvwinswch.3curses \
    target=curs_inswch.3curses
link path=usr/share/man/man3curses/mvwinswstr.3curses \
    target=curs_inswstr.3curses
link path=usr/share/man/man3curses/mvwinwch.3curses target=curs_inwch.3curses
link path=usr/share/man/man3curses/mvwinwchnstr.3curses \
    target=curs_inwchstr.3curses
link path=usr/share/man/man3curses/mvwinwchstr.3curses \
    target=curs_inwchstr.3curses
link path=usr/share/man/man3curses/mvwinwstr.3curses \
    target=curs_inwstr.3curses
link path=usr/share/man/man3curses/mvwprintw.3curses \
    target=curs_printw.3curses
link path=usr/share/man/man3curses/mvwscanw.3curses target=curs_scanw.3curses
link path=usr/share/man/man3curses/napms.3curses target=curs_kernel.3curses
link path=usr/share/man/man3curses/new_field.3curses \
    target=form_field_new.3curses
link path=usr/share/man/man3curses/new_fieldtype.3curses \
    target=form_fieldtype.3curses
link path=usr/share/man/man3curses/new_form.3curses target=form_new.3curses
link path=usr/share/man/man3curses/new_item.3curses \
    target=menu_item_new.3curses
link path=usr/share/man/man3curses/new_menu.3curses target=menu_new.3curses
link path=usr/share/man/man3curses/new_page.3curses \
    target=form_new_page.3curses
link path=usr/share/man/man3curses/new_panel.3curses target=panel_new.3curses
link path=usr/share/man/man3curses/newpad.3curses target=curs_pad.3curses
link path=usr/share/man/man3curses/newterm.3curses target=curs_initscr.3curses
link path=usr/share/man/man3curses/newwin.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/nl.3curses target=curs_outopts.3curses
link path=usr/share/man/man3curses/nocbreak.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/nodelay.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/noecho.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/nonl.3curses target=curs_outopts.3curses
link path=usr/share/man/man3curses/noqiflush.3curses \
    target=curs_inopts.3curses
link path=usr/share/man/man3curses/noraw.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/notimeout.3curses \
    target=curs_inopts.3curses
link path=usr/share/man/man3curses/overlay.3curses target=curs_overlay.3curses
link path=usr/share/man/man3curses/overwrite.3curses \
    target=curs_overlay.3curses
link path=usr/share/man/man3curses/pair_content.3curses \
    target=curs_color.3curses
link path=usr/share/man/man3curses/panel_below.3curses \
    target=panel_above.3curses
link path=usr/share/man/man3curses/panel_hidden.3curses \
    target=panel_show.3curses
link path=usr/share/man/man3curses/pechochar.3curses target=curs_pad.3curses
link path=usr/share/man/man3curses/pechowchar.3curses target=curs_pad.3curses
link path=usr/share/man/man3curses/pnoutrefresh.3curses \
    target=curs_pad.3curses
link path=usr/share/man/man3curses/pos_form_cursor.3curses \
    target=form_cursor.3curses
link path=usr/share/man/man3curses/pos_menu_cursor.3curses \
    target=menu_cursor.3curses
link path=usr/share/man/man3curses/post_form.3curses target=form_post.3curses
link path=usr/share/man/man3curses/post_menu.3curses target=menu_post.3curses
link path=usr/share/man/man3curses/prefresh.3curses target=curs_pad.3curses
link path=usr/share/man/man3curses/printw.3curses target=curs_printw.3curses
link path=usr/share/man/man3curses/putp.3curses target=curs_terminfo.3curses
link path=usr/share/man/man3curses/putwin.3curses target=curs_util.3curses
link path=usr/share/man/man3curses/qiflush.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/raw.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/redrawwin.3curses \
    target=curs_refresh.3curses
link path=usr/share/man/man3curses/refresh.3curses target=curs_refresh.3curses
link path=usr/share/man/man3curses/replace_panel.3curses \
    target=panel_window.3curses
link path=usr/share/man/man3curses/reset_prog_mode.3curses \
    target=curs_kernel.3curses
link path=usr/share/man/man3curses/reset_shell_mode.3curses \
    target=curs_kernel.3curses
link path=usr/share/man/man3curses/resetty.3curses target=curs_kernel.3curses
link path=usr/share/man/man3curses/restartterm.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/ripoffline.3curses \
    target=curs_kernel.3curses
link path=usr/share/man/man3curses/savetty.3curses target=curs_kernel.3curses
link path=usr/share/man/man3curses/scale_form.3curses target=form_win.3curses
link path=usr/share/man/man3curses/scale_menu.3curses target=menu_win.3curses
link path=usr/share/man/man3curses/scanw.3curses target=curs_scanw.3curses
link path=usr/share/man/man3curses/scr_dump.3curses \
    target=curs_scr_dump.3curses
link path=usr/share/man/man3curses/scr_init.3curses \
    target=curs_scr_dump.3curses
link path=usr/share/man/man3curses/scr_restore.3curses \
    target=curs_scr_dump.3curses
link path=usr/share/man/man3curses/scr_set.3curses \
    target=curs_scr_dump.3curses
link path=usr/share/man/man3curses/scrl.3curses target=curs_scroll.3curses
link path=usr/share/man/man3curses/scroll.3curses target=curs_scroll.3curses
link path=usr/share/man/man3curses/scrollok.3curses \
    target=curs_outopts.3curses
link path=usr/share/man/man3curses/set_current_field.3curses \
    target=form_page.3curses
link path=usr/share/man/man3curses/set_current_item.3curses \
    target=menu_item_current.3curses
link path=usr/share/man/man3curses/set_curterm.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/set_field_back.3curses \
    target=form_field_attributes.3curses
link path=usr/share/man/man3curses/set_field_buffer.3curses \
    target=form_field_buffer.3curses
link path=usr/share/man/man3curses/set_field_fore.3curses \
    target=form_field_attributes.3curses
link path=usr/share/man/man3curses/set_field_init.3curses \
    target=form_hook.3curses
link path=usr/share/man/man3curses/set_field_just.3curses \
    target=form_field_just.3curses
link path=usr/share/man/man3curses/set_field_opts.3curses \
    target=form_field_opts.3curses
link path=usr/share/man/man3curses/set_field_pad.3curses \
    target=form_field_attributes.3curses
link path=usr/share/man/man3curses/set_field_status.3curses \
    target=form_field_buffer.3curses
link path=usr/share/man/man3curses/set_field_term.3curses \
    target=form_hook.3curses
link path=usr/share/man/man3curses/set_field_type.3curses \
    target=form_field_validation.3curses
link path=usr/share/man/man3curses/set_field_userptr.3curses \
    target=form_field_userptr.3curses
link path=usr/share/man/man3curses/set_fieldtype_arg.3curses \
    target=form_fieldtype.3curses
link path=usr/share/man/man3curses/set_fieldtype_choice.3curses \
    target=form_fieldtype.3curses
link path=usr/share/man/man3curses/set_form_fields.3curses \
    target=form_field.3curses
link path=usr/share/man/man3curses/set_form_init.3curses \
    target=form_hook.3curses
link path=usr/share/man/man3curses/set_form_opts.3curses \
    target=form_opts.3curses
link path=usr/share/man/man3curses/set_form_page.3curses \
    target=form_page.3curses
link path=usr/share/man/man3curses/set_form_sub.3curses \
    target=form_win.3curses
link path=usr/share/man/man3curses/set_form_term.3curses \
    target=form_hook.3curses
link path=usr/share/man/man3curses/set_form_userptr.3curses \
    target=form_userptr.3curses
link path=usr/share/man/man3curses/set_form_win.3curses \
    target=form_win.3curses
link path=usr/share/man/man3curses/set_item_init.3curses \
    target=menu_hook.3curses
link path=usr/share/man/man3curses/set_item_opts.3curses \
    target=menu_item_opts.3curses
link path=usr/share/man/man3curses/set_item_term.3curses \
    target=menu_hook.3curses
link path=usr/share/man/man3curses/set_item_userptr.3curses \
    target=menu_item_userptr.3curses
link path=usr/share/man/man3curses/set_item_value.3curses \
    target=menu_item_value.3curses
link path=usr/share/man/man3curses/set_max_field.3curses \
    target=form_field_buffer.3curses
link path=usr/share/man/man3curses/set_menu_back.3curses \
    target=menu_attributes.3curses
link path=usr/share/man/man3curses/set_menu_fore.3curses \
    target=menu_attributes.3curses
link path=usr/share/man/man3curses/set_menu_format.3curses \
    target=menu_format.3curses
link path=usr/share/man/man3curses/set_menu_grey.3curses \
    target=menu_attributes.3curses
link path=usr/share/man/man3curses/set_menu_init.3curses \
    target=menu_hook.3curses
link path=usr/share/man/man3curses/set_menu_items.3curses \
    target=menu_items.3curses
link path=usr/share/man/man3curses/set_menu_mark.3curses \
    target=menu_mark.3curses
link path=usr/share/man/man3curses/set_menu_opts.3curses \
    target=menu_opts.3curses
link path=usr/share/man/man3curses/set_menu_pad.3curses \
    target=menu_attributes.3curses
link path=usr/share/man/man3curses/set_menu_pattern.3curses \
    target=menu_pattern.3curses
link path=usr/share/man/man3curses/set_menu_sub.3curses \
    target=menu_win.3curses
link path=usr/share/man/man3curses/set_menu_term.3curses \
    target=menu_hook.3curses
link path=usr/share/man/man3curses/set_menu_userptr.3curses \
    target=menu_userptr.3curses
link path=usr/share/man/man3curses/set_menu_win.3curses \
    target=menu_win.3curses
link path=usr/share/man/man3curses/set_new_page.3curses \
    target=form_new_page.3curses
link path=usr/share/man/man3curses/set_panel_userptr.3curses \
    target=panel_userptr.3curses
link path=usr/share/man/man3curses/set_term.3curses \
    target=curs_initscr.3curses
link path=usr/share/man/man3curses/set_top_row.3curses \
    target=menu_item_current.3curses
link path=usr/share/man/man3curses/setscrreg.3curses \
    target=curs_outopts.3curses
link path=usr/share/man/man3curses/setsyx.3curses target=curs_kernel.3curses
link path=usr/share/man/man3curses/setterm.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/setupterm.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/show_panel.3curses \
    target=panel_show.3curses
link path=usr/share/man/man3curses/slk_attroff.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_attron.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_attrset.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_clear.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_init.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_label.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_noutrefresh.3curses \
    target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_refresh.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_restore.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_set.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/slk_touch.3curses target=curs_slk.3curses
link path=usr/share/man/man3curses/standend.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/standout.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/start_color.3curses \
    target=curs_color.3curses
link path=usr/share/man/man3curses/subpad.3curses target=curs_pad.3curses
link path=usr/share/man/man3curses/subwin.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/syncok.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/termattrs.3curses \
    target=curs_termattrs.3curses
link path=usr/share/man/man3curses/termname.3curses \
    target=curs_termattrs.3curses
link path=usr/share/man/man3curses/tgetent.3curses target=curs_termcap.3curses
link path=usr/share/man/man3curses/tgetflag.3curses \
    target=curs_termcap.3curses
link path=usr/share/man/man3curses/tgetnum.3curses target=curs_termcap.3curses
link path=usr/share/man/man3curses/tgetstr.3curses target=curs_termcap.3curses
link path=usr/share/man/man3curses/tgoto.3curses target=curs_termcap.3curses
link path=usr/share/man/man3curses/tigetflag.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/tigetnum.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/tigetstr.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/timeout.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/top_panel.3curses target=panel_top.3curses
link path=usr/share/man/man3curses/top_row.3curses \
    target=menu_item_current.3curses
link path=usr/share/man/man3curses/touchline.3curses target=curs_touch.3curses
link path=usr/share/man/man3curses/touchwin.3curses target=curs_touch.3curses
link path=usr/share/man/man3curses/tparm.3curses target=curs_terminfo.3curses
link path=usr/share/man/man3curses/tputs.3curses target=curs_terminfo.3curses
link path=usr/share/man/man3curses/typeahead.3curses \
    target=curs_inopts.3curses
link path=usr/share/man/man3curses/unctrl.3curses target=curs_util.3curses
link path=usr/share/man/man3curses/ungetch.3curses target=curs_getch.3curses
link path=usr/share/man/man3curses/ungetwch.3curses target=curs_getwch.3curses
link path=usr/share/man/man3curses/unpost_form.3curses \
    target=form_post.3curses
link path=usr/share/man/man3curses/unpost_menu.3curses \
    target=menu_post.3curses
link path=usr/share/man/man3curses/untouchwin.3curses \
    target=curs_touch.3curses
link path=usr/share/man/man3curses/update_panels.3curses \
    target=panel_update.3curses
link path=usr/share/man/man3curses/use_env.3curses target=curs_util.3curses
link path=usr/share/man/man3curses/vidattr.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/vidputs.3curses \
    target=curs_terminfo.3curses
link path=usr/share/man/man3curses/vwprintw.3curses target=curs_printw.3curses
link path=usr/share/man/man3curses/vwscanw.3curses target=curs_scanw.3curses
link path=usr/share/man/man3curses/waddch.3curses target=curs_addch.3curses
link path=usr/share/man/man3curses/waddchnstr.3curses \
    target=curs_addchstr.3curses
link path=usr/share/man/man3curses/waddchstr.3curses \
    target=curs_addchstr.3curses
link path=usr/share/man/man3curses/waddnstr.3curses target=curs_addstr.3curses
link path=usr/share/man/man3curses/waddnwstr.3curses \
    target=curs_addwstr.3curses
link path=usr/share/man/man3curses/waddstr.3curses target=curs_addstr.3curses
link path=usr/share/man/man3curses/waddwch.3curses target=curs_addwch.3curses
link path=usr/share/man/man3curses/waddwchnstr.3curses \
    target=curs_addwchstr.3curses
link path=usr/share/man/man3curses/waddwchstr.3curses \
    target=curs_addwchstr.3curses
link path=usr/share/man/man3curses/waddwstr.3curses \
    target=curs_addwstr.3curses
link path=usr/share/man/man3curses/wadjcurspos.3curses \
    target=curs_alecompat.3curses
link path=usr/share/man/man3curses/wattroff.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/wattron.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/wattrset.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/wbkgd.3curses target=curs_bkgd.3curses
link path=usr/share/man/man3curses/wbkgdset.3curses target=curs_bkgd.3curses
link path=usr/share/man/man3curses/wborder.3curses target=curs_border.3curses
link path=usr/share/man/man3curses/wclear.3curses target=curs_clear.3curses
link path=usr/share/man/man3curses/wclrtobot.3curses target=curs_clear.3curses
link path=usr/share/man/man3curses/wclrtoeol.3curses target=curs_clear.3curses
link path=usr/share/man/man3curses/wcursyncup.3curses \
    target=curs_window.3curses
link path=usr/share/man/man3curses/wdelch.3curses target=curs_delch.3curses
link path=usr/share/man/man3curses/wdeleteln.3curses \
    target=curs_deleteln.3curses
link path=usr/share/man/man3curses/wechochar.3curses target=curs_addch.3curses
link path=usr/share/man/man3curses/wechowchar.3curses \
    target=curs_addwch.3curses
link path=usr/share/man/man3curses/werase.3curses target=curs_clear.3curses
link path=usr/share/man/man3curses/wgetch.3curses target=curs_getch.3curses
link path=usr/share/man/man3curses/wgetnstr.3curses target=curs_getstr.3curses
link path=usr/share/man/man3curses/wgetnwstr.3curses \
    target=curs_getwstr.3curses
link path=usr/share/man/man3curses/wgetstr.3curses target=curs_getstr.3curses
link path=usr/share/man/man3curses/wgetwch.3curses target=curs_getwch.3curses
link path=usr/share/man/man3curses/wgetwstr.3curses \
    target=curs_getwstr.3curses
link path=usr/share/man/man3curses/whline.3curses target=curs_border.3curses
link path=usr/share/man/man3curses/winch.3curses target=curs_inch.3curses
link path=usr/share/man/man3curses/winchnstr.3curses \
    target=curs_inchstr.3curses
link path=usr/share/man/man3curses/winchstr.3curses \
    target=curs_inchstr.3curses
link path=usr/share/man/man3curses/winnstr.3curses target=curs_instr.3curses
link path=usr/share/man/man3curses/winnwstr.3curses target=curs_inwstr.3curses
link path=usr/share/man/man3curses/winsch.3curses target=curs_insch.3curses
link path=usr/share/man/man3curses/winsdelln.3curses \
    target=curs_deleteln.3curses
link path=usr/share/man/man3curses/winsertln.3curses \
    target=curs_deleteln.3curses
link path=usr/share/man/man3curses/winsnstr.3curses target=curs_insstr.3curses
link path=usr/share/man/man3curses/winsnwstr.3curses \
    target=curs_inswstr.3curses
link path=usr/share/man/man3curses/winsstr.3curses target=curs_insstr.3curses
link path=usr/share/man/man3curses/winstr.3curses target=curs_instr.3curses
link path=usr/share/man/man3curses/winswch.3curses target=curs_inswch.3curses
link path=usr/share/man/man3curses/winswstr.3curses \
    target=curs_inswstr.3curses
link path=usr/share/man/man3curses/winwch.3curses target=curs_inwch.3curses
link path=usr/share/man/man3curses/winwchnstr.3curses \
    target=curs_inwchstr.3curses
link path=usr/share/man/man3curses/winwchstr.3curses \
    target=curs_inwchstr.3curses
link path=usr/share/man/man3curses/winwstr.3curses target=curs_inwstr.3curses
link path=usr/share/man/man3curses/wmove.3curses target=curs_move.3curses
link path=usr/share/man/man3curses/wmovenextch.3curses \
    target=curs_alecompat.3curses
link path=usr/share/man/man3curses/wmoveprevch.3curses \
    target=curs_alecompat.3curses
link path=usr/share/man/man3curses/wnoutrefresh.3curses \
    target=curs_refresh.3curses
link path=usr/share/man/man3curses/wprintw.3curses target=curs_printw.3curses
link path=usr/share/man/man3curses/wredrawln.3curses \
    target=curs_refresh.3curses
link path=usr/share/man/man3curses/wrefresh.3curses \
    target=curs_refresh.3curses
link path=usr/share/man/man3curses/wscanw.3curses target=curs_scanw.3curses
link path=usr/share/man/man3curses/wscrl.3curses target=curs_scroll.3curses
link path=usr/share/man/man3curses/wsetscrreg.3curses \
    target=curs_outopts.3curses
link path=usr/share/man/man3curses/wstandend.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/wstandout.3curses target=curs_attr.3curses
link path=usr/share/man/man3curses/wsyncdown.3curses \
    target=curs_window.3curses
link path=usr/share/man/man3curses/wsyncup.3curses target=curs_window.3curses
link path=usr/share/man/man3curses/wtimeout.3curses target=curs_inopts.3curses
link path=usr/share/man/man3curses/wtouchln.3curses target=curs_touch.3curses
link path=usr/share/man/man3curses/wvline.3curses target=curs_border.3curses
