#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
# Copyright 2013, OmniTI Computer Consulting, Inc.
#

file path=usr/share/man/man2/Intro.2
file path=usr/share/man/man2/__sparc_utrap_install.2
file path=usr/share/man/man2/_lwp_cond_signal.2
file path=usr/share/man/man2/_lwp_cond_wait.2
file path=usr/share/man/man2/_lwp_info.2
file path=usr/share/man/man2/_lwp_kill.2
file path=usr/share/man/man2/_lwp_mutex_lock.2
file path=usr/share/man/man2/_lwp_self.2
file path=usr/share/man/man2/_lwp_sema_wait.2
file path=usr/share/man/man2/_lwp_suspend.2
file path=usr/share/man/man2/access.2
file path=usr/share/man/man2/acct.2
file path=usr/share/man/man2/acl.2
file path=usr/share/man/man2/adjtime.2
file path=usr/share/man/man2/alarm.2
file path=usr/share/man/man2/audit.2
file path=usr/share/man/man2/auditon.2
file path=usr/share/man/man2/brk.2
file path=usr/share/man/man2/chdir.2
file path=usr/share/man/man2/chmod.2
file path=usr/share/man/man2/chown.2
file path=usr/share/man/man2/chroot.2
file path=usr/share/man/man2/close.2
file path=usr/share/man/man2/creat.2
file path=usr/share/man/man2/dup.2
file path=usr/share/man/man2/exec.2
file path=usr/share/man/man2/exit.2
file path=usr/share/man/man2/fcntl.2
file path=usr/share/man/man2/fork.2
file path=usr/share/man/man2/fpathconf.2
file path=usr/share/man/man2/getacct.2
file path=usr/share/man/man2/getaudit.2
file path=usr/share/man/man2/getauid.2
file path=usr/share/man/man2/getcontext.2
file path=usr/share/man/man2/getdents.2
file path=usr/share/man/man2/getgroups.2
file path=usr/share/man/man2/getisax.2
file path=usr/share/man/man2/getitimer.2
file path=usr/share/man/man2/getlabel.2
file path=usr/share/man/man2/getmsg.2
file path=usr/share/man/man2/getpflags.2
file path=usr/share/man/man2/getpid.2
file path=usr/share/man/man2/getppriv.2
file path=usr/share/man/man2/getrlimit.2
file path=usr/share/man/man2/getsid.2
file path=usr/share/man/man2/getuid.2
file path=usr/share/man/man2/getustack.2
file path=usr/share/man/man2/ioctl.2
file path=usr/share/man/man2/issetugid.2
file path=usr/share/man/man2/kill.2
file path=usr/share/man/man2/link.2
file path=usr/share/man/man2/llseek.2
file path=usr/share/man/man2/lseek.2
file path=usr/share/man/man2/memcntl.2
file path=usr/share/man/man2/meminfo.2
file path=usr/share/man/man2/mincore.2
file path=usr/share/man/man2/mkdir.2
file path=usr/share/man/man2/mknod.2
file path=usr/share/man/man2/mmap.2
file path=usr/share/man/man2/mmapobj.2
file path=usr/share/man/man2/mount.2
file path=usr/share/man/man2/mprotect.2
file path=usr/share/man/man2/msgctl.2
file path=usr/share/man/man2/msgget.2
file path=usr/share/man/man2/msgids.2
file path=usr/share/man/man2/msgrcv.2
file path=usr/share/man/man2/msgsnap.2
file path=usr/share/man/man2/msgsnd.2
file path=usr/share/man/man2/munmap.2
file path=usr/share/man/man2/nice.2
file path=usr/share/man/man2/ntp_adjtime.2
file path=usr/share/man/man2/ntp_gettime.2
file path=usr/share/man/man2/open.2
file path=usr/share/man/man2/p_online.2
file path=usr/share/man/man2/pause.2
file path=usr/share/man/man2/pcsample.2
file path=usr/share/man/man2/pipe.2
file path=usr/share/man/man2/poll.2
file path=usr/share/man/man2/priocntl.2
file path=usr/share/man/man2/priocntlset.2
file path=usr/share/man/man2/processor_bind.2
file path=usr/share/man/man2/processor_info.2
file path=usr/share/man/man2/profil.2
file path=usr/share/man/man2/pset_bind.2
file path=usr/share/man/man2/pset_create.2
file path=usr/share/man/man2/pset_info.2
file path=usr/share/man/man2/pset_list.2
file path=usr/share/man/man2/pset_setattr.2
file path=usr/share/man/man2/putmsg.2
file path=usr/share/man/man2/read.2
file path=usr/share/man/man2/readlink.2
file path=usr/share/man/man2/rename.2
file path=usr/share/man/man2/resolvepath.2
file path=usr/share/man/man2/rmdir.2
file path=usr/share/man/man2/semctl.2
file path=usr/share/man/man2/semget.2
file path=usr/share/man/man2/semids.2
file path=usr/share/man/man2/semop.2
file path=usr/share/man/man2/setpgid.2
file path=usr/share/man/man2/setpgrp.2
file path=usr/share/man/man2/setrctl.2
file path=usr/share/man/man2/setregid.2
file path=usr/share/man/man2/setreuid.2
file path=usr/share/man/man2/setsid.2
file path=usr/share/man/man2/settaskid.2
file path=usr/share/man/man2/setuid.2
file path=usr/share/man/man2/shmctl.2
file path=usr/share/man/man2/shmget.2
file path=usr/share/man/man2/shmids.2
file path=usr/share/man/man2/shmop.2
file path=usr/share/man/man2/sigaction.2
file path=usr/share/man/man2/sigaltstack.2
file path=usr/share/man/man2/sigpending.2
file path=usr/share/man/man2/sigprocmask.2
file path=usr/share/man/man2/sigsend.2
file path=usr/share/man/man2/sigsuspend.2
file path=usr/share/man/man2/sigwait.2
file path=usr/share/man/man2/stat.2
file path=usr/share/man/man2/statvfs.2
file path=usr/share/man/man2/stime.2
file path=usr/share/man/man2/swapctl.2
file path=usr/share/man/man2/symlink.2
file path=usr/share/man/man2/sync.2
file path=usr/share/man/man2/sysfs.2
file path=usr/share/man/man2/sysinfo.2
file path=usr/share/man/man2/time.2
file path=usr/share/man/man2/times.2
file path=usr/share/man/man2/uadmin.2
file path=usr/share/man/man2/ulimit.2
file path=usr/share/man/man2/umask.2
file path=usr/share/man/man2/umount.2
file path=usr/share/man/man2/uname.2
file path=usr/share/man/man2/unlink.2
file path=usr/share/man/man2/ustat.2
file path=usr/share/man/man2/utime.2
file path=usr/share/man/man2/utimes.2
file path=usr/share/man/man2/uucopy.2
file path=usr/share/man/man2/vfork.2
file path=usr/share/man/man2/vhangup.2
file path=usr/share/man/man2/waitid.2
file path=usr/share/man/man2/write.2
file path=usr/share/man/man2/yield.2
link path=usr/share/man/man2/_Exit.2 target=exit.2
link path=usr/share/man/man2/_exit.2 target=exit.2
link path=usr/share/man/man2/_lwp_cond_broadcast.2 target=_lwp_cond_signal.2
link path=usr/share/man/man2/_lwp_cond_reltimedwait.2 target=_lwp_cond_wait.2
link path=usr/share/man/man2/_lwp_cond_timedwait.2 target=_lwp_cond_wait.2
link path=usr/share/man/man2/_lwp_continue.2 target=_lwp_suspend.2
link path=usr/share/man/man2/_lwp_mutex_trylock.2 target=_lwp_mutex_lock.2
link path=usr/share/man/man2/_lwp_mutex_unlock.2 target=_lwp_mutex_lock.2
link path=usr/share/man/man2/_lwp_sema_init.2 target=_lwp_sema_wait.2
link path=usr/share/man/man2/_lwp_sema_post.2 target=_lwp_sema_wait.2
link path=usr/share/man/man2/_lwp_sema_trywait.2 target=_lwp_sema_wait.2
link path=usr/share/man/man2/execl.2 target=exec.2
link path=usr/share/man/man2/execle.2 target=exec.2
link path=usr/share/man/man2/execlp.2 target=exec.2
link path=usr/share/man/man2/execv.2 target=exec.2
link path=usr/share/man/man2/execve.2 target=exec.2
link path=usr/share/man/man2/execvp.2 target=exec.2
link path=usr/share/man/man2/faccessat.2 target=access.2
link path=usr/share/man/man2/facl.2 target=acl.2
link path=usr/share/man/man2/fchdir.2 target=chdir.2
link path=usr/share/man/man2/fchmod.2 target=chmod.2
link path=usr/share/man/man2/fchown.2 target=chown.2
link path=usr/share/man/man2/fchownat.2 target=chown.2
link path=usr/share/man/man2/fchroot.2 target=chroot.2
link path=usr/share/man/man2/fgetlabel.2 target=getlabel.2
link path=usr/share/man/man2/fork1.2 target=fork.2
link path=usr/share/man/man2/forkall.2 target=fork.2
link path=usr/share/man/man2/forkallx.2 target=fork.2
link path=usr/share/man/man2/forkx.2 target=fork.2
link path=usr/share/man/man2/fstat.2 target=stat.2
link path=usr/share/man/man2/fstatat.2 target=stat.2
link path=usr/share/man/man2/fstatvfs.2 target=statvfs.2
link path=usr/share/man/man2/futimesat.2 target=utimes.2
link path=usr/share/man/man2/getaudit_addr.2 target=getaudit.2
link path=usr/share/man/man2/getegid.2 target=getuid.2
link path=usr/share/man/man2/geteuid.2 target=getuid.2
link path=usr/share/man/man2/getgid.2 target=getuid.2
link path=usr/share/man/man2/getpgid.2 target=getpid.2
link path=usr/share/man/man2/getpgrp.2 target=getpid.2
link path=usr/share/man/man2/getpmsg.2 target=getmsg.2
link path=usr/share/man/man2/getppid.2 target=getpid.2
link path=usr/share/man/man2/getprojid.2 target=settaskid.2
link path=usr/share/man/man2/getrctl.2 target=setrctl.2
link path=usr/share/man/man2/gettaskid.2 target=settaskid.2
link path=usr/share/man/man2/intro.2 target=Intro.2
link path=usr/share/man/man2/lchown.2 target=chown.2
link path=usr/share/man/man2/lstat.2 target=stat.2
link path=usr/share/man/man2/openat.2 target=open.2
link path=usr/share/man/man2/pathconf.2 target=fpathconf.2
link path=usr/share/man/man2/pipe2.2 target=pipe.2
link path=usr/share/man/man2/pread.2 target=read.2
link path=usr/share/man/man2/pset_assign.2 target=pset_create.2
link path=usr/share/man/man2/pset_destroy.2 target=pset_create.2
link path=usr/share/man/man2/pset_getattr.2 target=pset_setattr.2
link path=usr/share/man/man2/putacct.2 target=getacct.2
link path=usr/share/man/man2/putpmsg.2 target=putmsg.2
link path=usr/share/man/man2/pwrite.2 target=write.2
link path=usr/share/man/man2/readv.2 target=read.2
link path=usr/share/man/man2/renameat.2 target=rename.2
link path=usr/share/man/man2/sbrk.2 target=brk.2
link path=usr/share/man/man2/semtimedop.2 target=semop.2
link path=usr/share/man/man2/setaudit.2 target=getaudit.2
link path=usr/share/man/man2/setaudit_addr.2 target=getaudit.2
link path=usr/share/man/man2/setauid.2 target=getauid.2
link path=usr/share/man/man2/setcontext.2 target=getcontext.2
link path=usr/share/man/man2/setegid.2 target=setuid.2
link path=usr/share/man/man2/seteuid.2 target=setuid.2
link path=usr/share/man/man2/setgid.2 target=setuid.2
link path=usr/share/man/man2/setgroups.2 target=getgroups.2
link path=usr/share/man/man2/setitimer.2 target=getitimer.2
link path=usr/share/man/man2/setpflags.2 target=getpflags.2
link path=usr/share/man/man2/setppriv.2 target=getppriv.2
link path=usr/share/man/man2/setrlimit.2 target=getrlimit.2
link path=usr/share/man/man2/setustack.2 target=getustack.2
link path=usr/share/man/man2/shmat.2 target=shmop.2
link path=usr/share/man/man2/shmdt.2 target=shmop.2
link path=usr/share/man/man2/sigsendset.2 target=sigsend.2
link path=usr/share/man/man2/umount2.2 target=umount.2
link path=usr/share/man/man2/unlinkat.2 target=unlink.2
link path=usr/share/man/man2/vforkx.2 target=vfork.2
link path=usr/share/man/man2/wracct.2 target=getacct.2
link path=usr/share/man/man2/writev.2 target=write.2
