#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2016 Nexenta Systems, Inc.
#

file path=usr/share/man/man7d/bscv.7d
file path=usr/share/man/man7d/console.7d
file path=usr/share/man/man7d/cpuid.7d
file path=usr/share/man/man7d/devinfo.7d
file path=usr/share/man/man7d/gld.7d
file path=usr/share/man/man7d/ipnet.7d
file path=usr/share/man/man7d/kmdb.7d
file path=usr/share/man/man7d/llc1.7d
file path=usr/share/man/man7d/lofi.7d
file path=usr/share/man/man7d/log.7d
file path=usr/share/man/man7d/mem.7d
file path=usr/share/man/man7d/msglog.7d
file path=usr/share/man/man7d/mt.7d
file path=usr/share/man/man7d/null.7d
file path=usr/share/man/man7d/nulldriver.7d
file path=usr/share/man/man7d/openprom.7d
file path=usr/share/man/man7d/physmem.7d
file path=usr/share/man/man7d/poll.7d
file path=usr/share/man/man7d/pty.7d
file path=usr/share/man/man7d/ramdisk.7d
file path=usr/share/man/man7d/random.7d
file path=usr/share/man/man7d/sad.7d
file path=usr/share/man/man7d/sata.7d
file path=usr/share/man/man7d/sd.7d
file path=usr/share/man/man7d/sgen.7d
file path=usr/share/man/man7d/st.7d
file path=usr/share/man/man7d/sysmsg.7d
file path=usr/share/man/man7d/ticlts.7d
file path=usr/share/man/man7d/tty.7d
file path=usr/share/man/man7d/ttymux.7d
file path=usr/share/man/man7d/tzmon.7d
file path=usr/share/man/man7d/virtualkm.7d
file path=usr/share/man/man7d/vni.7d
file path=usr/share/man/man7d/wscons.7d
file path=usr/share/man/man7d/zero.7d
link path=usr/share/man/man7d/allkmem.7d target=mem.7d
link path=usr/share/man/man7d/bscbus.7d target=bscv.7d
link path=usr/share/man/man7d/i2bsc.7d target=bscv.7d
link path=usr/share/man/man7d/kmem.7d target=mem.7d
link path=usr/share/man/man7d/lo0.7d target=ipnet.7d
link path=usr/share/man/man7d/ticots.7d target=ticlts.7d
link path=usr/share/man/man7d/ticotsord.7d target=ticlts.7d
link path=usr/share/man/man7d/urandom.7d target=random.7d
