#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

link path=usr/share/man/man4p/AH.4p target=ipsecah.4p
link path=usr/share/man/man4p/ARP.4p target=arp.4p
link path=usr/share/man/man4p/ESP.4p target=ipsecesp.4p
link path=usr/share/man/man4p/ICMP.4p target=icmp.4p
link path=usr/share/man/man4p/IP.4p target=ip.4p
link path=usr/share/man/man4p/NDP.4p target=ndp.4p
link path=usr/share/man/man4p/SCTP.4p target=sctp.4p
link path=usr/share/man/man4p/TCP.4p target=tcp.4p
link path=usr/share/man/man4p/UDP.4p target=udp.4p
file path=usr/share/man/man4p/arp.4p
file path=usr/share/man/man4p/dlpi.4p
file path=usr/share/man/man4p/icmp.4p
file path=usr/share/man/man4p/icmp6.4p
link path=usr/share/man/man4p/if.4p target=if_tcp.4p
file path=usr/share/man/man4p/if_tcp.4p
file path=usr/share/man/man4p/inet.4p
file path=usr/share/man/man4p/inet6.4p
file path=usr/share/man/man4p/ip.4p
file path=usr/share/man/man4p/ip6.4p
file path=usr/share/man/man4p/ipsec.4p
file path=usr/share/man/man4p/ipsecah.4p
file path=usr/share/man/man4p/ipsecesp.4p
file path=usr/share/man/man4p/ndp.4p
file path=usr/share/man/man4p/pf_key.4p
file path=usr/share/man/man4p/route.4p
file path=usr/share/man/man4p/routing.4p
file path=usr/share/man/man4p/sctp.4p
file path=usr/share/man/man4p/tcp.4p
file path=usr/share/man/man4p/udp.4p
