#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2017, Richard Lowe

file path=usr/share/man/man3project/getprojent.3project
file path=usr/share/man/man3project/project_walk.3project
file path=usr/share/man/man3project/setproject.3project
link path=usr/share/man/man3project/endprojent.3project \
    target=getprojent.3project
link path=usr/share/man/man3project/fgetprojent.3project \
    target=getprojent.3project
link path=usr/share/man/man3project/getdefaultproj.3project \
    target=getprojent.3project
link path=usr/share/man/man3project/getprojbyid.3project \
    target=getprojent.3project
link path=usr/share/man/man3project/getprojbyname.3project \
    target=getprojent.3project
link path=usr/share/man/man3project/getprojidbyname.3project \
    target=getprojent.3project
link path=usr/share/man/man3project/inproj.3project target=getprojent.3project
link path=usr/share/man/man3project/setprojent.3project \
    target=getprojent.3project
