#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3contract/ct_ctl_adopt.3contract
file path=usr/share/man/man3contract/ct_dev_status_get_dev_state.3contract
file path=usr/share/man/man3contract/ct_dev_tmpl_set_aset.3contract
file path=usr/share/man/man3contract/ct_event_read.3contract
file path=usr/share/man/man3contract/ct_pr_event_get_pid.3contract
file path=usr/share/man/man3contract/ct_pr_status_get_param.3contract
file path=usr/share/man/man3contract/ct_pr_tmpl_set_transfer.3contract
file path=usr/share/man/man3contract/ct_status_read.3contract
file path=usr/share/man/man3contract/ct_tmpl_activate.3contract
link path=usr/share/man/man3contract/ct_ctl_abandon.3contract \
    target=ct_ctl_adopt.3contract
link path=usr/share/man/man3contract/ct_ctl_ack.3contract \
    target=ct_ctl_adopt.3contract
link path=usr/share/man/man3contract/ct_ctl_nack.3contract \
    target=ct_ctl_adopt.3contract
link path=usr/share/man/man3contract/ct_ctl_newct.3contract \
    target=ct_ctl_adopt.3contract
link path=usr/share/man/man3contract/ct_ctl_qack.3contract \
    target=ct_ctl_adopt.3contract
link path=usr/share/man/man3contract/ct_dev_status_get_aset.3contract \
    target=ct_dev_status_get_dev_state.3contract
link path=usr/share/man/man3contract/ct_dev_status_get_minor.3contract \
    target=ct_dev_status_get_dev_state.3contract
link path=usr/share/man/man3contract/ct_dev_status_get_noneg.3contract \
    target=ct_dev_status_get_dev_state.3contract
link path=usr/share/man/man3contract/ct_dev_tmpl_clear_noneg.3contract \
    target=ct_dev_tmpl_set_aset.3contract
link path=usr/share/man/man3contract/ct_dev_tmpl_get_aset.3contract \
    target=ct_dev_tmpl_set_aset.3contract
link path=usr/share/man/man3contract/ct_dev_tmpl_get_minor.3contract \
    target=ct_dev_tmpl_set_aset.3contract
link path=usr/share/man/man3contract/ct_dev_tmpl_get_noneg.3contract \
    target=ct_dev_tmpl_set_aset.3contract
link path=usr/share/man/man3contract/ct_dev_tmpl_set_minor.3contract \
    target=ct_dev_tmpl_set_aset.3contract
link path=usr/share/man/man3contract/ct_dev_tmpl_set_noneg.3contract \
    target=ct_dev_tmpl_set_aset.3contract
link path=usr/share/man/man3contract/ct_event_free.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_get_ctid.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_get_evid.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_get_flags.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_get_nevid.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_get_newct.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_get_type.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_read_critical.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_reliable.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_event_reset.3contract \
    target=ct_event_read.3contract
link path=usr/share/man/man3contract/ct_pr_event_get_exitstatus.3contract \
    target=ct_pr_event_get_pid.3contract
link path=usr/share/man/man3contract/ct_pr_event_get_gcorefile.3contract \
    target=ct_pr_event_get_pid.3contract
link path=usr/share/man/man3contract/ct_pr_event_get_pcorefile.3contract \
    target=ct_pr_event_get_pid.3contract
link path=usr/share/man/man3contract/ct_pr_event_get_ppid.3contract \
    target=ct_pr_event_get_pid.3contract
link path=usr/share/man/man3contract/ct_pr_event_get_sender.3contract \
    target=ct_pr_event_get_pid.3contract
link path=usr/share/man/man3contract/ct_pr_event_get_senderct.3contract \
    target=ct_pr_event_get_pid.3contract
link path=usr/share/man/man3contract/ct_pr_event_get_signal.3contract \
    target=ct_pr_event_get_pid.3contract
link path=usr/share/man/man3contract/ct_pr_event_get_zcorefile.3contract \
    target=ct_pr_event_get_pid.3contract
link path=usr/share/man/man3contract/ct_pr_status_get_contracts.3contract \
    target=ct_pr_status_get_param.3contract
link path=usr/share/man/man3contract/ct_pr_status_get_fatal.3contract \
    target=ct_pr_status_get_param.3contract
link path=usr/share/man/man3contract/ct_pr_status_get_members.3contract \
    target=ct_pr_status_get_param.3contract
link path=usr/share/man/man3contract/ct_pr_status_get_svc_aux.3contract \
    target=ct_pr_status_get_param.3contract
link path=usr/share/man/man3contract/ct_pr_status_get_svc_creator.3contract \
    target=ct_pr_status_get_param.3contract
link path=usr/share/man/man3contract/ct_pr_status_get_svc_ctid.3contract \
    target=ct_pr_status_get_param.3contract
link path=usr/share/man/man3contract/ct_pr_status_get_svc_fmri.3contract \
    target=ct_pr_status_get_param.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_get_fatal.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_get_param.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_get_svc_aux.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_get_svc_fmri.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_get_transfer.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_set_fatal.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_set_param.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_set_svc_aux.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_pr_tmpl_set_svc_fmri.3contract \
    target=ct_pr_tmpl_set_transfer.3contract
link path=usr/share/man/man3contract/ct_status_free.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_cookie.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_critical.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_holder.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_id.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_informative.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_nevents.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_nevid.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_ntime.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_qtime.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_state.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_type.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_status_get_zoneid.3contract \
    target=ct_status_read.3contract
link path=usr/share/man/man3contract/ct_tmpl_clear.3contract \
    target=ct_tmpl_activate.3contract
link path=usr/share/man/man3contract/ct_tmpl_create.3contract \
    target=ct_tmpl_activate.3contract
link path=usr/share/man/man3contract/ct_tmpl_get_cookie.3contract \
    target=ct_tmpl_activate.3contract
link path=usr/share/man/man3contract/ct_tmpl_get_critical.3contract \
    target=ct_tmpl_activate.3contract
link path=usr/share/man/man3contract/ct_tmpl_get_informative.3contract \
    target=ct_tmpl_activate.3contract
link path=usr/share/man/man3contract/ct_tmpl_set_cookie.3contract \
    target=ct_tmpl_activate.3contract
link path=usr/share/man/man3contract/ct_tmpl_set_critical.3contract \
    target=ct_tmpl_activate.3contract
link path=usr/share/man/man3contract/ct_tmpl_set_informative.3contract \
    target=ct_tmpl_activate.3contract
