#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man7m/bufmod.7m
file path=usr/share/man/man7m/connld.7m
file path=usr/share/man/man7m/ldterm.7m
file path=usr/share/man/man7m/pckt.7m
file path=usr/share/man/man7m/pfmod.7m
file path=usr/share/man/man7m/pipemod.7m
file path=usr/share/man/man7m/ptem.7m
file path=usr/share/man/man7m/timod.7m
file path=usr/share/man/man7m/tirdwr.7m
file path=usr/share/man/man7m/ttcompat.7m
file path=usr/share/man/man7m/vuidmice.7m
link path=usr/share/man/man7m/vuid2ps2.7m target=vuidmice.7m
link path=usr/share/man/man7m/vuid3ps2.7m target=vuidmice.7m
link path=usr/share/man/man7m/vuidm3p.7m target=vuidmice.7m
link path=usr/share/man/man7m/vuidm4p.7m target=vuidmice.7m
link path=usr/share/man/man7m/vuidm5p.7m target=vuidmice.7m
