#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3gen/bgets.3gen
file path=usr/share/man/man3gen/bufsplit.3gen
file path=usr/share/man/man3gen/copylist.3gen
file path=usr/share/man/man3gen/gmatch.3gen
file path=usr/share/man/man3gen/isencrypt.3gen
file path=usr/share/man/man3gen/mkdirp.3gen
file path=usr/share/man/man3gen/p2open.3gen
file path=usr/share/man/man3gen/pathfind.3gen
file path=usr/share/man/man3gen/regexpr.3gen
file path=usr/share/man/man3gen/strccpy.3gen
file path=usr/share/man/man3gen/strfind.3gen
link path=usr/share/man/man3gen/advance.3gen target=regexpr.3gen
link path=usr/share/man/man3gen/compile.3gen target=regexpr.3gen
link path=usr/share/man/man3gen/p2close.3gen target=p2open.3gen
link path=usr/share/man/man3gen/rmdirp.3gen target=mkdirp.3gen
link path=usr/share/man/man3gen/step.3gen target=regexpr.3gen
link path=usr/share/man/man3gen/str.3gen target=strfind.3gen
link path=usr/share/man/man3gen/strcadd.3gen target=strccpy.3gen
link path=usr/share/man/man3gen/streadd.3gen target=strccpy.3gen
link path=usr/share/man/man3gen/strecpy.3gen target=strccpy.3gen
link path=usr/share/man/man3gen/strrspn.3gen target=strfind.3gen
link path=usr/share/man/man3gen/strtrns.3gen target=strfind.3gen
