#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3xcurses/COLS.3xcurses
file path=usr/share/man/man3xcurses/LINES.3xcurses
file path=usr/share/man/man3xcurses/add_wch.3xcurses
file path=usr/share/man/man3xcurses/add_wchnstr.3xcurses
file path=usr/share/man/man3xcurses/addch.3xcurses
file path=usr/share/man/man3xcurses/addchstr.3xcurses
file path=usr/share/man/man3xcurses/addnstr.3xcurses
file path=usr/share/man/man3xcurses/addnwstr.3xcurses
file path=usr/share/man/man3xcurses/attr_get.3xcurses
file path=usr/share/man/man3xcurses/attroff.3xcurses
file path=usr/share/man/man3xcurses/baudrate.3xcurses
file path=usr/share/man/man3xcurses/beep.3xcurses
file path=usr/share/man/man3xcurses/bkgd.3xcurses
file path=usr/share/man/man3xcurses/bkgrnd.3xcurses
file path=usr/share/man/man3xcurses/border.3xcurses
file path=usr/share/man/man3xcurses/border_set.3xcurses
file path=usr/share/man/man3xcurses/can_change_color.3xcurses
file path=usr/share/man/man3xcurses/cbreak.3xcurses
file path=usr/share/man/man3xcurses/chgat.3xcurses
file path=usr/share/man/man3xcurses/clear.3xcurses
file path=usr/share/man/man3xcurses/clearok.3xcurses
file path=usr/share/man/man3xcurses/clrtobot.3xcurses
file path=usr/share/man/man3xcurses/clrtoeol.3xcurses
file path=usr/share/man/man3xcurses/copywin.3xcurses
file path=usr/share/man/man3xcurses/cur_term.3xcurses
file path=usr/share/man/man3xcurses/curs_set.3xcurses
file path=usr/share/man/man3xcurses/curscr.3xcurses
file path=usr/share/man/man3xcurses/curses.3xcurses
file path=usr/share/man/man3xcurses/def_prog_mode.3xcurses
file path=usr/share/man/man3xcurses/del_curterm.3xcurses
file path=usr/share/man/man3xcurses/delay_output.3xcurses
file path=usr/share/man/man3xcurses/delch.3xcurses
file path=usr/share/man/man3xcurses/deleteln.3xcurses
file path=usr/share/man/man3xcurses/delscreen.3xcurses
file path=usr/share/man/man3xcurses/delwin.3xcurses
file path=usr/share/man/man3xcurses/derwin.3xcurses
file path=usr/share/man/man3xcurses/doupdate.3xcurses
file path=usr/share/man/man3xcurses/dupwin.3xcurses
file path=usr/share/man/man3xcurses/echo.3xcurses
file path=usr/share/man/man3xcurses/echo_wchar.3xcurses
file path=usr/share/man/man3xcurses/echochar.3xcurses
file path=usr/share/man/man3xcurses/endwin.3xcurses
file path=usr/share/man/man3xcurses/erasechar.3xcurses
file path=usr/share/man/man3xcurses/filter.3xcurses
file path=usr/share/man/man3xcurses/flushinp.3xcurses
file path=usr/share/man/man3xcurses/get_wch.3xcurses
file path=usr/share/man/man3xcurses/getbegyx.3xcurses
file path=usr/share/man/man3xcurses/getcchar.3xcurses
file path=usr/share/man/man3xcurses/getch.3xcurses
file path=usr/share/man/man3xcurses/getn_wstr.3xcurses
file path=usr/share/man/man3xcurses/getnstr.3xcurses
file path=usr/share/man/man3xcurses/getwin.3xcurses
file path=usr/share/man/man3xcurses/halfdelay.3xcurses
file path=usr/share/man/man3xcurses/has_ic.3xcurses
file path=usr/share/man/man3xcurses/hline.3xcurses
file path=usr/share/man/man3xcurses/hline_set.3xcurses
file path=usr/share/man/man3xcurses/idcok.3xcurses
file path=usr/share/man/man3xcurses/immedok.3xcurses
file path=usr/share/man/man3xcurses/in_wch.3xcurses
file path=usr/share/man/man3xcurses/in_wchnstr.3xcurses
file path=usr/share/man/man3xcurses/inch.3xcurses
file path=usr/share/man/man3xcurses/inchnstr.3xcurses
file path=usr/share/man/man3xcurses/initscr.3xcurses
file path=usr/share/man/man3xcurses/innstr.3xcurses
file path=usr/share/man/man3xcurses/innwstr.3xcurses
file path=usr/share/man/man3xcurses/ins_nwstr.3xcurses
file path=usr/share/man/man3xcurses/ins_wch.3xcurses
file path=usr/share/man/man3xcurses/insch.3xcurses
file path=usr/share/man/man3xcurses/insdelln.3xcurses
file path=usr/share/man/man3xcurses/insertln.3xcurses
file path=usr/share/man/man3xcurses/insnstr.3xcurses
file path=usr/share/man/man3xcurses/intrflush.3xcurses
file path=usr/share/man/man3xcurses/is_linetouched.3xcurses
file path=usr/share/man/man3xcurses/keyname.3xcurses
file path=usr/share/man/man3xcurses/keypad.3xcurses
file path=usr/share/man/man3xcurses/libcurses.3xcurses
file path=usr/share/man/man3xcurses/longname.3xcurses
file path=usr/share/man/man3xcurses/meta.3xcurses
file path=usr/share/man/man3xcurses/move.3xcurses
file path=usr/share/man/man3xcurses/mvcur.3xcurses
file path=usr/share/man/man3xcurses/mvderwin.3xcurses
file path=usr/share/man/man3xcurses/mvprintw.3xcurses
file path=usr/share/man/man3xcurses/mvscanw.3xcurses
file path=usr/share/man/man3xcurses/mvwin.3xcurses
file path=usr/share/man/man3xcurses/napms.3xcurses
file path=usr/share/man/man3xcurses/newpad.3xcurses
file path=usr/share/man/man3xcurses/nl.3xcurses
file path=usr/share/man/man3xcurses/nodelay.3xcurses
file path=usr/share/man/man3xcurses/noqiflush.3xcurses
file path=usr/share/man/man3xcurses/notimeout.3xcurses
file path=usr/share/man/man3xcurses/overlay.3xcurses
file path=usr/share/man/man3xcurses/pechochar.3xcurses
file path=usr/share/man/man3xcurses/putp.3xcurses
file path=usr/share/man/man3xcurses/redrawwin.3xcurses
file path=usr/share/man/man3xcurses/resetty.3xcurses
file path=usr/share/man/man3xcurses/ripoffline.3xcurses
file path=usr/share/man/man3xcurses/scr_dump.3xcurses
file path=usr/share/man/man3xcurses/scrl.3xcurses
file path=usr/share/man/man3xcurses/set_term.3xcurses
file path=usr/share/man/man3xcurses/setcchar.3xcurses
file path=usr/share/man/man3xcurses/slk_attroff.3xcurses
file path=usr/share/man/man3xcurses/standend.3xcurses
file path=usr/share/man/man3xcurses/stdscr.3xcurses
file path=usr/share/man/man3xcurses/syncok.3xcurses
file path=usr/share/man/man3xcurses/termattrs.3xcurses
file path=usr/share/man/man3xcurses/termname.3xcurses
file path=usr/share/man/man3xcurses/tgetent.3xcurses
file path=usr/share/man/man3xcurses/tigetflag.3xcurses
file path=usr/share/man/man3xcurses/typeahead.3xcurses
file path=usr/share/man/man3xcurses/unctrl.3xcurses
file path=usr/share/man/man3xcurses/ungetch.3xcurses
file path=usr/share/man/man3xcurses/use_env.3xcurses
file path=usr/share/man/man3xcurses/vidattr.3xcurses
file path=usr/share/man/man3xcurses/vw_printw.3xcurses
file path=usr/share/man/man3xcurses/vw_scanw.3xcurses
file path=usr/share/man/man3xcurses/vwprintw.3xcurses
file path=usr/share/man/man3xcurses/vwscanw.3xcurses
file path=usr/share/man/man3xcurses/wunctrl.3xcurses
link path=usr/share/man/man3xcurses/COLORS.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/COLOR_PAIR.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/COLOR_PAIRS.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/PAIR_NUMBER.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/add_wchstr.3xcurses \
    target=add_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/addchnstr.3xcurses \
    target=addchstr.3xcurses
link path=usr/share/man/man3xcurses/addstr.3xcurses target=addnstr.3xcurses
link path=usr/share/man/man3xcurses/addwstr.3xcurses target=addnwstr.3xcurses
link path=usr/share/man/man3xcurses/attr_off.3xcurses target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/attr_on.3xcurses target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/attr_set.3xcurses target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/attron.3xcurses target=attroff.3xcurses
link path=usr/share/man/man3xcurses/attrset.3xcurses target=attroff.3xcurses
link path=usr/share/man/man3xcurses/bkgdset.3xcurses target=bkgd.3xcurses
link path=usr/share/man/man3xcurses/bkgrndset.3xcurses target=bkgrnd.3xcurses
link path=usr/share/man/man3xcurses/box.3xcurses target=border.3xcurses
link path=usr/share/man/man3xcurses/box_set.3xcurses \
    target=border_set.3xcurses
link path=usr/share/man/man3xcurses/color_content.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/color_set.3xcurses \
    target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/def_shell_mode.3xcurses \
    target=def_prog_mode.3xcurses
link path=usr/share/man/man3xcurses/erase.3xcurses target=clear.3xcurses
link path=usr/share/man/man3xcurses/erasewchar.3xcurses \
    target=erasechar.3xcurses
link path=usr/share/man/man3xcurses/flash.3xcurses target=beep.3xcurses
link path=usr/share/man/man3xcurses/get_wstr.3xcurses \
    target=getn_wstr.3xcurses
link path=usr/share/man/man3xcurses/getbkgd.3xcurses target=bkgd.3xcurses
link path=usr/share/man/man3xcurses/getbkgrnd.3xcurses target=bkgrnd.3xcurses
link path=usr/share/man/man3xcurses/getmaxyx.3xcurses target=getbegyx.3xcurses
link path=usr/share/man/man3xcurses/getparyx.3xcurses target=getbegyx.3xcurses
link path=usr/share/man/man3xcurses/getstr.3xcurses target=getnstr.3xcurses
link path=usr/share/man/man3xcurses/getyx.3xcurses target=getbegyx.3xcurses
link path=usr/share/man/man3xcurses/has_colors.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/has_il.3xcurses target=has_ic.3xcurses
link path=usr/share/man/man3xcurses/idlok.3xcurses target=clearok.3xcurses
link path=usr/share/man/man3xcurses/in_wchstr.3xcurses \
    target=in_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/inchstr.3xcurses target=inchnstr.3xcurses
link path=usr/share/man/man3xcurses/init_color.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/init_pair.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/ins_wstr.3xcurses \
    target=ins_nwstr.3xcurses
link path=usr/share/man/man3xcurses/insstr.3xcurses target=insnstr.3xcurses
link path=usr/share/man/man3xcurses/instr.3xcurses target=innstr.3xcurses
link path=usr/share/man/man3xcurses/inwstr.3xcurses target=innwstr.3xcurses
link path=usr/share/man/man3xcurses/is_wintouched.3xcurses \
    target=is_linetouched.3xcurses
link path=usr/share/man/man3xcurses/isendwin.3xcurses target=endwin.3xcurses
link path=usr/share/man/man3xcurses/key_name.3xcurses target=keyname.3xcurses
link path=usr/share/man/man3xcurses/killchar.3xcurses \
    target=erasechar.3xcurses
link path=usr/share/man/man3xcurses/killwchar.3xcurses \
    target=erasechar.3xcurses
link path=usr/share/man/man3xcurses/leaveok.3xcurses target=clearok.3xcurses
link path=usr/share/man/man3xcurses/mvadd_wch.3xcurses target=add_wch.3xcurses
link path=usr/share/man/man3xcurses/mvadd_wchnstr.3xcurses \
    target=add_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvadd_wchstr.3xcurses \
    target=add_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvaddch.3xcurses target=addch.3xcurses
link path=usr/share/man/man3xcurses/mvaddchnstr.3xcurses \
    target=addchstr.3xcurses
link path=usr/share/man/man3xcurses/mvaddchstr.3xcurses \
    target=addchstr.3xcurses
link path=usr/share/man/man3xcurses/mvaddnstr.3xcurses target=addnstr.3xcurses
link path=usr/share/man/man3xcurses/mvaddnwstr.3xcurses \
    target=addnwstr.3xcurses
link path=usr/share/man/man3xcurses/mvaddstr.3xcurses target=addnstr.3xcurses
link path=usr/share/man/man3xcurses/mvaddwstr.3xcurses \
    target=addnwstr.3xcurses
link path=usr/share/man/man3xcurses/mvchgat.3xcurses target=chgat.3xcurses
link path=usr/share/man/man3xcurses/mvdelch.3xcurses target=delch.3xcurses
link path=usr/share/man/man3xcurses/mvget_wch.3xcurses target=get_wch.3xcurses
link path=usr/share/man/man3xcurses/mvget_wstr.3xcurses \
    target=getn_wstr.3xcurses
link path=usr/share/man/man3xcurses/mvgetch.3xcurses target=getch.3xcurses
link path=usr/share/man/man3xcurses/mvgetn_wstr.3xcurses \
    target=getn_wstr.3xcurses
link path=usr/share/man/man3xcurses/mvgetnstr.3xcurses target=getnstr.3xcurses
link path=usr/share/man/man3xcurses/mvgetstr.3xcurses target=getnstr.3xcurses
link path=usr/share/man/man3xcurses/mvhline.3xcurses target=hline.3xcurses
link path=usr/share/man/man3xcurses/mvhline_set.3xcurses \
    target=hline_set.3xcurses
link path=usr/share/man/man3xcurses/mvin_wch.3xcurses target=in_wch.3xcurses
link path=usr/share/man/man3xcurses/mvin_wchnstr.3xcurses \
    target=in_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvin_wchstr.3xcurses \
    target=in_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvinch.3xcurses target=inch.3xcurses
link path=usr/share/man/man3xcurses/mvinchnstr.3xcurses \
    target=inchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvinchstr.3xcurses \
    target=inchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvinnstr.3xcurses target=innstr.3xcurses
link path=usr/share/man/man3xcurses/mvinnwstr.3xcurses target=innwstr.3xcurses
link path=usr/share/man/man3xcurses/mvins_nwstr.3xcurses \
    target=ins_nwstr.3xcurses
link path=usr/share/man/man3xcurses/mvins_wch.3xcurses target=ins_wch.3xcurses
link path=usr/share/man/man3xcurses/mvins_wstr.3xcurses \
    target=ins_nwstr.3xcurses
link path=usr/share/man/man3xcurses/mvinsch.3xcurses target=insch.3xcurses
link path=usr/share/man/man3xcurses/mvinsnstr.3xcurses target=insnstr.3xcurses
link path=usr/share/man/man3xcurses/mvinsstr.3xcurses target=insnstr.3xcurses
link path=usr/share/man/man3xcurses/mvinstr.3xcurses target=innstr.3xcurses
link path=usr/share/man/man3xcurses/mvinwstr.3xcurses target=innwstr.3xcurses
link path=usr/share/man/man3xcurses/mvvline.3xcurses target=hline.3xcurses
link path=usr/share/man/man3xcurses/mvvline_set.3xcurses \
    target=hline_set.3xcurses
link path=usr/share/man/man3xcurses/mvwadd_wch.3xcurses \
    target=add_wch.3xcurses
link path=usr/share/man/man3xcurses/mvwadd_wchnstr.3xcurses \
    target=add_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwadd_wchstr.3xcurses \
    target=add_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwaddch.3xcurses target=addch.3xcurses
link path=usr/share/man/man3xcurses/mvwaddchnstr.3xcurses \
    target=addchstr.3xcurses
link path=usr/share/man/man3xcurses/mvwaddchstr.3xcurses \
    target=addchstr.3xcurses
link path=usr/share/man/man3xcurses/mvwaddnstr.3xcurses \
    target=addnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwaddnwstr.3xcurses \
    target=addnwstr.3xcurses
link path=usr/share/man/man3xcurses/mvwaddstr.3xcurses target=addnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwaddwstr.3xcurses \
    target=addnwstr.3xcurses
link path=usr/share/man/man3xcurses/mvwchgat.3xcurses target=chgat.3xcurses
link path=usr/share/man/man3xcurses/mvwdelch.3xcurses target=delch.3xcurses
link path=usr/share/man/man3xcurses/mvwget_wch.3xcurses \
    target=get_wch.3xcurses
link path=usr/share/man/man3xcurses/mvwget_wstr.3xcurses \
    target=getn_wstr.3xcurses
link path=usr/share/man/man3xcurses/mvwgetch.3xcurses target=getch.3xcurses
link path=usr/share/man/man3xcurses/mvwgetn_wstr.3xcurses \
    target=getn_wstr.3xcurses
link path=usr/share/man/man3xcurses/mvwgetnstr.3xcurses \
    target=getnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwgetstr.3xcurses target=getnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwhline.3xcurses target=hline.3xcurses
link path=usr/share/man/man3xcurses/mvwhline_set.3xcurses \
    target=hline_set.3xcurses
link path=usr/share/man/man3xcurses/mvwin_wch.3xcurses target=in_wch.3xcurses
link path=usr/share/man/man3xcurses/mvwin_wchnstr.3xcurses \
    target=in_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwin_wchstr.3xcurses \
    target=in_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwinch.3xcurses target=inch.3xcurses
link path=usr/share/man/man3xcurses/mvwinchnstr.3xcurses \
    target=inchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwinchstr.3xcurses \
    target=inchnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwinnstr.3xcurses target=innstr.3xcurses
link path=usr/share/man/man3xcurses/mvwinnwstr.3xcurses \
    target=innwstr.3xcurses
link path=usr/share/man/man3xcurses/mvwins_nwstr.3xcurses \
    target=ins_nwstr.3xcurses
link path=usr/share/man/man3xcurses/mvwins_wch.3xcurses \
    target=ins_wch.3xcurses
link path=usr/share/man/man3xcurses/mvwins_wstr.3xcurses \
    target=ins_nwstr.3xcurses
link path=usr/share/man/man3xcurses/mvwinsch.3xcurses target=insch.3xcurses
link path=usr/share/man/man3xcurses/mvwinsnstr.3xcurses \
    target=insnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwinsstr.3xcurses target=insnstr.3xcurses
link path=usr/share/man/man3xcurses/mvwinstr.3xcurses target=innstr.3xcurses
link path=usr/share/man/man3xcurses/mvwinwstr.3xcurses target=innwstr.3xcurses
link path=usr/share/man/man3xcurses/mvwprintw.3xcurses \
    target=mvprintw.3xcurses
link path=usr/share/man/man3xcurses/mvwscanw.3xcurses target=mvscanw.3xcurses
link path=usr/share/man/man3xcurses/mvwvline.3xcurses target=hline.3xcurses
link path=usr/share/man/man3xcurses/mvwvline_set.3xcurses \
    target=hline_set.3xcurses
link path=usr/share/man/man3xcurses/newterm.3xcurses target=initscr.3xcurses
link path=usr/share/man/man3xcurses/newwin.3xcurses target=derwin.3xcurses
link path=usr/share/man/man3xcurses/nocbreak.3xcurses target=cbreak.3xcurses
link path=usr/share/man/man3xcurses/noecho.3xcurses target=echo.3xcurses
link path=usr/share/man/man3xcurses/nonl.3xcurses target=nl.3xcurses
link path=usr/share/man/man3xcurses/noraw.3xcurses target=cbreak.3xcurses
link path=usr/share/man/man3xcurses/overwrite.3xcurses target=overlay.3xcurses
link path=usr/share/man/man3xcurses/pair_content.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/pecho_wchar.3xcurses \
    target=pechochar.3xcurses
link path=usr/share/man/man3xcurses/pnoutrefresh.3xcurses \
    target=newpad.3xcurses
link path=usr/share/man/man3xcurses/prefresh.3xcurses target=newpad.3xcurses
link path=usr/share/man/man3xcurses/printw.3xcurses target=mvprintw.3xcurses
link path=usr/share/man/man3xcurses/putwin.3xcurses target=getwin.3xcurses
link path=usr/share/man/man3xcurses/qiflush.3xcurses target=noqiflush.3xcurses
link path=usr/share/man/man3xcurses/raw.3xcurses target=cbreak.3xcurses
link path=usr/share/man/man3xcurses/refresh.3xcurses target=doupdate.3xcurses
link path=usr/share/man/man3xcurses/reset_prog_mode.3xcurses \
    target=def_prog_mode.3xcurses
link path=usr/share/man/man3xcurses/reset_shell_mode.3xcurses \
    target=def_prog_mode.3xcurses
link path=usr/share/man/man3xcurses/restartterm.3xcurses \
    target=del_curterm.3xcurses
link path=usr/share/man/man3xcurses/savetty.3xcurses target=resetty.3xcurses
link path=usr/share/man/man3xcurses/scanw.3xcurses target=mvscanw.3xcurses
link path=usr/share/man/man3xcurses/scr_init.3xcurses target=scr_dump.3xcurses
link path=usr/share/man/man3xcurses/scr_restore.3xcurses \
    target=scr_dump.3xcurses
link path=usr/share/man/man3xcurses/scr_set.3xcurses target=scr_dump.3xcurses
link path=usr/share/man/man3xcurses/scroll.3xcurses target=scrl.3xcurses
link path=usr/share/man/man3xcurses/scrollok.3xcurses target=clearok.3xcurses
link path=usr/share/man/man3xcurses/set_curterm.3xcurses \
    target=del_curterm.3xcurses
link path=usr/share/man/man3xcurses/setscrreg.3xcurses target=clearok.3xcurses
link path=usr/share/man/man3xcurses/setupterm.3xcurses \
    target=del_curterm.3xcurses
link path=usr/share/man/man3xcurses/slk_attr_off.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_attr_on.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_attr_set.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_attron.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_attrset.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_clear.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_color.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_init.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_label.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_noutrefresh.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_refresh.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_restore.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_set.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_touch.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/slk_wset.3xcurses \
    target=slk_attroff.3xcurses
link path=usr/share/man/man3xcurses/standout.3xcurses target=standend.3xcurses
link path=usr/share/man/man3xcurses/start_color.3xcurses \
    target=can_change_color.3xcurses
link path=usr/share/man/man3xcurses/subpad.3xcurses target=newpad.3xcurses
link path=usr/share/man/man3xcurses/subwin.3xcurses target=derwin.3xcurses
link path=usr/share/man/man3xcurses/term_attrs.3xcurses \
    target=termattrs.3xcurses
link path=usr/share/man/man3xcurses/tgetflag.3xcurses target=tgetent.3xcurses
link path=usr/share/man/man3xcurses/tgetnum.3xcurses target=tgetent.3xcurses
link path=usr/share/man/man3xcurses/tgetstr.3xcurses target=tgetent.3xcurses
link path=usr/share/man/man3xcurses/tgoto.3xcurses target=tgetent.3xcurses
link path=usr/share/man/man3xcurses/tigetnum.3xcurses \
    target=tigetflag.3xcurses
link path=usr/share/man/man3xcurses/tigetstr.3xcurses \
    target=tigetflag.3xcurses
link path=usr/share/man/man3xcurses/timeout.3xcurses target=notimeout.3xcurses
link path=usr/share/man/man3xcurses/touchline.3xcurses \
    target=is_linetouched.3xcurses
link path=usr/share/man/man3xcurses/touchwin.3xcurses \
    target=is_linetouched.3xcurses
link path=usr/share/man/man3xcurses/tparm.3xcurses target=tigetflag.3xcurses
link path=usr/share/man/man3xcurses/tputs.3xcurses target=putp.3xcurses
link path=usr/share/man/man3xcurses/unget_wch.3xcurses target=ungetch.3xcurses
link path=usr/share/man/man3xcurses/untouchwin.3xcurses \
    target=is_linetouched.3xcurses
link path=usr/share/man/man3xcurses/vid_attr.3xcurses target=vidattr.3xcurses
link path=usr/share/man/man3xcurses/vid_puts.3xcurses target=vidattr.3xcurses
link path=usr/share/man/man3xcurses/vidputs.3xcurses target=vidattr.3xcurses
link path=usr/share/man/man3xcurses/vline.3xcurses target=hline.3xcurses
link path=usr/share/man/man3xcurses/vline_set.3xcurses \
    target=hline_set.3xcurses
link path=usr/share/man/man3xcurses/wadd_wch.3xcurses target=add_wch.3xcurses
link path=usr/share/man/man3xcurses/wadd_wchnstr.3xcurses \
    target=add_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/wadd_wchstr.3xcurses \
    target=add_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/waddch.3xcurses target=addch.3xcurses
link path=usr/share/man/man3xcurses/waddchnstr.3xcurses \
    target=addchstr.3xcurses
link path=usr/share/man/man3xcurses/waddchstr.3xcurses \
    target=addchstr.3xcurses
link path=usr/share/man/man3xcurses/waddnstr.3xcurses target=addnstr.3xcurses
link path=usr/share/man/man3xcurses/waddnwstr.3xcurses \
    target=addnwstr.3xcurses
link path=usr/share/man/man3xcurses/waddstr.3xcurses target=addnstr.3xcurses
link path=usr/share/man/man3xcurses/waddwstr.3xcurses target=addnwstr.3xcurses
link path=usr/share/man/man3xcurses/wattr_get.3xcurses \
    target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/wattr_off.3xcurses \
    target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/wattr_on.3xcurses target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/wattr_set.3xcurses \
    target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/wattroff.3xcurses target=attroff.3xcurses
link path=usr/share/man/man3xcurses/wattron.3xcurses target=attroff.3xcurses
link path=usr/share/man/man3xcurses/wattrset.3xcurses target=attroff.3xcurses
link path=usr/share/man/man3xcurses/wbkgd.3xcurses target=bkgd.3xcurses
link path=usr/share/man/man3xcurses/wbkgdset.3xcurses target=bkgd.3xcurses
link path=usr/share/man/man3xcurses/wbkgrnd.3xcurses target=bkgrnd.3xcurses
link path=usr/share/man/man3xcurses/wbkgrndset.3xcurses target=bkgrnd.3xcurses
link path=usr/share/man/man3xcurses/wborder.3xcurses target=border.3xcurses
link path=usr/share/man/man3xcurses/wborder_set.3xcurses \
    target=border_set.3xcurses
link path=usr/share/man/man3xcurses/wchgat.3xcurses target=chgat.3xcurses
link path=usr/share/man/man3xcurses/wclear.3xcurses target=clear.3xcurses
link path=usr/share/man/man3xcurses/wclrtobot.3xcurses \
    target=clrtobot.3xcurses
link path=usr/share/man/man3xcurses/wclrtoeol.3xcurses \
    target=clrtoeol.3xcurses
link path=usr/share/man/man3xcurses/wcolor_set.3xcurses \
    target=attr_get.3xcurses
link path=usr/share/man/man3xcurses/wcursyncup.3xcurses target=syncok.3xcurses
link path=usr/share/man/man3xcurses/wdelch.3xcurses target=delch.3xcurses
link path=usr/share/man/man3xcurses/wdeleteln.3xcurses \
    target=deleteln.3xcurses
link path=usr/share/man/man3xcurses/wecho_wchar.3xcurses \
    target=echo_wchar.3xcurses
link path=usr/share/man/man3xcurses/wechochar.3xcurses \
    target=echochar.3xcurses
link path=usr/share/man/man3xcurses/werase.3xcurses target=clear.3xcurses
link path=usr/share/man/man3xcurses/wget_wch.3xcurses target=get_wch.3xcurses
link path=usr/share/man/man3xcurses/wget_wstr.3xcurses \
    target=getn_wstr.3xcurses
link path=usr/share/man/man3xcurses/wgetbkgrnd.3xcurses target=bkgrnd.3xcurses
link path=usr/share/man/man3xcurses/wgetch.3xcurses target=getch.3xcurses
link path=usr/share/man/man3xcurses/wgetn_wstr.3xcurses \
    target=getn_wstr.3xcurses
link path=usr/share/man/man3xcurses/wgetnstr.3xcurses target=getnstr.3xcurses
link path=usr/share/man/man3xcurses/wgetstr.3xcurses target=getnstr.3xcurses
link path=usr/share/man/man3xcurses/whline.3xcurses target=hline.3xcurses
link path=usr/share/man/man3xcurses/whline_set.3xcurses \
    target=hline_set.3xcurses
link path=usr/share/man/man3xcurses/win_wch.3xcurses target=in_wch.3xcurses
link path=usr/share/man/man3xcurses/win_wchnstr.3xcurses \
    target=in_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/win_wchstr.3xcurses \
    target=in_wchnstr.3xcurses
link path=usr/share/man/man3xcurses/winch.3xcurses target=inch.3xcurses
link path=usr/share/man/man3xcurses/winchnstr.3xcurses \
    target=inchnstr.3xcurses
link path=usr/share/man/man3xcurses/winchstr.3xcurses target=inchnstr.3xcurses
link path=usr/share/man/man3xcurses/winnstr.3xcurses target=innstr.3xcurses
link path=usr/share/man/man3xcurses/winnwstr.3xcurses target=innwstr.3xcurses
link path=usr/share/man/man3xcurses/wins_nwstr.3xcurses \
    target=ins_nwstr.3xcurses
link path=usr/share/man/man3xcurses/wins_wch.3xcurses target=ins_wch.3xcurses
link path=usr/share/man/man3xcurses/wins_wstr.3xcurses \
    target=ins_nwstr.3xcurses
link path=usr/share/man/man3xcurses/winsch.3xcurses target=insch.3xcurses
link path=usr/share/man/man3xcurses/winsdelln.3xcurses \
    target=insdelln.3xcurses
link path=usr/share/man/man3xcurses/winsertln.3xcurses \
    target=insertln.3xcurses
link path=usr/share/man/man3xcurses/winsnstr.3xcurses target=insnstr.3xcurses
link path=usr/share/man/man3xcurses/winsstr.3xcurses target=insnstr.3xcurses
link path=usr/share/man/man3xcurses/winstr.3xcurses target=innstr.3xcurses
link path=usr/share/man/man3xcurses/winwstr.3xcurses target=innwstr.3xcurses
link path=usr/share/man/man3xcurses/wmove.3xcurses target=move.3xcurses
link path=usr/share/man/man3xcurses/wnoutrefresh.3xcurses \
    target=doupdate.3xcurses
link path=usr/share/man/man3xcurses/wprintw.3xcurses target=mvprintw.3xcurses
link path=usr/share/man/man3xcurses/wredrawln.3xcurses \
    target=redrawwin.3xcurses
link path=usr/share/man/man3xcurses/wrefresh.3xcurses target=doupdate.3xcurses
link path=usr/share/man/man3xcurses/wscanw.3xcurses target=mvscanw.3xcurses
link path=usr/share/man/man3xcurses/wscrl.3xcurses target=scrl.3xcurses
link path=usr/share/man/man3xcurses/wsetscrreg.3xcurses \
    target=clearok.3xcurses
link path=usr/share/man/man3xcurses/wstandend.3xcurses \
    target=standend.3xcurses
link path=usr/share/man/man3xcurses/wstandout.3xcurses \
    target=standend.3xcurses
link path=usr/share/man/man3xcurses/wsyncdown.3xcurses target=syncok.3xcurses
link path=usr/share/man/man3xcurses/wsyncup.3xcurses target=syncok.3xcurses
link path=usr/share/man/man3xcurses/wtimeout.3xcurses \
    target=notimeout.3xcurses
link path=usr/share/man/man3xcurses/wtouchln.3xcurses \
    target=is_linetouched.3xcurses
link path=usr/share/man/man3xcurses/wvline.3xcurses target=hline.3xcurses
link path=usr/share/man/man3xcurses/wvline_set.3xcurses \
    target=hline_set.3xcurses
