#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright 2011, Richard Lowe

file path=usr/share/man/man7p/AH.7p
file path=usr/share/man/man7p/ARP.7p
file path=usr/share/man/man7p/ESP.7p
file path=usr/share/man/man7p/ICMP.7p
file path=usr/share/man/man7p/IP.7p
file path=usr/share/man/man7p/SCTP.7p
file path=usr/share/man/man7p/TCP.7p
file path=usr/share/man/man7p/UDP.7p
file path=usr/share/man/man7p/arp.7p
file path=usr/share/man/man7p/dlpi.7p
file path=usr/share/man/man7p/icmp.7p
file path=usr/share/man/man7p/icmp6.7p
file path=usr/share/man/man7p/if.7p
file path=usr/share/man/man7p/if_tcp.7p
file path=usr/share/man/man7p/inet.7p
file path=usr/share/man/man7p/inet6.7p
file path=usr/share/man/man7p/ip.7p
file path=usr/share/man/man7p/ip6.7p
file path=usr/share/man/man7p/ipsec.7p
file path=usr/share/man/man7p/ipsecah.7p
file path=usr/share/man/man7p/ipsecesp.7p
file path=usr/share/man/man7p/pf_key.7p
file path=usr/share/man/man7p/route.7p
file path=usr/share/man/man7p/routing.7p
file path=usr/share/man/man7p/sctp.7p
file path=usr/share/man/man7p/tcp.7p
file path=usr/share/man/man7p/udp.7p
