#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright (c) 2012, Igor Kozhukhov <ikozhukhov@gmail.com>
# Copyright (c) 2017, Chris Fraire <cfraire@me.com>.

file path=usr/share/man/man3m/acos.3m
file path=usr/share/man/man3m/acosh.3m
file path=usr/share/man/man3m/asin.3m
file path=usr/share/man/man3m/asinh.3m
file path=usr/share/man/man3m/atan.3m
file path=usr/share/man/man3m/atan2.3m
file path=usr/share/man/man3m/atanh.3m
file path=usr/share/man/man3m/cabs.3m
file path=usr/share/man/man3m/cacos.3m
file path=usr/share/man/man3m/cacosh.3m
file path=usr/share/man/man3m/carg.3m
file path=usr/share/man/man3m/casin.3m
file path=usr/share/man/man3m/casinh.3m
file path=usr/share/man/man3m/catan.3m
file path=usr/share/man/man3m/catanh.3m
file path=usr/share/man/man3m/cbrt.3m
file path=usr/share/man/man3m/ccos.3m
file path=usr/share/man/man3m/ccosh.3m
file path=usr/share/man/man3m/ceil.3m
file path=usr/share/man/man3m/cexp.3m
file path=usr/share/man/man3m/cimag.3m
file path=usr/share/man/man3m/clog.3m
file path=usr/share/man/man3m/conj.3m
file path=usr/share/man/man3m/copysign.3m
file path=usr/share/man/man3m/cos.3m
file path=usr/share/man/man3m/cosh.3m
file path=usr/share/man/man3m/cpow.3m
file path=usr/share/man/man3m/cproj.3m
file path=usr/share/man/man3m/creal.3m
file path=usr/share/man/man3m/csin.3m
file path=usr/share/man/man3m/csinh.3m
file path=usr/share/man/man3m/csqrt.3m
file path=usr/share/man/man3m/ctan.3m
file path=usr/share/man/man3m/ctanh.3m
file path=usr/share/man/man3m/erf.3m
file path=usr/share/man/man3m/erfc.3m
file path=usr/share/man/man3m/exp.3m
file path=usr/share/man/man3m/exp2.3m
file path=usr/share/man/man3m/expm1.3m
file path=usr/share/man/man3m/fabs.3m
file path=usr/share/man/man3m/fdim.3m
file path=usr/share/man/man3m/feclearexcept.3m
file path=usr/share/man/man3m/fegetenv.3m
file path=usr/share/man/man3m/fegetexceptflag.3m
file path=usr/share/man/man3m/fegetround.3m
file path=usr/share/man/man3m/feholdexcept.3m
file path=usr/share/man/man3m/feraiseexcept.3m
file path=usr/share/man/man3m/fesetprec.3m
file path=usr/share/man/man3m/fetestexcept.3m
file path=usr/share/man/man3m/feupdateenv.3m
file path=usr/share/man/man3m/fex_merge_flags.3m
file path=usr/share/man/man3m/fex_set_handling.3m
file path=usr/share/man/man3m/fex_set_log.3m
file path=usr/share/man/man3m/floor.3m
file path=usr/share/man/man3m/fma.3m
file path=usr/share/man/man3m/fmax.3m
file path=usr/share/man/man3m/fmin.3m
file path=usr/share/man/man3m/fmod.3m
file path=usr/share/man/man3m/fpclassify.3m
file path=usr/share/man/man3m/frexp.3m
file path=usr/share/man/man3m/hypot.3m
file path=usr/share/man/man3m/ilogb.3m
file path=usr/share/man/man3m/isfinite.3m
file path=usr/share/man/man3m/isgreater.3m
file path=usr/share/man/man3m/isgreaterequal.3m
file path=usr/share/man/man3m/isinf.3m
file path=usr/share/man/man3m/isless.3m
file path=usr/share/man/man3m/islessequal.3m
file path=usr/share/man/man3m/islessgreater.3m
file path=usr/share/man/man3m/isnan.3m
file path=usr/share/man/man3m/isnormal.3m
file path=usr/share/man/man3m/isunordered.3m
file path=usr/share/man/man3m/j0.3m
file path=usr/share/man/man3m/ldexp.3m
file path=usr/share/man/man3m/lgamma.3m
file path=usr/share/man/man3m/llrint.3m
file path=usr/share/man/man3m/llround.3m
file path=usr/share/man/man3m/log.3m
file path=usr/share/man/man3m/log10.3m
file path=usr/share/man/man3m/log1p.3m
file path=usr/share/man/man3m/log2.3m
file path=usr/share/man/man3m/logb.3m
file path=usr/share/man/man3m/lrint.3m
file path=usr/share/man/man3m/lround.3m
file path=usr/share/man/man3m/matherr.3m
file path=usr/share/man/man3m/modf.3m
file path=usr/share/man/man3m/nan.3m
file path=usr/share/man/man3m/nearbyint.3m
file path=usr/share/man/man3m/nextafter.3m
file path=usr/share/man/man3m/pow.3m
file path=usr/share/man/man3m/remainder.3m
file path=usr/share/man/man3m/remquo.3m
file path=usr/share/man/man3m/rint.3m
file path=usr/share/man/man3m/round.3m
file path=usr/share/man/man3m/scalb.3m
file path=usr/share/man/man3m/scalbln.3m
file path=usr/share/man/man3m/signbit.3m
file path=usr/share/man/man3m/significand.3m
file path=usr/share/man/man3m/sin.3m
file path=usr/share/man/man3m/sincos.3m
file path=usr/share/man/man3m/sinh.3m
file path=usr/share/man/man3m/sqrt.3m
file path=usr/share/man/man3m/tan.3m
file path=usr/share/man/man3m/tanh.3m
file path=usr/share/man/man3m/tgamma.3m
file path=usr/share/man/man3m/trunc.3m
file path=usr/share/man/man3m/y0.3m
link path=usr/share/man/man3m/acosf.3m target=acos.3m
link path=usr/share/man/man3m/acoshf.3m target=acosh.3m
link path=usr/share/man/man3m/acoshl.3m target=acosh.3m
link path=usr/share/man/man3m/acosl.3m target=acos.3m
link path=usr/share/man/man3m/asinf.3m target=asin.3m
link path=usr/share/man/man3m/asinhf.3m target=asinh.3m
link path=usr/share/man/man3m/asinhl.3m target=asinh.3m
link path=usr/share/man/man3m/asinl.3m target=asin.3m
link path=usr/share/man/man3m/atan2f.3m target=atan2.3m
link path=usr/share/man/man3m/atan2l.3m target=atan2.3m
link path=usr/share/man/man3m/atanf.3m target=atan.3m
link path=usr/share/man/man3m/atanhf.3m target=atanh.3m
link path=usr/share/man/man3m/atanhl.3m target=atanh.3m
link path=usr/share/man/man3m/atanl.3m target=atan.3m
link path=usr/share/man/man3m/cabsf.3m target=cabs.3m
link path=usr/share/man/man3m/cabsl.3m target=cabs.3m
link path=usr/share/man/man3m/cacosf.3m target=cacos.3m
link path=usr/share/man/man3m/cacoshf.3m target=cacosh.3m
link path=usr/share/man/man3m/cacoshl.3m target=cacosh.3m
link path=usr/share/man/man3m/cacosl.3m target=cacos.3m
link path=usr/share/man/man3m/cargf.3m target=carg.3m
link path=usr/share/man/man3m/cargl.3m target=carg.3m
link path=usr/share/man/man3m/casinf.3m target=casin.3m
link path=usr/share/man/man3m/casinhf.3m target=casinh.3m
link path=usr/share/man/man3m/casinhl.3m target=casinh.3m
link path=usr/share/man/man3m/casinl.3m target=casin.3m
link path=usr/share/man/man3m/catanf.3m target=catan.3m
link path=usr/share/man/man3m/catanhf.3m target=catanh.3m
link path=usr/share/man/man3m/catanhl.3m target=catanh.3m
link path=usr/share/man/man3m/catanl.3m target=catan.3m
link path=usr/share/man/man3m/cbrtf.3m target=cbrt.3m
link path=usr/share/man/man3m/cbrtl.3m target=cbrt.3m
link path=usr/share/man/man3m/ccosf.3m target=ccos.3m
link path=usr/share/man/man3m/ccoshf.3m target=ccosh.3m
link path=usr/share/man/man3m/ccoshl.3m target=ccosh.3m
link path=usr/share/man/man3m/ccosl.3m target=ccos.3m
link path=usr/share/man/man3m/ceilf.3m target=ceil.3m
link path=usr/share/man/man3m/ceill.3m target=ceil.3m
link path=usr/share/man/man3m/cexpf.3m target=cexp.3m
link path=usr/share/man/man3m/cexpl.3m target=cexp.3m
link path=usr/share/man/man3m/cimagf.3m target=cimag.3m
link path=usr/share/man/man3m/cimagl.3m target=cimag.3m
link path=usr/share/man/man3m/clogf.3m target=clog.3m
link path=usr/share/man/man3m/clogl.3m target=clog.3m
link path=usr/share/man/man3m/conjf.3m target=conj.3m
link path=usr/share/man/man3m/conjl.3m target=conj.3m
link path=usr/share/man/man3m/copysignf.3m target=copysign.3m
link path=usr/share/man/man3m/copysignl.3m target=copysign.3m
link path=usr/share/man/man3m/cosf.3m target=cos.3m
link path=usr/share/man/man3m/coshf.3m target=cosh.3m
link path=usr/share/man/man3m/coshl.3m target=cosh.3m
link path=usr/share/man/man3m/cosl.3m target=cos.3m
link path=usr/share/man/man3m/cpowf.3m target=cpow.3m
link path=usr/share/man/man3m/cpowl.3m target=cpow.3m
link path=usr/share/man/man3m/cprojf.3m target=cproj.3m
link path=usr/share/man/man3m/cprojl.3m target=cproj.3m
link path=usr/share/man/man3m/crealf.3m target=creal.3m
link path=usr/share/man/man3m/creall.3m target=creal.3m
link path=usr/share/man/man3m/csinf.3m target=csin.3m
link path=usr/share/man/man3m/csinhf.3m target=csinh.3m
link path=usr/share/man/man3m/csinhl.3m target=csinh.3m
link path=usr/share/man/man3m/csinl.3m target=csin.3m
link path=usr/share/man/man3m/csqrtf.3m target=csqrt.3m
link path=usr/share/man/man3m/csqrtl.3m target=csqrt.3m
link path=usr/share/man/man3m/ctanf.3m target=ctan.3m
link path=usr/share/man/man3m/ctanhf.3m target=ctanh.3m
link path=usr/share/man/man3m/ctanhl.3m target=ctanh.3m
link path=usr/share/man/man3m/ctanl.3m target=ctan.3m
link path=usr/share/man/man3m/erfcf.3m target=erfc.3m
link path=usr/share/man/man3m/erfcl.3m target=erfc.3m
link path=usr/share/man/man3m/erff.3m target=erf.3m
link path=usr/share/man/man3m/erfl.3m target=erf.3m
link path=usr/share/man/man3m/exp2f.3m target=exp2.3m
link path=usr/share/man/man3m/exp2l.3m target=exp2.3m
link path=usr/share/man/man3m/expf.3m target=exp.3m
link path=usr/share/man/man3m/expl.3m target=exp.3m
link path=usr/share/man/man3m/expm1f.3m target=expm1.3m
link path=usr/share/man/man3m/expm1l.3m target=expm1.3m
link path=usr/share/man/man3m/fabsf.3m target=fabs.3m
link path=usr/share/man/man3m/fabsl.3m target=fabs.3m
link path=usr/share/man/man3m/fdimf.3m target=fdim.3m
link path=usr/share/man/man3m/fdiml.3m target=fdim.3m
link path=usr/share/man/man3m/fegetprec.3m target=fesetprec.3m
link path=usr/share/man/man3m/fesetenv.3m target=fegetenv.3m
link path=usr/share/man/man3m/fesetexceptflag.3m target=fegetexceptflag.3m
link path=usr/share/man/man3m/fesetround.3m target=fegetround.3m
link path=usr/share/man/man3m/fex_get_handling.3m target=fex_set_handling.3m
link path=usr/share/man/man3m/fex_get_log.3m target=fex_set_log.3m
link path=usr/share/man/man3m/fex_get_log_depth.3m target=fex_set_log.3m
link path=usr/share/man/man3m/fex_getexcepthandler.3m target=fex_set_handling.3m
link path=usr/share/man/man3m/fex_log_entry.3m target=fex_set_log.3m
link path=usr/share/man/man3m/fex_set_log_depth.3m target=fex_set_log.3m
link path=usr/share/man/man3m/fex_setexcepthandler.3m target=fex_set_handling.3m
link path=usr/share/man/man3m/floorf.3m target=floor.3m
link path=usr/share/man/man3m/floorl.3m target=floor.3m
link path=usr/share/man/man3m/fmaf.3m target=fma.3m
link path=usr/share/man/man3m/fmal.3m target=fma.3m
link path=usr/share/man/man3m/fmaxf.3m target=fmax.3m
link path=usr/share/man/man3m/fmaxl.3m target=fmax.3m
link path=usr/share/man/man3m/fminf.3m target=fmin.3m
link path=usr/share/man/man3m/fminl.3m target=fmin.3m
link path=usr/share/man/man3m/fmodf.3m target=fmod.3m
link path=usr/share/man/man3m/fmodl.3m target=fmod.3m
link path=usr/share/man/man3m/frexpf.3m target=frexp.3m
link path=usr/share/man/man3m/frexpl.3m target=frexp.3m
link path=usr/share/man/man3m/gamma.3m target=lgamma.3m
link path=usr/share/man/man3m/gamma_r.3m target=lgamma.3m
link path=usr/share/man/man3m/gammaf.3m target=lgamma.3m
link path=usr/share/man/man3m/gammaf_r.3m target=lgamma.3m
link path=usr/share/man/man3m/gammal.3m target=lgamma.3m
link path=usr/share/man/man3m/gammal_r.3m target=lgamma.3m
link path=usr/share/man/man3m/hypotf.3m target=hypot.3m
link path=usr/share/man/man3m/hypotl.3m target=hypot.3m
link path=usr/share/man/man3m/ilogbf.3m target=ilogb.3m
link path=usr/share/man/man3m/ilogbl.3m target=ilogb.3m
link path=usr/share/man/man3m/j0f.3m target=j0.3m
link path=usr/share/man/man3m/j0l.3m target=j0.3m
link path=usr/share/man/man3m/j1.3m target=j0.3m
link path=usr/share/man/man3m/j1f.3m target=j0.3m
link path=usr/share/man/man3m/j1l.3m target=j0.3m
link path=usr/share/man/man3m/jn.3m target=j0.3m
link path=usr/share/man/man3m/jnf.3m target=j0.3m
link path=usr/share/man/man3m/jnl.3m target=j0.3m
link path=usr/share/man/man3m/ldexpf.3m target=ldexp.3m
link path=usr/share/man/man3m/ldexpl.3m target=ldexp.3m
link path=usr/share/man/man3m/lgamma_r.3m target=lgamma.3m
link path=usr/share/man/man3m/lgammaf.3m target=lgamma.3m
link path=usr/share/man/man3m/lgammaf_r.3m target=lgamma.3m
link path=usr/share/man/man3m/lgammal.3m target=lgamma.3m
link path=usr/share/man/man3m/lgammal_r.3m target=lgamma.3m
link path=usr/share/man/man3m/llrintf.3m target=llrint.3m
link path=usr/share/man/man3m/llrintl.3m target=llrint.3m
link path=usr/share/man/man3m/llroundf.3m target=llround.3m
link path=usr/share/man/man3m/llroundl.3m target=llround.3m
link path=usr/share/man/man3m/log10f.3m target=log10.3m
link path=usr/share/man/man3m/log10l.3m target=log10.3m
link path=usr/share/man/man3m/log1pf.3m target=log1p.3m
link path=usr/share/man/man3m/log1pl.3m target=log1p.3m
link path=usr/share/man/man3m/log2f.3m target=log2.3m
link path=usr/share/man/man3m/log2l.3m target=log2.3m
link path=usr/share/man/man3m/logbf.3m target=logb.3m
link path=usr/share/man/man3m/logbl.3m target=logb.3m
link path=usr/share/man/man3m/logf.3m target=log.3m
link path=usr/share/man/man3m/logl.3m target=log.3m
link path=usr/share/man/man3m/lrintf.3m target=lrint.3m
link path=usr/share/man/man3m/lrintl.3m target=lrint.3m
link path=usr/share/man/man3m/lroundf.3m target=lround.3m
link path=usr/share/man/man3m/lroundl.3m target=lround.3m
link path=usr/share/man/man3m/modff.3m target=modf.3m
link path=usr/share/man/man3m/modfl.3m target=modf.3m
link path=usr/share/man/man3m/nanf.3m target=nan.3m
link path=usr/share/man/man3m/nanl.3m target=nan.3m
link path=usr/share/man/man3m/nearbyintf.3m target=nearbyint.3m
link path=usr/share/man/man3m/nearbyintl.3m target=nearbyint.3m
link path=usr/share/man/man3m/nextafterf.3m target=nextafter.3m
link path=usr/share/man/man3m/nextafterl.3m target=nextafter.3m
link path=usr/share/man/man3m/nexttoward.3m target=nextafter.3m
link path=usr/share/man/man3m/nexttowardf.3m target=nextafter.3m
link path=usr/share/man/man3m/nexttowardl.3m target=nextafter.3m
link path=usr/share/man/man3m/powf.3m target=pow.3m
link path=usr/share/man/man3m/powl.3m target=pow.3m
link path=usr/share/man/man3m/remainderf.3m target=remainder.3m
link path=usr/share/man/man3m/remainderl.3m target=remainder.3m
link path=usr/share/man/man3m/remquof.3m target=remquo.3m
link path=usr/share/man/man3m/remquol.3m target=remquo.3m
link path=usr/share/man/man3m/rintf.3m target=rint.3m
link path=usr/share/man/man3m/rintl.3m target=rint.3m
link path=usr/share/man/man3m/roundf.3m target=round.3m
link path=usr/share/man/man3m/roundl.3m target=round.3m
link path=usr/share/man/man3m/scalbf.3m target=scalb.3m
link path=usr/share/man/man3m/scalbl.3m target=scalb.3m
link path=usr/share/man/man3m/scalblnf.3m target=scalbln.3m
link path=usr/share/man/man3m/scalblnl.3m target=scalbln.3m
link path=usr/share/man/man3m/scalbn.3m target=scalbln.3m
link path=usr/share/man/man3m/scalbnf.3m target=scalbln.3m
link path=usr/share/man/man3m/scalbnl.3m target=scalbln.3m
link path=usr/share/man/man3m/significandf.3m target=significand.3m
link path=usr/share/man/man3m/significandl.3m target=significand.3m
link path=usr/share/man/man3m/sincosf.3m target=sincos.3m
link path=usr/share/man/man3m/sincosl.3m target=sincos.3m
link path=usr/share/man/man3m/sinf.3m target=sin.3m
link path=usr/share/man/man3m/sinhf.3m target=sinh.3m
link path=usr/share/man/man3m/sinhl.3m target=sinh.3m
link path=usr/share/man/man3m/sinl.3m target=sin.3m
link path=usr/share/man/man3m/sqrtf.3m target=sqrt.3m
link path=usr/share/man/man3m/sqrtl.3m target=sqrt.3m
link path=usr/share/man/man3m/tanf.3m target=tan.3m
link path=usr/share/man/man3m/tanhf.3m target=tanh.3m
link path=usr/share/man/man3m/tanhl.3m target=tanh.3m
link path=usr/share/man/man3m/tanl.3m target=tan.3m
link path=usr/share/man/man3m/tgammaf.3m target=tgamma.3m
link path=usr/share/man/man3m/tgammal.3m target=tgamma.3m
link path=usr/share/man/man3m/truncf.3m target=trunc.3m
link path=usr/share/man/man3m/truncl.3m target=trunc.3m
link path=usr/share/man/man3m/y0f.3m target=y0.3m
link path=usr/share/man/man3m/y0l.3m target=y0.3m
link path=usr/share/man/man3m/y1.3m target=y0.3m
link path=usr/share/man/man3m/y1f.3m target=y0.3m
link path=usr/share/man/man3m/y1l.3m target=y0.3m
link path=usr/share/man/man3m/yn.3m target=y0.3m
link path=usr/share/man/man3m/ynf.3m target=y0.3m
link path=usr/share/man/man3m/ynl.3m target=y0.3m
