#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man4m/bufmod.4m
file path=usr/share/man/man4m/connld.4m
file path=usr/share/man/man4m/ldterm.4m
file path=usr/share/man/man4m/pckt.4m
file path=usr/share/man/man4m/pfmod.4m
file path=usr/share/man/man4m/pipemod.4m
file path=usr/share/man/man4m/ptem.4m
file path=usr/share/man/man4m/timod.4m
file path=usr/share/man/man4m/tirdwr.4m
file path=usr/share/man/man4m/ttcompat.4m
link path=usr/share/man/man4m/vuid2ps2.4m target=vuidmice.4m
link path=usr/share/man/man4m/vuid3ps2.4m target=vuidmice.4m
link path=usr/share/man/man4m/vuidm3p.4m target=vuidmice.4m
link path=usr/share/man/man4m/vuidm4p.4m target=vuidmice.4m
link path=usr/share/man/man4m/vuidm5p.4m target=vuidmice.4m
file path=usr/share/man/man4m/vuidmice.4m
