#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3lib/libadm.3lib
file path=usr/share/man/man3lib/libaio.3lib
file path=usr/share/man/man3lib/libavl.3lib
file path=usr/share/man/man3lib/libbsdmalloc.3lib
file path=usr/share/man/man3lib/libbsm.3lib
file path=usr/share/man/man3lib/libc.3lib
file path=usr/share/man/man3lib/libc_db.3lib
file path=usr/share/man/man3lib/libcfgadm.3lib
file path=usr/share/man/man3lib/libcommputil.3lib
file path=usr/share/man/man3lib/libcontract.3lib
file path=usr/share/man/man3lib/libcrypt.3lib
file path=usr/share/man/man3lib/libcurses.3lib
file path=usr/share/man/man3lib/libdevid.3lib
file path=usr/share/man/man3lib/libdevinfo.3lib
file path=usr/share/man/man3lib/libdl.3lib
file path=usr/share/man/man3lib/libdlpi.3lib
file path=usr/share/man/man3lib/libdoor.3lib
file path=usr/share/man/man3lib/libefi.3lib
file path=usr/share/man/man3lib/libelf.3lib
file path=usr/share/man/man3lib/libexacct.3lib
file path=usr/share/man/man3lib/libform.3lib
file path=usr/share/man/man3lib/libfstyp.3lib
file path=usr/share/man/man3lib/libgen.3lib
file path=usr/share/man/man3lib/libintl.3lib
file path=usr/share/man/man3lib/libkmf.3lib
file path=usr/share/man/man3lib/libkstat.3lib
file path=usr/share/man/man3lib/libkvm.3lib
file path=usr/share/man/man3lib/libl.3lib
file path=usr/share/man/man3lib/liblgrp.3lib
file path=usr/share/man/man3lib/libmail.3lib
file path=usr/share/man/man3lib/libmalloc.3lib
file path=usr/share/man/man3lib/libmapmalloc.3lib
file path=usr/share/man/man3lib/libmd.3lib
file path=usr/share/man/man3lib/libmd5.3lib
file path=usr/share/man/man3lib/libmenu.3lib
file path=usr/share/man/man3lib/libmp.3lib
file path=usr/share/man/man3lib/libmtmalloc.3lib
file path=usr/share/man/man3lib/libnls.3lib
file path=usr/share/man/man3lib/libnsl.3lib
file path=usr/share/man/man3lib/libnvpair.3lib
file path=usr/share/man/man3lib/libpam.3lib
file path=usr/share/man/man3lib/libpanel.3lib
file path=usr/share/man/man3lib/libpkcs11.3lib
file path=usr/share/man/man3lib/libproject.3lib
file path=usr/share/man/man3lib/libpthread.3lib
file path=usr/share/man/man3lib/libresolv.3lib
file path=usr/share/man/man3lib/librpcsvc.3lib
file path=usr/share/man/man3lib/librt.3lib
file path=usr/share/man/man3lib/librtld_db.3lib
file path=usr/share/man/man3lib/libscf.3lib
file path=usr/share/man/man3lib/libsctp.3lib
file path=usr/share/man/man3lib/libsec.3lib
file path=usr/share/man/man3lib/libsecdb.3lib
file path=usr/share/man/man3lib/libsendfile.3lib
file path=usr/share/man/man3lib/libsip.3lib
file path=usr/share/man/man3lib/libsocket.3lib
file path=usr/share/man/man3lib/libsys.3lib
file path=usr/share/man/man3lib/libsysevent.3lib
file path=usr/share/man/man3lib/libthread.3lib
file path=usr/share/man/man3lib/libtsnet.3lib
file path=usr/share/man/man3lib/libtsol.3lib
file path=usr/share/man/man3lib/libumem.3lib
file path=usr/share/man/man3lib/libuuid.3lib
file path=usr/share/man/man3lib/libvolmgt.3lib
file path=usr/share/man/man3lib/libw.3lib
file path=usr/share/man/man3lib/libxnet.3lib
file path=usr/share/man/man3lib/liby.3lib
link path=usr/share/man/man3lib/libposix4.3lib target=librt.3lib
link path=usr/share/man/man3lib/libtermcap.3lib target=libcurses.3lib
link path=usr/share/man/man3lib/libtermlib.3lib target=libcurses.3lib
