#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3mp/mp.3mp
link path=usr/share/man/man3mp/mp_gcd.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_itom.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_madd.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_mcmp.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_mdiv.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_mfree.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_min.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_mout.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_msqrt.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_msub.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_mtox.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_mult.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_pow.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_rpow.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_sdiv.3mp target=mp.3mp
link path=usr/share/man/man3mp/mp_xtom.3mp target=mp.3mp
