#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man4/cardbus.4
file path=usr/share/man/man4/dir_ufs.4
file path=usr/share/man/man4/driver.conf.4
file path=usr/share/man/man4/pci.4
file path=usr/share/man/man4/priv_names.4
file path=usr/share/man/man4/proc.4
file path=usr/share/man/man4/process.4
file path=usr/share/man/man4/pseudo.4
file path=usr/share/man/man4/scsi.4
file path=usr/share/man/man4/sock2path.4
file path=usr/share/man/man4/system.4
file path=usr/share/man/man4/tnf_kernel_probes.4
file path=usr/share/man/man4/ts_dptbl.4
link path=usr/share/man/man4/dir.4 target=dir_ufs.4
link path=usr/share/man/man4/pcie.4 target=pci.4
