#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3commputil/sdp_add_origin.3commputil
file path=usr/share/man/man3commputil/sdp_clone_session.3commputil
file path=usr/share/man/man3commputil/sdp_delete_all_field.3commputil
file path=usr/share/man/man3commputil/sdp_delete_media.3commputil
file path=usr/share/man/man3commputil/sdp_find_attribute.3commputil
file path=usr/share/man/man3commputil/sdp_find_media.3commputil
file path=usr/share/man/man3commputil/sdp_find_media_rtpmap.3commputil
file path=usr/share/man/man3commputil/sdp_new_session.3commputil
file path=usr/share/man/man3commputil/sdp_parse.3commputil
file path=usr/share/man/man3commputil/sdp_session_to_str.3commputil
link path=usr/share/man/man3commputil/sdp_add_attribute.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_bandwidth.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_connection.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_email.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_information.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_key.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_media.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_name.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_phone.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_repeat.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_time.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_uri.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_add_zone.3commputil \
    target=sdp_add_origin.3commputil
link path=usr/share/man/man3commputil/sdp_delete_all_media_field.3commputil \
    target=sdp_delete_all_field.3commputil
link path=usr/share/man/man3commputil/sdp_delete_attribute.3commputil \
    target=sdp_delete_media.3commputil
link path=usr/share/man/man3commputil/sdp_free_session.3commputil \
    target=sdp_new_session.3commputil
