#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3uuid/uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_compare.3uuid target=uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_copy.3uuid target=uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_generate.3uuid target=uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_generate_random.3uuid \
    target=uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_generate_time.3uuid \
    target=uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_is_null.3uuid target=uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_parse.3uuid target=uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_time.3uuid target=uuid_clear.3uuid
link path=usr/share/man/man3uuid/uuid_unparse.3uuid target=uuid_clear.3uuid
