#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2014 Nexenta Systems, Inc.
#

file path=usr/share/man/man5/audit_binfile.5
file path=usr/share/man/man5/audit_remote.5
file path=usr/share/man/man5/audit_syslog.5
file path=usr/share/man/man5/cancellation.5
file path=usr/share/man/man5/charmap.5
file path=usr/share/man/man5/condition.5
file path=usr/share/man/man5/crypt_bsdbf.5
file path=usr/share/man/man5/crypt_bsdmd5.5
file path=usr/share/man/man5/crypt_sha256.5
file path=usr/share/man/man5/crypt_sha512.5
file path=usr/share/man/man5/crypt_sunmd5.5
file path=usr/share/man/man5/crypt_unix.5
file path=usr/share/man/man5/environ.5
file path=usr/share/man/man5/extendedFILE.5
file path=usr/share/man/man5/fnmatch.5
file path=usr/share/man/man5/isalist.5
file path=usr/share/man/man5/largefile.5
file path=usr/share/man/man5/lf64.5
file path=usr/share/man/man5/lfcompile.5
file path=usr/share/man/man5/lfcompile64.5
file path=usr/share/man/man5/locale.5
file path=usr/share/man/man5/mutex.5
file path=usr/share/man/man5/pam_allow.5
file path=usr/share/man/man5/pam_authtok_check.5
file path=usr/share/man/man5/pam_authtok_get.5
file path=usr/share/man/man5/pam_authtok_store.5
file path=usr/share/man/man5/pam_deny.5
file path=usr/share/man/man5/pam_dhkeys.5
file path=usr/share/man/man5/pam_dial_auth.5
file path=usr/share/man/man5/pam_ldap.5
file path=usr/share/man/man5/pam_list.5
file path=usr/share/man/man5/pam_passwd_auth.5
file path=usr/share/man/man5/pam_rhosts_auth.5
file path=usr/share/man/man5/pam_roles.5
file path=usr/share/man/man5/pam_sample.5
file path=usr/share/man/man5/pam_timestamp.5
file path=usr/share/man/man5/pam_tsol_account.5
file path=usr/share/man/man5/pam_unix_account.5
file path=usr/share/man/man5/pam_unix_auth.5
file path=usr/share/man/man5/pam_unix_cred.5
file path=usr/share/man/man5/pam_unix_session.5
file path=usr/share/man/man5/pkcs11_kernel.5
file path=usr/share/man/man5/pkcs11_softtoken.5
file path=usr/share/man/man5/pkcs11_tpm.5
file path=usr/share/man/man5/regex.5
file path=usr/share/man/man5/regexp.5
file path=usr/share/man/man5/threads.5
link path=usr/share/man/man5/advance.5 target=regexp.5
link path=usr/share/man/man5/compile.5 target=regexp.5
link path=usr/share/man/man5/pthreads.5 target=threads.5
link path=usr/share/man/man5/step.5 target=regexp.5
