#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3devid/devid_get.3devid
link path=usr/share/man/man3devid/devid_compare.3devid target=devid_get.3devid
link path=usr/share/man/man3devid/devid_deviceid_to_nmlist.3devid \
    target=devid_get.3devid
link path=usr/share/man/man3devid/devid_free.3devid target=devid_get.3devid
link path=usr/share/man/man3devid/devid_free_nmlist.3devid \
    target=devid_get.3devid
link path=usr/share/man/man3devid/devid_get_minor_name.3devid \
    target=devid_get.3devid
link path=usr/share/man/man3devid/devid_sizeof.3devid target=devid_get.3devid
link path=usr/share/man/man3devid/devid_str_decode.3devid \
    target=devid_get.3devid
link path=usr/share/man/man3devid/devid_str_encode.3devid \
    target=devid_get.3devid
link path=usr/share/man/man3devid/devid_str_free.3devid \
    target=devid_get.3devid
link path=usr/share/man/man3devid/devid_valid.3devid target=devid_get.3devid
