#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2017 Nexenta Systems, Inc.
#

file path=usr/share/man/man3ofmt/ofmt.3ofmt
link path=usr/share/man/man3ofmt/ofmt_close.3ofmt target=ofmt.3ofmt
link path=usr/share/man/man3ofmt/ofmt_open.3ofmt target=ofmt.3ofmt
link path=usr/share/man/man3ofmt/ofmt_print.3ofmt target=ofmt.3ofmt
link path=usr/share/man/man3ofmt/ofmt_strerror.3ofmt target=ofmt.3ofmt
link path=usr/share/man/man3ofmt/ofmt_update_winsize.3ofmt target=ofmt.3ofmt
