#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3sec/acl_check.3sec
file path=usr/share/man/man3sec/acl_free.3sec
file path=usr/share/man/man3sec/acl_get.3sec
file path=usr/share/man/man3sec/acl_strip.3sec
file path=usr/share/man/man3sec/acl_totext.3sec
file path=usr/share/man/man3sec/acl_trivial.3sec
file path=usr/share/man/man3sec/aclcheck.3sec
file path=usr/share/man/man3sec/aclsort.3sec
file path=usr/share/man/man3sec/acltomode.3sec
file path=usr/share/man/man3sec/acltotext.3sec
link path=usr/share/man/man3sec/acl_fromtext.3sec target=acl_totext.3sec
link path=usr/share/man/man3sec/acl_set.3sec target=acl_get.3sec
link path=usr/share/man/man3sec/aclfrommode.3sec target=acltomode.3sec
link path=usr/share/man/man3sec/aclfromtext.3sec target=acltotext.3sec
link path=usr/share/man/man3sec/facl_get.3sec target=acl_get.3sec
link path=usr/share/man/man3sec/facl_set.3sec target=acl_get.3sec
