#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3tsol/blcompare.3tsol
file path=usr/share/man/man3tsol/blminmax.3tsol
file path=usr/share/man/man3tsol/bltocolor.3tsol
file path=usr/share/man/man3tsol/bltos.3tsol
file path=usr/share/man/man3tsol/btohex.3tsol
file path=usr/share/man/man3tsol/getdevicerange.3tsol
file path=usr/share/man/man3tsol/getpathbylabel.3tsol
file path=usr/share/man/man3tsol/getplabel.3tsol
file path=usr/share/man/man3tsol/getuserrange.3tsol
file path=usr/share/man/man3tsol/getzonelabelbyid.3tsol
file path=usr/share/man/man3tsol/getzonerootbyid.3tsol
file path=usr/share/man/man3tsol/hextob.3tsol
file path=usr/share/man/man3tsol/label_to_str.3tsol
file path=usr/share/man/man3tsol/labelbuilder.3tsol
file path=usr/share/man/man3tsol/labelclipping.3tsol
file path=usr/share/man/man3tsol/m_label.3tsol
file path=usr/share/man/man3tsol/sbltos.3tsol
file path=usr/share/man/man3tsol/setflabel.3tsol
file path=usr/share/man/man3tsol/stobl.3tsol
file path=usr/share/man/man3tsol/str_to_label.3tsol
file path=usr/share/man/man3tsol/tsol_getrhtype.3tsol
link path=usr/share/man/man3tsol/Xbcleartos.3tsol target=labelclipping.3tsol
link path=usr/share/man/man3tsol/Xbsltos.3tsol target=labelclipping.3tsol
link path=usr/share/man/man3tsol/bcleartoh.3tsol target=btohex.3tsol
link path=usr/share/man/man3tsol/bcleartoh_r.3tsol target=btohex.3tsol
link path=usr/share/man/man3tsol/bcleartos.3tsol target=bltos.3tsol
link path=usr/share/man/man3tsol/bldominates.3tsol target=blcompare.3tsol
link path=usr/share/man/man3tsol/blequal.3tsol target=blcompare.3tsol
link path=usr/share/man/man3tsol/blinrange.3tsol target=blcompare.3tsol
link path=usr/share/man/man3tsol/blmaximum.3tsol target=blminmax.3tsol
link path=usr/share/man/man3tsol/blminimum.3tsol target=blminmax.3tsol
link path=usr/share/man/man3tsol/blstrictdom.3tsol target=blcompare.3tsol
link path=usr/share/man/man3tsol/bltocolor_r.3tsol target=bltocolor.3tsol
link path=usr/share/man/man3tsol/bsltoh.3tsol target=btohex.3tsol
link path=usr/share/man/man3tsol/bsltoh_r.3tsol target=btohex.3tsol
link path=usr/share/man/man3tsol/bsltos.3tsol target=bltos.3tsol
link path=usr/share/man/man3tsol/getzoneidbylabel.3tsol \
    target=getzonelabelbyid.3tsol
link path=usr/share/man/man3tsol/getzonelabelbyname.3tsol \
    target=getzonelabelbyid.3tsol
link path=usr/share/man/man3tsol/getzonerootbylabel.3tsol \
    target=getzonerootbyid.3tsol
link path=usr/share/man/man3tsol/getzonerootbyname.3tsol \
    target=getzonerootbyid.3tsol
link path=usr/share/man/man3tsol/h_alloc.3tsol target=btohex.3tsol
link path=usr/share/man/man3tsol/h_free.3tsol target=btohex.3tsol
link path=usr/share/man/man3tsol/htobclear.3tsol target=hextob.3tsol
link path=usr/share/man/man3tsol/htobsl.3tsol target=hextob.3tsol
link path=usr/share/man/man3tsol/m_label_alloc.3tsol target=m_label.3tsol
link path=usr/share/man/man3tsol/m_label_dup.3tsol target=m_label.3tsol
link path=usr/share/man/man3tsol/m_label_free.3tsol target=m_label.3tsol
link path=usr/share/man/man3tsol/sbcleartos.3tsol target=sbltos.3tsol
link path=usr/share/man/man3tsol/sbsltos.3tsol target=sbltos.3tsol
link path=usr/share/man/man3tsol/stobclear.3tsol target=stobl.3tsol
link path=usr/share/man/man3tsol/stobsl.3tsol target=stobl.3tsol
