#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3secdb/getauthattr.3secdb
file path=usr/share/man/man3secdb/getexecattr.3secdb
file path=usr/share/man/man3secdb/getprofattr.3secdb
file path=usr/share/man/man3secdb/getuserattr.3secdb
file path=usr/share/man/man3secdb/kva_match.3secdb
link path=usr/share/man/man3secdb/chkauthattr.3secdb target=getauthattr.3secdb
link path=usr/share/man/man3secdb/endauthattr.3secdb target=getauthattr.3secdb
link path=usr/share/man/man3secdb/endexecattr.3secdb target=getexecattr.3secdb
link path=usr/share/man/man3secdb/endprofattr.3secdb target=getprofattr.3secdb
link path=usr/share/man/man3secdb/enduserattr.3secdb target=getuserattr.3secdb
link path=usr/share/man/man3secdb/fgetuserattr.3secdb \
    target=getuserattr.3secdb
link path=usr/share/man/man3secdb/free_authattr.3secdb \
    target=getauthattr.3secdb
link path=usr/share/man/man3secdb/free_execattr.3secdb \
    target=getexecattr.3secdb
link path=usr/share/man/man3secdb/free_profattr.3secdb \
    target=getprofattr.3secdb
link path=usr/share/man/man3secdb/free_proflist.3secdb \
    target=getprofattr.3secdb
link path=usr/share/man/man3secdb/free_userattr.3secdb \
    target=getuserattr.3secdb
link path=usr/share/man/man3secdb/getauthnam.3secdb target=getauthattr.3secdb
link path=usr/share/man/man3secdb/getexecprof.3secdb target=getexecattr.3secdb
link path=usr/share/man/man3secdb/getexecuser.3secdb target=getexecattr.3secdb
link path=usr/share/man/man3secdb/getproflist.3secdb target=getprofattr.3secdb
link path=usr/share/man/man3secdb/getprofnam.3secdb target=getprofattr.3secdb
link path=usr/share/man/man3secdb/getusernam.3secdb target=getuserattr.3secdb
link path=usr/share/man/man3secdb/getuseruid.3secdb target=getuserattr.3secdb
link path=usr/share/man/man3secdb/match_execattr.3secdb \
    target=getexecattr.3secdb
link path=usr/share/man/man3secdb/setauthattr.3secdb target=getauthattr.3secdb
link path=usr/share/man/man3secdb/setexecattr.3secdb target=getexecattr.3secdb
link path=usr/share/man/man3secdb/setprofattr.3secdb target=getprofattr.3secdb
link path=usr/share/man/man3secdb/setuserattr.3secdb target=getuserattr.3secdb
