#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2013 Nexenta Systems, Inc.  All rights reserved.
# Copyright 2013 OmniTI Computer Consulting, Inc. All rights reserved.
# Copyright 2014 Garrett D'Amore <garrett@damore.org>
#

file path=usr/share/man/man3c/__fbufsize.3c
file path=usr/share/man/man3c/_longjmp.3c
file path=usr/share/man/man3c/_stack_grow.3c
file path=usr/share/man/man3c/a64l.3c
file path=usr/share/man/man3c/abort.3c
file path=usr/share/man/man3c/abs.3c
file path=usr/share/man/man3c/addsev.3c
file path=usr/share/man/man3c/addseverity.3c
file path=usr/share/man/man3c/aio_cancel.3c
file path=usr/share/man/man3c/aio_error.3c
file path=usr/share/man/man3c/aio_fsync.3c
file path=usr/share/man/man3c/aio_read.3c
file path=usr/share/man/man3c/aio_return.3c
file path=usr/share/man/man3c/aio_suspend.3c
file path=usr/share/man/man3c/aio_waitn.3c
file path=usr/share/man/man3c/aio_write.3c
file path=usr/share/man/man3c/aiocancel.3c
file path=usr/share/man/man3c/aioread.3c
file path=usr/share/man/man3c/aiowait.3c
file path=usr/share/man/man3c/aligned_alloc.3c
file path=usr/share/man/man3c/arc4random.3c
file path=usr/share/man/man3c/assert.3c
file path=usr/share/man/man3c/atexit.3c
file path=usr/share/man/man3c/atomic_add.3c
file path=usr/share/man/man3c/atomic_and.3c
file path=usr/share/man/man3c/atomic_bits.3c
file path=usr/share/man/man3c/atomic_cas.3c
file path=usr/share/man/man3c/atomic_dec.3c
file path=usr/share/man/man3c/atomic_inc.3c
file path=usr/share/man/man3c/atomic_ops.3c
file path=usr/share/man/man3c/atomic_or.3c
file path=usr/share/man/man3c/atomic_swap.3c
file path=usr/share/man/man3c/attropen.3c
file path=usr/share/man/man3c/basename.3c
file path=usr/share/man/man3c/bsd_signal.3c
file path=usr/share/man/man3c/bsearch.3c
file path=usr/share/man/man3c/bstring.3c
file path=usr/share/man/man3c/btowc.3c
file path=usr/share/man/man3c/call_once.3c
file path=usr/share/man/man3c/catgets.3c
file path=usr/share/man/man3c/catopen.3c
file path=usr/share/man/man3c/cfgetispeed.3c
file path=usr/share/man/man3c/cfsetispeed.3c
file path=usr/share/man/man3c/clearenv.3c
file path=usr/share/man/man3c/clock.3c
file path=usr/share/man/man3c/clock_nanosleep.3c
file path=usr/share/man/man3c/clock_settime.3c
file path=usr/share/man/man3c/closedir.3c
file path=usr/share/man/man3c/closefrom.3c
file path=usr/share/man/man3c/cnd.3c
file path=usr/share/man/man3c/cond_init.3c
file path=usr/share/man/man3c/confstr.3c
file path=usr/share/man/man3c/crypt.3c
file path=usr/share/man/man3c/crypt_genhash_impl.3c
file path=usr/share/man/man3c/crypt_gensalt.3c
file path=usr/share/man/man3c/crypt_gensalt_impl.3c
file path=usr/share/man/man3c/cset.3c
file path=usr/share/man/man3c/ctermid.3c
file path=usr/share/man/man3c/ctime.3c
file path=usr/share/man/man3c/ctype.3c
file path=usr/share/man/man3c/cuserid.3c
file path=usr/share/man/man3c/daemon.3c
file path=usr/share/man/man3c/decimal_to_floating.3c
file path=usr/share/man/man3c/difftime.3c
file path=usr/share/man/man3c/directio.3c
file path=usr/share/man/man3c/dirfd.3c
file path=usr/share/man/man3c/dirname.3c
file path=usr/share/man/man3c/div.3c
file path=usr/share/man/man3c/dladdr.3c
file path=usr/share/man/man3c/dlclose.3c
file path=usr/share/man/man3c/dldump.3c
file path=usr/share/man/man3c/dlerror.3c
file path=usr/share/man/man3c/dlinfo.3c
file path=usr/share/man/man3c/dlopen.3c
file path=usr/share/man/man3c/dlsym.3c
file path=usr/share/man/man3c/door_bind.3c
file path=usr/share/man/man3c/door_call.3c
file path=usr/share/man/man3c/door_create.3c
file path=usr/share/man/man3c/door_cred.3c
file path=usr/share/man/man3c/door_getparam.3c
file path=usr/share/man/man3c/door_info.3c
file path=usr/share/man/man3c/door_return.3c
file path=usr/share/man/man3c/door_revoke.3c
file path=usr/share/man/man3c/door_server_create.3c
file path=usr/share/man/man3c/door_ucred.3c
file path=usr/share/man/man3c/drand48.3c
file path=usr/share/man/man3c/dup2.3c
file path=usr/share/man/man3c/econvert.3c
file path=usr/share/man/man3c/ecvt.3c
file path=usr/share/man/man3c/enable_extended_FILE_stdio.3c
file path=usr/share/man/man3c/encrypt.3c
file path=usr/share/man/man3c/end.3c
file path=usr/share/man/man3c/endian.3c
file path=usr/share/man/man3c/epoll_create.3c
file path=usr/share/man/man3c/epoll_ctl.3c
file path=usr/share/man/man3c/epoll_wait.3c
file path=usr/share/man/man3c/err.3c
file path=usr/share/man/man3c/euclen.3c
file path=usr/share/man/man3c/eventfd.3c
file path=usr/share/man/man3c/exit.3c
file path=usr/share/man/man3c/fattach.3c
file path=usr/share/man/man3c/fclose.3c
file path=usr/share/man/man3c/fcloseall.3c
file path=usr/share/man/man3c/fdatasync.3c
file path=usr/share/man/man3c/fdetach.3c
file path=usr/share/man/man3c/fdopen.3c
file path=usr/share/man/man3c/ferror.3c
file path=usr/share/man/man3c/fflush.3c
file path=usr/share/man/man3c/ffs.3c
file path=usr/share/man/man3c/fgetattr.3c
file path=usr/share/man/man3c/fgetc.3c
file path=usr/share/man/man3c/fgetpos.3c
file path=usr/share/man/man3c/fgetwc.3c
file path=usr/share/man/man3c/floating_to_decimal.3c
file path=usr/share/man/man3c/flock.3c
file path=usr/share/man/man3c/flockfile.3c
file path=usr/share/man/man3c/fmtmsg.3c
file path=usr/share/man/man3c/fnmatch.3c
file path=usr/share/man/man3c/fopen.3c
file path=usr/share/man/man3c/fpgetround.3c
file path=usr/share/man/man3c/fputc.3c
file path=usr/share/man/man3c/fputwc.3c
file path=usr/share/man/man3c/fputws.3c
file path=usr/share/man/man3c/fread.3c
file path=usr/share/man/man3c/freopen.3c
file path=usr/share/man/man3c/fseek.3c
file path=usr/share/man/man3c/fsetpos.3c
file path=usr/share/man/man3c/fsync.3c
file path=usr/share/man/man3c/ftell.3c
file path=usr/share/man/man3c/ftime.3c
file path=usr/share/man/man3c/ftok.3c
file path=usr/share/man/man3c/ftw.3c
file path=usr/share/man/man3c/fwide.3c
file path=usr/share/man/man3c/fwprintf.3c
file path=usr/share/man/man3c/fwrite.3c
file path=usr/share/man/man3c/fwscanf.3c
file path=usr/share/man/man3c/get_nprocs.3c
file path=usr/share/man/man3c/getcpuid.3c
file path=usr/share/man/man3c/getcwd.3c
file path=usr/share/man/man3c/getdate.3c
file path=usr/share/man/man3c/getdtablesize.3c
file path=usr/share/man/man3c/getentropy.3c
file path=usr/share/man/man3c/getenv.3c
file path=usr/share/man/man3c/getexecname.3c
file path=usr/share/man/man3c/getgrnam.3c
file path=usr/share/man/man3c/gethostid.3c
file path=usr/share/man/man3c/gethostname.3c
file path=usr/share/man/man3c/gethrtime.3c
file path=usr/share/man/man3c/getline.3c
file path=usr/share/man/man3c/getloadavg.3c
file path=usr/share/man/man3c/getlogin.3c
file path=usr/share/man/man3c/getmntent.3c
file path=usr/share/man/man3c/getnetgrent.3c
file path=usr/share/man/man3c/getopt.3c
file path=usr/share/man/man3c/getpagesize.3c
file path=usr/share/man/man3c/getpagesizes.3c
file path=usr/share/man/man3c/getpass.3c
file path=usr/share/man/man3c/getpeerucred.3c
file path=usr/share/man/man3c/getpriority.3c
file path=usr/share/man/man3c/getprogname.3c
file path=usr/share/man/man3c/getpw.3c
file path=usr/share/man/man3c/getpwnam.3c
file path=usr/share/man/man3c/getrusage.3c
file path=usr/share/man/man3c/gets.3c
file path=usr/share/man/man3c/getspnam.3c
file path=usr/share/man/man3c/getsubopt.3c
file path=usr/share/man/man3c/gettext.3c
file path=usr/share/man/man3c/gettimeofday.3c
file path=usr/share/man/man3c/gettxt.3c
file path=usr/share/man/man3c/getusershell.3c
file path=usr/share/man/man3c/getutent.3c
file path=usr/share/man/man3c/getutxent.3c
file path=usr/share/man/man3c/getvfsent.3c
file path=usr/share/man/man3c/getwc.3c
file path=usr/share/man/man3c/getwchar.3c
file path=usr/share/man/man3c/getwd.3c
file path=usr/share/man/man3c/getwidth.3c
file path=usr/share/man/man3c/getws.3c
file path=usr/share/man/man3c/getzoneid.3c
file path=usr/share/man/man3c/glob.3c
file path=usr/share/man/man3c/grantpt.3c
file path=usr/share/man/man3c/hsearch.3c
file path=usr/share/man/man3c/iconv.3c
file path=usr/share/man/man3c/iconv_close.3c
file path=usr/share/man/man3c/iconv_open.3c
file path=usr/share/man/man3c/imaxabs.3c
file path=usr/share/man/man3c/imaxdiv.3c
file path=usr/share/man/man3c/index.3c
file path=usr/share/man/man3c/initgroups.3c
file path=usr/share/man/man3c/insque.3c
file path=usr/share/man/man3c/is_system_labeled.3c
file path=usr/share/man/man3c/isaexec.3c
file path=usr/share/man/man3c/isastream.3c
file path=usr/share/man/man3c/isatty.3c
file path=usr/share/man/man3c/isnand.3c
file path=usr/share/man/man3c/iswalpha.3c
file path=usr/share/man/man3c/iswctype.3c
file path=usr/share/man/man3c/killpg.3c
file path=usr/share/man/man3c/lckpwdf.3c
file path=usr/share/man/man3c/lfmt.3c
file path=usr/share/man/man3c/lio_listio.3c
file path=usr/share/man/man3c/localeconv.3c
file path=usr/share/man/man3c/lockf.3c
file path=usr/share/man/man3c/lsearch.3c
file path=usr/share/man/man3c/madvise.3c
file path=usr/share/man/man3c/makecontext.3c
file path=usr/share/man/man3c/makedev.3c
file path=usr/share/man/man3c/malloc.3c
file path=usr/share/man/man3c/mblen.3c
file path=usr/share/man/man3c/mbrlen.3c
file path=usr/share/man/man3c/mbrtowc.3c
file path=usr/share/man/man3c/mbsinit.3c
file path=usr/share/man/man3c/mbsrtowcs.3c
file path=usr/share/man/man3c/mbstowcs.3c
file path=usr/share/man/man3c/mbtowc.3c
file path=usr/share/man/man3c/membar_ops.3c
file path=usr/share/man/man3c/memory.3c
file path=usr/share/man/man3c/mkfifo.3c
file path=usr/share/man/man3c/mkstemp.3c
file path=usr/share/man/man3c/mktemp.3c
file path=usr/share/man/man3c/mktime.3c
file path=usr/share/man/man3c/mlock.3c
file path=usr/share/man/man3c/mlockall.3c
file path=usr/share/man/man3c/monitor.3c
file path=usr/share/man/man3c/mq_close.3c
file path=usr/share/man/man3c/mq_getattr.3c
file path=usr/share/man/man3c/mq_notify.3c
file path=usr/share/man/man3c/mq_open.3c
file path=usr/share/man/man3c/mq_receive.3c
file path=usr/share/man/man3c/mq_send.3c
file path=usr/share/man/man3c/mq_setattr.3c
file path=usr/share/man/man3c/mq_unlink.3c
file path=usr/share/man/man3c/msync.3c
file path=usr/share/man/man3c/mtx.3c
file path=usr/share/man/man3c/mutex_init.3c
file path=usr/share/man/man3c/nanosleep.3c
file path=usr/share/man/man3c/ndbm.3c
file path=usr/share/man/man3c/newlocale.3c
file path=usr/share/man/man3c/nl_langinfo.3c
file path=usr/share/man/man3c/offsetof.3c
file path=usr/share/man/man3c/opendir.3c
file path=usr/share/man/man3c/perror.3c
file path=usr/share/man/man3c/pfmt.3c
file path=usr/share/man/man3c/plock.3c
file path=usr/share/man/man3c/popen.3c
file path=usr/share/man/man3c/port_alert.3c
file path=usr/share/man/man3c/port_associate.3c
file path=usr/share/man/man3c/port_create.3c
file path=usr/share/man/man3c/port_get.3c
file path=usr/share/man/man3c/port_send.3c
file path=usr/share/man/man3c/posix_fadvise.3c
file path=usr/share/man/man3c/posix_fallocate.3c
file path=usr/share/man/man3c/posix_madvise.3c
file path=usr/share/man/man3c/posix_memalign.3c
file path=usr/share/man/man3c/posix_openpt.3c
file path=usr/share/man/man3c/posix_spawn.3c
file path=usr/share/man/man3c/posix_spawn_file_actions_addclose.3c
file path=usr/share/man/man3c/posix_spawn_file_actions_addclosefrom_np.3c
file path=usr/share/man/man3c/posix_spawn_file_actions_adddup2.3c
file path=usr/share/man/man3c/posix_spawn_file_actions_destroy.3c
file path=usr/share/man/man3c/posix_spawn_pipe_np.3c
file path=usr/share/man/man3c/posix_spawnattr_destroy.3c
file path=usr/share/man/man3c/posix_spawnattr_getflags.3c
file path=usr/share/man/man3c/posix_spawnattr_getpgroup.3c
file path=usr/share/man/man3c/posix_spawnattr_getschedparam.3c
file path=usr/share/man/man3c/posix_spawnattr_getschedpolicy.3c
file path=usr/share/man/man3c/posix_spawnattr_getsigdefault.3c
file path=usr/share/man/man3c/posix_spawnattr_getsigignore_np.3c
file path=usr/share/man/man3c/posix_spawnattr_getsigmask.3c
file path=usr/share/man/man3c/printf.3c
file path=usr/share/man/man3c/priv_addset.3c
file path=usr/share/man/man3c/priv_set.3c
file path=usr/share/man/man3c/priv_str_to_set.3c
file path=usr/share/man/man3c/pset_getloadavg.3c
file path=usr/share/man/man3c/psignal.3c
file path=usr/share/man/man3c/pthread_atfork.3c
file path=usr/share/man/man3c/pthread_attr_get_np.3c
file path=usr/share/man/man3c/pthread_attr_getdetachstate.3c
file path=usr/share/man/man3c/pthread_attr_getguardsize.3c
file path=usr/share/man/man3c/pthread_attr_getinheritsched.3c
file path=usr/share/man/man3c/pthread_attr_getschedparam.3c
file path=usr/share/man/man3c/pthread_attr_getschedpolicy.3c
file path=usr/share/man/man3c/pthread_attr_getscope.3c
file path=usr/share/man/man3c/pthread_attr_getstack.3c
file path=usr/share/man/man3c/pthread_attr_getstackaddr.3c
file path=usr/share/man/man3c/pthread_attr_getstacksize.3c
file path=usr/share/man/man3c/pthread_attr_init.3c
file path=usr/share/man/man3c/pthread_barrier_destroy.3c
file path=usr/share/man/man3c/pthread_barrier_wait.3c
file path=usr/share/man/man3c/pthread_barrierattr_destroy.3c
file path=usr/share/man/man3c/pthread_barrierattr_getpshared.3c
file path=usr/share/man/man3c/pthread_cancel.3c
file path=usr/share/man/man3c/pthread_cleanup_pop.3c
file path=usr/share/man/man3c/pthread_cleanup_push.3c
file path=usr/share/man/man3c/pthread_cond_init.3c
file path=usr/share/man/man3c/pthread_cond_signal.3c
file path=usr/share/man/man3c/pthread_cond_wait.3c
file path=usr/share/man/man3c/pthread_condattr_getclock.3c
file path=usr/share/man/man3c/pthread_condattr_getpshared.3c
file path=usr/share/man/man3c/pthread_condattr_init.3c
file path=usr/share/man/man3c/pthread_create.3c
file path=usr/share/man/man3c/pthread_detach.3c
file path=usr/share/man/man3c/pthread_equal.3c
file path=usr/share/man/man3c/pthread_exit.3c
file path=usr/share/man/man3c/pthread_getconcurrency.3c
file path=usr/share/man/man3c/pthread_getschedparam.3c
file path=usr/share/man/man3c/pthread_getspecific.3c
file path=usr/share/man/man3c/pthread_join.3c
file path=usr/share/man/man3c/pthread_key_create.3c
file path=usr/share/man/man3c/pthread_key_delete.3c
file path=usr/share/man/man3c/pthread_kill.3c
file path=usr/share/man/man3c/pthread_mutex_consistent.3c
file path=usr/share/man/man3c/pthread_mutex_getprioceiling.3c
file path=usr/share/man/man3c/pthread_mutex_init.3c
file path=usr/share/man/man3c/pthread_mutex_lock.3c
file path=usr/share/man/man3c/pthread_mutex_timedlock.3c
file path=usr/share/man/man3c/pthread_mutexattr_getprioceiling.3c
file path=usr/share/man/man3c/pthread_mutexattr_getprotocol.3c
file path=usr/share/man/man3c/pthread_mutexattr_getpshared.3c
file path=usr/share/man/man3c/pthread_mutexattr_getrobust.3c
file path=usr/share/man/man3c/pthread_mutexattr_gettype.3c
file path=usr/share/man/man3c/pthread_mutexattr_init.3c
file path=usr/share/man/man3c/pthread_once.3c
file path=usr/share/man/man3c/pthread_rwlock_init.3c
file path=usr/share/man/man3c/pthread_rwlock_rdlock.3c
file path=usr/share/man/man3c/pthread_rwlock_timedrdlock.3c
file path=usr/share/man/man3c/pthread_rwlock_timedwrlock.3c
file path=usr/share/man/man3c/pthread_rwlock_unlock.3c
file path=usr/share/man/man3c/pthread_rwlock_wrlock.3c
file path=usr/share/man/man3c/pthread_rwlockattr_getpshared.3c
file path=usr/share/man/man3c/pthread_rwlockattr_init.3c
file path=usr/share/man/man3c/pthread_self.3c
file path=usr/share/man/man3c/pthread_setcancelstate.3c
file path=usr/share/man/man3c/pthread_setcanceltype.3c
file path=usr/share/man/man3c/pthread_setschedprio.3c
file path=usr/share/man/man3c/pthread_sigmask.3c
file path=usr/share/man/man3c/pthread_spin_destroy.3c
file path=usr/share/man/man3c/pthread_spin_lock.3c
file path=usr/share/man/man3c/pthread_spin_unlock.3c
file path=usr/share/man/man3c/pthread_testcancel.3c
file path=usr/share/man/man3c/ptrace.3c
file path=usr/share/man/man3c/ptsname.3c
file path=usr/share/man/man3c/putenv.3c
file path=usr/share/man/man3c/putpwent.3c
file path=usr/share/man/man3c/puts.3c
file path=usr/share/man/man3c/putspent.3c
file path=usr/share/man/man3c/putws.3c
file path=usr/share/man/man3c/qsort.3c
file path=usr/share/man/man3c/quick_exit.3c
file path=usr/share/man/man3c/raise.3c
file path=usr/share/man/man3c/rand.3c
file path=usr/share/man/man3c/random.3c
file path=usr/share/man/man3c/rctl_walk.3c
file path=usr/share/man/man3c/rctlblk_set_value.3c
file path=usr/share/man/man3c/re_comp.3c
file path=usr/share/man/man3c/readdir.3c
file path=usr/share/man/man3c/realpath.3c
file path=usr/share/man/man3c/reboot.3c
file path=usr/share/man/man3c/regcmp.3c
file path=usr/share/man/man3c/regcomp.3c
file path=usr/share/man/man3c/remove.3c
file path=usr/share/man/man3c/rewind.3c
file path=usr/share/man/man3c/rewinddir.3c
file path=usr/share/man/man3c/rwlock.3c
file path=usr/share/man/man3c/scandir.3c
file path=usr/share/man/man3c/scanf.3c
file path=usr/share/man/man3c/sched_get_priority_max.3c
file path=usr/share/man/man3c/sched_getparam.3c
file path=usr/share/man/man3c/sched_getscheduler.3c
file path=usr/share/man/man3c/sched_rr_get_interval.3c
file path=usr/share/man/man3c/sched_setparam.3c
file path=usr/share/man/man3c/sched_setscheduler.3c
file path=usr/share/man/man3c/sched_yield.3c
file path=usr/share/man/man3c/schedctl_init.3c
file path=usr/share/man/man3c/seekdir.3c
file path=usr/share/man/man3c/select.3c
file path=usr/share/man/man3c/sem_close.3c
file path=usr/share/man/man3c/sem_destroy.3c
file path=usr/share/man/man3c/sem_getvalue.3c
file path=usr/share/man/man3c/sem_init.3c
file path=usr/share/man/man3c/sem_open.3c
file path=usr/share/man/man3c/sem_post.3c
file path=usr/share/man/man3c/sem_timedwait.3c
file path=usr/share/man/man3c/sem_unlink.3c
file path=usr/share/man/man3c/sem_wait.3c
file path=usr/share/man/man3c/semaphore.3c
file path=usr/share/man/man3c/setbuf.3c
file path=usr/share/man/man3c/setbuffer.3c
file path=usr/share/man/man3c/setcat.3c
file path=usr/share/man/man3c/setenv.3c
file path=usr/share/man/man3c/setjmp.3c
file path=usr/share/man/man3c/setkey.3c
file path=usr/share/man/man3c/setlabel.3c
file path=usr/share/man/man3c/setlocale.3c
file path=usr/share/man/man3c/shm_open.3c
file path=usr/share/man/man3c/shm_unlink.3c
file path=usr/share/man/man3c/sigfpe.3c
file path=usr/share/man/man3c/siginterrupt.3c
file path=usr/share/man/man3c/signal.3c
file path=usr/share/man/man3c/signalfd.3c
file path=usr/share/man/man3c/sigqueue.3c
file path=usr/share/man/man3c/sigsetops.3c
file path=usr/share/man/man3c/sigstack.3c
file path=usr/share/man/man3c/sigwaitinfo.3c
file path=usr/share/man/man3c/sleep.3c
file path=usr/share/man/man3c/smt_pause.3c
file path=usr/share/man/man3c/ssignal.3c
file path=usr/share/man/man3c/stack_getbounds.3c
file path=usr/share/man/man3c/stack_inbounds.3c
file path=usr/share/man/man3c/stack_setbounds.3c
file path=usr/share/man/man3c/stack_violation.3c
file path=usr/share/man/man3c/stdio.3c
file path=usr/share/man/man3c/str2sig.3c
file path=usr/share/man/man3c/strcoll.3c
file path=usr/share/man/man3c/strerror.3c
file path=usr/share/man/man3c/strfmon.3c
file path=usr/share/man/man3c/strftime.3c
file path=usr/share/man/man3c/string.3c
file path=usr/share/man/man3c/string_to_decimal.3c
file path=usr/share/man/man3c/strptime.3c
file path=usr/share/man/man3c/strsignal.3c
file path=usr/share/man/man3c/strtod.3c
file path=usr/share/man/man3c/strtoimax.3c
file path=usr/share/man/man3c/strtol.3c
file path=usr/share/man/man3c/strtoul.3c
file path=usr/share/man/man3c/strtows.3c
file path=usr/share/man/man3c/strxfrm.3c
file path=usr/share/man/man3c/swab.3c
file path=usr/share/man/man3c/sync_instruction_memory.3c
file path=usr/share/man/man3c/sysconf.3c
file path=usr/share/man/man3c/syslog.3c
file path=usr/share/man/man3c/system.3c
file path=usr/share/man/man3c/tcdrain.3c
file path=usr/share/man/man3c/tcflow.3c
file path=usr/share/man/man3c/tcflush.3c
file path=usr/share/man/man3c/tcgetattr.3c
file path=usr/share/man/man3c/tcgetpgrp.3c
file path=usr/share/man/man3c/tcgetsid.3c
file path=usr/share/man/man3c/tcsendbreak.3c
file path=usr/share/man/man3c/tcsetattr.3c
file path=usr/share/man/man3c/tcsetpgrp.3c
file path=usr/share/man/man3c/tell.3c
file path=usr/share/man/man3c/telldir.3c
file path=usr/share/man/man3c/termios.3c
file path=usr/share/man/man3c/thr_create.3c
file path=usr/share/man/man3c/thr_exit.3c
file path=usr/share/man/man3c/thr_getconcurrency.3c
file path=usr/share/man/man3c/thr_getprio.3c
file path=usr/share/man/man3c/thr_join.3c
file path=usr/share/man/man3c/thr_keycreate.3c
file path=usr/share/man/man3c/thr_kill.3c
file path=usr/share/man/man3c/thr_main.3c
file path=usr/share/man/man3c/thr_min_stack.3c
file path=usr/share/man/man3c/thr_self.3c
file path=usr/share/man/man3c/thr_sigsetmask.3c
file path=usr/share/man/man3c/thr_stksegment.3c
file path=usr/share/man/man3c/thr_suspend.3c
file path=usr/share/man/man3c/thr_yield.3c
file path=usr/share/man/man3c/thrd_create.3c
file path=usr/share/man/man3c/thrd_current.3c
file path=usr/share/man/man3c/thrd_detach.3c
file path=usr/share/man/man3c/thrd_equal.3c
file path=usr/share/man/man3c/thrd_exit.3c
file path=usr/share/man/man3c/thrd_join.3c
file path=usr/share/man/man3c/thrd_yield.3c
file path=usr/share/man/man3c/timer_create.3c
file path=usr/share/man/man3c/timer_delete.3c
file path=usr/share/man/man3c/timer_settime.3c
file path=usr/share/man/man3c/timeradd.3c
file path=usr/share/man/man3c/timerfd_create.3c
file path=usr/share/man/man3c/timespec_get.3c
file path=usr/share/man/man3c/tmpfile.3c
file path=usr/share/man/man3c/tmpnam.3c
file path=usr/share/man/man3c/toascii.3c
file path=usr/share/man/man3c/tolower.3c
file path=usr/share/man/man3c/toupper.3c
file path=usr/share/man/man3c/towlower.3c
file path=usr/share/man/man3c/towupper.3c
file path=usr/share/man/man3c/truncate.3c
file path=usr/share/man/man3c/tsearch.3c
file path=usr/share/man/man3c/tss.3c
file path=usr/share/man/man3c/ttyname.3c
file path=usr/share/man/man3c/ttyslot.3c
file path=usr/share/man/man3c/u8_strcmp.3c
file path=usr/share/man/man3c/u8_textprep_str.3c
file path=usr/share/man/man3c/u8_validate.3c
file path=usr/share/man/man3c/ualarm.3c
file path=usr/share/man/man3c/uconv_u16tou32.3c
file path=usr/share/man/man3c/ucred.3c
file path=usr/share/man/man3c/ungetc.3c
file path=usr/share/man/man3c/ungetwc.3c
file path=usr/share/man/man3c/unlockpt.3c
file path=usr/share/man/man3c/unsetenv.3c
file path=usr/share/man/man3c/uselocale.3c
file path=usr/share/man/man3c/usleep.3c
file path=usr/share/man/man3c/vfwprintf.3c
file path=usr/share/man/man3c/vlfmt.3c
file path=usr/share/man/man3c/vpfmt.3c
file path=usr/share/man/man3c/vprintf.3c
file path=usr/share/man/man3c/vsyslog.3c
file path=usr/share/man/man3c/wait.3c
file path=usr/share/man/man3c/wait3.3c
file path=usr/share/man/man3c/waitpid.3c
file path=usr/share/man/man3c/walkcontext.3c
file path=usr/share/man/man3c/wcpcpy.3c
file path=usr/share/man/man3c/wcrtomb.3c
file path=usr/share/man/man3c/wcscasecmp.3c
file path=usr/share/man/man3c/wcscoll.3c
file path=usr/share/man/man3c/wcsdup.3c
file path=usr/share/man/man3c/wcsftime.3c
file path=usr/share/man/man3c/wcslen.3c
file path=usr/share/man/man3c/wcsrtombs.3c
file path=usr/share/man/man3c/wcsstr.3c
file path=usr/share/man/man3c/wcstod.3c
file path=usr/share/man/man3c/wcstoimax.3c
file path=usr/share/man/man3c/wcstol.3c
file path=usr/share/man/man3c/wcstombs.3c
file path=usr/share/man/man3c/wcstoul.3c
file path=usr/share/man/man3c/wcstring.3c
file path=usr/share/man/man3c/wcswidth.3c
file path=usr/share/man/man3c/wcsxfrm.3c
file path=usr/share/man/man3c/wctob.3c
file path=usr/share/man/man3c/wctomb.3c
file path=usr/share/man/man3c/wctrans.3c
file path=usr/share/man/man3c/wctype.3c
file path=usr/share/man/man3c/wcwidth.3c
file path=usr/share/man/man3c/wmemchr.3c
file path=usr/share/man/man3c/wmemcmp.3c
file path=usr/share/man/man3c/wmemcpy.3c
file path=usr/share/man/man3c/wmemmove.3c
file path=usr/share/man/man3c/wmemset.3c
file path=usr/share/man/man3c/wordexp.3c
file path=usr/share/man/man3c/wsprintf.3c
file path=usr/share/man/man3c/wsscanf.3c
file path=usr/share/man/man3c/wstring.3c
link path=usr/share/man/man3c/FD_CLR.3c target=select.3c
link path=usr/share/man/man3c/FD_ISSET.3c target=select.3c
link path=usr/share/man/man3c/FD_SET.3c target=select.3c
link path=usr/share/man/man3c/FD_ZERO.3c target=select.3c
link path=usr/share/man/man3c/__flbf.3c target=__fbufsize.3c
link path=usr/share/man/man3c/__fpending.3c target=__fbufsize.3c
link path=usr/share/man/man3c/__fpurge.3c target=__fbufsize.3c
link path=usr/share/man/man3c/__freadable.3c target=__fbufsize.3c
link path=usr/share/man/man3c/__freading.3c target=__fbufsize.3c
link path=usr/share/man/man3c/__fsetlocking.3c target=__fbufsize.3c
link path=usr/share/man/man3c/__fwritable.3c target=__fbufsize.3c
link path=usr/share/man/man3c/__fwriting.3c target=__fbufsize.3c
link path=usr/share/man/man3c/_edata.3c target=end.3c
link path=usr/share/man/man3c/_end.3c target=end.3c
link path=usr/share/man/man3c/_etext.3c target=end.3c
link path=usr/share/man/man3c/_exithandle.3c target=exit.3c
link path=usr/share/man/man3c/_flushlbf.3c target=__fbufsize.3c
link path=usr/share/man/man3c/_setjmp.3c target=_longjmp.3c
link path=usr/share/man/man3c/addrtosymstr.3c target=walkcontext.3c
link path=usr/share/man/man3c/aiowrite.3c target=aioread.3c
link path=usr/share/man/man3c/alloca.3c target=malloc.3c
link path=usr/share/man/man3c/alphasort.3c target=scandir.3c
link path=usr/share/man/man3c/arc4random_buf.3c target=arc4random.3c
link path=usr/share/man/man3c/arc4random_uniform.3c target=arc4random.3c
link path=usr/share/man/man3c/ascftime.3c target=strftime.3c
link path=usr/share/man/man3c/asctime.3c target=ctime.3c
link path=usr/share/man/man3c/asctime_r.3c target=ctime.3c
link path=usr/share/man/man3c/asprintf.3c target=printf.3c
link path=usr/share/man/man3c/at_quick_exit.3c target=quick_exit.3c
link path=usr/share/man/man3c/atof.3c target=strtod.3c
link path=usr/share/man/man3c/atoi.3c target=strtol.3c
link path=usr/share/man/man3c/atol.3c target=strtol.3c
link path=usr/share/man/man3c/atoll.3c target=strtol.3c
link path=usr/share/man/man3c/atomic_add_16.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_16_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_32.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_32_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_64.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_64_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_8.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_8_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_char.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_char_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_int.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_int_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_long.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_long_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_ptr.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_ptr_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_short.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_add_short_nv.3c target=atomic_add.3c
link path=usr/share/man/man3c/atomic_and_16.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_16_nv.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_32.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_32_nv.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_64.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_64_nv.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_8.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_8_nv.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_uchar.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_uchar_nv.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_uint.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_uint_nv.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_ulong.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_ulong_nv.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_ushort.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_and_ushort_nv.3c target=atomic_and.3c
link path=usr/share/man/man3c/atomic_cas_16.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_cas_32.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_cas_64.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_cas_8.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_cas_ptr.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_cas_uchar.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_cas_uint.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_cas_ulong.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_cas_ushort.3c target=atomic_cas.3c
link path=usr/share/man/man3c/atomic_clear_long_excl.3c target=atomic_bits.3c
link path=usr/share/man/man3c/atomic_dec_16.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_16_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_32.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_32_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_64.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_64_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_8.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_8_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_ptr.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_ptr_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_uchar.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_uchar_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_uint.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_uint_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_ulong.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_ulong_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_ushort.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_dec_ushort_nv.3c target=atomic_dec.3c
link path=usr/share/man/man3c/atomic_inc_16.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_16_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_32.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_32_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_64.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_64_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_8.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_8_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_ptr.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_ptr_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_uchar.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_uchar_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_uint.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_uint_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_ulong.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_ulong_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_ushort.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_inc_ushort_nv.3c target=atomic_inc.3c
link path=usr/share/man/man3c/atomic_or_16.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_16_nv.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_32.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_32_nv.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_64.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_64_nv.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_8.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_8_nv.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_uchar.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_uchar_nv.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_uint.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_uint_nv.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_ulong.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_ulong_nv.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_ushort.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_or_ushort_nv.3c target=atomic_or.3c
link path=usr/share/man/man3c/atomic_set_long_excl.3c target=atomic_bits.3c
link path=usr/share/man/man3c/atomic_swap_16.3c target=atomic_swap.3c
link path=usr/share/man/man3c/atomic_swap_32.3c target=atomic_swap.3c
link path=usr/share/man/man3c/atomic_swap_64.3c target=atomic_swap.3c
link path=usr/share/man/man3c/atomic_swap_8.3c target=atomic_swap.3c
link path=usr/share/man/man3c/atomic_swap_ptr.3c target=atomic_swap.3c
link path=usr/share/man/man3c/atomic_swap_uchar.3c target=atomic_swap.3c
link path=usr/share/man/man3c/atomic_swap_uint.3c target=atomic_swap.3c
link path=usr/share/man/man3c/atomic_swap_ulong.3c target=atomic_swap.3c
link path=usr/share/man/man3c/atomic_swap_ushort.3c target=atomic_swap.3c
link path=usr/share/man/man3c/backtrace.3c target=walkcontext.3c
link path=usr/share/man/man3c/backtrace_symbols.3c target=walkcontext.3c
link path=usr/share/man/man3c/backtrace_symbols_fd.3c target=walkcontext.3c
link path=usr/share/man/man3c/bcmp.3c target=bstring.3c
link path=usr/share/man/man3c/bcopy.3c target=bstring.3c
link path=usr/share/man/man3c/be16toh.3c target=endian.3c
link path=usr/share/man/man3c/be32toh.3c target=endian.3c
link path=usr/share/man/man3c/be64toh.3c target=endian.3c
link path=usr/share/man/man3c/betoh16.3c target=endian.3c
link path=usr/share/man/man3c/betoh32.3c target=endian.3c
link path=usr/share/man/man3c/betoh64.3c target=endian.3c
link path=usr/share/man/man3c/bind_textdomain_codeset.3c target=gettext.3c
link path=usr/share/man/man3c/bindtextdomain.3c target=gettext.3c
link path=usr/share/man/man3c/btowc_l.3c target=btowc.3c
link path=usr/share/man/man3c/bzero.3c target=bstring.3c
link path=usr/share/man/man3c/calloc.3c target=malloc.3c
link path=usr/share/man/man3c/canonicalize_file_name.3c target=realpath.3c
link path=usr/share/man/man3c/catclose.3c target=catopen.3c
link path=usr/share/man/man3c/cfgetospeed.3c target=cfgetispeed.3c
link path=usr/share/man/man3c/cfsetospeed.3c target=cfsetispeed.3c
link path=usr/share/man/man3c/cftime.3c target=strftime.3c
link path=usr/share/man/man3c/clearerr.3c target=ferror.3c
link path=usr/share/man/man3c/clock_getres.3c target=clock_settime.3c
link path=usr/share/man/man3c/clock_gettime.3c target=clock_settime.3c
link path=usr/share/man/man3c/closelog.3c target=syslog.3c
link path=usr/share/man/man3c/cnd_broadcast.3c target=cnd.3c
link path=usr/share/man/man3c/cnd_destroy.3c target=cnd.3c
link path=usr/share/man/man3c/cnd_init.3c target=cnd.3c
link path=usr/share/man/man3c/cnd_signal.3c target=cnd.3c
link path=usr/share/man/man3c/cnd_timedwait.3c target=cnd.3c
link path=usr/share/man/man3c/cnd_wait.3c target=cnd.3c
link path=usr/share/man/man3c/cond_broadcast.3c target=cond_init.3c
link path=usr/share/man/man3c/cond_destroy.3c target=cond_init.3c
link path=usr/share/man/man3c/cond_reltimedwait.3c target=cond_init.3c
link path=usr/share/man/man3c/cond_signal.3c target=cond_init.3c
link path=usr/share/man/man3c/cond_timedwait.3c target=cond_init.3c
link path=usr/share/man/man3c/cond_wait.3c target=cond_init.3c
link path=usr/share/man/man3c/csetcol.3c target=cset.3c
link path=usr/share/man/man3c/csetlen.3c target=cset.3c
link path=usr/share/man/man3c/csetno.3c target=cset.3c
link path=usr/share/man/man3c/ctermid_r.3c target=ctermid.3c
link path=usr/share/man/man3c/ctime_r.3c target=ctime.3c
link path=usr/share/man/man3c/dbm_clearerr.3c target=ndbm.3c
link path=usr/share/man/man3c/dbm_close.3c target=ndbm.3c
link path=usr/share/man/man3c/dbm_delete.3c target=ndbm.3c
link path=usr/share/man/man3c/dbm_error.3c target=ndbm.3c
link path=usr/share/man/man3c/dbm_fetch.3c target=ndbm.3c
link path=usr/share/man/man3c/dbm_firstkey.3c target=ndbm.3c
link path=usr/share/man/man3c/dbm_nextkey.3c target=ndbm.3c
link path=usr/share/man/man3c/dbm_open.3c target=ndbm.3c
link path=usr/share/man/man3c/dbm_store.3c target=ndbm.3c
link path=usr/share/man/man3c/dcgettext.3c target=gettext.3c
link path=usr/share/man/man3c/dcngettext.3c target=gettext.3c
link path=usr/share/man/man3c/decimal_to_double.3c \
    target=decimal_to_floating.3c
link path=usr/share/man/man3c/decimal_to_extended.3c \
    target=decimal_to_floating.3c
link path=usr/share/man/man3c/decimal_to_quadruple.3c \
    target=decimal_to_floating.3c
link path=usr/share/man/man3c/decimal_to_single.3c \
    target=decimal_to_floating.3c
link path=usr/share/man/man3c/dgettext.3c target=gettext.3c
link path=usr/share/man/man3c/dladdr1.3c target=dladdr.3c
link path=usr/share/man/man3c/dlmopen.3c target=dlopen.3c
link path=usr/share/man/man3c/dngettext.3c target=gettext.3c
link path=usr/share/man/man3c/door_setparam.3c target=door_getparam.3c
link path=usr/share/man/man3c/door_unbind.3c target=door_bind.3c
link path=usr/share/man/man3c/double_to_decimal.3c \
    target=floating_to_decimal.3c
link path=usr/share/man/man3c/dup3.3c target=dup2.3c
link path=usr/share/man/man3c/duplocale.3c target=newlocale.3c
link path=usr/share/man/man3c/edata.3c target=end.3c
link path=usr/share/man/man3c/endgrent.3c target=getgrnam.3c
link path=usr/share/man/man3c/endnetgrent.3c target=getnetgrent.3c
link path=usr/share/man/man3c/endpwent.3c target=getpwnam.3c
link path=usr/share/man/man3c/endspent.3c target=getspnam.3c
link path=usr/share/man/man3c/endusershell.3c target=getusershell.3c
link path=usr/share/man/man3c/endutent.3c target=getutent.3c
link path=usr/share/man/man3c/endutxent.3c target=getutxent.3c
link path=usr/share/man/man3c/epoll_create1.3c target=epoll_create.3c
link path=usr/share/man/man3c/epoll_pwait.3c target=epoll_wait.3c
link path=usr/share/man/man3c/erand48.3c target=drand48.3c
link path=usr/share/man/man3c/errno.3c target=perror.3c
link path=usr/share/man/man3c/errx.3c target=err.3c
link path=usr/share/man/man3c/etext.3c target=end.3c
link path=usr/share/man/man3c/euccol.3c target=euclen.3c
link path=usr/share/man/man3c/eucscol.3c target=euclen.3c
link path=usr/share/man/man3c/explicit_bzero.3c target=bstring.3c
link path=usr/share/man/man3c/extended_to_decimal.3c \
    target=floating_to_decimal.3c
link path=usr/share/man/man3c/fconvert.3c target=econvert.3c
link path=usr/share/man/man3c/fcvt.3c target=ecvt.3c
link path=usr/share/man/man3c/fdopendir.3c target=opendir.3c
link path=usr/share/man/man3c/fdwalk.3c target=closefrom.3c
link path=usr/share/man/man3c/feof.3c target=ferror.3c
link path=usr/share/man/man3c/ffsl.3c target=ffs.3c
link path=usr/share/man/man3c/ffsll.3c target=ffs.3c
link path=usr/share/man/man3c/fgetgrent.3c target=getgrnam.3c
link path=usr/share/man/man3c/fgetgrent_r.3c target=getgrnam.3c
link path=usr/share/man/man3c/fgetpwent.3c target=getpwnam.3c
link path=usr/share/man/man3c/fgetpwent_r.3c target=getpwnam.3c
link path=usr/share/man/man3c/fgets.3c target=gets.3c
link path=usr/share/man/man3c/fgetspent.3c target=getspnam.3c
link path=usr/share/man/man3c/fgetspent_r.3c target=getspnam.3c
link path=usr/share/man/man3c/fgetwc_l.3c target=fgetwc.3c
link path=usr/share/man/man3c/fgetws.3c target=getws.3c
link path=usr/share/man/man3c/file_to_decimal.3c target=string_to_decimal.3c
link path=usr/share/man/man3c/fileno.3c target=ferror.3c
link path=usr/share/man/man3c/finite.3c target=isnand.3c
link path=usr/share/man/man3c/fls.3c target=ffs.3c
link path=usr/share/man/man3c/flsl.3c target=ffs.3c
link path=usr/share/man/man3c/flsll.3c target=ffs.3c
link path=usr/share/man/man3c/fpclass.3c target=isnand.3c
link path=usr/share/man/man3c/fpgetmask.3c target=fpgetround.3c
link path=usr/share/man/man3c/fpgetsticky.3c target=fpgetround.3c
link path=usr/share/man/man3c/fprintf.3c target=printf.3c
link path=usr/share/man/man3c/fpsetmask.3c target=fpgetround.3c
link path=usr/share/man/man3c/fpsetround.3c target=fpgetround.3c
link path=usr/share/man/man3c/fpsetsticky.3c target=fpgetround.3c
link path=usr/share/man/man3c/fputs.3c target=puts.3c
link path=usr/share/man/man3c/free.3c target=malloc.3c
link path=usr/share/man/man3c/freelocale.3c target=newlocale.3c
link path=usr/share/man/man3c/fscanf.3c target=scanf.3c
link path=usr/share/man/man3c/fseeko.3c target=fseek.3c
link path=usr/share/man/man3c/fsetattr.3c target=fgetattr.3c
link path=usr/share/man/man3c/ftello.3c target=ftell.3c
link path=usr/share/man/man3c/ftruncate.3c target=truncate.3c
link path=usr/share/man/man3c/ftrylockfile.3c target=flockfile.3c
link path=usr/share/man/man3c/func_to_decimal.3c target=string_to_decimal.3c
link path=usr/share/man/man3c/funlockfile.3c target=flockfile.3c
link path=usr/share/man/man3c/gconvert.3c target=econvert.3c
link path=usr/share/man/man3c/gcvt.3c target=ecvt.3c
link path=usr/share/man/man3c/get_nprocs_conf.3c target=get_nprocs.3c
link path=usr/share/man/man3c/getattrat.3c target=fgetattr.3c
link path=usr/share/man/man3c/getc.3c target=fgetc.3c
link path=usr/share/man/man3c/getc_unlocked.3c target=fgetc.3c
link path=usr/share/man/man3c/getchar.3c target=fgetc.3c
link path=usr/share/man/man3c/getchar_unlocked.3c target=fgetc.3c
link path=usr/share/man/man3c/getdelim.3c target=getline.3c
link path=usr/share/man/man3c/getextmntent.3c target=getmntent.3c
link path=usr/share/man/man3c/getgrent.3c target=getgrnam.3c
link path=usr/share/man/man3c/getgrent_r.3c target=getgrnam.3c
link path=usr/share/man/man3c/getgrgid.3c target=getgrnam.3c
link path=usr/share/man/man3c/getgrgid_r.3c target=getgrnam.3c
link path=usr/share/man/man3c/getgrnam_r.3c target=getgrnam.3c
link path=usr/share/man/man3c/gethomelgroup.3c target=getcpuid.3c
link path=usr/share/man/man3c/gethrvtime.3c target=gethrtime.3c
link path=usr/share/man/man3c/getlogin_r.3c target=getlogin.3c
link path=usr/share/man/man3c/getmntany.3c target=getmntent.3c
link path=usr/share/man/man3c/getnetgrent_r.3c target=getnetgrent.3c
link path=usr/share/man/man3c/getpassphrase.3c target=getpass.3c
link path=usr/share/man/man3c/getpwent.3c target=getpwnam.3c
link path=usr/share/man/man3c/getpwent_r.3c target=getpwnam.3c
link path=usr/share/man/man3c/getpwnam_r.3c target=getpwnam.3c
link path=usr/share/man/man3c/getpwuid.3c target=getpwnam.3c
link path=usr/share/man/man3c/getpwuid_r.3c target=getpwnam.3c
link path=usr/share/man/man3c/getspent.3c target=getspnam.3c
link path=usr/share/man/man3c/getspent_r.3c target=getspnam.3c
link path=usr/share/man/man3c/getspnam_r.3c target=getspnam.3c
link path=usr/share/man/man3c/getutid.3c target=getutent.3c
link path=usr/share/man/man3c/getutline.3c target=getutent.3c
link path=usr/share/man/man3c/getutmp.3c target=getutxent.3c
link path=usr/share/man/man3c/getutmpx.3c target=getutxent.3c
link path=usr/share/man/man3c/getutxid.3c target=getutxent.3c
link path=usr/share/man/man3c/getutxline.3c target=getutxent.3c
link path=usr/share/man/man3c/getvfsany.3c target=getvfsent.3c
link path=usr/share/man/man3c/getvfsfile.3c target=getvfsent.3c
link path=usr/share/man/man3c/getvfsspec.3c target=getvfsent.3c
link path=usr/share/man/man3c/getw.3c target=fgetc.3c
link path=usr/share/man/man3c/getwc_l.3c target=getwc.3c
link path=usr/share/man/man3c/getwchar_l.3c target=getwchar.3c
link path=usr/share/man/man3c/getzoneidbyname.3c target=getzoneid.3c
link path=usr/share/man/man3c/getzonenamebyid.3c target=getzoneid.3c
link path=usr/share/man/man3c/globfree.3c target=glob.3c
link path=usr/share/man/man3c/gmtime.3c target=ctime.3c
link path=usr/share/man/man3c/gmtime_r.3c target=ctime.3c
link path=usr/share/man/man3c/gsignal.3c target=ssignal.3c
link path=usr/share/man/man3c/hasmntopt.3c target=getmntent.3c
link path=usr/share/man/man3c/hcreate.3c target=hsearch.3c
link path=usr/share/man/man3c/hdestroy.3c target=hsearch.3c
link path=usr/share/man/man3c/htobe16.3c target=endian.3c
link path=usr/share/man/man3c/htobe32.3c target=endian.3c
link path=usr/share/man/man3c/htobe64.3c target=endian.3c
link path=usr/share/man/man3c/htole16.3c target=endian.3c
link path=usr/share/man/man3c/htole32.3c target=endian.3c
link path=usr/share/man/man3c/htole64.3c target=endian.3c
link path=usr/share/man/man3c/initstate.3c target=random.3c
link path=usr/share/man/man3c/innetgr.3c target=getnetgrent.3c
link path=usr/share/man/man3c/isalnum.3c target=ctype.3c
link path=usr/share/man/man3c/isalnum_l.3c target=ctype.3c
link path=usr/share/man/man3c/isalpha.3c target=ctype.3c
link path=usr/share/man/man3c/isalpha_l.3c target=ctype.3c
link path=usr/share/man/man3c/isascii.3c target=ctype.3c
link path=usr/share/man/man3c/isblank.3c target=ctype.3c
link path=usr/share/man/man3c/isblank_l.3c target=ctype.3c
link path=usr/share/man/man3c/iscntrl.3c target=ctype.3c
link path=usr/share/man/man3c/iscntrl_l.3c target=ctype.3c
link path=usr/share/man/man3c/isdigit.3c target=ctype.3c
link path=usr/share/man/man3c/isdigit_l.3c target=ctype.3c
link path=usr/share/man/man3c/isenglish.3c target=iswalpha.3c
link path=usr/share/man/man3c/isgraph.3c target=ctype.3c
link path=usr/share/man/man3c/isgraph_l.3c target=ctype.3c
link path=usr/share/man/man3c/isideogram.3c target=iswalpha.3c
link path=usr/share/man/man3c/islower.3c target=ctype.3c
link path=usr/share/man/man3c/islower_l.3c target=ctype.3c
link path=usr/share/man/man3c/isnanf.3c target=isnand.3c
link path=usr/share/man/man3c/isnumber.3c target=iswalpha.3c
link path=usr/share/man/man3c/isphonogram.3c target=iswalpha.3c
link path=usr/share/man/man3c/isprint.3c target=ctype.3c
link path=usr/share/man/man3c/isprint_l.3c target=ctype.3c
link path=usr/share/man/man3c/ispunct.3c target=ctype.3c
link path=usr/share/man/man3c/ispunct_l.3c target=ctype.3c
link path=usr/share/man/man3c/isspace.3c target=ctype.3c
link path=usr/share/man/man3c/isspace_l.3c target=ctype.3c
link path=usr/share/man/man3c/isspecial.3c target=iswalpha.3c
link path=usr/share/man/man3c/isupper.3c target=ctype.3c
link path=usr/share/man/man3c/isupper_l.3c target=ctype.3c
link path=usr/share/man/man3c/iswalnum.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswalnum_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswalpha_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswascii.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswblank.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswblank_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswcntrl.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswcntrl_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswctype_l.3c target=iswctype.3c
link path=usr/share/man/man3c/iswdigit.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswdigit_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswgraph.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswgraph_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswhexnumber.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswhexnumber_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswideogram.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswideogram_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswlower.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswlower_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswnumber.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswnumber_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswphonogram.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswphonogram_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswprint.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswprint_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswpunct.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswpunct_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswspace.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswspace_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswspecial.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswspecial_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswupper.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswupper_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswxdigit.3c target=iswalpha.3c
link path=usr/share/man/man3c/iswxdigit_l.3c target=iswalpha.3c
link path=usr/share/man/man3c/isxdigit.3c target=ctype.3c
link path=usr/share/man/man3c/isxdigit_l.3c target=ctype.3c
link path=usr/share/man/man3c/jrand48.3c target=drand48.3c
link path=usr/share/man/man3c/l64a.3c target=a64l.3c
link path=usr/share/man/man3c/labs.3c target=abs.3c
link path=usr/share/man/man3c/lcong48.3c target=drand48.3c
link path=usr/share/man/man3c/ldiv.3c target=div.3c
link path=usr/share/man/man3c/le16toh.3c target=endian.3c
link path=usr/share/man/man3c/le32toh.3c target=endian.3c
link path=usr/share/man/man3c/le64toh.3c target=endian.3c
link path=usr/share/man/man3c/letoh16.3c target=endian.3c
link path=usr/share/man/man3c/letoh32.3c target=endian.3c
link path=usr/share/man/man3c/letoh64.3c target=endian.3c
link path=usr/share/man/man3c/lfind.3c target=lsearch.3c
link path=usr/share/man/man3c/llabs.3c target=abs.3c
link path=usr/share/man/man3c/lldiv.3c target=div.3c
link path=usr/share/man/man3c/lltostr.3c target=strtol.3c
link path=usr/share/man/man3c/localtime.3c target=ctime.3c
link path=usr/share/man/man3c/localtime_r.3c target=ctime.3c
link path=usr/share/man/man3c/longjmp.3c target=setjmp.3c
link path=usr/share/man/man3c/lrand48.3c target=drand48.3c
link path=usr/share/man/man3c/major.3c target=makedev.3c
link path=usr/share/man/man3c/mblen_l.3c target=mblen.3c
link path=usr/share/man/man3c/mbrlen_l.3c target=mbrlen.3c
link path=usr/share/man/man3c/mbrtowc_l.3c target=mbrtowc.3c
link path=usr/share/man/man3c/mbsinit_l.3c target=mbsinit.3c
link path=usr/share/man/man3c/mbsnrtowcs.3c target=mbsrtowcs.3c
link path=usr/share/man/man3c/mbsnrtowcs_l.3c target=mbsrtowcs.3c
link path=usr/share/man/man3c/mbsrtowcs_l.3c target=mbsrtowcs.3c
link path=usr/share/man/man3c/mbstowcs_l.3c target=mbstowcs.3c
link path=usr/share/man/man3c/mbtowc_l.3c target=mbtowc.3c
link path=usr/share/man/man3c/memalign.3c target=malloc.3c
link path=usr/share/man/man3c/membar_consumer.3c target=membar_ops.3c
link path=usr/share/man/man3c/membar_enter.3c target=membar_ops.3c
link path=usr/share/man/man3c/membar_exit.3c target=membar_ops.3c
link path=usr/share/man/man3c/membar_producer.3c target=membar_ops.3c
link path=usr/share/man/man3c/memccpy.3c target=memory.3c
link path=usr/share/man/man3c/memchr.3c target=memory.3c
link path=usr/share/man/man3c/memcmp.3c target=memory.3c
link path=usr/share/man/man3c/memcpy.3c target=memory.3c
link path=usr/share/man/man3c/memmem.3c target=memory.3c
link path=usr/share/man/man3c/memmove.3c target=memory.3c
link path=usr/share/man/man3c/memset.3c target=memory.3c
link path=usr/share/man/man3c/minor.3c target=makedev.3c
link path=usr/share/man/man3c/mkdtemp.3c target=mkstemp.3c
link path=usr/share/man/man3c/mkfifoat.3c target=mkfifo.3c
link path=usr/share/man/man3c/mkostemp.3c target=mkstemp.3c
link path=usr/share/man/man3c/mkostemps.3c target=mkstemp.3c
link path=usr/share/man/man3c/mkstemps.3c target=mkstemp.3c
link path=usr/share/man/man3c/mq_reltimedreceive_np.3c target=mq_receive.3c
link path=usr/share/man/man3c/mq_reltimedsend_np.3c target=mq_send.3c
link path=usr/share/man/man3c/mq_timedreceive.3c target=mq_receive.3c
link path=usr/share/man/man3c/mq_timedsend.3c target=mq_send.3c
link path=usr/share/man/man3c/mrand48.3c target=drand48.3c
link path=usr/share/man/man3c/mtx_destroy.3c target=mtx.3c
link path=usr/share/man/man3c/mtx_init.3c target=mtx.3c
link path=usr/share/man/man3c/mtx_lock.3c target=mtx.3c
link path=usr/share/man/man3c/mtx_timedlock.3c target=mtx.3c
link path=usr/share/man/man3c/mtx_trylock.3c target=mtx.3c
link path=usr/share/man/man3c/mtx_unlock.3c target=mtx.3c
link path=usr/share/man/man3c/munlock.3c target=mlock.3c
link path=usr/share/man/man3c/munlockall.3c target=mlockall.3c
link path=usr/share/man/man3c/mutex_consistent.3c target=mutex_init.3c
link path=usr/share/man/man3c/mutex_destroy.3c target=mutex_init.3c
link path=usr/share/man/man3c/mutex_lock.3c target=mutex_init.3c
link path=usr/share/man/man3c/mutex_trylock.3c target=mutex_init.3c
link path=usr/share/man/man3c/mutex_unlock.3c target=mutex_init.3c
link path=usr/share/man/man3c/nftw.3c target=ftw.3c
link path=usr/share/man/man3c/ngettext.3c target=gettext.3c
link path=usr/share/man/man3c/nl_langinfo_l.3c target=nl_langinfo.3c
link path=usr/share/man/man3c/nrand48.3c target=drand48.3c
link path=usr/share/man/man3c/openlog.3c target=syslog.3c
link path=usr/share/man/man3c/pclose.3c target=popen.3c
link path=usr/share/man/man3c/port_dissociate.3c target=port_associate.3c
link path=usr/share/man/man3c/port_getn.3c target=port_get.3c
link path=usr/share/man/man3c/port_sendn.3c target=port_send.3c
link path=usr/share/man/man3c/posix_spawn_file_actions_addopen.3c \
    target=posix_spawn_file_actions_addclose.3c
link path=usr/share/man/man3c/posix_spawn_file_actions_init.3c \
    target=posix_spawn_file_actions_destroy.3c
link path=usr/share/man/man3c/posix_spawnattr_init.3c \
    target=posix_spawnattr_destroy.3c
link path=usr/share/man/man3c/posix_spawnattr_setflags.3c \
    target=posix_spawnattr_getflags.3c
link path=usr/share/man/man3c/posix_spawnattr_setpgroup.3c \
    target=posix_spawnattr_getpgroup.3c
link path=usr/share/man/man3c/posix_spawnattr_setschedparam.3c \
    target=posix_spawnattr_getschedparam.3c
link path=usr/share/man/man3c/posix_spawnattr_setschedpolicy.3c \
    target=posix_spawnattr_getschedpolicy.3c
link path=usr/share/man/man3c/posix_spawnattr_setsigdefault.3c \
    target=posix_spawnattr_getsigdefault.3c
link path=usr/share/man/man3c/posix_spawnattr_setsigignore_np.3c \
    target=posix_spawnattr_getsigignore_np.3c
link path=usr/share/man/man3c/posix_spawnattr_setsigmask.3c \
    target=posix_spawnattr_getsigmask.3c
link path=usr/share/man/man3c/posix_spawnp.3c target=posix_spawn.3c
link path=usr/share/man/man3c/printstack.3c target=walkcontext.3c
link path=usr/share/man/man3c/priv_allocset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_basicset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_copyset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_delset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_emptyset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_fillset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_freeset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_getbyname.3c target=priv_str_to_set.3c
link path=usr/share/man/man3c/priv_getbynum.3c target=priv_str_to_set.3c
link path=usr/share/man/man3c/priv_getsetbyname.3c target=priv_str_to_set.3c
link path=usr/share/man/man3c/priv_getsetbynum.3c target=priv_str_to_set.3c
link path=usr/share/man/man3c/priv_gettext.3c target=priv_str_to_set.3c
link path=usr/share/man/man3c/priv_ineffect.3c target=priv_set.3c
link path=usr/share/man/man3c/priv_intersect.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_inverse.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_isemptyset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_isequalset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_isfullset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_ismember.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_issubset.3c target=priv_addset.3c
link path=usr/share/man/man3c/priv_set_to_str.3c target=priv_str_to_set.3c
link path=usr/share/man/man3c/priv_union.3c target=priv_addset.3c
link path=usr/share/man/man3c/pselect.3c target=select.3c
link path=usr/share/man/man3c/psiginfo.3c target=psignal.3c
link path=usr/share/man/man3c/pthread_attr_destroy.3c \
    target=pthread_attr_init.3c
link path=usr/share/man/man3c/pthread_attr_setdetachstate.3c \
    target=pthread_attr_getdetachstate.3c
link path=usr/share/man/man3c/pthread_attr_setguardsize.3c \
    target=pthread_attr_getguardsize.3c
link path=usr/share/man/man3c/pthread_attr_setinheritsched.3c \
    target=pthread_attr_getinheritsched.3c
link path=usr/share/man/man3c/pthread_attr_setschedparam.3c \
    target=pthread_attr_getschedparam.3c
link path=usr/share/man/man3c/pthread_attr_setschedpolicy.3c \
    target=pthread_attr_getschedpolicy.3c
link path=usr/share/man/man3c/pthread_attr_setscope.3c \
    target=pthread_attr_getscope.3c
link path=usr/share/man/man3c/pthread_attr_setstack.3c \
    target=pthread_attr_getstack.3c
link path=usr/share/man/man3c/pthread_attr_setstackaddr.3c \
    target=pthread_attr_getstackaddr.3c
link path=usr/share/man/man3c/pthread_attr_setstacksize.3c \
    target=pthread_attr_getstacksize.3c
link path=usr/share/man/man3c/pthread_barrier_init.3c \
    target=pthread_barrier_destroy.3c
link path=usr/share/man/man3c/pthread_barrierattr_init.3c \
    target=pthread_barrierattr_destroy.3c
link path=usr/share/man/man3c/pthread_barrierattr_setpshared.3c \
    target=pthread_barrierattr_getpshared.3c
link path=usr/share/man/man3c/pthread_cond_broadcast.3c \
    target=pthread_cond_signal.3c
link path=usr/share/man/man3c/pthread_cond_destroy.3c \
    target=pthread_cond_init.3c
link path=usr/share/man/man3c/pthread_cond_reltimedwait_np.3c \
    target=pthread_cond_wait.3c
link path=usr/share/man/man3c/pthread_cond_timedwait.3c \
    target=pthread_cond_wait.3c
link path=usr/share/man/man3c/pthread_condattr_destroy.3c \
    target=pthread_condattr_init.3c
link path=usr/share/man/man3c/pthread_condattr_setclock.3c \
    target=pthread_condattr_getclock.3c
link path=usr/share/man/man3c/pthread_condattr_setpshared.3c \
    target=pthread_condattr_getpshared.3c
link path=usr/share/man/man3c/pthread_key_create_once_np.3c \
    target=pthread_key_create.3c
link path=usr/share/man/man3c/pthread_mutex_destroy.3c \
    target=pthread_mutex_init.3c
link path=usr/share/man/man3c/pthread_mutex_reltimedlock_np.3c \
    target=pthread_mutex_timedlock.3c
link path=usr/share/man/man3c/pthread_mutex_setprioceiling.3c \
    target=pthread_mutex_getprioceiling.3c
link path=usr/share/man/man3c/pthread_mutex_trylock.3c \
    target=pthread_mutex_lock.3c
link path=usr/share/man/man3c/pthread_mutex_unlock.3c \
    target=pthread_mutex_lock.3c
link path=usr/share/man/man3c/pthread_mutexattr_destroy.3c \
    target=pthread_mutexattr_init.3c
link path=usr/share/man/man3c/pthread_mutexattr_setprioceiling.3c \
    target=pthread_mutexattr_getprioceiling.3c
link path=usr/share/man/man3c/pthread_mutexattr_setprotocol.3c \
    target=pthread_mutexattr_getprotocol.3c
link path=usr/share/man/man3c/pthread_mutexattr_setpshared.3c \
    target=pthread_mutexattr_getpshared.3c
link path=usr/share/man/man3c/pthread_mutexattr_setrobust.3c \
    target=pthread_mutexattr_getrobust.3c
link path=usr/share/man/man3c/pthread_mutexattr_settype.3c \
    target=pthread_mutexattr_gettype.3c
link path=usr/share/man/man3c/pthread_rwlock_destroy.3c \
    target=pthread_rwlock_init.3c
link path=usr/share/man/man3c/pthread_rwlock_reltimedrdlock_np.3c \
    target=pthread_rwlock_timedrdlock.3c
link path=usr/share/man/man3c/pthread_rwlock_reltimedwrlock_np.3c \
    target=pthread_rwlock_timedwrlock.3c
link path=usr/share/man/man3c/pthread_rwlock_tryrdlock.3c \
    target=pthread_rwlock_rdlock.3c
link path=usr/share/man/man3c/pthread_rwlock_trywrlock.3c \
    target=pthread_rwlock_wrlock.3c
link path=usr/share/man/man3c/pthread_rwlockattr_destroy.3c \
    target=pthread_rwlockattr_init.3c
link path=usr/share/man/man3c/pthread_rwlockattr_setpshared.3c \
    target=pthread_rwlockattr_getpshared.3c
link path=usr/share/man/man3c/pthread_setconcurrency.3c \
    target=pthread_getconcurrency.3c
link path=usr/share/man/man3c/pthread_setschedparam.3c \
    target=pthread_getschedparam.3c
link path=usr/share/man/man3c/pthread_setspecific.3c \
    target=pthread_getspecific.3c
link path=usr/share/man/man3c/pthread_spin_init.3c \
    target=pthread_spin_destroy.3c
link path=usr/share/man/man3c/pthread_spin_trylock.3c \
    target=pthread_spin_lock.3c
link path=usr/share/man/man3c/putc.3c target=fputc.3c
link path=usr/share/man/man3c/putc_unlocked.3c target=fputc.3c
link path=usr/share/man/man3c/putchar.3c target=fputc.3c
link path=usr/share/man/man3c/putchar_unlocked.3c target=fputc.3c
link path=usr/share/man/man3c/putmntent.3c target=getmntent.3c
link path=usr/share/man/man3c/pututline.3c target=getutent.3c
link path=usr/share/man/man3c/pututxline.3c target=getutxent.3c
link path=usr/share/man/man3c/putw.3c target=fputc.3c
link path=usr/share/man/man3c/putwc.3c target=fputwc.3c
link path=usr/share/man/man3c/putwchar.3c target=fputwc.3c
link path=usr/share/man/man3c/qeconvert.3c target=econvert.3c
link path=usr/share/man/man3c/qfconvert.3c target=econvert.3c
link path=usr/share/man/man3c/qgconvert.3c target=econvert.3c
link path=usr/share/man/man3c/quadruple_to_decimal.3c \
    target=floating_to_decimal.3c
link path=usr/share/man/man3c/rand_r.3c target=rand.3c
link path=usr/share/man/man3c/rctlblk_get_enforced_value.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_get_firing_time.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_get_global_action.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_get_global_flags.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_get_local_action.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_get_local_flags.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_get_privilege.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_get_recipient_pid.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_get_value.3c target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_set_local_action.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_set_local_flags.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_set_privilege.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_set_recipient_pid.3c \
    target=rctlblk_set_value.3c
link path=usr/share/man/man3c/rctlblk_size.3c target=rctlblk_set_value.3c
link path=usr/share/man/man3c/re_exec.3c target=re_comp.3c
link path=usr/share/man/man3c/readdir_r.3c target=readdir.3c
link path=usr/share/man/man3c/realloc.3c target=malloc.3c
link path=usr/share/man/man3c/regerror.3c target=regcomp.3c
link path=usr/share/man/man3c/regex.3c target=regcmp.3c
link path=usr/share/man/man3c/regexec.3c target=regcomp.3c
link path=usr/share/man/man3c/regfree.3c target=regcomp.3c
link path=usr/share/man/man3c/remque.3c target=insque.3c
link path=usr/share/man/man3c/resetmnttab.3c target=getmntent.3c
link path=usr/share/man/man3c/rindex.3c target=index.3c
link path=usr/share/man/man3c/rw_rdlock.3c target=rwlock.3c
link path=usr/share/man/man3c/rw_tryrdlock.3c target=rwlock.3c
link path=usr/share/man/man3c/rw_trywrlock.3c target=rwlock.3c
link path=usr/share/man/man3c/rw_unlock.3c target=rwlock.3c
link path=usr/share/man/man3c/rw_wrlock.3c target=rwlock.3c
link path=usr/share/man/man3c/rwlock_destroy.3c target=rwlock.3c
link path=usr/share/man/man3c/rwlock_init.3c target=rwlock.3c
link path=usr/share/man/man3c/sched_get_priority_min.3c \
    target=sched_get_priority_max.3c
link path=usr/share/man/man3c/schedctl_exit.3c target=schedctl_init.3c
link path=usr/share/man/man3c/schedctl_lookup.3c target=schedctl_init.3c
link path=usr/share/man/man3c/schedctl_start.3c target=schedctl_init.3c
link path=usr/share/man/man3c/schedctl_stop.3c target=schedctl_init.3c
link path=usr/share/man/man3c/seconvert.3c target=econvert.3c
link path=usr/share/man/man3c/seed48.3c target=drand48.3c
link path=usr/share/man/man3c/sem_reltimedwait_np.3c target=sem_timedwait.3c
link path=usr/share/man/man3c/sem_trywait.3c target=sem_wait.3c
link path=usr/share/man/man3c/sema_destroy.3c target=semaphore.3c
link path=usr/share/man/man3c/sema_init.3c target=semaphore.3c
link path=usr/share/man/man3c/sema_post.3c target=semaphore.3c
link path=usr/share/man/man3c/sema_trywait.3c target=semaphore.3c
link path=usr/share/man/man3c/sema_wait.3c target=semaphore.3c
link path=usr/share/man/man3c/setattrat.3c target=fgetattr.3c
link path=usr/share/man/man3c/setgrent.3c target=getgrnam.3c
link path=usr/share/man/man3c/sethostname.3c target=gethostname.3c
link path=usr/share/man/man3c/setlinebuf.3c target=setbuffer.3c
link path=usr/share/man/man3c/setlogmask.3c target=syslog.3c
link path=usr/share/man/man3c/setnetgrent.3c target=getnetgrent.3c
link path=usr/share/man/man3c/setpriority.3c target=getpriority.3c
link path=usr/share/man/man3c/setprogname.3c target=getprogname.3c
link path=usr/share/man/man3c/setpwent.3c target=getpwnam.3c
link path=usr/share/man/man3c/setspent.3c target=getspnam.3c
link path=usr/share/man/man3c/setstate.3c target=random.3c
link path=usr/share/man/man3c/settimeofday.3c target=gettimeofday.3c
link path=usr/share/man/man3c/setusershell.3c target=getusershell.3c
link path=usr/share/man/man3c/setutent.3c target=getutent.3c
link path=usr/share/man/man3c/setutxent.3c target=getutxent.3c
link path=usr/share/man/man3c/setvbuf.3c target=setbuf.3c
link path=usr/share/man/man3c/sfconvert.3c target=econvert.3c
link path=usr/share/man/man3c/sgconvert.3c target=econvert.3c
link path=usr/share/man/man3c/sig2str.3c target=str2sig.3c
link path=usr/share/man/man3c/sigaddset.3c target=sigsetops.3c
link path=usr/share/man/man3c/sigdelset.3c target=sigsetops.3c
link path=usr/share/man/man3c/sigemptyset.3c target=sigsetops.3c
link path=usr/share/man/man3c/sigfillset.3c target=sigsetops.3c
link path=usr/share/man/man3c/sighold.3c target=signal.3c
link path=usr/share/man/man3c/sigignore.3c target=signal.3c
link path=usr/share/man/man3c/sigismember.3c target=sigsetops.3c
link path=usr/share/man/man3c/siglongjmp.3c target=setjmp.3c
link path=usr/share/man/man3c/sigpause.3c target=signal.3c
link path=usr/share/man/man3c/sigrelse.3c target=signal.3c
link path=usr/share/man/man3c/sigset.3c target=signal.3c
link path=usr/share/man/man3c/sigsetjmp.3c target=setjmp.3c
link path=usr/share/man/man3c/sigtimedwait.3c target=sigwaitinfo.3c
link path=usr/share/man/man3c/single_to_decimal.3c \
    target=floating_to_decimal.3c
link path=usr/share/man/man3c/snprintf.3c target=printf.3c
link path=usr/share/man/man3c/sprintf.3c target=printf.3c
link path=usr/share/man/man3c/srand.3c target=rand.3c
link path=usr/share/man/man3c/srand48.3c target=drand48.3c
link path=usr/share/man/man3c/srandom.3c target=random.3c
link path=usr/share/man/man3c/sscanf.3c target=scanf.3c
link path=usr/share/man/man3c/stderr.3c target=stdio.3c
link path=usr/share/man/man3c/stdin.3c target=stdio.3c
link path=usr/share/man/man3c/stdout.3c target=stdio.3c
link path=usr/share/man/man3c/stpcpy.3c target=string.3c
link path=usr/share/man/man3c/stpncpy.3c target=string.3c
link path=usr/share/man/man3c/strcasecmp.3c target=string.3c
link path=usr/share/man/man3c/strcasecmp_l.3c target=string.3c
link path=usr/share/man/man3c/strcasestr.3c target=string.3c
link path=usr/share/man/man3c/strcasestr_l.3c target=string.3c
link path=usr/share/man/man3c/strcat.3c target=string.3c
link path=usr/share/man/man3c/strchr.3c target=string.3c
link path=usr/share/man/man3c/strchrnul.3c target=string.3c
link path=usr/share/man/man3c/strcmp.3c target=string.3c
link path=usr/share/man/man3c/strcoll_l.3c target=strcoll.3c
link path=usr/share/man/man3c/strcpy.3c target=string.3c
link path=usr/share/man/man3c/strcspn.3c target=string.3c
link path=usr/share/man/man3c/strdup.3c target=string.3c
link path=usr/share/man/man3c/strdupa.3c target=string.3c
link path=usr/share/man/man3c/strerror_l.3c target=strerror.3c
link path=usr/share/man/man3c/strerror_r.3c target=strerror.3c
link path=usr/share/man/man3c/strfmon_l.3c target=strfmon.3c
link path=usr/share/man/man3c/strftime_l.3c target=strftime.3c
link path=usr/share/man/man3c/strlcat.3c target=string.3c
link path=usr/share/man/man3c/strlcpy.3c target=string.3c
link path=usr/share/man/man3c/strlen.3c target=string.3c
link path=usr/share/man/man3c/strncasecmp.3c target=string.3c
link path=usr/share/man/man3c/strncasecmp_l.3c target=string.3c
link path=usr/share/man/man3c/strncat.3c target=string.3c
link path=usr/share/man/man3c/strncmp.3c target=string.3c
link path=usr/share/man/man3c/strncpy.3c target=string.3c
link path=usr/share/man/man3c/strndup.3c target=string.3c
link path=usr/share/man/man3c/strndupa.3c target=string.3c
link path=usr/share/man/man3c/strnlen.3c target=string.3c
link path=usr/share/man/man3c/strnstr.3c target=string.3c
link path=usr/share/man/man3c/strpbrk.3c target=string.3c
link path=usr/share/man/man3c/strptime_l.3c target=strptime.3c
link path=usr/share/man/man3c/strrchr.3c target=string.3c
link path=usr/share/man/man3c/strsep.3c target=string.3c
link path=usr/share/man/man3c/strspn.3c target=string.3c
link path=usr/share/man/man3c/strstr.3c target=string.3c
link path=usr/share/man/man3c/strtof.3c target=strtod.3c
link path=usr/share/man/man3c/strtok.3c target=string.3c
link path=usr/share/man/man3c/strtok_r.3c target=string.3c
link path=usr/share/man/man3c/strtold.3c target=strtod.3c
link path=usr/share/man/man3c/strtoll.3c target=strtol.3c
link path=usr/share/man/man3c/strtoull.3c target=strtoul.3c
link path=usr/share/man/man3c/strtoumax.3c target=strtoimax.3c
link path=usr/share/man/man3c/strxfrm_l.3c target=strxfrm.3c
link path=usr/share/man/man3c/swapcontext.3c target=makecontext.3c
link path=usr/share/man/man3c/swprintf.3c target=fwprintf.3c
link path=usr/share/man/man3c/swscanf.3c target=fwscanf.3c
link path=usr/share/man/man3c/tdelete.3c target=tsearch.3c
link path=usr/share/man/man3c/tempnam.3c target=tmpnam.3c
link path=usr/share/man/man3c/textdomain.3c target=gettext.3c
link path=usr/share/man/man3c/tfind.3c target=tsearch.3c
link path=usr/share/man/man3c/thr_continue.3c target=thr_suspend.3c
link path=usr/share/man/man3c/thr_getspecific.3c target=thr_keycreate.3c
link path=usr/share/man/man3c/thr_keycreate_once.3c target=thr_keycreate.3c
link path=usr/share/man/man3c/thr_setconcurrency.3c \
    target=thr_getconcurrency.3c
link path=usr/share/man/man3c/thr_setprio.3c target=thr_getprio.3c
link path=usr/share/man/man3c/thr_setspecific.3c target=thr_keycreate.3c
link path=usr/share/man/man3c/thrd_sleep.3c target=nanosleep.3c
link path=usr/share/man/man3c/timegm.3c target=mktime.3c
link path=usr/share/man/man3c/timer_getoverrun.3c target=timer_settime.3c
link path=usr/share/man/man3c/timer_gettime.3c target=timer_settime.3c
link path=usr/share/man/man3c/timerclear.3c target=timeradd.3c
link path=usr/share/man/man3c/timercmp.3c target=timeradd.3c
link path=usr/share/man/man3c/timerfd_gettime.3c target=timerfd_create.3c
link path=usr/share/man/man3c/timerfd_settime.3c target=timerfd_create.3c
link path=usr/share/man/man3c/timerisset.3c target=timeradd.3c
link path=usr/share/man/man3c/timersub.3c target=timeradd.3c
link path=usr/share/man/man3c/tmpnam_r.3c target=tmpnam.3c
link path=usr/share/man/man3c/tolower_l.3c target=tolower.3c
link path=usr/share/man/man3c/toupper_l.3c target=toupper.3c
link path=usr/share/man/man3c/towctrans.3c target=wctrans.3c
link path=usr/share/man/man3c/towctrans_l.3c target=wctrans.3c
link path=usr/share/man/man3c/towlower_l.3c target=towlower.3c
link path=usr/share/man/man3c/towupper_l.3c target=towupper.3c
link path=usr/share/man/man3c/tss_create.3c target=tss.3c
link path=usr/share/man/man3c/tss_delete.3c target=tss.3c
link path=usr/share/man/man3c/tss_get.3c target=tss.3c
link path=usr/share/man/man3c/tss_set.3c target=tss.3c
link path=usr/share/man/man3c/ttyname_r.3c target=ttyname.3c
link path=usr/share/man/man3c/twalk.3c target=tsearch.3c
link path=usr/share/man/man3c/tzset.3c target=ctime.3c
link path=usr/share/man/man3c/uconv_u16tou8.3c target=uconv_u16tou32.3c
link path=usr/share/man/man3c/uconv_u32tou16.3c target=uconv_u16tou32.3c
link path=usr/share/man/man3c/uconv_u32tou8.3c target=uconv_u16tou32.3c
link path=usr/share/man/man3c/uconv_u8tou16.3c target=uconv_u16tou32.3c
link path=usr/share/man/man3c/uconv_u8tou32.3c target=uconv_u16tou32.3c
link path=usr/share/man/man3c/ucred_free.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_get.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getegid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_geteuid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getgroups.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getlabel.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getpflags.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getpid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getprivset.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getprojid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getrgid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getruid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getsgid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getsuid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_getzoneid.3c target=ucred.3c
link path=usr/share/man/man3c/ucred_size.3c target=ucred.3c
link path=usr/share/man/man3c/ulckpwdf.3c target=lckpwdf.3c
link path=usr/share/man/man3c/ulltostr.3c target=strtol.3c
link path=usr/share/man/man3c/unordered.3c target=isnand.3c
link path=usr/share/man/man3c/updwtmp.3c target=getutxent.3c
link path=usr/share/man/man3c/updwtmpx.3c target=getutxent.3c
link path=usr/share/man/man3c/utmpname.3c target=getutent.3c
link path=usr/share/man/man3c/utmpxname.3c target=getutxent.3c
link path=usr/share/man/man3c/valloc.3c target=malloc.3c
link path=usr/share/man/man3c/vasprintf.3c target=vprintf.3c
link path=usr/share/man/man3c/verr.3c target=err.3c
link path=usr/share/man/man3c/verrx.3c target=err.3c
link path=usr/share/man/man3c/vfprintf.3c target=vprintf.3c
link path=usr/share/man/man3c/vfscanf.3c target=scanf.3c
link path=usr/share/man/man3c/vfwscanf.3c target=fwscanf.3c
link path=usr/share/man/man3c/vscanf.3c target=scanf.3c
link path=usr/share/man/man3c/vsnprintf.3c target=vprintf.3c
link path=usr/share/man/man3c/vsprintf.3c target=vprintf.3c
link path=usr/share/man/man3c/vsscanf.3c target=scanf.3c
link path=usr/share/man/man3c/vswprintf.3c target=vfwprintf.3c
link path=usr/share/man/man3c/vswscanf.3c target=fwscanf.3c
link path=usr/share/man/man3c/vwarn.3c target=err.3c
link path=usr/share/man/man3c/vwarnx.3c target=err.3c
link path=usr/share/man/man3c/vwprintf.3c target=vfwprintf.3c
link path=usr/share/man/man3c/vwscanf.3c target=fwscanf.3c
link path=usr/share/man/man3c/wait4.3c target=wait3.3c
link path=usr/share/man/man3c/warn.3c target=err.3c
link path=usr/share/man/man3c/warnx.3c target=err.3c
link path=usr/share/man/man3c/watof.3c target=wcstod.3c
link path=usr/share/man/man3c/watoi.3c target=wcstol.3c
link path=usr/share/man/man3c/watol.3c target=wcstol.3c
link path=usr/share/man/man3c/watoll.3c target=wcstol.3c
link path=usr/share/man/man3c/wcpncpy.3c target=wcpcpy.3c
link path=usr/share/man/man3c/wcrtomb_l.3c target=wcrtomb.3c
link path=usr/share/man/man3c/wcscasecmp_l.3c target=wcscasecmp.3c
link path=usr/share/man/man3c/wcscat.3c target=wcstring.3c
link path=usr/share/man/man3c/wcschr.3c target=wcstring.3c
link path=usr/share/man/man3c/wcscmp.3c target=wcstring.3c
link path=usr/share/man/man3c/wcscoll_l.3c target=wcscoll.3c
link path=usr/share/man/man3c/wcscpy.3c target=wcstring.3c
link path=usr/share/man/man3c/wcscspn.3c target=wcstring.3c
link path=usr/share/man/man3c/wcsetno.3c target=cset.3c
link path=usr/share/man/man3c/wcsncasecmp.3c target=wcscasecmp.3c
link path=usr/share/man/man3c/wcsncasecmp_l.3c target=wcscasecmp.3c
link path=usr/share/man/man3c/wcsncat.3c target=wcstring.3c
link path=usr/share/man/man3c/wcsncmp.3c target=wcstring.3c
link path=usr/share/man/man3c/wcsncpy.3c target=wcstring.3c
link path=usr/share/man/man3c/wcsnlen.3c target=wcslen.3c
link path=usr/share/man/man3c/wcsnrtombs.3c target=wcsrtombs.3c
link path=usr/share/man/man3c/wcsnrtombs_l.3c target=wcsrtombs.3c
link path=usr/share/man/man3c/wcspbrk.3c target=wcstring.3c
link path=usr/share/man/man3c/wcsrchr.3c target=wcstring.3c
link path=usr/share/man/man3c/wcsrtombs_l.3c target=wcsrtombs.3c
link path=usr/share/man/man3c/wcsspn.3c target=wcstring.3c
link path=usr/share/man/man3c/wcstof.3c target=wcstod.3c
link path=usr/share/man/man3c/wcstok.3c target=wcstring.3c
link path=usr/share/man/man3c/wcstold.3c target=wcstod.3c
link path=usr/share/man/man3c/wcstoll.3c target=wcstol.3c
link path=usr/share/man/man3c/wcstombs_l.3c target=wcstombs.3c
link path=usr/share/man/man3c/wcstoull.3c target=wcstoul.3c
link path=usr/share/man/man3c/wcstoumax.3c target=wcstoimax.3c
link path=usr/share/man/man3c/wcswcs.3c target=wcstring.3c
link path=usr/share/man/man3c/wcswidth_l.3c target=wcswidth.3c
link path=usr/share/man/man3c/wctob_l.3c target=wctob.3c
link path=usr/share/man/man3c/wctomb_l.3c target=wctomb.3c
link path=usr/share/man/man3c/wctrans_l.3c target=wctrans.3c
link path=usr/share/man/man3c/wctype_l.3c target=wctype.3c
link path=usr/share/man/man3c/wcwidth_l.3c target=wcwidth.3c
link path=usr/share/man/man3c/windex.3c target=wcstring.3c
link path=usr/share/man/man3c/wordfree.3c target=wordexp.3c
link path=usr/share/man/man3c/wprintf.3c target=fwprintf.3c
link path=usr/share/man/man3c/wrindex.3c target=wcstring.3c
link path=usr/share/man/man3c/wscanf.3c target=fwscanf.3c
link path=usr/share/man/man3c/wscasecmp.3c target=wstring.3c
link path=usr/share/man/man3c/wscat.3c target=wcstring.3c
link path=usr/share/man/man3c/wschr.3c target=wcstring.3c
link path=usr/share/man/man3c/wscmp.3c target=wcstring.3c
link path=usr/share/man/man3c/wscol.3c target=wstring.3c
link path=usr/share/man/man3c/wscoll.3c target=wcscoll.3c
link path=usr/share/man/man3c/wscpy.3c target=wcstring.3c
link path=usr/share/man/man3c/wscspn.3c target=wcstring.3c
link path=usr/share/man/man3c/wsdup.3c target=wstring.3c
link path=usr/share/man/man3c/wslen.3c target=wcstring.3c
link path=usr/share/man/man3c/wsncasecmp.3c target=wstring.3c
link path=usr/share/man/man3c/wsncat.3c target=wcstring.3c
link path=usr/share/man/man3c/wsncmp.3c target=wcstring.3c
link path=usr/share/man/man3c/wsncpy.3c target=wcstring.3c
link path=usr/share/man/man3c/wspbrk.3c target=wcstring.3c
link path=usr/share/man/man3c/wsrchr.3c target=wcstring.3c
link path=usr/share/man/man3c/wsspn.3c target=wcstring.3c
link path=usr/share/man/man3c/wstod.3c target=wcstod.3c
link path=usr/share/man/man3c/wstok.3c target=wcstring.3c
link path=usr/share/man/man3c/wstol.3c target=wcstol.3c
link path=usr/share/man/man3c/wstostr.3c target=strtows.3c
link path=usr/share/man/man3c/wsxfrm.3c target=wcsxfrm.3c
