#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3bsm/au_open.3bsm
file path=usr/share/man/man3bsm/au_preselect.3bsm
file path=usr/share/man/man3bsm/au_to.3bsm
file path=usr/share/man/man3bsm/au_user_mask.3bsm
file path=usr/share/man/man3bsm/getacinfo.3bsm
file path=usr/share/man/man3bsm/getauclassent.3bsm
file path=usr/share/man/man3bsm/getauditflags.3bsm
file path=usr/share/man/man3bsm/getauevent.3bsm
file path=usr/share/man/man3bsm/getauusernam.3bsm
file path=usr/share/man/man3bsm/getddent.3bsm
file path=usr/share/man/man3bsm/getfauditflags.3bsm
link path=usr/share/man/man3bsm/au_close.3bsm target=au_open.3bsm
link path=usr/share/man/man3bsm/au_to_arg.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_arg32.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_arg64.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_attr.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_cmd.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_data.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_groups.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_in_addr.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_ipc.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_iport.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_me.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_newgroups.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_opaque.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_path.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_process.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_process_ex.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_return.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_return32.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_return64.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_socket.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_subject.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_subject_ex.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_to_text.3bsm target=au_to.3bsm
link path=usr/share/man/man3bsm/au_write.3bsm target=au_open.3bsm
link path=usr/share/man/man3bsm/endac.3bsm target=getacinfo.3bsm
link path=usr/share/man/man3bsm/endauclass.3bsm target=getauclassent.3bsm
link path=usr/share/man/man3bsm/endauevent.3bsm target=getauevent.3bsm
link path=usr/share/man/man3bsm/endauuser.3bsm target=getauusernam.3bsm
link path=usr/share/man/man3bsm/endddent.3bsm target=getddent.3bsm
link path=usr/share/man/man3bsm/getacdir.3bsm target=getacinfo.3bsm
link path=usr/share/man/man3bsm/getacflg.3bsm target=getacinfo.3bsm
link path=usr/share/man/man3bsm/getacmin.3bsm target=getacinfo.3bsm
link path=usr/share/man/man3bsm/getacna.3bsm target=getacinfo.3bsm
link path=usr/share/man/man3bsm/getauclassent_r.3bsm target=getauclassent.3bsm
link path=usr/share/man/man3bsm/getauclassnam.3bsm target=getauclassent.3bsm
link path=usr/share/man/man3bsm/getauclassnam_r.3bsm target=getauclassent.3bsm
link path=usr/share/man/man3bsm/getauditflagsbin.3bsm \
    target=getauditflags.3bsm
link path=usr/share/man/man3bsm/getauditflagschar.3bsm \
    target=getauditflags.3bsm
link path=usr/share/man/man3bsm/getauevent_r.3bsm target=getauevent.3bsm
link path=usr/share/man/man3bsm/getauevnam.3bsm target=getauevent.3bsm
link path=usr/share/man/man3bsm/getauevnam_r.3bsm target=getauevent.3bsm
link path=usr/share/man/man3bsm/getauevnonam.3bsm target=getauevent.3bsm
link path=usr/share/man/man3bsm/getauevnum.3bsm target=getauevent.3bsm
link path=usr/share/man/man3bsm/getauevnum_r.3bsm target=getauevent.3bsm
link path=usr/share/man/man3bsm/getauuserent.3bsm target=getauusernam.3bsm
link path=usr/share/man/man3bsm/getauuserent_r.3bsm target=getauusernam.3bsm
link path=usr/share/man/man3bsm/getauusernam_r.3bsm target=getauusernam.3bsm
link path=usr/share/man/man3bsm/getddnam.3bsm target=getddent.3bsm
link path=usr/share/man/man3bsm/setac.3bsm target=getacinfo.3bsm
link path=usr/share/man/man3bsm/setauclass.3bsm target=getauclassent.3bsm
link path=usr/share/man/man3bsm/setauevent.3bsm target=getauevent.3bsm
link path=usr/share/man/man3bsm/setauuser.3bsm target=getauusernam.3bsm
link path=usr/share/man/man3bsm/setddent.3bsm target=getddent.3bsm
link path=usr/share/man/man3bsm/setddfile.3bsm target=getddent.3bsm
