#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3lgrp/lgrp_affinity_get.3lgrp
file path=usr/share/man/man3lgrp/lgrp_children.3lgrp
file path=usr/share/man/man3lgrp/lgrp_cookie_stale.3lgrp
file path=usr/share/man/man3lgrp/lgrp_cpus.3lgrp
file path=usr/share/man/man3lgrp/lgrp_fini.3lgrp
file path=usr/share/man/man3lgrp/lgrp_home.3lgrp
file path=usr/share/man/man3lgrp/lgrp_init.3lgrp
file path=usr/share/man/man3lgrp/lgrp_latency.3lgrp
file path=usr/share/man/man3lgrp/lgrp_mem_size.3lgrp
file path=usr/share/man/man3lgrp/lgrp_nlgrps.3lgrp
file path=usr/share/man/man3lgrp/lgrp_parents.3lgrp
file path=usr/share/man/man3lgrp/lgrp_resources.3lgrp
file path=usr/share/man/man3lgrp/lgrp_root.3lgrp
file path=usr/share/man/man3lgrp/lgrp_version.3lgrp
file path=usr/share/man/man3lgrp/lgrp_view.3lgrp
link path=usr/share/man/man3lgrp/lgrp_affinity_set.3lgrp \
    target=lgrp_affinity_get.3lgrp
link path=usr/share/man/man3lgrp/lgrp_latency_cookie.3lgrp \
    target=lgrp_latency.3lgrp
