#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man3sip/sip_add_branchid_to_via.3sip
file path=usr/share/man/man3sip/sip_add_from.3sip
file path=usr/share/man/man3sip/sip_add_header.3sip
file path=usr/share/man/man3sip/sip_add_param.3sip
file path=usr/share/man/man3sip/sip_add_request_line.3sip
file path=usr/share/man/man3sip/sip_branchid.3sip
file path=usr/share/man/man3sip/sip_clone_msg.3sip
file path=usr/share/man/man3sip/sip_copy_start_line.3sip
file path=usr/share/man/man3sip/sip_create_OKack.3sip
file path=usr/share/man/man3sip/sip_create_dialog_req.3sip
file path=usr/share/man/man3sip/sip_create_response.3sip
file path=usr/share/man/man3sip/sip_delete_dialog.3sip
file path=usr/share/man/man3sip/sip_delete_start_line.3sip
file path=usr/share/man/man3sip/sip_enable_counters.3sip
file path=usr/share/man/man3sip/sip_enable_trans_logging.3sip
file path=usr/share/man/man3sip/sip_get_contact_display_name.3sip
file path=usr/share/man/man3sip/sip_get_cseq.3sip
file path=usr/share/man/man3sip/sip_get_dialog_state.3sip
file path=usr/share/man/man3sip/sip_get_header.3sip
file path=usr/share/man/man3sip/sip_get_header_value.3sip
file path=usr/share/man/man3sip/sip_get_msg_len.3sip
file path=usr/share/man/man3sip/sip_get_num_via.3sip
file path=usr/share/man/man3sip/sip_get_param_value.3sip
file path=usr/share/man/man3sip/sip_get_request_method.3sip
file path=usr/share/man/man3sip/sip_get_request_uri_str.3sip
file path=usr/share/man/man3sip/sip_get_resp_desc.3sip
file path=usr/share/man/man3sip/sip_get_trans.3sip
file path=usr/share/man/man3sip/sip_get_trans_method.3sip
file path=usr/share/man/man3sip/sip_get_uri_parsed.3sip
file path=usr/share/man/man3sip/sip_guid.3sip
file path=usr/share/man/man3sip/sip_hold_dialog.3sip
file path=usr/share/man/man3sip/sip_hold_msg.3sip
file path=usr/share/man/man3sip/sip_hold_trans.3sip
file path=usr/share/man/man3sip/sip_init_conn_object.3sip
file path=usr/share/man/man3sip/sip_is_sip_uri.3sip
file path=usr/share/man/man3sip/sip_msg_is_request.3sip
file path=usr/share/man/man3sip/sip_msg_to_str.3sip
file path=usr/share/man/man3sip/sip_new_msg.3sip
file path=usr/share/man/man3sip/sip_parse_uri.3sip
file path=usr/share/man/man3sip/sip_process_new_packet.3sip
file path=usr/share/man/man3sip/sip_register_sent_by.3sip
file path=usr/share/man/man3sip/sip_sendmsg.3sip
file path=usr/share/man/man3sip/sip_stack_init.3sip
link path=usr/share/man/man3sip/sip_add_accept.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_accept_enc.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_accept_lang.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_alert_info.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_allow.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_allow_events.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_authen_info.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_author.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_call_info.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_callid.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_contact.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_content.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_content_disp.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_content_enc.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_content_lang.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_content_type.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_cseq.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_date.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_error_info.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_event.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_expires.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_in_reply_to.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_maxforward.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_mime_version.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_min_expires.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_org.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_passertedid.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_ppreferredid.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_priority.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_privacy.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_proxy_authen.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_proxy_author.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_proxy_require.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_rack.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_record_route.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_reply_to.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_require.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_response_line.3sip \
    target=sip_add_request_line.3sip
link path=usr/share/man/man3sip/sip_add_retry_after.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_route.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_rseq.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_server.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_subject.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_substate.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_supported.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_to.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_tstamp.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_unsupported.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_user_agent.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_via.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_warning.3sip target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_add_www_authen.3sip \
    target=sip_add_from.3sip
link path=usr/share/man/man3sip/sip_clear_stale_data.3sip \
    target=sip_init_conn_object.3sip
link path=usr/share/man/man3sip/sip_conn_destroyed.3sip \
    target=sip_init_conn_object.3sip
link path=usr/share/man/man3sip/sip_copy_all_headers.3sip \
    target=sip_copy_start_line.3sip
link path=usr/share/man/man3sip/sip_copy_header.3sip \
    target=sip_copy_start_line.3sip
link path=usr/share/man/man3sip/sip_copy_header_by_name.3sip \
    target=sip_copy_start_line.3sip
link path=usr/share/man/man3sip/sip_create_dialog_req_nocontact.3sip \
    target=sip_create_dialog_req.3sip
link path=usr/share/man/man3sip/sip_delete_header.3sip \
    target=sip_delete_start_line.3sip
link path=usr/share/man/man3sip/sip_delete_header_by_name.3sip \
    target=sip_delete_start_line.3sip
link path=usr/share/man/man3sip/sip_delete_value.3sip \
    target=sip_delete_start_line.3sip
link path=usr/share/man/man3sip/sip_disable_counters.3sip \
    target=sip_enable_counters.3sip
link path=usr/share/man/man3sip/sip_disable_dialog_logging.3sip \
    target=sip_enable_trans_logging.3sip
link path=usr/share/man/man3sip/sip_disable_trans_logging.3sip \
    target=sip_enable_trans_logging.3sip
link path=usr/share/man/man3sip/sip_enable_dialog_logging.3sip \
    target=sip_enable_trans_logging.3sip
link path=usr/share/man/man3sip/sip_free_msg.3sip target=sip_hold_msg.3sip
link path=usr/share/man/man3sip/sip_free_parsed_uri.3sip \
    target=sip_parse_uri.3sip
link path=usr/share/man/man3sip/sip_get_accept_enc.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_accept_lang.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_accept_sub_type.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_accept_type.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_alert_info_uri.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_allow_events.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_allow_method.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_authen_info.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_author_param.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_author_scheme.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_branchid.3sip \
    target=sip_get_num_via.3sip
link path=usr/share/man/man3sip/sip_get_call_info_uri.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_callid.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_callseq_method.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_callseq_num.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_contact_uri_str.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_content.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_content_disp.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_content_enc.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_content_lang.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_content_length.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_content_sub_type.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_content_type.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_counter_value.3sip \
    target=sip_enable_counters.3sip
link path=usr/share/man/man3sip/sip_get_date_day.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_date_month.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_date_time.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_date_timezone.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_date_wkday.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_date_year.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_dialog_callid.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_local_contact_uri.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_local_cseq.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_local_tag.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_local_uri.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_method.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_msgcnt.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_remote_cseq.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_remote_tag.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_remote_target_uri.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_remote_uri.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_route_set.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_dialog_type.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_get_error_info_uri.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_event.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_expires.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_from_display_name.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_from_tag.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_from_uri_str.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_in_reply_to.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_maxforward.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_mime_version.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_min_expires.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_next_value.3sip \
    target=sip_get_header_value.3sip
link path=usr/share/man/man3sip/sip_get_org.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_params.3sip \
    target=sip_get_param_value.3sip
link path=usr/share/man/man3sip/sip_get_passertedid_display_name.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_passertedid_uri_str.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_ppreferredid_display_name.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_ppreferredid_uri_str.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_priority.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_priv_value.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_proxy_authen_param.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_proxy_authen_scheme.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_proxy_author_param.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_proxy_author_scheme.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_proxy_require.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_rack_cseq_num.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_rack_method.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_rack_resp_num.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_replyto_display_name.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_replyto_uri_str.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_require.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_response_code.3sip \
    target=sip_get_request_method.3sip
link path=usr/share/man/man3sip/sip_get_response_phrase.3sip \
    target=sip_get_request_method.3sip
link path=usr/share/man/man3sip/sip_get_retry_after_cmts.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_retry_after_time.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_route_display_name.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_route_uri_str.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_rseq.3sip target=sip_get_cseq.3sip
link path=usr/share/man/man3sip/sip_get_rseq_resp_num.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_server.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_sip_version.3sip \
    target=sip_get_request_method.3sip
link path=usr/share/man/man3sip/sip_get_subject.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_substate.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_supported.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_to_display_name.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_to_tag.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_to_uri_str.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_trans_branchid.3sip \
    target=sip_get_trans_method.3sip
link path=usr/share/man/man3sip/sip_get_trans_conn_obj.3sip \
    target=sip_get_trans_method.3sip
link path=usr/share/man/man3sip/sip_get_trans_orig_msg.3sip \
    target=sip_get_trans_method.3sip
link path=usr/share/man/man3sip/sip_get_trans_resp_msg.3sip \
    target=sip_get_trans_method.3sip
link path=usr/share/man/man3sip/sip_get_trans_state.3sip \
    target=sip_get_trans_method.3sip
link path=usr/share/man/man3sip/sip_get_tstamp_delay.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_tstamp_value.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_unsupported.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_uri_errflags.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_headers.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_host.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_opaque.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_params.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_password.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_path.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_port.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_query.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_regname.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_scheme.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_uri_user.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_get_user_agent.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_via_sent_by_host.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_via_sent_by_port.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_via_sent_protocol_name.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_via_sent_protocol_version.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_via_sent_transport.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_warning_agent.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_warning_code.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_warning_text.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_www_authen_param.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_get_www_authen_scheme.3sip \
    target=sip_get_contact_display_name.3sip
link path=usr/share/man/man3sip/sip_hdr_to_str.3sip target=sip_msg_to_str.3sip
link path=usr/share/man/man3sip/sip_is_dialog_secure.3sip \
    target=sip_get_dialog_state.3sip
link path=usr/share/man/man3sip/sip_is_param_present.3sip \
    target=sip_get_param_value.3sip
link path=usr/share/man/man3sip/sip_is_uri_teluser.3sip \
    target=sip_is_sip_uri.3sip
link path=usr/share/man/man3sip/sip_message_is_response.3sip \
    target=sip_msg_is_request.3sip
link path=usr/share/man/man3sip/sip_release_dialog.3sip \
    target=sip_hold_dialog.3sip
link path=usr/share/man/man3sip/sip_release_trans.3sip \
    target=sip_hold_trans.3sip
link path=usr/share/man/man3sip/sip_reqline_to_str.3sip \
    target=sip_msg_to_str.3sip
link path=usr/share/man/man3sip/sip_respline_to_str.3sip \
    target=sip_msg_to_str.3sip
link path=usr/share/man/man3sip/sip_sent_by_to_str.3sip \
    target=sip_msg_to_str.3sip
link path=usr/share/man/man3sip/sip_unregister_all_sent_by.3sip \
    target=sip_register_sent_by.3sip
link path=usr/share/man/man3sip/sip_unregister_sent_by.3sip \
    target=sip_register_sent_by.3sip
link path=usr/share/man/man3sip/sip_uri_errflags_to_str.3sip \
    target=sip_is_sip_uri.3sip
