#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man7fs/bootfs.7fs
file path=usr/share/man/man7fs/ctfs.7fs
file path=usr/share/man/man7fs/dcfs.7fs
file path=usr/share/man/man7fs/dev.7fs
file path=usr/share/man/man7fs/devfs.7fs
file path=usr/share/man/man7fs/fd.7fs
file path=usr/share/man/man7fs/hsfs.7fs
file path=usr/share/man/man7fs/lofs.7fs
file path=usr/share/man/man7fs/objfs.7fs
file path=usr/share/man/man7fs/sharefs.7fs
file path=usr/share/man/man7fs/tmpfs.7fs
file path=usr/share/man/man7fs/ufs.7fs
link path=usr/share/man/man7fs/stderr.7fs target=fd.7fs
link path=usr/share/man/man7fs/stdin.7fs target=fd.7fs
link path=usr/share/man/man7fs/stdout.7fs target=fd.7fs
