#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011, Richard Lowe
# Copyright 2012 Nexenta Systems, Inc. All rights reserved.
#

file path=usr/share/man/man9e/Intro.9e
file path=usr/share/man/man9e/_fini.9e
file path=usr/share/man/man9e/aread.9e
file path=usr/share/man/man9e/attach.9e
file path=usr/share/man/man9e/awrite.9e
file path=usr/share/man/man9e/chpoll.9e
file path=usr/share/man/man9e/close.9e
file path=usr/share/man/man9e/csx_event_handler.9e
file path=usr/share/man/man9e/detach.9e
file path=usr/share/man/man9e/devmap.9e
file path=usr/share/man/man9e/devmap_access.9e
file path=usr/share/man/man9e/devmap_contextmgt.9e
file path=usr/share/man/man9e/devmap_dup.9e
file path=usr/share/man/man9e/devmap_map.9e
file path=usr/share/man/man9e/devmap_unmap.9e
file path=usr/share/man/man9e/dump.9e
file path=usr/share/man/man9e/getinfo.9e
file path=usr/share/man/man9e/gld.9e
file path=usr/share/man/man9e/identify.9e
file path=usr/share/man/man9e/ioctl.9e
file path=usr/share/man/man9e/ks_snapshot.9e
file path=usr/share/man/man9e/ks_update.9e
file path=usr/share/man/man9e/mac.9e
file path=usr/share/man/man9e/mc_getcapab.9e
file path=usr/share/man/man9e/mc_getprop.9e
file path=usr/share/man/man9e/mc_getstat.9e
file path=usr/share/man/man9e/mc_ioctl.9e
file path=usr/share/man/man9e/mc_multicst.9e
file path=usr/share/man/man9e/mc_open.9e
file path=usr/share/man/man9e/mc_propinfo.9e
file path=usr/share/man/man9e/mc_setpromisc.9e
file path=usr/share/man/man9e/mc_setprop.9e
file path=usr/share/man/man9e/mc_start.9e
file path=usr/share/man/man9e/mc_tx.9e
file path=usr/share/man/man9e/mc_unicst.9e
file path=usr/share/man/man9e/mmap.9e
file path=usr/share/man/man9e/open.9e
file path=usr/share/man/man9e/power.9e
file path=usr/share/man/man9e/print.9e
file path=usr/share/man/man9e/probe.9e
file path=usr/share/man/man9e/prop_op.9e
file path=usr/share/man/man9e/put.9e
file path=usr/share/man/man9e/quiesce.9e
file path=usr/share/man/man9e/read.9e
file path=usr/share/man/man9e/segmap.9e
file path=usr/share/man/man9e/srv.9e
file path=usr/share/man/man9e/strategy.9e
file path=usr/share/man/man9e/tran_abort.9e
file path=usr/share/man/man9e/tran_bus_reset.9e
file path=usr/share/man/man9e/tran_dmafree.9e
file path=usr/share/man/man9e/tran_getcap.9e
file path=usr/share/man/man9e/tran_init_pkt.9e
file path=usr/share/man/man9e/tran_quiesce.9e
file path=usr/share/man/man9e/tran_reset.9e
file path=usr/share/man/man9e/tran_reset_notify.9e
file path=usr/share/man/man9e/tran_setup_pkt.9e
file path=usr/share/man/man9e/tran_start.9e
file path=usr/share/man/man9e/tran_sync_pkt.9e
file path=usr/share/man/man9e/tran_tgt_free.9e
file path=usr/share/man/man9e/tran_tgt_init.9e
file path=usr/share/man/man9e/tran_tgt_probe.9e
file path=usr/share/man/man9e/write.9e
link path=usr/share/man/man9e/GLDv3.9e target=mac.9e
link path=usr/share/man/man9e/MAC.9e target=mac.9e
link path=usr/share/man/man9e/_info.9e target=_fini.9e
link path=usr/share/man/man9e/_init.9e target=_fini.9e
link path=usr/share/man/man9e/gldm_get_stats.9e target=gld.9e
link path=usr/share/man/man9e/gldm_intr.9e target=gld.9e
link path=usr/share/man/man9e/gldm_ioctl.9e target=gld.9e
link path=usr/share/man/man9e/gldm_reset.9e target=gld.9e
link path=usr/share/man/man9e/gldm_send.9e target=gld.9e
link path=usr/share/man/man9e/gldm_set_mac_addr.9e target=gld.9e
link path=usr/share/man/man9e/gldm_set_multicast.9e target=gld.9e
link path=usr/share/man/man9e/gldm_set_promiscuous.9e target=gld.9e
link path=usr/share/man/man9e/gldm_start.9e target=gld.9e
link path=usr/share/man/man9e/gldm_stop.9e target=gld.9e
link path=usr/share/man/man9e/gldv3.9e target=mac.9e
link path=usr/share/man/man9e/intro.9e target=Intro.9e
link path=usr/share/man/man9e/mc_close.9e target=mc_open.9e
link path=usr/share/man/man9e/mc_stop.9e target=mc_start.9e
link path=usr/share/man/man9e/tran_destroy_pkt.9e target=tran_init_pkt.9e
link path=usr/share/man/man9e/tran_pkt_constructor.9e target=tran_setup_pkt.9e
link path=usr/share/man/man9e/tran_pkt_destructor.9e target=tran_setup_pkt.9e
link path=usr/share/man/man9e/tran_setcap.9e target=tran_getcap.9e
link path=usr/share/man/man9e/tran_teardown_pkt.9e target=tran_setup_pkt.9e
link path=usr/share/man/man9e/tran_unquiesce.9e target=tran_quiesce.9e
