#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2015, Joyent, Inc.
#

file path=usr/share/man/man3avl/avl_add.3avl
file path=usr/share/man/man3avl/avl_create.3avl
file path=usr/share/man/man3avl/avl_destroy.3avl
file path=usr/share/man/man3avl/avl_destroy_nodes.3avl
file path=usr/share/man/man3avl/avl_find.3avl
file path=usr/share/man/man3avl/avl_first.3avl
file path=usr/share/man/man3avl/avl_insert.3avl
file path=usr/share/man/man3avl/avl_is_empty.3avl
file path=usr/share/man/man3avl/avl_nearest.3avl
file path=usr/share/man/man3avl/avl_numnodes.3avl
file path=usr/share/man/man3avl/avl_swap.3avl
link path=usr/share/man/man3avl/AVL_NEXT.3avl target=avl_first.3avl
link path=usr/share/man/man3avl/AVL_PREV.3avl target=avl_first.3avl
link path=usr/share/man/man3avl/avl_insert_here.3avl target=avl_insert.3avl
link path=usr/share/man/man3avl/avl_last.3avl target=avl_first.3avl
link path=usr/share/man/man3avl/avl_remove.3avl target=avl_add.3avl

