#!/usr/bin/sh
#
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2015 Joyent, Inc.
#

. /lib/svc/share/smf_include.sh

#
# For the time being, we're going to manually make sure that the
# overlay driver is loaded. We probably shouldn't do that in the long
# run, but it helps for bootstrapping
#
add_drv overlay 2>/dev/null

/usr/lib/varpd/varpd
if [ $? = 0 ]; then
	exit $SMF_EXIT_OK
else
	exit $SMF_EXIT_ERR_FATAL
fi
