'\" te
.\" Copyright (c) 2000, Sun Microsystems, Inc.  All Rights Reserved
.\" Copyright 1989 AT&T
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH DEPEND 4 "Oct 4, 1996"
.SH NAME
depend \- software dependencies file
.SH DESCRIPTION
.sp
.LP
\fBdepend\fR is an \fBASCII\fR file used to specify information concerning
software dependencies for a particular package. The file is created by a
software developer.
.sp
.LP
Each entry in the \fBdepend\fR file describes a single software package. The
instance of the package is described after the entry line by giving the package
architecture and/or version. The format of each entry and subsequent instance
definition is:
.sp
.in +2
.nf
\fItype pkg name
	(arch)version
 	(arch)version
        .\|.\|.\fR
.fi
.in -2
.sp

.sp
.LP
The fields are:
.sp
.ne 2
.na
\fB\fBtype\fR\fR
.ad
.RS 17n
Defines the dependency type. Must be one of the following characters:
.sp
.ne 2
.na
\fB\fBP\fR\fR
.ad
.RS 5n
Indicates a prerequisite for installation; for example, the referenced package
or versions must be installed.
.RE

.sp
.ne 2
.na
\fB\fBI\fR\fR
.ad
.RS 5n
Implies that the existence of the indicated package or version is incompatible.
.RE

.sp
.ne 2
.na
\fB\fBR\fR\fR
.ad
.RS 5n
Indicates a reverse dependency. Instead of defining the package's own
dependencies, this designates that another package depends on this one. This
type should be used only when an old package does not have a \fBdepend\fR file,
but relies on the newer package nonetheless. Therefore, the present package
should not be removed if the designated old package is still on the system
since, if it is removed, the old package will no longer work.
.RE

.RE

.sp
.ne 2
.na
\fB\fIpkg\fR\fR
.ad
.RS 17n
Indicates the package abbreviation.
.RE

.sp
.ne 2
.na
\fB\fIname\fR\fR
.ad
.RS 17n
Specifies the full package name.
.RE

.sp
.ne 2
.na
\fB\fI(arch)version\fR\fR
.ad
.RS 17n
Specifies a particular instance of the software. A version name cannot begin
with a left parenthesis. The instance specifications, both \fI(arch)\fR and
\fIversion\fR, are completely optional, but each \fI(arch)version\fR pair must
begin on a new line that begins with white space. A null version set equates to
any version of the indicated package.
.RE

.SH EXAMPLES
.LP
\fBExample 1 \fRSample of \fBdepend\fR file
.sp
.LP
Here are the contents of a sample \fBdepend\fR file, for the \fBSUNWftpr\fR
(FTP Server) package, stored in \fB/var/sadm/pkg/SUNWftpr/install\fR:

.sp
.in +2
.nf
P SUNWcar       Core Architecture, (Root)
P SUNWkvm       Core Architecture, (Kvm)
P SUNWcsr       Core Solaris, (Root)
P SUNWcsu       Core Solaris, (Usr)
P SUNWcsd       Core Solaris Devices
P SUNWcsl       Core Solaris Libraries
R SUNWftpu      FTP Server, (Usr)
.fi
.in -2

.SH SEE ALSO
.sp
.LP
\fBpkginfo\fR(4)
.sp
.LP
\fIApplication Packaging Developer\&'s Guide\fR
