'\" te
.\"  Copyright (c) 2001 Sun Microsystems, Inc.  All rights reserved.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH NFSSEC.CONF 4 "Nov 12, 2001"
.SH NAME
nfssec.conf \- list NFS security modes
.SH SYNOPSIS
.LP
.nf
\fB/etc/nfssec.conf\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fBnfssec.conf\fR file lists the NFS security modes supported on a system.
These modes are defined in \fBnfssec\fR(5).
.sp
.LP
The \fBnfssec.conf\fR file should not be edited by a user.
.SH SEE ALSO
.sp
.LP
\fBnfssec\fR(5)
