'\" te
.\" Copyright (c) 2004, Sun Microsystems, Inc. All Rights Reserved.
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH NOTROUTER 4 "Sep 10, 2004"
.SH NAME
notrouter \- flag to turn off IPv4 routing
.SH SYNOPSIS
.LP
.nf
\fB/etc/notrouter\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fB/etc/notrouter\fR file is no longer used as of the current release of
the Solaris operating system. IPv4 forwarding is disabled by default and can be
enabled using \fBrouteadm\fR(1M).
.SH SEE ALSO
.sp
.LP
\fBrouteadm\fR(1M)
