'\" te
.\" Copyright (C) 2003, Sun Microsystems, Inc. All Rights Reserved
.\" The contents of this file are subject to the terms of the Common Development and Distribution License (the "License").  You may not use this file except in compliance with the License.
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE or http://www.opensolaris.org/os/licensing.  See the License for the specific language governing permissions and limitations under the License.
.\" When distributing Covered Code, include this CDDL HEADER in each file and include the License file at usr/src/OPENSOLARIS.LICENSE.  If applicable, add the following below this CDDL HEADER, with the fields enclosed by brackets "[]" replaced with your own identifying information: Portions Copyright [yyyy] [name of copyright owner]
.TH XFERLOG 4 "Apr 25, 2003"
.SH NAME
xferlog \- FTP Server transfer log file
.SH SYNOPSIS
.LP
.nf
\fB/var/log/xferlog\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fBxferlog\fR file contains transfer logging information from the FTP
Server, \fBin.ftpd\fR(1M). You can use the logfile capability to change the
location of the log file. See \fBftpaccess\fR(4).
.sp
.LP
By default, each server entry is composed of a single line of the following
form. All fields are separated by spaces.
.sp
.in +2
.nf
\fIcurrent-time\fR  \fItransfer-time \fR   \fIremote-host\fR  \fIbytes-transferred\fR  \e
        \fIfilename\fR
\fItransfer-type\fR  \fIspecial-action-flag\fR  \fIdirection\fR \fIaccess-mode\fR  \fIusername\fR
\fIservice-name\fR  \fIauthentication-method\fR  \fIauthenticated-user-id\fR \e
         \fIcompletion-status\fR
.fi
.in -2

.sp
.LP
The \fBxferlog\fR format capability can be used to customize the transfer log
file format used. In addition to those in the default format, it also supports
\fBchroot-filename\fR, \fBfile-size\fR, and \fBrestart-offset\fR fields. See
\fBftpaccess\fR(4).
.sp
.LP
The fields are defined as follows:
.sp
.ne 2
.na
\fB\fIcurrent-time\fR\fR
.ad
.RS 25n
The current local time in the form \fBDDD MMM dd hh:mm:ss YYYY\fR, where:
.sp
.ne 2
.na
\fB\fBDDD\fR\fR
.ad
.RS 8n
Is the day of the week
.RE

.sp
.ne 2
.na
\fB\fBMMM\fR\fR
.ad
.RS 8n
Is the month
.RE

.sp
.ne 2
.na
\fB\fBdd\fR\fR
.ad
.RS 8n
Is the day of the month
.RE

.sp
.ne 2
.na
\fB\fBhh\fR\fR
.ad
.RS 8n
Is the hour
.RE

.sp
.ne 2
.na
\fB\fBmm\fR\fR
.ad
.RS 8n
Is the minutes
.RE

.sp
.ne 2
.na
\fB\fBss\fR\fR
.ad
.RS 8n
Is the seconds
.RE

.sp
.ne 2
.na
\fB\fBYYYY\fR\fR
.ad
.RS 8n
Is the year
.RE

.RE

.sp
.ne 2
.na
\fB\fItransfer-time \fR\fR
.ad
.RS 25n
The total time in seconds for the transfer
.RE

.sp
.ne 2
.na
\fB\fIremote-host\fR\fR
.ad
.RS 25n
The remote host name
.RE

.sp
.ne 2
.na
\fB\fIbytes-transferred\fR\fR
.ad
.RS 25n
The number of bytes transferred
.RE

.sp
.ne 2
.na
\fB\fIfilename\fR\fR
.ad
.RS 25n
The absolute pathname of the transferred file
.RE

.sp
.ne 2
.na
\fB\fItransfer-type\fR\fR
.ad
.RS 25n
A single character indicating the type of transfer:
.sp
.ne 2
.na
\fBa\fR
.ad
.RS 5n
Indicates an ascii transfer
.RE

.sp
.ne 2
.na
\fBb\fR
.ad
.RS 5n
Indicates a binary transfer
.RE

.RE

.sp
.ne 2
.na
\fB\fIspecial-action-flag\fR\fR
.ad
.RS 25n
One or more single character flags that indicate any special action taken. The
\fIspecial-action-flag\fR can have one of more of the following values:
.sp
.ne 2
.na
\fBC\fR
.ad
.RS 16n
File was compressed
.RE

.sp
.ne 2
.na
\fBU\fR
.ad
.RS 16n
File was uncompressed
.RE

.sp
.ne 2
.na
\fBT\fR
.ad
.RS 16n
File was archived, for example, by using \fBtar\fR(1)
.RE

.sp
.ne 2
.na
\fB_ (underbar)\fR
.ad
.RS 16n
No action was taken.
.RE

.RE

.sp
.ne 2
.na
\fB\fIdirection\fR\fR
.ad
.RS 25n
The direction of the transfer. \fIdirection\fR can have one of the following
values:
.sp
.ne 2
.na
\fBo\fR
.ad
.RS 5n
Outgoing
.RE

.sp
.ne 2
.na
\fBi\fR
.ad
.RS 5n
Incoming
.RE

.RE

.sp
.ne 2
.na
\fB\fIaccess-mode\fR\fR
.ad
.RS 25n
The method by which the user is logged in. \fIaccess-mode\fR can have one of
the following values:
.sp
.ne 2
.na
\fBa\fR
.ad
.RS 5n
For an anonymous user.
.RE

.sp
.ne 2
.na
\fBg\fR
.ad
.RS 5n
For a passworded guest user. See the description of the \fBguestgroup\fR
capability in \fBftpaccess\fR(4).
.RE

.sp
.ne 2
.na
\fBr\fR
.ad
.RS 5n
For a real, locally authenticated user
.RE

.RE

.sp
.ne 2
.na
\fB\fIusername\fR\fR
.ad
.RS 25n
The local username, or if anonymous, the ID string given
.RE

.sp
.ne 2
.na
\fB\fIservice-name\fR\fR
.ad
.RS 25n
The name of the service invoked, usually \fBftp\fR
.RE

.sp
.ne 2
.na
\fB\fIauthentication-method\fR\fR
.ad
.RS 25n
The method of authentication used. \fIauthentication-method\fR can have one of
the following values:
.sp
.ne 2
.na
\fB0\fR
.ad
.RS 5n
None
.RE

.sp
.ne 2
.na
\fB1\fR
.ad
.RS 5n
\fIRFC 931\fR authentication
.RE

.RE

.sp
.ne 2
.na
\fB\fIauthenticated-user-id\fR\fR
.ad
.RS 25n
The user ID returned by the authentication method. A \fB*\fR is used if an
authenticated user ID is not available.
.RE

.sp
.ne 2
.na
\fB\fIcompletion-status\fR\fR
.ad
.RS 25n
A single character indicating the status of the transfer.
\fIcompletion-status\fR can have one of the following values:
.sp
.ne 2
.na
\fBc\fR
.ad
.RS 5n
Indicates complete transfer
.RE

.sp
.ne 2
.na
\fBi\fR
.ad
.RS 5n
Indicates incomplete transfer
.RE

.RE

.sp
.ne 2
.na
\fB\fIchroot-filename\fR\fR
.ad
.RS 25n
The pathname of the transferred file relative to the \fBchroot\fR point. This
will differ from the \fIfilename\fR field for anonymous and guest users.
.RE

.sp
.ne 2
.na
\fB\fIfile-size\fR\fR
.ad
.RS 25n
The size, in bytes, of the file on the server.
.RE

.sp
.ne 2
.na
\fB\fIrestart-offset\fR\fR
.ad
.RS 25n
The offset, in bytes, at which the file transfer was restarted (0 when no
restart offset was specified).
.RE

.SH FILES
.sp
.LP
\fB/var/log/xferlog\fR
.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
box;
c | c
l | l .
ATTRIBUTE TYPE	ATTRIBUTE VALUE
_
Interface Stability	External
.TE

.SH SEE ALSO
.sp
.LP
\fBtar\fR(1), \fBin.ftpd\fR(1M), \fBftpaccess\fR(4), \fBftpconversions\fR(4),
\fBattributes\fR(5)
.sp
.LP
StJohns, Mike. \fIRFC 931, Authentication Server\fR. Network Working Group.
January 1985.
