#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

#
# Copyright 2023 Oxide Computer company
#

include		$(SRC)/Makefile.master

MANSECT=	3jedec

MANFILES=					\
		libjedec_spd.3jedec		\
		libjedec_temp_range.3jedec	\
		libjedec_vendor_string.3jedec

.KEEP_STATE:

include		$(SRC)/man/Makefile.man

install:	$(ROOTMANFILES)
