#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"
#

include ../Makefile.com

DATAFILES += depend

LICENSEFILES += ../../uts/common/sys/THIRDPARTYLICENSE.agpgart

.KEEP_STATE:

all: $(FILES) postinstall preremove
install: all pkg

include ../Makefile.targ
