#! /bin/sh
#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"
#
# SUNWagp preremove script

PATH=/usr/bin:/usr/sbin:${PATH}
export PATH

EXIT=0

not_installed() {
	driver=$1
	grep "^${driver} " $BASEDIR/etc/name_to_major > /dev/null 2>&1
	if [ "$?" -eq 0 ]; then
		return 1
	else
		return 0
	fi
}

case "${ARCH}" in
	i386)
		not_installed agpgart || rem_drv -b ${BASEDIR} agpgart || \
			EXIT=1
		not_installed agptarget || rem_drv -b ${BASEDIR} agptarget || \
			EXIT=1
		not_installed amd64_gart || \
			rem_drv -b ${BASEDIR} amd64_gart || EXIT=1
	;;
esac

exit ${EXIT}
