#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2013 by Delphix. All rights reserved.
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 600
post_user = root
post = cleanup
outputdir = /var/tmp/test_results

[/opt/zfs-tests/tests/functional/acl/cifs]
tests = ['cifs_attr_001_pos', 'cifs_attr_002_pos', 'cifs_attr_003_pos']

[/opt/zfs-tests/tests/functional/acl/nontrivial]
tests = ['zfs_acl_chmod_001_neg', 'zfs_acl_chmod_002_pos',
    'zfs_acl_chmod_aclmode_001_pos', 'zfs_acl_chmod_compact_001_pos',
    'zfs_acl_chmod_delete_001_pos', 'zfs_acl_chmod_inherit_001_pos',
    'zfs_acl_chmod_inherit_002_neg', 'zfs_acl_chmod_inherit_002_pos',
    'zfs_acl_chmod_inherit_003_pos', 'zfs_acl_chmod_inherit_004_pos',
    'zfs_acl_chmod_owner_001_pos', 'zfs_acl_chmod_rwacl_001_pos',
    'zfs_acl_chmod_rwx_001_pos', 'zfs_acl_chmod_rwx_002_pos',
    'zfs_acl_chmod_rwx_003_pos', 'zfs_acl_chmod_rwx_004_pos',
    'zfs_acl_chmod_xattr_001_pos', 'zfs_acl_chmod_xattr_002_pos',
    'zfs_acl_cp_001_pos', 'zfs_acl_cp_002_pos', 'zfs_acl_cpio_001_pos',
    'zfs_acl_cpio_002_pos', 'zfs_acl_find_001_pos', 'zfs_acl_ls_001_pos',
    'zfs_acl_mv_001_pos', 'zfs_acl_tar_001_pos', 'zfs_acl_tar_002_pos',
    'zfs_acl_aclmode_restricted_001_neg']

[/opt/zfs-tests/tests/functional/acl/trivial]
tests = ['zfs_acl_chmod_001_pos', 'zfs_acl_compress_001_pos',
    'zfs_acl_cp_001_pos', 'zfs_acl_cp_002_neg', 'zfs_acl_cp_003_neg',
    'zfs_acl_find_001_pos', 'zfs_acl_find_002_neg', 'zfs_acl_ls_001_pos',
    'zfs_acl_ls_002_neg', 'zfs_acl_mv_001_pos', 'zfs_acl_pack_001_pos',
    'zfs_acl_pax_001_pos', 'zfs_acl_pax_002_pos', 'zfs_acl_pax_003_pos',
    'zfs_acl_pax_004_pos', 'zfs_acl_pax_005_pos', 'zfs_acl_pax_006_pos',
    'zfs_acl_tar_001_pos', 'zfs_acl_tar_002_neg',
    'zfs_acl_aclmode_restricted_001_pos']

[/opt/zfs-tests/tests/functional/atime]
tests = ['atime_001_pos', 'atime_002_neg']

[/opt/zfs-tests/tests/functional/bootfs]
tests = ['bootfs_001_pos', 'bootfs_002_neg', 'bootfs_003_pos', 'bootfs_004_neg',
    'bootfs_005_neg', 'bootfs_006_pos', 'bootfs_007_neg', 'bootfs_008_neg']
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zdb]
tests = ['zdb_001_neg']
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zfs]
tests = ['zfs_001_neg', 'zfs_002_pos', 'zfs_003_neg']

[/opt/zfs-tests/tests/functional/cli_root/zfs_clone]
tests = ['zfs_clone_001_neg', 'zfs_clone_002_pos', 'zfs_clone_003_pos',
    'zfs_clone_004_pos', 'zfs_clone_005_pos', 'zfs_clone_006_pos',
    'zfs_clone_007_pos', 'zfs_clone_008_neg', 'zfs_clone_009_neg',
    'zfs_clone_010_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_copies]
tests = ['zfs_copies_001_pos', 'zfs_copies_002_pos', 'zfs_copies_003_pos',
    'zfs_copies_004_neg', 'zfs_copies_005_neg', 'zfs_copies_006_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_create]
tests = ['zfs_create_001_pos', 'zfs_create_002_pos', 'zfs_create_003_pos',
    'zfs_create_004_pos', 'zfs_create_005_pos', 'zfs_create_006_pos',
    'zfs_create_007_pos', 'zfs_create_008_neg', 'zfs_create_009_neg',
    'zfs_create_010_neg', 'zfs_create_011_pos', 'zfs_create_012_pos',
    'zfs_create_013_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_destroy]
tests = ['zfs_destroy_001_pos', 'zfs_destroy_002_pos', 'zfs_destroy_003_pos',
    'zfs_destroy_004_pos', 'zfs_destroy_005_neg', 'zfs_destroy_006_neg',
    'zfs_destroy_007_neg', 'zfs_destroy_008_pos', 'zfs_destroy_009_pos',
    'zfs_destroy_010_pos', 'zfs_destroy_011_pos', 'zfs_destroy_012_pos',
    'zfs_destroy_013_neg', 'zfs_destroy_014_pos', 'zfs_destroy_015_pos',
    'zfs_destroy_016_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_get]
tests = ['zfs_get_001_pos', 'zfs_get_002_pos', 'zfs_get_003_pos',
    'zfs_get_004_pos', 'zfs_get_005_neg', 'zfs_get_006_neg', 'zfs_get_007_neg',
    'zfs_get_008_pos', 'zfs_get_009_pos', 'zfs_get_010_neg']

[/opt/zfs-tests/tests/functional/cli_root/zfs_inherit]
tests = ['zfs_inherit_001_neg', 'zfs_inherit_002_neg', 'zfs_inherit_003_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_mount]
tests = ['zfs_mount_001_pos', 'zfs_mount_002_pos', 'zfs_mount_003_pos',
    'zfs_mount_004_pos', 'zfs_mount_005_pos', 'zfs_mount_006_pos',
    'zfs_mount_007_pos', 'zfs_mount_008_pos', 'zfs_mount_009_neg',
    'zfs_mount_010_neg', 'zfs_mount_011_neg', 'zfs_mount_all_001_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_promote]
tests = ['zfs_promote_001_pos', 'zfs_promote_002_pos', 'zfs_promote_003_pos',
    'zfs_promote_004_pos', 'zfs_promote_005_pos', 'zfs_promote_006_neg',
    'zfs_promote_007_neg', 'zfs_promote_008_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_property]
tests = ['zfs_written_property_001_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_receive]
tests = ['zfs_receive_001_pos', 'zfs_receive_002_pos', 'zfs_receive_003_pos',
    'zfs_receive_004_neg', 'zfs_receive_005_neg', 'zfs_receive_006_pos',
    'zfs_receive_007_neg', 'zfs_receive_008_pos', 'zfs_receive_009_neg']

[/opt/zfs-tests/tests/functional/cli_root/zfs_rename]
tests = ['zfs_rename_001_pos', 'zfs_rename_002_pos', 'zfs_rename_003_pos',
    'zfs_rename_004_neg', 'zfs_rename_005_neg', 'zfs_rename_006_pos',
    'zfs_rename_007_pos', 'zfs_rename_008_pos', 'zfs_rename_009_neg',
    'zfs_rename_010_neg', 'zfs_rename_011_pos', 'zfs_rename_012_neg',
    'zfs_rename_013_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_reservation]
tests = ['zfs_reservation_001_pos', 'zfs_reservation_002_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_rollback]
tests = ['zfs_rollback_001_pos', 'zfs_rollback_002_pos', 'zfs_rollback_003_neg',
    'zfs_rollback_004_neg']

[/opt/zfs-tests/tests/functional/cli_root/zfs_send]
tests = ['zfs_send_001_pos', 'zfs_send_002_pos', 'zfs_send_003_pos',
    'zfs_send_004_neg', 'zfs_send_005_pos', 'zfs_send_006_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_set]
tests = ['cache_001_pos', 'cache_002_neg', 'canmount_001_pos',
    'canmount_002_pos', 'canmount_003_pos', 'canmount_004_pos',
    'checksum_001_pos', 'compression_001_pos', 'mountpoint_001_pos',
    'mountpoint_002_pos', 'mountpoint_003_pos', 'onoffs_001_pos',
    'property_alias_001_pos', 'readonly_001_pos', 'reservation_001_neg',
    'ro_props_001_pos', 'share_mount_001_neg', 'snapdir_001_pos',
    'user_property_001_pos', 'user_property_002_pos', 'user_property_003_neg',
    'user_property_004_pos', 'version_001_neg', 'zfs_set_001_neg',
    'zfs_set_002_neg', 'zfs_set_003_neg']

[/opt/zfs-tests/tests/functional/cli_root/zfs_share]
tests = ['zfs_share_001_pos', 'zfs_share_002_pos', 'zfs_share_003_pos',
    'zfs_share_004_pos', 'zfs_share_005_pos', 'zfs_share_006_pos',
    'zfs_share_007_neg', 'zfs_share_008_neg', 'zfs_share_009_neg',
    'zfs_share_010_neg', 'zfs_share_011_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_snapshot]
tests = ['zfs_snapshot_001_neg', 'zfs_snapshot_002_neg', 'zfs_snapshot_003_neg',
    'zfs_snapshot_004_neg', 'zfs_snapshot_005_neg', 'zfs_snapshot_006_pos',
    'zfs_snapshot_007_neg', 'zfs_snapshot_008_neg', 'zfs_snapshot_009_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_unmount]
tests = ['zfs_unmount_001_pos', 'zfs_unmount_002_pos', 'zfs_unmount_003_pos',
    'zfs_unmount_004_pos', 'zfs_unmount_005_pos', 'zfs_unmount_006_pos',
    'zfs_unmount_007_neg', 'zfs_unmount_008_neg', 'zfs_unmount_009_pos',
    'zfs_unmount_all_001_pos']

[/opt/zfs-tests/tests/functional/cli_root/zfs_unshare]
tests = ['zfs_unshare_001_pos', 'zfs_unshare_002_pos', 'zfs_unshare_003_pos',
    'zfs_unshare_004_neg', 'zfs_unshare_005_neg']

[/opt/zfs-tests/tests/functional/cli_root/zfs_upgrade]
tests = ['zfs_upgrade_001_pos', 'zfs_upgrade_002_pos', 'zfs_upgrade_003_pos',
    'zfs_upgrade_004_pos', 'zfs_upgrade_005_pos', 'zfs_upgrade_006_neg',
    'zfs_upgrade_007_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool]
tests = ['zpool_001_neg', 'zpool_002_pos', 'zpool_003_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_add]
tests = ['zpool_add_001_pos', 'zpool_add_002_pos', 'zpool_add_003_pos',
    'zpool_add_004_pos', 'zpool_add_005_pos', 'zpool_add_006_pos',
    'zpool_add_007_neg', 'zpool_add_008_neg', 'zpool_add_009_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_attach]
tests = ['zpool_attach_001_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_clear]
tests = ['zpool_clear_001_pos', 'zpool_clear_002_neg', 'zpool_clear_003_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_create]
tests = ['zpool_create_001_pos', 'zpool_create_002_pos', 'zpool_create_003_pos',
    'zpool_create_004_pos', 'zpool_create_005_pos', 'zpool_create_006_pos',
    'zpool_create_007_neg', 'zpool_create_008_pos', 'zpool_create_009_neg',
    'zpool_create_010_neg', 'zpool_create_011_neg', 'zpool_create_012_neg',
    'zpool_create_013_neg', 'zpool_create_014_neg', 'zpool_create_015_neg',
    'zpool_create_016_pos', 'zpool_create_017_neg', 'zpool_create_018_pos',
    'zpool_create_019_pos', 'zpool_create_020_pos', 'zpool_create_021_pos',
    'zpool_create_022_pos', 'zpool_create_023_neg',
    'zpool_create_features_001_pos', 'zpool_create_features_002_pos',
    'zpool_create_features_003_pos', 'zpool_create_features_004_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_destroy]
tests = ['zpool_destroy_001_pos', 'zpool_destroy_002_pos',
    'zpool_destroy_003_neg']
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zpool_detach]
tests = ['zpool_detach_001_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_expand]
tests = ['zpool_expand_001_pos', 'zpool_expand_002_pos', 'zpool_expand_003_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_export]
tests = ['zpool_export_001_pos', 'zpool_export_002_pos', 'zpool_export_003_neg',
    'zpool_export_004_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_get]
tests = ['zpool_get_001_pos', 'zpool_get_002_pos', 'zpool_get_003_pos',
    'zpool_get_004_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_history]
tests = ['zpool_history_001_neg', 'zpool_history_002_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_import]
tests = ['zpool_import_001_pos', 'zpool_import_002_pos', 'zpool_import_003_pos',
    'zpool_import_004_pos', 'zpool_import_005_pos', 'zpool_import_006_pos',
    'zpool_import_007_pos', 'zpool_import_008_pos', 'zpool_import_009_neg',
    'zpool_import_010_pos', 'zpool_import_011_neg', 'zpool_import_012_pos',
    'zpool_import_013_neg', 'zpool_import_all_001_pos',
    'zpool_import_features_001_pos', 'zpool_import_features_002_neg',
    'zpool_import_features_003_pos', 'zpool_import_missing_001_pos',
    'zpool_import_missing_002_pos', 'zpool_import_missing_003_pos',
    'zpool_import_rename_001_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_offline]
tests = ['zpool_offline_001_pos', 'zpool_offline_002_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_online]
tests = ['zpool_online_001_pos', 'zpool_online_002_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_remove]
tests = ['zpool_remove_001_neg', 'zpool_remove_002_pos', 'zpool_remove_003_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_replace]
tests = ['zpool_replace_001_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_scrub]
tests = ['zpool_scrub_001_neg', 'zpool_scrub_002_pos', 'zpool_scrub_003_pos',
    'zpool_scrub_004_pos', 'zpool_scrub_005_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_set]
tests = ['zpool_set_001_pos', 'zpool_set_002_neg', 'zpool_set_003_neg']
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zpool_status]
tests = ['zpool_status_001_pos', 'zpool_status_002_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_upgrade]
tests = ['zpool_upgrade_001_pos', 'zpool_upgrade_002_pos',
    'zpool_upgrade_003_pos', 'zpool_upgrade_004_pos', 'zpool_upgrade_005_neg',
    'zpool_upgrade_006_neg', 'zpool_upgrade_007_pos', 'zpool_upgrade_008_pos',
    'zpool_upgrade_009_neg']

[/opt/zfs-tests/tests/functional/truncate]
tests = ['truncate_001_pos', 'truncate_002_pos']

[/opt/zfs-tests/tests/functional/nopwrite]
tests = ['nopwrite_copies', 'nopwrite_mtime', 'nopwrite_negative',
    'nopwrite_promoted_clone', 'nopwrite_recsize', 'nopwrite_sync',
    'nopwrite_varying_compression', 'nopwrite_volume']
