#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 Joyent, Inc.
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 1800
post_user = root
post = cleanup
outputdir = /var/tmp/test_results

[/opt/zfs-tests/tests/functional/alloc_class]
tests = ['alloc_class_001_pos', 'alloc_class_002_neg', 'alloc_class_003_pos',
    'alloc_class_004_pos', 'alloc_class_005_pos', 'alloc_class_006_pos',
    'alloc_class_007_pos', 'alloc_class_008_pos', 'alloc_class_009_pos',
    'alloc_class_010_pos', 'alloc_class_011_neg', 'alloc_class_012_pos',
    'alloc_class_013_pos']
tags = ['functional', 'alloc_class']

[/opt/zfs-tests/tests/functional/cli_root/zpool_add]
tests = ['zpool_add_010_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_get]
tests = ['zpool_get_001_pos', 'zpool_get_002_pos', 'zpool_get_003_pos',
    'zpool_get_004_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_import]
tests = ['zpool_import_001_pos', 'zpool_import_002_pos',
    'zpool_import_003_pos', 'zpool_import_004_pos', 'zpool_import_005_pos',
    'zpool_import_006_pos', 'zpool_import_007_pos', 'zpool_import_008_pos',
    'zpool_import_009_neg', 'zpool_import_010_pos', 'zpool_import_011_neg',
    'zpool_import_012_pos', 'zpool_import_013_neg', 'zpool_import_all_001_pos',
    'zpool_import_missing_001_pos',
    'zpool_import_missing_002_pos', 'zpool_import_missing_003_pos',
    'zpool_import_rename_001_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_labelclear]
tests = ['zpool_labelclear_active', 'zpool_labelclear_exported']
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zpool_offline]
tests = ['zpool_offline_001_pos', 'zpool_offline_002_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_online]
tests = ['zpool_online_001_pos', 'zpool_online_002_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_remove]
tests = ['zpool_remove_002_pos', 'zpool_remove_003_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_replace]
tests = ['zpool_replace_001_neg', 'zpool_replace_002_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_resilver]
tests = ['zpool_resilver_bad_args', 'zpool_resilver_restart']

[/opt/zfs-tests/tests/functional/cli_root/zpool_scrub]
tests = ['zpool_scrub_001_neg',
    'zpool_scrub_004_pos', 'zpool_scrub_005_pos', 'zpool_scrub_print_repairing',
    'zpool_scrub_offline_device', 'zpool_scrub_multiple_copies']

[/opt/zfs-tests/tests/functional/cli_root/zpool_set]
tests = ['zpool_set_001_pos', 'zpool_set_002_neg', 'zpool_set_003_neg']
pre =
post =

[/opt/zfs-tests/tests/functional/cli_root/zpool_status]
tests = ['zpool_status_001_pos', 'zpool_status_002_pos']

[/opt/zfs-tests/tests/functional/cli_root/zpool_upgrade]
tests = ['zpool_upgrade_001_pos', 'zpool_upgrade_002_pos',
    'zpool_upgrade_003_pos', 'zpool_upgrade_004_pos', 'zpool_upgrade_005_neg',
    'zpool_upgrade_006_neg', 'zpool_upgrade_008_pos',
    'zpool_upgrade_009_neg']

[/opt/zfs-tests/tests/functional/cli_root/zpool_sync]
tests = ['zpool_sync_001_pos', 'zpool_sync_002_neg']

[/opt/zfs-tests/tests/functional/cli_user/misc]
tests = ['zdb_001_neg', 'zfs_001_neg', 'zfs_allow_001_neg',
    'zfs_clone_001_neg', 'zfs_create_001_neg', 'zfs_destroy_001_neg',
    'zfs_get_001_neg', 'zfs_inherit_001_neg', 'zfs_mount_001_neg',
    'zfs_promote_001_neg', 'zfs_receive_001_neg', 'zfs_rename_001_neg',
    'zfs_rollback_001_neg', 'zfs_send_001_neg', 'zfs_set_001_neg',
    'zfs_share_001_neg', 'zfs_snapshot_001_neg', 'zfs_unallow_001_neg',
    'zfs_unmount_001_neg', 'zfs_unshare_001_neg', 'zfs_upgrade_001_neg',
    'zfs_channel_001_neg',
    'zpool_001_neg', 'zpool_add_001_neg', 'zpool_attach_001_neg',
    'zpool_clear_001_neg', 'zpool_create_001_neg', 'zpool_destroy_001_neg',
    'zpool_detach_001_neg', 'zpool_export_001_neg', 'zpool_get_001_neg',
    'zpool_history_001_neg', 'zpool_import_001_neg', 'zpool_import_002_neg',
    'zpool_offline_001_neg', 'zpool_online_001_neg', 'zpool_remove_001_neg',
    'zpool_replace_001_neg', 'zpool_scrub_001_neg', 'zpool_set_001_neg',
    'zpool_status_001_neg', 'zpool_upgrade_001_neg']
user =

[/opt/zfs-tests/tests/functional/cli_user/zfs_list]
tests = ['zfs_list_001_pos', 'zfs_list_002_pos', 'zfs_list_003_pos',
    'zfs_list_004_neg', 'zfs_list_007_pos', 'zfs_list_008_neg']
user =

[/opt/zfs-tests/tests/functional/cli_user/zpool_iostat]
tests = ['zpool_iostat_001_neg', 'zpool_iostat_002_pos',
    'zpool_iostat_003_neg']
user =

[/opt/zfs-tests/tests/functional/cli_user/zpool_list]
tests = ['zpool_list_001_pos', 'zpool_list_002_neg']
user =

[/opt/zfs-tests/tests/functional/compression]
tests = ['compress_001_pos', 'compress_002_pos', 'compress_003_pos',
    'compress_004_pos']

[/opt/zfs-tests/tests/functional/ctime]
tests = ['ctime_001_pos' ]

[/opt/zfs-tests/tests/functional/devices]
tests = ['devices_003_pos']

[/opt/zfs-tests/tests/functional/exec]
tests = ['exec_001_pos', 'exec_002_neg']

[/opt/zfs-tests/tests/functional/features/async_destroy]
tests = ['async_destroy_001_pos']

[/opt/zfs-tests/tests/functional/grow_pool]
tests = ['grow_pool_001_pos']

[/opt/zfs-tests/tests/functional/history]
tests = ['history_001_pos', 'history_002_pos', 'history_003_pos',
    'history_004_pos', 'history_005_neg', 'history_006_neg',
    'history_008_pos']

[/opt/zfs-tests/tests/functional/holes]
tests = ['holes_sanity']

[/opt/zfs-tests/tests/functional/inuse]
tests = ['inuse_001_pos', 'inuse_003_pos', 'inuse_004_pos',
    'inuse_005_pos', 'inuse_006_pos', 'inuse_007_pos', 'inuse_008_pos',
    'inuse_009_pos']
post =

[/opt/zfs-tests/tests/functional/large_dnode]
tests = ['large_dnode_001_pos', 'large_dnode_003_pos',
    'large_dnode_004_neg', 'large_dnode_005_pos', 'large_dnode_007_neg']

[/opt/zfs-tests/tests/functional/large_files]
tests = ['large_files_001_pos']

[/opt/zfs-tests/tests/functional/link_count]
tests = ['link_count_001']

[/opt/zfs-tests/tests/functional/migration]
tests = ['migration_001_pos', 'migration_002_pos', 'migration_003_pos',
    'migration_004_pos', 'migration_005_pos', 'migration_006_pos',
    'migration_007_pos', 'migration_008_pos', 'migration_009_pos',
    'migration_010_pos', 'migration_011_pos', 'migration_012_pos']

[/opt/zfs-tests/tests/functional/mmap]
tests = ['mmap_read_001_pos', 'mmap_write_001_pos']

[/opt/zfs-tests/tests/functional/mmp]
tests = ['mmp_on_thread', 'mmp_on_off', 'mmp_interval',
    'mmp_active_import', 'mmp_inactive_import', 'mmp_exported_import',
    'mmp_on_zdb']

[/opt/zfs-tests/tests/functional/mount]
tests = ['umount_001', 'umountall_001']

[/opt/zfs-tests/tests/functional/mv_files]
tests = ['mv_files_001_pos', 'mv_files_002_pos']

[/opt/zfs-tests/tests/functional/nestedfs]
tests = ['nestedfs_001_pos']

[/opt/zfs-tests/tests/functional/no_space]
tests = ['enospc_001_pos']

[/opt/zfs-tests/tests/functional/nopwrite]
tests = ['nopwrite_copies', 'nopwrite_mtime', 'nopwrite_negative',
    'nopwrite_promoted_clone', 'nopwrite_recsize',
    'nopwrite_varying_compression', 'nopwrite_volume']

[/opt/zfs-tests/tests/functional/online_offline]
tests = ['online_offline_001_pos', 'online_offline_002_neg',
    'online_offline_003_neg']

[/opt/zfs-tests/tests/functional/pool_checkpoint]
tests = ['checkpoint_after_rewind', 'checkpoint_big_rewind',
    'checkpoint_capacity', 'checkpoint_conf_change', 'checkpoint_discard',
    'checkpoint_discard_busy', 'checkpoint_discard_many',
    'checkpoint_indirect', 'checkpoint_invalid', 'checkpoint_lun_expsz',
    'checkpoint_open', 'checkpoint_removal', 'checkpoint_rewind' ]

[/opt/zfs-tests/tests/functional/pool_names]
tests = ['pool_names_002_neg']
pre =
post =

[/opt/zfs-tests/tests/functional/poolversion]
tests = ['poolversion_001_pos', 'poolversion_002_pos']

[/opt/zfs-tests/tests/functional/quota]
tests = ['quota_001_pos', 'quota_002_pos', 'quota_003_pos', 'quota_004_pos',
    'quota_005_pos', 'quota_006_neg']

[/opt/zfs-tests/tests/functional/refquota]
tests = ['refquota_001_pos', 'refquota_002_pos', 'refquota_003_pos',
    'refquota_004_pos', 'refquota_005_pos', 'refquota_006_neg']

[/opt/zfs-tests/tests/functional/refreserv]
tests = ['refreserv_001_pos', 'refreserv_002_pos', 'refreserv_003_pos',
    'refreserv_005_pos']

[/opt/zfs-tests/tests/functional/rename_dirs]
tests = ['rename_dirs_001_pos']

[/opt/zfs-tests/tests/functional/replacement]
tests = ['replacement_001_pos', 'replacement_002_pos']

[/opt/zfs-tests/tests/functional/reservation]
tests = ['reservation_001_pos', 'reservation_002_pos', 'reservation_003_pos',
    'reservation_004_pos', 'reservation_005_pos', 'reservation_006_pos',
    'reservation_007_pos', 'reservation_008_pos', 'reservation_009_pos',
    'reservation_010_pos', 'reservation_011_pos', 'reservation_012_pos',
    'reservation_014_pos', 'reservation_015_pos', 'reservation_016_pos',
    'reservation_018_pos', 'reservation_019_pos', 'reservation_020_pos',
    'reservation_021_neg', 'reservation_022_pos']

[/opt/zfs-tests/tests/functional/rootpool]
tests = ['rootpool_003_neg']

[/opt/zfs-tests/tests/functional/rsend]
tests = ['rsend_001_pos', 'rsend_002_pos', 'rsend_003_pos', 'rsend_004_pos',
    'rsend_005_pos', 'rsend_006_pos', 'rsend_007_pos',
    'rsend_013_pos', 'rsend_014_pos',
    'rsend_019_pos', 'rsend_020_pos',
    'rsend_021_pos', 'rsend_022_pos', 'rsend_024_pos',
    'send-c_verify_ratio', 'send-c_verify_contents',
    'send-c_incremental',
    'send-c_resume',
    'send-c_recv_dedup']

[/opt/zfs-tests/tests/functional/slog]
tests = ['slog_001_pos', 'slog_002_pos', 'slog_003_pos', 'slog_004_pos',
    'slog_005_pos', 'slog_006_pos', 'slog_007_pos', 'slog_008_neg',
    'slog_009_neg', 'slog_010_neg', 'slog_011_neg', 'slog_012_neg',
    'slog_013_pos', 'slog_014_pos']

[/opt/zfs-tests/tests/functional/snapshot]
tests = ['clone_001_pos', 'rollback_001_pos', 'rollback_002_pos',
    'rollback_003_pos', 'snapshot_001_pos', 'snapshot_002_pos',
    'snapshot_003_pos', 'snapshot_004_pos', 'snapshot_005_pos',
    'snapshot_006_pos', 'snapshot_007_pos',
    'snapshot_009_pos', 'snapshot_010_pos', 'snapshot_011_pos',
    'snapshot_012_pos', 'snapshot_013_pos', 'snapshot_014_pos',
    'snapshot_015_pos', 'snapshot_016_pos', 'snapshot_017_pos',
    'deadlist_lock']

[/opt/zfs-tests/tests/functional/snapused]
tests = ['snapused_001_pos', 'snapused_002_pos', 'snapused_003_pos',
    'snapused_004_pos', 'snapused_005_pos']

[/opt/zfs-tests/tests/functional/sparse]
tests = ['sparse_001_pos']

[/opt/zfs-tests/tests/functional/threadsappend]
tests = ['threadsappend_001_pos']

[/opt/zfs-tests/tests/functional/truncate]
tests = ['truncate_001_pos', 'truncate_002_pos']

[/opt/zfs-tests/tests/functional/utils_test]
tests = ['utils_test_001_pos', 'utils_test_002_pos', 'utils_test_003_pos',
    'utils_test_004_pos', 'utils_test_005_pos', 'utils_test_006_pos',
    'utils_test_007_pos', 'utils_test_008_pos', 'utils_test_009_pos']

[/opt/zfs-tests/tests/functional/vdev_zaps]
tests = ['vdev_zaps_001_pos', 'vdev_zaps_002_pos', 'vdev_zaps_003_pos',
    'vdev_zaps_004_pos', 'vdev_zaps_005_pos', 'vdev_zaps_006_pos']

[/opt/zfs-tests/tests/functional/write_dirs]
tests = ['write_dirs_001_pos', 'write_dirs_002_pos']

[/opt/zfs-tests/tests/functional/zvol/zvol_ENOSPC]
tests = ['zvol_ENOSPC_001_pos']

[/opt/zfs-tests/tests/functional/zvol/zvol_cli]
tests = ['zvol_cli_001_pos', 'zvol_cli_002_pos', 'zvol_cli_003_neg']

[/opt/zfs-tests/tests/functional/zvol/zvol_dump]
tests = ['zvol_dump_raidz']
pre =
post =

[/opt/zfs-tests/tests/functional/libzfs]
tests = ['many_fds']
pre =
post =

