#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/libsasl/plugins/cram/sparcv9/Makefile

include ../Makefile.com
include ../../../Makefile.lib.64

install: all $(ROOTLIBS64)
