#
# Copyright (c) 2001 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/libldap5/spec/Makefile.targ
#

LIBRARY	=	libldap.a
VERS	=	.5

OBJECTS	=	ldap.o

SPECCPP =	-I..
