#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
# Copyright 2014 Garrett D'Amore <garrett@damore.org>
# Copyright 2014 Nexenta Systems, Inc. All rights reserved.
# Copyright 2020 Joyent, Inc.
# Copyright 2022 OmniOS Community Edition (OmniOSce) Association.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results

[/opt/util-tests/tests/du/dutest]

[/opt/util-tests/tests/iconv_test]
[/opt/util-tests/tests/printf_test]

[/opt/util-tests/tests/allowed-ips]
user = root

[/opt/util-tests/tests/set-linkprop]
user = root

[/opt/util-tests/tests/show-class-confusion]
user = root

[/opt/util-tests/tests/libsff/libsff]
[/opt/util-tests/tests/libjedec_vendors.32]
[/opt/util-tests/tests/libjedec_temp.32]
[/opt/util-tests/tests/libjedec_spd.32]
[/opt/util-tests/tests/libjedec_hex2spd.32]
[/opt/util-tests/tests/libjedec_vendors.64]
[/opt/util-tests/tests/libjedec_temp.64]
[/opt/util-tests/tests/libjedec_spd.64]
[/opt/util-tests/tests/libjedec_hex2spd.64]
[/opt/util-tests/tests/smbios.32]
[/opt/util-tests/tests/smbios.64]

[/opt/util-tests/tests/show-overlay-exit]
user = root

#
# The sleep tests require destructive DTrace. Therefore they must be run
# as root.
#
[/opt/util-tests/tests/sleep/sleeptest]
user = root

[/opt/util-tests/tests/xargs_test]

[/opt/util-tests/tests/mergeq/mqt]
[/opt/util-tests/tests/mergeq/wqt]

[/opt/util-tests/tests/libnvpair_json]
tests = ['json_00_blank', 'json_01_boolean', 'json_02_numbers',
    'json_03_empty_arrays', 'json_04_number_arrays', 'json_05_strings',
    'json_06_nested', 'json_07_nested_arrays']

#
# The awk tests have a number of individual tests which can take several
# minutes to run. Bumping the timeout to 5 minutes should cover us
# reasonably well as of 7 Aug 2019.
#
[/opt/util-tests/tests/awk]
user = nobody
tests = [ 'runtests.sh' ]
timeout = 300

[/opt/util-tests/tests/grep_test]
[/opt/util-tests/tests/date_test]

[/opt/util-tests/tests/chown_test]
user = root

[/opt/util-tests/tests/make_test]
[/opt/util-tests/tests/head/head_test]

[/opt/util-tests/tests/demangle]
tests = ['afl-fast', 'gcc-libstdc++', 'llvm-stdcxxabi']

[/opt/util-tests/tests/ctf]
pre = precheck
tests = [ 'ctftest' ]

[/opt/util-tests/tests/libcustr]
tests = ['custr_remove', 'custr_trunc']

[/opt/util-tests/tests/find/findtest]

[/opt/util-tests/tests/find/findroot]
user=root

[/opt/util-tests/tests/mdb/mdbtest]

[/opt/util-tests/tests/sed]
tests = ['sed_addr', 'multi_test']

[/opt/util-tests/tests/pcidbtest]
[/opt/util-tests/tests/pcieadmtest]
[/opt/util-tests/tests/pcieadm-priv]
user = root

[/opt/util-tests/tests/svr4pkg_test]
user = root

[/opt/util-tests/tests/ar/artest]
[/opt/util-tests/tests/cpio/cpio_test]

#
# This test ndeds to run as an explicitly unprivileged user to ensure that the
# mv checks around permissions don't fire due to super-user privileges.
#
[/opt/util-tests/tests/cpmvln/overwrite]
user = nobody
