#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet
# at http://www.illumos.org/license/CDDL.
#

# Copyright (c) 2012, Igor Kozhukhov <ikozhukhov@gmail.com>

include ../../Makefile.master

MANSECT = 	3mvec

MANFILES =	vatan2_.3mvec \
		vatan_.3mvec \
		vcos_.3mvec \
		vcospi_.3mvec \
		vexp_.3mvec \
		vhypot_.3mvec \
		vlog_.3mvec \
		vpow_.3mvec \
		vrhypot_.3mvec \
		vrsqrt_.3mvec \
		vsin_.3mvec \
		vsincos_.3mvec \
		vsincospi_.3mvec \
		vsinpi_.3mvec \
		vsqrt_.3mvec \
		vz_abs_.3mvec \
		vz_exp_.3mvec \
		vz_log_.3mvec \
		vz_pow_.3mvec

.KEEP_STATE:

include ../Makefile.man

install: $(ROOTMANFILES)
