/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License, Version 1.0 only
 * (the "License").  You may not use this file except in compliance
 * with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */
/*
 * Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 */

/*	Copyright (c) 1988 AT&T	*/
/*	  All Rights Reserved  	*/


#ifndef _LIBC_SYNONYMS_H
#define	_LIBC_SYNONYMS_H

#pragma ident	"%Z%%M%	%I%	%E% SMI"

#ifdef __cplusplus
extern "C" {
#endif

#if !defined(__lint)

/* external data */
#define	altzone		_altzone
#define	daylight	_daylight
#define	lone		_lone
#define	lten		_lten
#define	lzero		_lzero
#define	timezone	_timezone
#define	tzname		_tzname

/* functions */
#define	Msgdb		_Msgdb
#define	a64l		_a64l
#define	access		_access
#define	acct		_acct
#define	acctctl		_acctctl
#define	acl		_acl
#define	addseverity	_addseverity
#define	adjtime		_adjtime
#define	alarm		_alarm
#define	alphasort	_alphasort
#define	ascftime	_ascftime
#define	asctime_r	_asctime_r
#define	attropen	_attropen
#define	basename	_basename
#define	brk		_brk
#define	brkbase		_brkbase
#define	bsd_signal	_bsd_signal
#define	catclose	_catclose
#define	catgets		_catgets
#define	catopen		_catopen
#define	cfgetispeed	_cfgetispeed
#define	cfgetospeed	_cfgetospeed
#define	cfree		_cfree
#define	cfsetispeed	_cfsetispeed
#define	cfsetospeed	_cfsetospeed
#define	cftime		_cftime
#define	ctime_r		_ctime_r
#define	chdir		_chdir
#define	chmod		_chmod
#define	chown		_chown
#define	chroot		_chroot
#define	close		_close
#define	closedir	_closedir
#define	closefrom	_closefrom
#define	closelog	_closelog
#define	core_set_options		_core_set_options
#define	core_get_options		_core_get_options
#define	core_set_global_content		_core_set_global_content
#define	core_get_global_content		_core_get_global_content
#define	core_set_global_path		_core_set_global_path
#define	core_get_global_path		_core_get_global_path
#define	core_set_default_content	_core_set_default_content
#define	core_get_default_content	_core_get_default_content
#define	core_set_default_path		_core_set_default_path
#define	core_get_default_path		_core_get_default_path
#define	core_set_process_content	_core_set_process_content
#define	core_get_process_content	_core_get_process_content
#define	core_set_process_path		_core_set_process_path
#define	core_get_process_path		_core_get_process_path
#define	countbase	_countbase
#define	creat		_creat
#define	crypt		_crypt
#define	ctermid		_ctermid
#define	ctermid_r	_ctermid_r
#define	cuserid		_cuserid
#define	dial		_dial
#define	dirname		_dirname
#define	dlclose		_dlclose
#define	dlopen		_dlopen
#define	dlsym		_dlsym
#define	dlerror		_dlerror
#define	door_bind		_door_bind
#define	door_call		_door_call
#define	door_create		_door_create
#define	door_cred		_door_cred
#define	door_getparam		_door_getparam
#define	door_info		_door_info
#define	door_return		_door_return
#define	door_revoke		_door_revoke
#define	door_setparam		_door_setparam
#define	door_server_create	_door_server_create
#define	door_ucred		_door_ucred
#define	door_unbind		_door_unbind
#define	drand48		_drand48
#define	dup		_dup
#define	dup2		_dup2
#define	ecvt		_ecvt
#define	edata		_edata
#define	encrypt		_encrypt
#define	end		_end
#define	endgrent	_endgrent
#define	endpwent	_endpwent
#define	endspent	_endspent
#define	endutent	_endutent
#define	endutxent	_endutxent
#define	environ		_environ
#define	erand48		_erand48
#define	etext		_etext
#define	execl		_execl
#define	execle		_execle
#define	execlp		_execlp
#define	execv		_execv
#define	execve		_execve
#define	execvp		_execvp
#define	exportfs	_exportfs
#define	facl		_facl
#define	fattach		_fattach
#define	fchdir		_fchdir
#define	fchmod		_fchmod
#define	fchown		_fchown
#define	fchownat	_fchownat
#define	fchroot		_fchroot
#define	fcntl		_fcntl
#define	fcvt		_fcvt
#define	fdetach		_fdetach
#define	fdopen		_fdopen
#define	fdwalk		_fdwalk
#define	ffs		_ffs
#define	fgetgrent	_fgetgrent
#define	fgetgrent_r	_fgetgrent_r
#define	fgetpwent	_fgetpwent
#define	fgetpwent_r	_fgetpwent_r
#define	fgetspent	_fgetspent
#define	fgetspent_r	_fgetspent_r
#define	finite		_finite
#define	flockfile	_flockfile
#define	ftrylockfile	_ftrylockfile
#define	funlockfile	_funlockfile
#define	fmtmsg		_fmtmsg
#define	fork		_fork
#define	fork1		_fork1
#define	forkall		_forkall
#define	fpathconf	_fpathconf
#define	fpclass		_fpclass
#define	fpgetmask	_fpgetmask
#define	fpgetround	_fpgetround
#define	fpgetsticky	_fpgetsticky
#define	fprintf		_fprintf
#define	fpsetmask	_fpsetmask
#define	fpsetround	_fpsetround
#define	fpsetsticky	_fpsetsticky
#define	fstat		_fstat
#define	fstatat		_fstatat
#define	fstatfs		_fstatfs
#define	fstatvfs	_fstatvfs
#define	fsync		_fsync
#define	ftell		_ftell
#define	ftello		_ftello
#define	fseek		_fseek
#define	fseeko		_fseeko
#define	ftok		_ftok
#define	ftruncate	_ftruncate
#define	unlinkat	_unlinkat
#define	futimesat	_futimesat
#define	gcvt		_gcvt
#define	getacct		_getacct
#define	getcontext	_getcontext
#define	getcpuid	_getcpuid
#define	getcwd		_getcwd
#define	getdate		_getdate
#define	getdents	_getdents
#define	getegid		_getegid
#define	geteuid		_geteuid
#define	getexecname	_getexecname
#define	getextmntent	_getextmntent
#define	getgid		_getgid
#define	getloadavg	_getloadavg
#define	getgrent	_getgrent
#define	getgrent_r	_getgrent_r
#define	getgrgid	_getgrgid
#define	getgrgid_r	_getgrgid_r
#define	getgrnam	_getgrnam
#define	getgrnam_r	_getgrnam_r
#define	getgroups	_getgroups
#define	gethomelgroup	_gethomelgroup	/* Being replaced by lgrp_home() */
#define	gethz		_gethz
#define	getisax		_getisax
#define	getitimer	_getitimer
#define	gettaskid	_gettaskid
#define	getlogin	_getlogin
#define	getmntany	_getmntany
#define	getmntent	_getmntent
#define	getmsg		_getmsg
#define	getopt		_getopt
#define	getopt_clip	_getopt_clip
#define	getopt_long	_getopt_long
#define	getopt_long_only	_getopt_long_only
#define	getpagesizes	_getpagesizes
#define	getpass		_getpass
#define	getpassphrase	_getpassphrase
#define	getpeerucred	_getpeerucred
#define	getpgid		_getpgid
#define	getpgrp		_getpgrp
#define	getpid		_getpid
#define	getpmsg		_getpmsg
#define	getppid		_getppid
#define	getppriv	_getppriv
#define	getprivimplinfo	_getprivimplinfo
#define	getpflags	_getpflags
#define	getprojid	_getprojid
#define	getpw		_getpw
#define	getpwent	_getpwent
#define	getpwent_r	_getpwent_r
#define	getpwnam	_getpwnam
#define	getpwnam_r	_getpwnam_r
#define	getpwuid	_getpwuid
#define	getpwuid_r	_getpwuid_r
#define	getrctl		_getrctl
#define	getrlimit	_getrlimit
#define	getsid		_getsid
#define	getspent	_getspent
#define	getspent_r	_getspent_r
#define	getspnam	_getspnam
#define	getspnam_r	_getspnam_r
#define	getsubopt	_getsubopt
#define	gettimeofday	_gettimeofday
#define	gettxt		_gettxt
#define	getuid		_getuid
#define	getustack	_getustack
#define	getutent	_getutent
#define	getutid		_getutid
#define	getutline	_getutline
#define	getutmp		_getutmp
#define	getutmpx	_getutmpx
#define	getutxent	_getutxent
#define	getutxid	_getutxid
#define	getutxline	_getutxline
#define	getvfsany	_getvfsany
#define	getvfsent	_getvfsent
#define	getvfsfile	_getvfsfile
#define	getvfsspec	_getvfsspec
#define	getw		_getw
#define	getzoneid	_getzoneid
#define	getzoneidbyname	_getzoneidbyname
#define	getzonenamebyid	_getzonenamebyid
#define	grantpt		_grantpt
#define	gsignal		_gsignal
#define	gtty		_gtty
#define	hasmntopt	_hasmntopt
#define	hcreate		_hcreate
#define	hdestroy	_hdestroy
#define	hsearch		_hsearch
#define	initgroups	_initgroups
#define	insque		_insque
#define	install_utrap	_install_utrap
#define	inst_sync	_inst_sync
#define	ioctl		_ioctl
#define	isaexec		_isaexec
#define	isastream	_isastream
#define	isatty		_isatty
#define	issetugid	_issetugid
#define	jrand48		_jrand48
#define	kaio		_kaio
#define	kill		_kill
#define	l64a		_l64a
#define	ladd		_ladd
#define	lchown		_lchown
#define	lckpwdf		_lckpwdf
#define	lcong48		_lcong48
#define	ldivide		_ldivide
#define	lexp10		_lexp10
#define	lfind		_lfind
#define	link		_link
#define	llog10		_llog10
#define	llseek		_llseek
#define	lmul		_lmul
#define	lockf		_lockf
#define	localtime_r	_localtime_r
#define	longjmp		_longjmp
#define	lrand48		_lrand48
#define	lsearch		_lsearch
#define	lseek		_lseek
#define	lshiftl		_lshiftl
#define	lsign		_lsign
#define	lstat		_lstat
#define	lsub		_lsub
#define	ltol3		_ltol3
#define	madvise		_madvise
#define	makecontext	_makecontext
#define	__makecontext_v2	___makecontext_v2
#define	makeut		_makeut
#define	makeutx		_makeutx
#define	memalign	_memalign
#define	memccpy		_memccpy
#define	memcntl		_memcntl
#define	memcmp		_memcmp
#define	memcpy		_memcpy
#define	meminfo		_meminfo
#define	memmove		_memmove
#define	memset		_memset
#define	mincore		_mincore
#define	mkdir		_mkdir
#define	mkfifo		_mkfifo
#define	mknod		_mknod
#define	mktemp		_mktemp
#define	mkstemp		_mkstemp
#define	mlock		_mlock
#define	mlockall	_mlockall
#define	mmap		_mmap
#define	modut		_modut
#define	modutx		_modutx
#define	monitor		_monitor
#define	mount		_mount
#define	mprotect	_mprotect
#define	mrand48		_mrand48
#define	msgctl		_msgctl
#define	msgctl64	_msgctl64
#define	msgget		_msgget
#define	msgids		_msgids
#define	msgsnap		_msgsnap
#define	msgrcv		_msgrcv
#define	msgsnd		_msgsnd
#define	msync		_msync
#define	munlock		_munlock
#define	munlockall	_munlockall
#define	munmap		_munmap
#define	nfs_getfh	_nfs_getfh
#define	nfssvc		_nfssvc
#define	nftw		_nftw
#define	nice		_nice
#define	nrand48		_nrand48
#define	nss_delete	_nss_delete
#define	nss_endent	_nss_endent
#define	nss_getent	_nss_getent
#define	nss_search	_nss_search
#define	nss_setent	_nss_setent
#define	ntp_gettime	_ntp_gettime
#define	ntp_adjtime	_ntp_adjtime
#define	open		_open
#define	openat		_openat
#define	opendir		_opendir
#define	fdopendir	_fdopendir
#define	openlog		_openlog
#define	pathconf	_pathconf
#define	pause		_pause
#define	pclose		_pclose
#define	pcsample	_pcsample
#define	pipe		_pipe
#define	plock		_plock
#define	poll		_poll
#define	port_create	_port_create
#define	port_associate	_port_associate
#define	port_dissociate	_port_dissociate
#define	port_send	_port_send
#define	port_sendn	_port_sendn
#define	port_get	_port_get
#define	port_getn	_port_getn
#define	port_alert	_port_alert
#define	port_dispatch	_port_dispatch
#define	popen		_popen
#define	posix_openpt	_posix_openpt
#define	pread		_pread
#define	pselect		_pselect
#define	pset_assign	_pset_assign
#define	pset_bind	_pset_bind
#define	printstack	_printstack
#define	pset_create	_pset_create
#define	pset_destroy	_pset_destroy
#define	pset_getattr	_pset_getattr
#define	pset_getloadavg	_pset_getloadavg
#define	pset_info	_pset_info
#define	pset_list	_pset_list
#define	pset_setattr	_pset_setattr
#define	priv_addset	_priv_addset
#define	priv_allocset	_priv_allocset
#define	priv_copyset	_priv_copyset
#define	priv_delset	_priv_delset
#define	priv_emptyset	_priv_emptyset
#define	priv_fillset	_priv_fillset
#define	priv_freeset	_priv_freeset
#define	priv_getbyname	_priv_getbyname
#define	priv_getbynum	_priv_getbynum
#define	priv_getsetbyname	_priv_getsetbyname
#define	priv_getsetbynum	_priv_getsetbynum
#define	priv_gettext	_priv_gettext
#define	priv_ineffect	_priv_ineffect
#define	priv_intersect	_priv_intersect
#define	priv_inverse	_priv_inverse
#define	priv_isemptyset	_priv_isemptyset
#define	priv_isequalset	_priv_isequalset
#define	priv_isfullset	_priv_isfullset
#define	priv_ismember	_priv_ismember
#define	priv_issubset	_priv_issubset
#define	priv_set	_priv_set
#define	priv_set_to_str	_priv_set_to_str
#define	priv_str_to_set	_priv_str_to_set
#define	priv_union	_priv_union
#define	profil		_profil
#define	psiginfo	_psiginfo
#define	psignal		_psignal
#define	ptrace		_ptrace
#define	ptsname		_ptsname
#define	putacct		_putacct
#define	pwrite		_pwrite
#define	putenv		_putenv
#define	putmsg		_putmsg
#define	putpmsg		_putpmsg
#define	putpwent	_putpwent
#define	putspent	_putspent
#define	pututline	_pututline
#define	pututxline	_pututxline
#define	putw		_putw
#define	rand_r		_rand_r
#define	rctlctl		_rctlctl
#define	rctllist	_rctllist
#define	read		_read
#define	readdir		_readdir
#define	readdir_r	_readdir_r
#define	readlink	_readlink
#define	readv		_readv
#define	realpath	_realpath
#define	regcmp		_regcmp
#define	regcomp		_regcomp
#define	regerror	_regerror
#define	regex		_regex
#define	regexec		_regexec
#define	regfree		_regfree
#define	remque		_remque
#define	renameat	_renameat
#define	resetmnttab	_resetmnttab
#define	resolvepath	_resolvepath
#define	rmdir		_rmdir
#define	sbrk		_sbrk
#define	scandir		_scandir
#define	scrwidth	_scrwidth
#define	seed48		_seed48
#define	seekdir		_seekdir
#define	select		_select
#define	semctl		_semctl
#define	semctl64	_semctl64
#define	semget		_semget
#define	semids		_semids
#define	semop		_semop
#define	semtimedop	_semtimedop
#define	setcontext	_setcontext
#define	setegid		_setegid
#define	setenv		_setenv
#define	seteuid		_seteuid
#define	setgid		_setgid
#define	setgrent	_setgrent
#define	setgroups	_setgroups
#define	setitimer	_setitimer
#define	settaskid	_settaskid
#define	setjmp		_setjmp
#define	setkey		_setkey
#define	setlocale	_setlocale
#define	setlogmask	_setlogmask
#define	setpgid		_setpgid
#define	setpgrp		_setpgrp
#define	setppriv	_setppriv
#define	setpflags	_setpflags
#define	setpwent	_setpwent
#define	setrctl		_setrctl
#define	setregid	_setregid
#define	setreuid	_setreuid
#define	setrlimit	_setrlimit
#define	setsid		_setsid
#define	setspent	_setspent
#define	settimeofday	_settimeofday
#define	setuid		_setuid
#define	setustack	_setustack
#define	setutent	_setutent
#define	setutxent	_setutxent
#define	shmat		_shmat
#define	shmctl		_shmctl
#define	shmctl64	_shmctl64
#define	shmdt		_shmdt
#define	shmget		_shmget
#define	shmids		_shmids
#define	sig2str		_sig2str
#define	sigaction	_sigaction
#define	sigaddset	_sigaddset
#define	sigaltstack	_sigaltstack
#define	sigdelset	_sigdelset
#define	sigemptyset	_sigemptyset
#define	sigfillset	_sigfillset
#define	sigflag		_sigflag
#define	sigfpe		_sigfpe
#define	sighold		_sighold
#define	sigignore	_sigignore
#define	siginterrupt	_siginterrupt
#define	sigismember	_sigismember
#define	siglongjmp	_siglongjmp
#define	sigpause	_sigpause
#define	sigpending	_sigpending
#define	sigprocmask	_sigprocmask
#define	sigrelse	_sigrelse
#define	sigsend		_sigsend
#define	sigsendset	_sigsendset
#define	sigset		_sigset
#define	signal		_signal
#define	sigsetjmp	_sigsetjmp
#define	sigsuspend	_sigsuspend
#define	sigwait		_sigwait
#define	sleep		_sleep
#define	srand48		_srand48
#define	ssignal		_ssignal
#define	stack_getbounds	_stack_getbounds
#define	stack_setbounds	_stack_setbounds
#define	stack_inbounds	_stack_inbounds
#define	stack_violation	_stack_violation
#define	stat		_stat
#define	statfs		_statfs
#define	statvfs		_statvfs
#define	stime		_stime
#define	str2sig		_str2sig
#define	strdup		_strdup
#define	strtok_r	_strtok_r
#define	stty		_stty
#define	swab		_swab
#define	swapcontext	_swapcontext
#define	swapctl		_swapctl
#define	symlink		_symlink
#define	sync		_sync
#define	synchutmp	_synchutmp
#define	syssun		_syssun
#define	sys_errlist	_sys_errlist
#define	sys_nerr	_sys_nerr
#define	syscall		_syscall6
#define	_syscall	_syscall6
#define	sysconf		_sysconf
#define	sysfs		_sysfs
#define	sysinfo		_sysinfo
#define	syslog		_syslog
#define	tcdrain		_tcdrain
#define	tcflow		_tcflow
#define	tcflush		_tcflush
#define	tcgetattr	_tcgetattr
#define	tcgetpgrp	_tcgetpgrp
#define	tcgetsid	_tcgetsid
#define	tcsendbreak	_tcsendbreak
#define	tcsetattr	_tcsetattr
#define	tcsetpgrp	_tcsetpgrp
#define	tdelete		_tdelete
#define	tell		_tell
#define	telldir		_telldir
#define	tempnam		_tempnam
#define	tfind		_tfind
#define	time		_time
#define	times		_times
#define	tmpnam		_tmpnam
#define	tmpnam_r	_tmpnam_r
#define	truncate	_truncate
#define	tsearch		_tsearch
#define	ttyname		_ttyname
#define	ttyslot		_ttyslot
#define	twalk		_twalk
#define	tzname		_tzname
#define	tzset		_tzset
#define	uadmin		_uadmin
#define	ucred_free	_ucred_free
#define	ucred_get	_ucred_get
#define	ucred_getamask	_ucred_getamask
#define	ucred_getasid	_ucred_getasid
#define	ucred_getatid	_ucred_getatid
#define	ucred_getauid	_ucred_getauid
#define	ucred_getegid	_ucred_getegid
#define	ucred_geteuid	_ucred_geteuid
#define	ucred_getgroups	_ucred_getgroups
#define	ucred_getpflags	_ucred_getpflags
#define	ucred_getpid	_ucred_getpid
#define	ucred_getprojid	_ucred_getprojid
#define	ucred_getprivset	_ucred_getprivset
#define	ucred_getrgid	_ucred_getrgid
#define	ucred_getruid	_ucred_getruid
#define	ucred_getsuid	_ucred_getsuid
#define	ucred_getsgid	_ucred_getsgid
#define	ucred_getzoneid	_ucred_getzoneid
#define	ucred_size	_ucred_size
#define	ulckpwdf	_ulckpwdf
#define	ulimit		_ulimit
#define	umask		_umask
#define	umount		_umount
#define	umount2		_umount2
#define	uname		_uname
#define	undial		_undial
#define	unlink		_unlink
#define	unlockpt	_unlockpt
#define	unordered	_unordered
#define	unsetenv	_unsetenv
#define	updutfile	_updutfile
#define	updutxfile	_updutxfile
#define	updutmp		_updutmp
#define	updutmpx	_updutmpx
#define	updwtmp		_updwtmp
#define	updwtmpx	_updwtmpx
#define	ustat		_ustat
#define	utime		_utime
#define	utimes		_utimes
#define	utmpname	_utmpname
#define	utmpxname	_utmpxname
#define	utssys		_utssys
#define	valloc		_valloc
#define	vfork		_vfork
#define	vfscanf		_vfscanf
#define	vhangup		_vhangup
#define	vscanf		_vscanf
#define	vsscanf		_vsscanf
#define	vsyslog		_vsyslog
#define	wait		_wait
#define	waitid		_waitid
#define	waitpid		_waitpid
#define	walkcontext	_walkcontext
#define	wcwidth		_wcwidth
#define	wcswidth	_wcswidth
#define	wracct		_wracct
#define	write		_write
#define	writev		_writev
#define	yield		_yield
#define	usleep		_usleep
#define	wait3		_wait3
#define	_assert		__assert
#define	_assert_c99	__assert_c99
#define	_cladm		__cladm
#define	_ctype		__ctype
#define	_filbuf		__filbuf
#define	_flsbuf		__flsbuf
#define	_iob		__iob
#define	_lwp_info		__lwp_info
#define	_lwp_self		__lwp_self
#define	_lwp_kill		__lwp_kill
#define	_lwp_private		__lwp_private
#define	_lwp_suspend		__lwp_suspend
#define	_lwp_continue		__lwp_continue
#define	_lwp_mutex_lock		__lwp_mutex_lock
#define	_lwp_mutex_timedlock	__lwp_mutex_timedlock
#define	_lwp_mutex_reltimedlock	__lwp_mutex_reltimedlock
#define	_lwp_mutex_trylock	__lwp_mutex_trylock
#define	_lwp_mutex_unlock	__lwp_mutex_unlock
#define	_lwp_cond_wait		__lwp_cond_wait
#define	_lwp_cond_timedwait	__lwp_cond_timedwait
#define	_lwp_cond_reltimedwait	__lwp_cond_reltimedwait
#define	_lwp_cond_signal	__lwp_cond_signal
#define	_lwp_cond_broadcast	__lwp_cond_broadcast
#define	_lwp_sema_wait		__lwp_sema_wait
#define	_lwp_sema_trywait	__lwp_sema_trywait
#define	_lwp_sema_post		__lwp_sema_post
#define	_lwp_sema_init		__lwp_sema_init
#define	__systemcall		__systemcall6

/* fp and ll functions */
#define	decimal_to_double	_decimal_to_double
#define	decimal_to_extended	_decimal_to_extended
#define	decimal_to_quadruple	_decimal_to_quadruple
#define	decimal_to_single	_decimal_to_single
#define	double_to_decimal	_double_to_decimal
#define	econvert		_econvert
#define	extended_to_decimal	_extended_to_decimal
#define	fconvert		_fconvert
#define	file_to_decimal		_file_to_decimal
#define	func_to_decimal		_func_to_decimal
#define	gconvert		_gconvert
#define	qeconvert		_qeconvert
#define	qecvt			_qecvt
#define	qfconvert		_qfconvert
#define	qfcvt			_qfcvt
#define	qgconvert		_qgconvert
#define	qgcvt			_qgcvt
#define	quadruple_to_decimal	_quadruple_to_decimal
#define	seconvert		_seconvert
#define	sfconvert		_sfconvert
#define	sgconvert		_sgconvert
#define	single_to_decimal	_single_to_decimal
#define	string_to_decimal	_string_to_decimal
#define	atoll			_atoll
#define	llabs			_llabs
#define	lldiv			_lldiv
#define	lltostr			_lltostr
#define	strtoll			_strtoll
#define	strtoull		_strtoull
#define	ulltostr		_ulltostr

#if !defined(_LP64)
/* transitional large file interfaces */
#define	alphasort64	_alphasort64
#define	attropen64	_attropen64
#define	creat64		_creat64
#define	ftello64	_ftello64
#define	fseeko64	_fseeko64
#define	fstat64		_fstat64
#define	ftw64		_ftw64
#define	fstatvfs64	_fstatvfs64
#define	ftruncate64	_ftruncate64
#define	getdents64	_getdents64
#define	getrlimit64	_getrlimit64
#define	lockf64		_lockf64
#define	lseek64		_lseek64
#define	lstat64		_lstat64
#define	mkstemp64	_mkstemp64
#define	mmap64		_mmap64
#define	nftw64		_nftw64
#define	openat64	_openat64
#define	open64		_open64
#define	pread64		_pread64
#define	pwrite64	_pwrite64
#define	readdir64	_readdir64
#define	readdir64_r	_readdir64_r
#define	scandir64	_scandir64
#define	seekdir64	_seekdir64
#define	tell64		_tell64
#define	telldir64	_telldir64
#define	setrlimit64	_setrlimit64
#define	stat64		_stat64
#define	fstatat64	_fstatat64
#define	statvfs64	_statvfs64
#define	truncate64	_truncate64
#endif	/* !_LP64 */

/* lock primitives and other multithreading interfaces */
#define	atomic_inc_8		_atomic_inc_8
#define	atomic_inc_uchar	_atomic_inc_uchar
#define	atomic_inc_16		_atomic_inc_16
#define	atomic_inc_ushort	_atomic_inc_ushort
#define	atomic_inc_32		_atomic_inc_32
#define	atomic_inc_uint		_atomic_inc_uint
#define	atomic_inc_ulong	_atomic_inc_ulong
#define	atomic_inc_64		_atomic_inc_64
#define	atomic_dec_8		_atomic_dec_8
#define	atomic_dec_uchar	_atomic_dec_uchar
#define	atomic_dec_16		_atomic_dec_16
#define	atomic_dec_ushort	_atomic_dec_ushort
#define	atomic_dec_32		_atomic_dec_32
#define	atomic_dec_uint		_atomic_dec_uint
#define	atomic_dec_ulong	_atomic_dec_ulong
#define	atomic_dec_64		_atomic_dec_64
#define	atomic_add_8		_atomic_add_8
#define	atomic_add_char		_atomic_add_char
#define	atomic_add_16		_atomic_add_16
#define	atomic_add_short	_atomic_add_short
#define	atomic_add_32		_atomic_add_32
#define	atomic_add_int		_atomic_add_int
#define	atomic_add_64		_atomic_add_64
#define	atomic_add_ptr		_atomic_add_ptr
#define	atomic_add_long		_atomic_add_long
#define	atomic_or_8		_atomic_or_8
#define	atomic_or_uchar		_atomic_or_uchar
#define	atomic_or_16		_atomic_or_16
#define	atomic_or_ushort	_atomic_or_ushort
#define	atomic_or_32		_atomic_or_32
#define	atomic_or_uint		_atomic_or_uint
#define	atomic_or_64		_atomic_or_64
#define	atomic_or_ulong		_atomic_or_ulong
#define	atomic_and_8		_atomic_and_8
#define	atomic_and_uchar	_atomic_and_uchar
#define	atomic_and_16		_atomic_and_16
#define	atomic_and_ushort	_atomic_and_ushort
#define	atomic_and_32		_atomic_and_32
#define	atomic_and_uint		_atomic_and_uint
#define	atomic_and_64		_atomic_and_64
#define	atomic_and_ulong	_atomic_and_ulong
#define	atomic_inc_8_nv		_atomic_inc_8_nv
#define	atomic_inc_uchar_nv	_atomic_inc_uchar_nv
#define	atomic_inc_16_nv	_atomic_inc_16_nv
#define	atomic_inc_ushort_nv	_atomic_inc_ushort_nv
#define	atomic_inc_32_nv	_atomic_inc_32_nv
#define	atomic_inc_uint_nv	_atomic_inc_uint_nv
#define	atomic_inc_ulong_nv	_atomic_inc_ulong_nv
#define	atomic_inc_64_nv	_atomic_inc_64_nv
#define	atomic_dec_8_nv		_atomic_dec_8_nv
#define	atomic_dec_uchar_nv	_atomic_dec_uchar_nv
#define	atomic_dec_16_nv	_atomic_dec_16_nv
#define	atomic_dec_ushort_nv	_atomic_dec_ushort_nv
#define	atomic_dec_32_nv	_atomic_dec_32_nv
#define	atomic_dec_uint_nv	_atomic_dec_uint_nv
#define	atomic_dec_ulong_nv	_atomic_dec_ulong_nv
#define	atomic_dec_64_nv	_atomic_dec_64_nv
#define	atomic_add_8_nv		_atomic_add_8_nv
#define	atomic_add_char_nv	_atomic_add_char_nv
#define	atomic_add_16_nv	_atomic_add_16_nv
#define	atomic_add_short_nv	_atomic_add_short_nv
#define	atomic_add_32_nv	_atomic_add_32_nv
#define	atomic_add_int_nv	_atomic_add_int_nv
#define	atomic_add_64_nv	_atomic_add_64_nv
#define	atomic_add_ptr_nv	_atomic_add_ptr_nv
#define	atomic_add_long_nv	_atomic_add_long_nv
#define	atomic_or_8_nv		_atomic_or_8_nv
#define	atomic_or_uchar_nv	_atomic_or_uchar_nv
#define	atomic_or_16_nv		_atomic_or_16_nv
#define	atomic_or_ushort_nv	_atomic_or_ushort_nv
#define	atomic_or_32_nv		_atomic_or_32_nv
#define	atomic_or_uint_nv	_atomic_or_uint_nv
#define	atomic_or_64_nv		_atomic_or_64_nv
#define	atomic_or_ulong_nv	_atomic_or_ulong_nv
#define	atomic_and_8_nv		_atomic_and_8_nv
#define	atomic_and_uchar_nv	_atomic_and_uchar_nv
#define	atomic_and_16_nv	_atomic_and_16_nv
#define	atomic_and_ushort_nv	_atomic_and_ushort_nv
#define	atomic_and_32_nv	_atomic_and_32_nv
#define	atomic_and_uint_nv	_atomic_and_uint_nv
#define	atomic_and_64_nv	_atomic_and_64_nv
#define	atomic_and_ulong_nv	_atomic_and_ulong_nv
#define	atomic_cas_8		_atomic_cas_8
#define	atomic_cas_uchar	_atomic_cas_uchar
#define	atomic_cas_16		_atomic_cas_16
#define	atomic_cas_ushort	_atomic_cas_ushort
#define	atomic_cas_32		_atomic_cas_32
#define	atomic_cas_uint		_atomic_cas_uint
#define	atomic_cas_ptr		_atomic_cas_ptr
#define	atomic_cas_ulong	_atomic_cas_ulong
#define	atomic_cas_64		_atomic_cas_64
#define	atomic_swap_8		_atomic_swap_8
#define	atomic_swap_uchar	_atomic_swap_uchar
#define	atomic_swap_16		_atomic_swap_16
#define	atomic_swap_ushort	_atomic_swap_ushort
#define	atomic_swap_32		_atomic_swap_32
#define	atomic_swap_uint	_atomic_swap_uint
#define	atomic_swap_ptr		_atomic_swap_ptr
#define	atomic_swap_ulong	_atomic_swap_ulong
#define	atomic_swap_64		_atomic_swap_64
#define	atomic_set_long_excl	_atomic_set_long_excl
#define	atomic_clear_long_excl	_atomic_clear_long_excl
#define	membar_enter		_membar_enter
#define	membar_exit		_membar_exit
#define	membar_producer		_membar_producer
#define	membar_consumer		_membar_consumer
#define	mutex_init		_mutex_init
#define	mutex_destroy		_mutex_destroy
#define	mutex_lock		_mutex_lock
#define	mutex_trylock		_mutex_trylock
#define	mutex_unlock		_mutex_unlock
#define	cond_init		_cond_init
#define	cond_destroy		_cond_destroy
#define	cond_wait		_cond_wait
#define	cond_timedwait		_cond_timedwait
#define	cond_reltimedwait	_cond_reltimedwait
#define	cond_signal		_cond_signal
#define	cond_broadcast		_cond_broadcast
#define	rwlock_init		_rwlock_init
#define	rwlock_destroy		_rwlock_destroy
#define	rw_rdlock		_rw_rdlock
#define	rw_wrlock		_rw_wrlock
#define	rw_tryrdlock		_rw_tryrdlock
#define	rw_trywrlock		_rw_trywrlock
#define	rw_unlock		_rw_unlock
#define	thr_main		_thr_main
#define	thr_self		_thr_self
#define	thr_exit		_thr_exit
#define	thr_min_stack		_thr_min_stack
#define	thr_kill		_thr_kill
#define	thr_keycreate		_thr_keycreate
#define	thr_setspecific		_thr_setspecific
#define	thr_getspecific		_thr_getspecific

/* new POSIX SUSV3 stuff */
#define	posix_spawn				_posix_spawn
#define	posix_spawnp				_posix_spawnp
#define	posix_spawn_file_actions_init		_posix_spawn_file_actions_init
#define	posix_spawn_file_actions_destroy	\
				_posix_spawn_file_actions_destroy
#define	posix_spawn_file_actions_addopen	\
				_posix_spawn_file_actions_addopen
#define	posix_spawn_file_actions_addclose	\
				_posix_spawn_file_actions_addclose
#define	posix_spawn_file_actions_adddup2	\
				_posix_spawn_file_actions_adddup2
#define	posix_spawnattr_init			_posix_spawnattr_init
#define	posix_spawnattr_destroy			_posix_spawnattr_destroy
#define	posix_spawnattr_setflags		_posix_spawnattr_setflags
#define	posix_spawnattr_getflags		_posix_spawnattr_getflags
#define	posix_spawnattr_setpgroup		_posix_spawnattr_setpgroup
#define	posix_spawnattr_getpgroup		_posix_spawnattr_getpgroup
#define	posix_spawnattr_setschedparam		_posix_spawnattr_setschedparam
#define	posix_spawnattr_getschedparam		_posix_spawnattr_getschedparam
#define	posix_spawnattr_setschedpolicy		_posix_spawnattr_setschedpolicy
#define	posix_spawnattr_getschedpolicy		_posix_spawnattr_getschedpolicy
#define	posix_spawnattr_setsigdefault		_posix_spawnattr_setsigdefault
#define	posix_spawnattr_getsigdefault		_posix_spawnattr_getsigdefault
#define	posix_spawnattr_setsigmask		_posix_spawnattr_setsigmask
#define	posix_spawnattr_getsigmask		_posix_spawnattr_getsigmask

/* unwind stuff (amd64 only) */
#if defined(__amd64)
#define	_Unwind_DeleteException		_SUNW_Unwind_DeleteException
#define	_Unwind_ForcedUnwind		_SUNW_Unwind_ForcedUnwind
#define	_Unwind_GetCFA			_SUNW_Unwind_GetCFA
#define	_Unwind_GetGR			_SUNW_Unwind_GetGR
#define	_Unwind_GetIP			_SUNW_Unwind_GetIP
#define	_Unwind_GetLanguageSpecificData	_SUNW_Unwind_GetLanguageSpecificData
#define	_Unwind_GetRegionStart		_SUNW_Unwind_GetRegionStart
#define	_Unwind_RaiseException		_SUNW_Unwind_RaiseException
#define	_Unwind_Resume			_SUNW_Unwind_Resume
#define	_Unwind_SetGR			_SUNW_Unwind_SetGR
#define	_Unwind_SetIP			_SUNW_Unwind_SetIP
#endif	/* __amd64 */

#endif	/* !defined(__lint) */

/*
 * Almost all libc source files have to include lint.h
 * We do it here for the benefit of files already including synonyms.h
 */
#include "lint.h"

#ifdef __cplusplus
}
#endif

#endif /* _LIBC_SYNONYMS_H */
