#! /bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#
 
PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

installed() {
	driver=$1
	grep "^${driver} " $BASEDIR/etc/name_to_major > /dev/null 2>&1

	return $?
}

EXIT=0

if installed hid 
then 
	rem_drv -b ${BASEDIR} hid || EXIT=1
fi

if installed hubd
then
	rem_drv -b ${BASEDIR} hubd || EXIT=1
fi

if installed usb_ia
then
	rem_drv -b ${BASEDIR} usb_ia || EXIT=1
fi

if installed usb_mid
then
	rem_drv -b ${BASEDIR} usb_mid || EXIT=1
fi

if installed scsa2usb
then
	rem_drv -b ${BASEDIR} scsa2usb || EXIT=1
fi

if installed usbprn
then
	rem_drv -b ${BASEDIR} usbprn || EXIT=1
fi

if installed usb_ac
then
	rem_drv -b ${BASEDIR} usb_ac || EXIT=1
fi

if installed usb_as
then
	rem_drv -b ${BASEDIR} usb_as || EXIT=1
fi

if installed ohci
then
	rem_drv -b ${BASEDIR} ohci || EXIT=1
fi

if installed ehci
then
	#
	# Only rem_drv ehci if there are no user-defined aliases
	# Be careful about the egrep [ ] regexp - it should be
	# [<SAPCE><TAB>]
	# 

	egrep "^ehci[ 	]" $BASEDIR/etc/driver_aliases | \
	    grep -v "pciclass,0c0320" > /dev/null 2>&1

	if [ $? -eq 1 ]; then
		rem_drv -b ${BASEDIR} ehci || EXIT=1
	fi
fi

if installed uhci
then
	rem_drv -b ${BASEDIR} uhci || EXIT=1
fi

if installed wusb_ca
then
	rem_drv -b ${BASEDIR} wusb_ca || EXIT=1
fi

if installed wusb_df
then
	rem_drv -b ${BASEDIR} wusb_df || EXIT=1
fi

if installed hwahc
then
	rem_drv -b ${BASEDIR} hwahc || EXIT=1
fi

if installed hwarc
then
	rem_drv -b ${BASEDIR} hwarc || EXIT=1
fi

exit $EXIT
